### ISSUE TITLE
Html ID attribute removal

### ISSUE THREAD

**Issue by dvprod7** [foundation/foundation-emails#1029]
Hi everyone, **Im developing a custom email template for Marketo (platform for marketing automation) with Foundation for emails and I having some issues when Im adding custom IDs attributes** for editing in Marketo, marketo needs some extra custom IDs and classes in some html tags to work on their platform and let a email template be edited (change text, images, colors, moving up and down custom modules or editable areas).

When I put classes in the tags that I need and run 'npm start', everything looks fine in the final Inky to HTML render, but **I noticed that the ID attributes are missing**... I know maybe its a default core function to remove ID attributes of the html tags because of non working or not have sense to be there for a email server (gmail, oulook, etc.)...but for my case I need the ID attributes for the purpose of my project to develop a email template for marketo and be used by my design team.

I appreciate your help and I ask excuses if my english its not correct... the last thing that i want to do its to hard-code the final Html inlined css like this guy:
[https://nation.marketo.com/t5/Product-Discussions/Building-emails-using-Foundation/m-p/85528#M49772](https://nation.marketo.com/t5/Product-Discussions/Building-emails-using-Foundation/m-p/85528#M49772)

**The render of Inky to HTML**
<img width="366" alt="Captura de Pantalla 2020-09-09 a la(s) 8 52 02 p  m" src="https://user-images.githubusercontent.com/21014455/92672453-53c06280-f2de-11ea-8b5e-e5c8fde4e6a9.png">

**My Code**
<img width="485" alt="Captura de Pantalla 2020-09-09 a la(s) 8 53 18 p  m" src="https://user-images.githubusercontent.com/21014455/92672526-810d1080-f2de-11ea-8580-b3adb65fe933.png">

Thanks a lot.

**Comment by DanielRuf** [comment]
IDs are not supported in this component.

See https://github.com/foundation/inky/blob/925cbee89f8e9b946469e67cec16e9f8ada4292f/lib/componentFactory.js#L65-L74

You can adjust the logic by writing your own component and use that or by patching it with [patch-package](https://www.npmjs.com/package/patch-package).

https://www.npmjs.com/package/inky#plugin-settings
https://www.npmjs.com/package/inky#custom-elements

**Comment by dvprod7** [comment]
Thanks for the solution @DanielRuf  I had to write the Marketo's sintax and IDs one by one in the final inlined css Html to control the correct functioning, its a more slow but more effective to the final result, I hope for someone with this issue in the future finds this and have feedback to continue with **correct developing for Marketo with Foundation fo Emails.**
