### ISSUE TITLE
Email scroll issue on Mail app (Catalina OS)

### ISSUE THREAD

**Issue by priyankshivhare-mb** [foundation/foundation-emails#1032]
**How can we reproduce this bug?**
Send the email that we created using foundation-emails@2.2.1
https://jsfiddle.net/8761urys/
Send it to a Gmail address which is set on the mail app on Mac Catalina OS
You will not be able to scroll the mail down, to scroll down we first need to scroll it up and then the scroll bar appears.
The issue has been reported on other forums as well. 
https://discussions.apple.com/thread/251330881?answerId=252723882022#252723882022

Write out the HTML (or Inky code) that causes the issue.
https://jsfiddle.net/8761urys/

**What did you expect to happen?**
Receive normal scrollable mail
**What happened instead?**
Mail was not scrollable without deliberately scrolling upwards to enable scroll down
**What email clients does this happen in?**
Mail App Catalina OS (Mac)

**Comment by DanielRuf** [comment]
This looks like an issue on the side of Apple and macOS.
