### ISSUE TITLE
[Feature Request] Support *.hbs file extension

### ISSUE THREAD

**Issue by putzwasser** [foundation/foundation-emails#1034]
As Panini relies largely on Handelbars it would be nice to support the *.hbs file type extension. By doing so, code editors (like Visual Studio Code) could support the Handlebars syntax highlighting.

I don't know how to contribute to the `gulfile.js` deployed via the `foundation` CLI, since the `gulpfile.js` of this repo is quite different, but this is how it could be achieved:

```
import gulp from 'gulp';
import plugins from 'gulp-load-plugins';
import rename from 'gulp-rename';
import browser from 'browser-sync';
import rimraf from 'rimraf';
import panini from 'panini';
import yargs from 'yargs';
import lazypipe from 'lazypipe';
import inky from 'inky';
import fs from 'fs';
import siphon from 'siphon-media-query';
import path from 'path';
import merge from 'merge-stream';
import beep from 'beepbeep';
import colors from 'colors';

function pages() {
  return gulp.src(['src/pages/**/*.html', 'src/pages/**/*.hbs', '!src/pages/archive/**/*.html'])
    .pipe(panini({
      root: 'src/pages',
      layouts: 'src/layouts',
      partials: 'src/partials',
      helpers: 'src/helpers'
    }))
    .pipe(inky())
    .pipe(rename(function (path) {
      path.extname = '.html'
    }))
    .pipe(gulp.dest('dist'));
}

function watch() {
  gulp.watch(['src/pages/**/*.html', 'src/pages/**/*.hbs']).on('all', gulp.series(pages, inline, browser.reload));
  gulp.watch(['src/layouts/**/*', 'src/partials/**/*']).on('all', gulp.series(resetPages, pages, inline, browser.reload));
  gulp.watch(['../scss/**/*.scss', 'src/assets/scss/**/*.scss']).on('all', gulp.series(resetPages, sass, pages, inline, browser.reload));
  gulp.watch('src/assets/img/**/*').on('all', gulp.series(images, browser.reload));
}
```

It includes a `*.hbs` GLOB to the `pages()` function and renames every file to `*.html`.

`gulp-rename` has to be added to the package.json, too, of course.

**Comment by DanielRuf** [comment]
I guess you mean the emails-template repo:

https://github.com/foundation/foundation-emails-template/blob/master/gulpfile.babel.js

You can adjust it in your products as you need.
It's just a template and so far we did not have (many) users who needed it so we did not add it to the template (that you can extand and change as you want).
