### ISSUE TITLE
First time attempting to make an email HTML

### ISSUE THREAD

**Issue by KurtGoetz** [foundation/foundation-emails#1047]
I was working on making an a signature for emails with HTML email and this is my first attempt at doing it, I managed to make it and it looks when I preview it, but aftert I test it sending it through a mail, it doesn't visualize correctly.

Is there something I'm doing wrong?

**How can we reproduce this bug?**

Write out the HTML (or Inky code) that causes the issue.
This is the project that I'm working on.
[Email-Signature.zip](https://github.com/foundation/foundation-emails/files/6062254/Email-Signature.zip)

**What did you expect to happen?**
![Desk virw](https://user-images.githubusercontent.com/79851903/109508719-e87e6e80-7a7e-11eb-92df-d6542469c3e3.jpg)
![Mob virw](https://user-images.githubusercontent.com/79851903/109508732-eb795f00-7a7e-11eb-9a22-631f812dfd10.jpg)

**What happened instead?**
![How it looks](https://user-images.githubusercontent.com/79851903/109508885-1499ef80-7a7f-11eb-93ae-cff73c594172.jpg)

**What email clients does this happen in?**
It happens in every email I've tested.

**Comment by ouw-devs** [comment]
You have to run the build script, so the styles can be inlined. You'll also need to upload the image assets somewhere and reference the URLs

**Comment by ghost** [comment]
Have you tried running the build task? Your after-inlining file still has CSS in the head

**Comment by nitrokevin** [comment]
You are going to have to lose the background image to start with, you can only use solid colours as backgrounds
