### ISSUE TITLE
Online Email Inliner: Links with &'s are being converted to &amp;

### ISSUE THREAD

**Issue by picklepicante** [foundation/foundation-emails#1056]
When using the online responsive inliner (https://get.foundation/emails/inliner.html), ampersands in links (&'s) are being converted to ```&amp;``` or even ```&amp;amp;```

**How can we reproduce this bug?**

Use the following code with or without the Compress HTML option selected:
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Test</title>
<style type="text/css">
body {
font-size: 12px;
}
</style>
</head>
<body>
<a href="http://www.example.com?var1=1&var2=2">Link &amp; Text</a>
</body>
```

**What did you expect to happen?**

I expected the link in the HTML ```http://www.example.com?var1=1&var2=2``` to remain as it was. In other words the full out put should be:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title>Test</title></head><body style="font-size:12px"><style type="text/css"></style><a href="http://www.example.com?var1=1&var2=2">Link &amp; Text</a></body></html>
```

**What happened instead?**
The code looks fine in the textarea preview. The problem occurs when I copy that code to use in my email program.

When copying using Cmd-C, the link gets converted to ```http://www.example.com?var1=1&amp;var2=2```. Also, if I were to change the link text above to say ```Link & Test``` it would also be converted to ```Link &amp; Text```; however if the link text already uses the ```&amp;``` (as it does in the code above), it does not get converted any further.

The full copied code is looks as follows:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title>Test</title></head><body style="font-size:12px"><style type="text/css"></style><a href="http://www.example.com?var1=1&amp;var2=2">Link &amp; Text</a></body></html>
```

When copying using the "Copy to Clipboard" button, the link gets converted to ```http://www.example.com?var1=1&amp;amp;var2=2```. The full copied code copied is as follows:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title>Test</title></head><body style="font-size:12px"><style type="text/css"></style><a href="http://www.example.com?var1=1&amp;amp;var2=2">Link</a></body></html>
```

**What web browsers does this happen in?**

I have gotten the same results on MacOS 10.14.6 using Safari Version 14.0.3, Firefox Developer Edition 86.0b9 (64-bit), and Chrome Version 89.0.4389.114.

**Comment by DanielRuf** [comment]
This issue is a duplicate, please see https://github.com/foundation/foundation-emails/search?q=ampersand+is%3Aissue&type=issues

See https://github.com/foundation/foundation-emails/issues/841

**Comment by picklepicante** [comment]
> This issue is a duplicate, please see https://github.com/foundation/foundation-emails/search?q=ampersand+is%3Aissue&type=issues
> 
> See #841

I saw the issue that you referenced; however, the behavior I'm describing is slightly different. In  issue #841, a workaround was to not use the "Copy to Clipboard" button. But while I can verify that this workaround **used** to work, that is no longer the case, at least for me.

As stated in my original issue, when *not* using the "Copy to Clipboard" button (i.e., when copying using Cmd-C, right clicking and clicking "copy" or using the browser menu Edit->Copy), the text ```http://www.example.com?var1=1&var2=2``` becomes ```http://www.example.com?var1=1&amp;var2=2```. In other words, the ```&``` becomes ```&amp;```, which used to only happen when using the "Copy to Clipboard" button.

Of course when using the "Copy to Clipboard" button, the result is worse: ```http://www.example.com?var1=1&amp;amp;var2=2```. In other words the ```&``` becomes ```&amp;amp;```.
