### ISSUE TITLE
Deprecation warning on `else if` SCSS syntax

### ISSUE THREAD

**Issue by bobmaerten** [foundation/foundation-emails#1059]
**How can we reproduce this bug?**

Starting webpack-cli to serve foundation emails, results in this deprecation warning:
```
webpack    | DEPRECATION WARNING on line 180, column 7 of node_modules/foundation-emails/scss/components/_typography.scss:
webpack    | @elseif is deprecated and will not be supported in future Sass versions.
webpack    | Use "@else if" instead.
webpack    |     ╷
webpack    | 180 │     } @elseif $align == 'right' {
webpack    |     │       ^^^^^^^
webpack    |     ╵
webpack    |
```

**What did you expect to happen?**
Not having a warning ¯\_(ツ)_/¯

**What happened instead?**
Had a warning ¯\_(ツ)_/¯

**Comment by GALCF** [comment]
@bobmaerten The fix was already commited, your changes add this deprecation again.

**Comment by GALCF** [comment]
Reference: https://github.com/foundation/foundation-emails/commit/adf0b3c4ffb6d8d3636b099d500fef29c8666669#diff-7d23987b42669a30b994f978e2aa0c25c1ae51f3a6c6bf8d02cefdfff1f53e14

@DanielRuf

**Comment by bobmaerten** [comment]
Oh dear... I've been fooled by unreleased code then... August 2020, that's really sad :'(
