### ISSUE TITLE
[Getting Started with Sass] NodeJS version 10

### ISSUE THREAD

**Issue by ARTUR3X** [foundation/foundation-emails#1066]
I think it is important to write on the requirements that the SASS version will run only if you have  no greater than version 10 of nodejs

**Comment by ballermatic** [comment]
Amen! And thank you for pointing this out. I was losing my mind.

**Comment by stinhambo** [comment]
Which means people on Apple Silicon (M1 based) processors can't work with it as Node 10 isn't supported.

**Comment by justingit** [comment]
Yup! I was very excited to check out all the hard work done for the new release, but it's unfortunately not working on an M1 Macbook.

**Comment by joeworkman** [comment]
Closing. ref https://github.com/foundation/foundation-emails/issues/1113
