### ISSUE TITLE
Deprecation warning on SASS/SCSS files

### ISSUE THREAD

**Issue by msandrini** [foundation/foundation-emails#1070]
Hi,

Compiling the Foundation e-mail SCSS files from a "root" (`foundation-emails.scss`) with the `sass` lib version 1.35.2 and using its CLI to generate CSS files I get the following feedback on my terminal:

For example, on `_util.scss`:
```
Deprecation Warning: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($containerWidth, $totalColumns)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
21 │   @return ($containerWidth / $totalColumns * $columnNumber - $global-gutter);
   │            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
```

Also, on `_typography.scss`:

```
    src/assets/scss/util/_util.scss 11:11       -zf-grid-calc-pct()
    src/assets/scss/grid/_grid.scss 152:12      @import
    src/assets/scss/foundation-emails.scss 8:1  root stylesheet

Deprecation Warning on line 180, column 7 of src/assets/scss/components/_typography.scss:
@elseif is deprecated and will not be supported in future Sass versions.

Recommendation: @else if
    ╷
180 │     } @elseif $align == 'right' {
    │       ^^^^^^^
```

In total, I got 8 warnings in different files, 7 of them about `/` as the division sign and one about the `elseif`. **(see note below about this)**

**How can we reproduce this bug?** (not a bug *per se*, but it may turn into one in the future)

Try generating CSS from the SCSS files from Foundation e-mail using a sass lib that follows the current standards, like the one I used (mentioned above).

---

In fact, according to the official SASS docs, division using a `/` character is indeed deprecated and will be removed on a further version and should be replaced by `math.div`: https://sass-lang.com/documentation/breaking-changes/slash-div

The `elseif` without space is not even mentioned in the docs there: https://sass-lang.com/documentation/at-rules/control/if#else-if

UPDATE: i saw that the `elseif` is fixed on master but it is "unfixed" on develop 🤔

**Comment by msandrini** [comment]
Hi,
I opened a forked branch for that: https://github.com/msandrini/foundation-emails/tree/feat/remove-deprecations-sass
I didn't send a PR because I cannot build the project on my machine (Mac M1, lots of issues to build stuff) and I didn't have time to look into it yet. But it is there to whoever has the availability to test and ensure everything is ok.

**Comment by CPatchane** [comment]
Hello @msandrini, I think that the issue is to use `dart-sass` over to `node-sass` since those warnings are for the last versions. Also, `sass:math` are available only in the last `dart-sass` versions.

I pushed a PR: https://github.com/foundation/foundation-emails/pull/1071

If needed, it can been installed as a module using:
```
yarn add foundation-emails@CPatchane/foundation-emails#sass_div
```

Looking forward to get a new official release with those fixes 🙏

**Comment by msandrini** [comment]
Hi, yeah, all is related to this `node-sass`/`dart-sass` migration. I had to migrate because `node-sass` doesn't work on my ARM machine (M1 Mac) so I ended up seeing those. In any case, I appreciate the PR and thanks!

**Comment by joeworkman** [comment]
dart support was added in 2.4
