### ISSUE TITLE
[Getting Started with Sass] Please update Requirements

### ISSUE THREAD

**Issue by LittleHoopoe** [foundation/foundation-emails#1115]
First of all you need NodeJS Version 14! The new LTS Version is not working with node-sass in your package. 
Next you need python to run
`yarn install `
successfully 
after running:
`foundation new --framework emails`

`foundation watch` 
throws this error:
(node:11451) UnhandledPromiseRejectionWarning: TypeError: npm.commands.start.apply is not a function
    at /usr/lib/node_modules/foundation-cli/lib/commands/watch.js:26:24
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11451) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11451) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by joeworkman** [comment]
The foundation CLI is broken at this time. I fixed some of the basics in v2.3.0. You can see the details at https://github.com/foundation/foundation-cli/releases
