### ISSUE TITLE
[Getting Started with CSS] Docs for old version?

### ISSUE THREAD

**Issue by sryze** [foundation/foundation-emails#1117]
**How can we reproduce this bug?**

I would like to see documentation for an old version of Foundation for Emails, because I have a lot of email templates written via this framework.

**What did you expect to happen?**

Expected to find documentation for older versions of the framework.

**What happened instead?**

Found documentation for the latest version only.

**Comment by joeworkman** [comment]
Your best bet at this time is to go the release/tag that you want and build the docs from that version. 

https://github.com/foundation/foundation-emails/releases
