### ISSUE TITLE
Invalid CSS after "  @return math"

### ISSUE THREAD

**Issue by m00nh3ck** [foundation/foundation-emails#1125]
composer1
node v10.24.1
PHP 7.1

devDependencies": {
        "@fancyapps/fancybox": "^3.3.5",
        "cross-env": "^5.1",
        "foundation-emails": "^2.4.0",
        "foundation-sites": "~6.4",
        "jquery.scrollto": "^2.1.2",
        "laravel-mix": "^2.0",
        "motion-ui": "^1.0",
        "node-gd": "^1.5",
        "parallax-js": "^1.0.0"

npm install 
npm run production throwing errors

/resources/assets/sass/mail/index.scss

/node_modules/foundation-emails/scss/util/_util.scss (line 12, column 15)

return math.div(floor(percentage(math.div($colNumber, $totalColumns)) * 1000000), 1000000);

Invalid CSS after "  @return math": expected expression (e.g. 1px, bold), was ".div(floor(percenta"

I have tried several things using sass dart-sass sass-loader but no luck yet.

Any idea will be welcomed

**Comment by mdieudonne** [comment]
Hey there,

I pinned version number to 2.3.1 and it seems to work.

Give it a try

**Comment by m00nh3ck** [comment]
Many thanks for your help. I can confirm it finally works!

"devDependencies": {
        "@fancyapps/fancybox": "^3.3.5",
        "cross-env": "^5.1",
        "foundation-emails": "2.3.1",
        "foundation-sites": "~6.4",
        "jquery.scrollto": "^2.1.2",
        "laravel-mix": "^2.0",
        "motion-ui": "^1.0",
        "node-gd": "^1.5",
        "parallax-js": "^1.0.0"
    }
