### ISSUE TITLE
Documentation Links on website are broken!! https://get.foundation/emails/docs/

### ISSUE THREAD

**Issue by lukeoregan88** [foundation/foundation-emails#1148]
The page links on the documentation site [https://get.foundation/emails/docs/](https://get.foundation/emails/docs/) are broken. Clicking on internal links such as 'Getting Started', 'Guides', or 'Components' leads to a 404 error. It appears to be a routing problem where all links are routing to the root domain instead of the correct path.

For example, the link [https://get.foundation/alignment](https://get.foundation/alignment) ...

**Should be** [https://get.foundation/emails/docs/alignment](https://get.foundation/emails/docs/alignment).

**Comment by joeworkman** [comment]
all fixed now.
