### ISSUE TITLE
Discussion -  Workflow

### ISSUE THREAD

**Issue by gakimball** [foundation/foundation-emails#160]
_From @tdhartwick on December 17, 2015 17:27_

We've created a brand new Gulp workflow for Foundation for emails including a command line interface to templataize emails, inline them and modify Sass.  We want to know if this is even a thing you're interested in using! We have a few questions around this:
1. Will you use our gulp set up?
2. Does Inky do what you need it to do?
3. Is there anything you're using that you'd love to see?

_Copied from original issue: zurb/foundation-emails#9_

**Comment by gakimball** [comment]
_From @txcbenji on December 18, 2015 23:58_

Our current workflow mirrors this one to an extent, though we're living in grunt-land.  We are ( were ) using the most recent version of ink, and then keeping client emails in their own separate repos on bitbucket.  We generally just branch off any similar emails and start there ( with no intention of merging ).  In any case our build process looks like this:
- Code out email ( generally using brackets for it's live preview functionality )
- Run our custom grunt processes that do the following:
  - Runs a url search/replace for images to give them the full path url of the image ( using a common naming convention )
  - Grunt uncss
  - Grunt-processhtml - used to combine our 1 custom css file with the stock ink.css file
  - Grunt-premailer - inlines our styles
  - Grunt minifyhtml - creates a minified version of the build ( we ran across an online mailer who had a character limit that we were hitting )
  - Custom Grunt task to commit the changes back to the current branch
  - Grunt Mailgun - sends a test email to our emailonacid account.
  - Custom grunt task to ssh to our email staging server and then rsync the build files over.

This kind of a process that automates so many of the tedious tasks has given us huge improvements in productivity and drastically cut the overall production time down.

I think the addition of sass and reusable layout templates, and a similar 'build' workflow will be great.  The simplified markup is a godsend, I'm excited to dig a bit deeper and see how we can up our email game even further... So 1st impressions... Well on your way Team Zurb!

**Comment by gakimball** [comment]
_From @leemunroe on December 19, 2015 15:34_

Great job! To echo @txcbenji would be nice to see more integrations like image CDN/path replacement, send a test email, all those things that fit into the end-to-end workflow. But looking awesome.

**Comment by gakimball** [comment]
_From @alfatreze on December 21, 2015 16:53_

Looks nice, but I have an issue building the test, where it generates an error in the sass:
Error in plugin 'sass'
Message:
    scss\app.scss
undefined

Although the generated css is fine, it is not copied to the build directory. 
I can't seem to figure out the reason, does not seem to be an issue with the paths...

**Comment by gakimball** [comment]
_From @macbookandrew on December 21, 2015 20:51_

One suggestion: why not have gulp watch the layouts folder for changes, as well as the pages folder?

**Comment by gakimball** [comment]
_From @kchez on December 21, 2015 21:21_

I vote for @macbookandrew 's suggestion of adding the layouts folder to the default task

**Comment by gakimball** [comment]
_From @zurbrandon on December 22, 2015 0:0_

This won;t be the final build of Foundation for emails. We've set up the 'test' folder as a temporary home inside our docs repo. Eventually it'll follow a pretty similar pattern as Foundation for Sites does when you spin up a new project.

**Comment by gakimball** [comment]
_From @travis-zookacreative on January 4, 2016 16:56_

Some clarification on workflow... Sorry if I missed this anywhere but how is one able to switch between pages for live preview? Essentially I would like to have 1 repo for the client and 1 or 2 layouts. Then every new email just create a new email under "pages". When this happens though the only file that gets livereloaded is the index.html file. How do I switch between files in "pages"?

**Comment by gakimball** [comment]
_From @macbookandrew on January 4, 2016 17:3_

@travis-zookacreative Take a look at [this repo](https://github.com/leemunroe/grunt-email-workflow/) for ideas. I see @leemunroe commented above, so I’m hoping he’s thinking about using Foundation for Emails in his Grunt email workflow plugin. :smile:

**Comment by gakimball** [comment]
_From @travis-zookacreative on January 4, 2016 17:19_

@macbookandrew thanks for sharing, I actually already have my own custom version based off that repo that I have been using for some time. I was hoping the new foundation for emails workflow would replace that entirely.

**Comment by gakimball** [comment]
_From @tdhartwick on January 5, 2016 19:58_

@txcbenji Thanks for sharing your workflow! Can you elaborate on the character limit issue you were running into? We omitted the minifying the HTML with the understanding that most mailers are alright with larger HTML files. Anybody else running into this?

@macbookandrew and @kchez We'll add the watch task to look at both pages and layouts. Thanks for pointing this out! You can track the issue here: https://github.com/zurb/foundation-emails/issues/26

**Comment by gakimball** [comment]
_From @tdhartwick on January 5, 2016 20:3_

@travis-zookacreative To chime in on our question earlier about live reloading, you can update the URL of the BrowserSync server. For instance, we have `index.html` and `basic.html` in our `test/pages` folder. By default BrowserSync will show `index.html` to `localhost:3000`. You can get to `basic.html` by adding the file extension like so: `localhost:3000/basic.html`. Once on this server, it should live update this email. Is this the issue you were describing?

**Comment by gakimball** [comment]
_From @txcbenji on January 5, 2016 20:12_

@tdhartwick Sure thing... it was in vertical response, they had a 50k character limit in the custom text editor they use for you to input your code, so with some of our larger and more complicated layouts, after inlining, our email file was ending up over that limit, so we added the minification step in as part of our core build-out, just in case we needed it.  We later learned we could ask them to increase that limit for our account, but it involved getting their tech dept on chat and getting them to change it.  We only had 1 client that was using VR, and have since convinced them to let us use campaign monitor, so we haven't run in to it for awhile.

**Comment by gakimball** [comment]
_From @travis-zookacreative on January 5, 2016 23:25_

@tdhartwick thats it! Not totally sure why that didn't work for me the first few times but I'll give it a go again. Thanks!

**Comment by gakimball** [comment]
_From @kchez on January 6, 2016 19:48_

@txcbenji, @tdhartwick VR is one of my primary ESP (derp), and I did have to up my limit to 75K and still went over that limit (prior to using this new templating language). So yes, it's a reality some of us have to deal with, but I haven't tried it yet with new and improved version. I'll report back any issues.

**Comment by gakimball** [comment]
_From @tdhartwick on January 8, 2016 23:28_

Thanks for the feedback @txcbenji. Interested in hearing your feedback!

**Comment by wssrstrm** [comment]
@gakimball and @tdhartwick: Wanted to chime in here, as I am deeply, deeply interested in this workflow and have been using it since practically the day you made it available.

The workflow is amazing and I have used it to very, very quickly integrate Foundation for Emails into my projects without straying from your provided gulpfile. 

Inky is terrific so far, does what we need it to do basically pretty hampered but hampered by the fact that very little about Inky is documented and the Zurb for Email documentation itself is for 1.0 and not the current 2.0rc.

This all to basically to say that these products are terrific and the only issue is that they are not moving thru the release and documentation process quickly enough for me to abandon all my other tools!

Please let me know if I can be helpful in any way on this.

**Comment by gakimball** [comment]
We deployed the docs along with the stable 2.0 version on Wednesday. All of the samples include plain HTML and Inky examples: http://foundation.zurb.com/emails/docs/

**Comment by gakimball** [comment]
Now that 2.0 is out, we're going to close the discussion threads. Thanks so much for the feedback, and if you have further ideas, feel free to open new issues to get a discussion going :)
