### ISSUE TITLE
Test template not working responsively on Edge, Firefox and IE (works fine in Chrome)

### ISSUE THREAD

**Issue by gakimball** [foundation/foundation-emails#163]
_From @bago on December 18, 2015 18:43_

When I test the bundled template using "npm test" I can see it correctly react to window-width changes only on Chrome while it breaks on Firefox, IE11, Edge 13 (windows 10).
![edge-13-foundemail2](https://cloud.githubusercontent.com/assets/173498/11903978/5dd1a0c2-a5bd-11e5-9fe2-fbf8d667379d.png)

I guess the issue is related to some CSS applying a `display: block !important` to `<table>` tags and Chrome not supporting altering the display on `table` (and other table related) tags.

Of course this doesn't seem an issue with foundation for emails itself, but maybe the default css.

_Copied from original issue: zurb/foundation-emails#12_

**Comment by gakimball** [comment]
_From @akeilox on December 18, 2015 19:23_

I was about to post the same, having npm test launched first on firefox noticed the layout issue on resize, not present in Chrome. IE 11 is the same, not tested on Edge.

**Comment by gakimball** [comment]
_From @tdhartwick on December 18, 2015 23:14_

We've found that browsers render emails a little wonky sometimes, especially when testing. We've been working on ironing out all of the visual bugs with Litmus tests. You can see the current state of that template here (inlined with `npm run production`): https://litmus.com/checklist/emails/public/753f023

I'm not sure if we'll be able to reconcile this for testing purposes however. Maybe we recommend people to use chrome, or webkit browsers, if they want to test locally before running it through Litmus or other email testers.

**Comment by tdhartwick** [comment]
Looks like this issue was closed. Our recommendation is to develop within chrome and test using Litmus or Emails on Acid.
