### ISSUE TITLE
Small-12 needs to stack to 100%

### ISSUE THREAD

**Issue by gakimball** [foundation/foundation-emails#166]
_From @tdhartwick on January 6, 2016 17:33_

In order to have the small grids work, and not automatically stack on small, we needed to remove the `display: block` from the wrapper element. This now makes all of the other small combinations work, i.e. a `small=5` and a `small=7` now work. The problem occurs when we have multiple `small=12`'s that need to stack.

We should either:
- Remove wrapper elements. Or...
- Target the parent wrapper of small-12 columns to have `display: block`

My hunch is that we should offset what wrappers used to do into the row table

_Copied from original issue: zurb/foundation-emails#27_

**Comment by rafibomb** [comment]
@tdhartwick Is this solved for already?

**Comment by rafibomb** [comment]
This has been resolved.
