### ISSUE TITLE
.wrapper distorting column size on small breakpoint

### ISSUE THREAD

**Issue by gakimball** [foundation/foundation-emails#167]
_From @treechime on February 5, 2016 2:8_

I may be doing something wrong (I've only been playing with this for about an hour) but using the examples given, on mobile, if I have two columns the .wrapper td will distribute it's space evenly, instead of as determined by the column size on the table inside it. 

```
<container>
  <row>
    <columns large='4' small='9'>
      <p>Phasellus dictum sapien a neque luctus cursus. Pellentesque sem dolor, fringilla et pharetra vitae. consequat vel lacus. Sed iaculis pulvinar ligula, ornare fringilla ante viverra et. In hac habitasse platea dictumst. Donec vel orci mi, eu congue justo. Integer eget odio est, eget malesuada lorem. Aenean sed tellus dui, vitae viverra risus. Nullam massa sapien, pulvinar eleifend fringilla id, convallis eget nisi. Mauris a sagittis dui. Pellentesque non lacinia mi. Fusce sit amet libero sit amet erat venenatis sollicitudin vitae vel eros. Cras nunc sapien, interdum sit amet porttitor ut, congue quis urna.</p>
    </columns>
    <columns large='8' small='3'>
      <p>Phasellus dictum sapien a neque luctus cursus. Pellentesque sem dolor, fringilla et pharetra vitae. consequat vel lacus. Sed iaculis pulvinar ligula, ornare fringilla ante viverra et. In hac habitasse platea dictumst. Donec vel orci mi, eu congue justo. Integer eget odio est, eget malesuada lorem. Aenean sed tellus dui, vitae viverra risus. Nullam massa sapien, pulvinar eleifend fringilla id, convallis eget nisi. Mauris a sagittis dui. Pellentesque non lacinia mi. Fusce sit amet libero sit amet erat venenatis sollicitudin vitae vel eros. Cras nunc sapien, interdum sit amet porttitor ut, congue quis urna.</p>
    </columns>
  </row>
</container>
```

On desktop the above is fine but on mobile it shows the .wrapper tds as 50% of the width and distributing the column widths within that 50% causing them to be the wrong widths.

![slack_for_ios_upload_1024](https://cloud.githubusercontent.com/assets/8661599/12836028/dd393186-cc00-11e5-88af-aceaa9fe7a4b.jpg)

I found adding `display:inline` to .wrapper on the small breakpoint fixed this, but I assume that might break something else.

_Copied from original issue: zurb/foundation-emails#32_

**Comment by rafibomb** [comment]
@treechime There is no longer a .wrapped need for the new markup. I didn't see where you're using it?

**Comment by tdhartwick** [comment]
V2 has an updated syntax that circumvents this issue. Let us know if you're still experiencing this with the latest build. Thanks!
