### ISSUE TITLE
Variable naming needs updates

### ISSUE THREAD

**Issue by gakimball** [foundation/foundation-emails#169]
_From @rafibomb on February 8, 2016 3:32_

Couple variable might need renaming since the markup has been simplified:

$wrapper-padding-top
$sub-column-padding-right

_Copied from original issue: zurb/foundation-emails#34_

**Comment by rafibomb** [comment]
Done and removed unneeded variable
https://github.com/zurb/foundation-emails/commit/7139a1513bd7793c3e0977faeb73c085e3ba01d9
