### ISSUE TITLE
Grid column padding variable does not affect container

### ISSUE THREAD

**Issue by gakimball** [foundation/foundation-emails#170]
_From @rafibomb on February 8, 2016 3:35_

Trying to space text away from container edge. I expect the column padding to handle the spacing of text from the container edge.

Changing $grid-column-gutter does not affect this.

_Copied from original issue: zurb/foundation-emails#35_

**Comment by gakimball** [comment]
_From @rafibomb on February 8, 2016 3:36_

Looks like it's defined on the `<th>` at 8px. This needs a setting.

**Comment by gakimball** [comment]
_From @rafibomb on February 9, 2016 22:30_

Actually, the variable doesn't take effect at all.

**Comment by rafibomb** [comment]
Fixed! New variable is `$global-gutter`
