### ISSUE TITLE
Changing $body-font-size does nothing

### ISSUE THREAD

**Issue by gakimball** [foundation/foundation-emails#171]
_From @rafibomb on February 8, 2016 3:40_

Expected this to change the body font size from 14px. 

No effect.

_Copied from original issue: zurb/foundation-emails#36_

**Comment by marcusmoore** [comment]
(At least in Chrome) the `font-size` is compiled to `12px` no matter what `$body-font-size` is set to. I'm starting to dive in to see where this is coming from...

**Comment by rafibomb** [comment]
Fixed - now `$global-font-size` is the typeography variable we're using
