### ISSUE TITLE
Changes not taking effect in production

### ISSUE THREAD

**Issue by gakimball** [foundation/foundation-emails#174]
_From @rafibomb on February 10, 2016 0:18_

Running `npm run production` starts the server and loads the page in browser. Changing CSS does not show until command is run again.

_Copied from original issue: zurb/foundation-emails#40_

**Comment by gakimball** [comment]
Confirmed to still be happening in the [template repo](https://github.com/zurb/foundation-emails-template).

**Comment by gakimball** [comment]
This is only an issue if we need to be able to live develop with the inliner. Which is to say, you can keep the server running and it inlines every time, versus you running the inlining process once.

@tdhartwick @rafibomb Do we need live watching functionality with the inlining process? With the other frameworks, when you build for production, it's a one-time build.

**Comment by rafibomb** [comment]
It would be better to have this run all the time - but only be used when debugging and testing for production.

**Comment by gakimball** [comment]
Made some changes to the template that resolve this: 8b7ee9efa79b8b13ccdc325bf81b4e0181eaaeea

One issue is that the `inline` task in the Gulpfile would only run once, right when you hit `npm run build`. However, when files change, only the `pages` task would run, not the `inline` task after.

Another issue is that Sass changes would not re-run the inlining process—remember that even if the page didn't change, if the CSS changes, you have to re-inline. Now, whenever you change any HTML or CSS, the inlining process starts again.
