### ISSUE TITLE
Buttons should have a margin bottom

### ISSUE THREAD

**Issue by gakimball** [foundation/foundation-emails#175]
_From @rafibomb on February 10, 2016 0:59_

This matters on small screens when you expect the buttons to stack. Since there is a touch target, it doesn't make sense to have them stacked up without a space.

_Copied from original issue: zurb/foundation-emails#41_

**Comment by kchez** [comment]
The margin bottom on buttons should be placed on 
`table.button` and not `table.button table` ('button.scss:61' ) because if devs need to add a border bottom, as it stands now, there will be a gap of space above the border.

-- since this is closed, i'm reopening as new issue.

**Comment by rafibomb** [comment]
New issue opened https://github.com/zurb/foundation-emails/issues/181
