### ISSUE TITLE
Project Can't Be Deleted - Node Paths Too Long

### ISSUE THREAD

**Issue by gakimball** [foundation/foundation-emails#177]
_From @kchez on February 22, 2016 18:51_

Having issues deleting a project folder. I'm getting messages about filename too long or path too long.  This is a huge issue for regular users.  And my solution may not work for others.  **Is there a better way to package your dependencies?**

Installed both ways and got different results:
1. **Using the CLI** = resulted with 21 items in node_modules\
   ![installed-using-cli-21-node-modules](https://cloud.githubusercontent.com/assets/11340351/13230470/7f6ec64e-d973-11e5-90a8-b9df79bb03f4.png)
2. **Manual Setup** = resulted with **711 items** in node_modules. **Why so many??***
   ![installed-manually-711-node-modules](https://cloud.githubusercontent.com/assets/11340351/13230477/820a128c-d973-11e5-8328-d6ebeb92f3c8.png)

I did a little digging and what I learned was that in Windows and DOS, there is a flag called MAX_PATH which has value 260, meaning a file path can have a maximum of 260 characters including the drive. So, when files are created by other programs that have more than 260 characters they cannot be deleted using Windows or DOS commands. You’ll get the message file name too long or path too long.

My solution was to use Robocopy as explained here: https://blog.bertvanlangen.com/articles/path-too-long-use-robocopy/.  See attached robocopy output log. 
[path-too-long-robocopy-output.txt](https://github.com/zurb/foundation-emails/files/141185/path-too-long-robocopy-output.txt)

Running:
- Windows 7
- node v. 4.2.6
- npm v. 3.7.2.  (latest version is supposed to fix this known issue, as described here: https://www.npmjs.com/package/npm-windows-upgrade - but in my case, it didn't.)

_Copied from original issue: zurb/foundation-emails#46_

**Comment by kevin-coyle** [comment]
I think this is a common windows issue with npm, not specifically foundation emails. I believe it's been fixed in npm 3. See here for more details. https://github.com/nodejs/node-v0.x-archive/issues/6960

**Comment by gakimball** [comment]
Yeah, unfortunately it's not something we can fix. We're using Node and npm the exact same way everyone else does, and npm has its share of quirks.

**Comment by kamila1011** [comment]
I am getting this same issue and its very difficult to solve this problem without any third party app, i guess the best thing to do is to use a third party app like Long Path Tool. Just download it and use it to solve this issue. I hope this would help.

**Comment by riona01** [comment]
Try long path tool. it works awesome

**Comment by Ankit546** [comment]
I too have encountered this problem with node packages because they are deeply nested so basically we can't perform operation on that file because they are listed as "long path name" in windows API. It allows only 256 characters. To solve this I used GS Richcopy 360. You too can use this to get rid of this problem. Although its paid but it will save your time and efforts. And TIME IS MONEY!
