### ISSUE TITLE
It work with gmail ?

### ISSUE THREAD

**Issue by Chrysweel** [foundation/foundation-emails#180]
Hello.

I just download this project. And I customized one basic template with one css which I found in tools

> https://cdnjs.com/libraries/zurb-ink

But in gmail this email, dont have styles and the content render very bad... Any idea ? This templates works in all client as gmail, hotmail.. etc ?

Thanks in advance !

**Comment by jondcallahan** [comment]
You need to inline the styles for them to work in gmail. Consider using http://foundation.zurb.com/emails/inliner.html

**Comment by rafibomb** [comment]
Thanks @jondcallahan !

@Chrysweel We'll close this as inlining will likely solve it for you. If you find any issues let us know!

**Comment by chunkitdesign** [comment]
as i know the responsive style will be moved into the body tag. And Google Gmail will also strip the style tag inside the body tag. Then how can the foundation email be responsive? thanks very much
