### ISSUE TITLE
Buttons margin bottom #175

### ISSUE THREAD

**Issue by kchez** [foundation/foundation-emails#181]
The margin bottom on buttons that was added from Issue #175, should I think be placed on 
`table.button` and not `table.button table` ('button.scss:61' ) because if devs need to add a border bottom, as it stands now, there will be a gap of space above the border.
![buttons-table-button-table](https://cloud.githubusercontent.com/assets/11340351/13254840/46e04d22-da11-11e5-8036-9f786e9da3fe.png)
![buttons-table-button](https://cloud.githubusercontent.com/assets/11340351/13254843/498fc192-da11-11e5-92d0-17248eddbe1b.png)

**Comment by rafibomb** [comment]
Yes, looks like with the new markup the margin should be on the outer table.

**Comment by kball** [comment]
fixed in https://github.com/zurb/foundation-emails/commit/fcd3040fedbca6a66fcd59cc9e1b2de3bf47abed
