### ISSUE TITLE
Why is the img element default to float: left

### ISSUE THREAD

**Issue by garretthyder** [foundation/foundation-emails#183]
Hello,

I built a template using Zurb Ink that I'm using on Mailchimp, I realized that the align functionality on images within the Mailchimp editor had no affect. Upon inspecting I discovered that images are defaulting to float:left as the Zurb template has this specified in the css. Is there a reason for this? Can I simply drop that css or will that cause issues with the boilerplate?

Thank you

**Comment by rafibomb** [comment]
Are you using version 1 (ink) for Foundation for Emails 2.0 RC?

**Comment by garretthyder** [comment]
Hi @rafibomb I'm using Ink v1.0.5

**Comment by tdhartwick** [comment]
That's a good question! It looks like this rule hasn't made it into v2. We're no longer supporting v1, however we're merging pull requests into our v1.0.0 branch. However, we recommend using v2. Closing this issue in the meantime. Thanks!

**Comment by garretthyder** [comment]
Thanks for the follow-up
