### ISSUE TITLE
Visibility Class naming

### ISSUE THREAD

**Issue by rafibomb** [foundation/foundation-emails#187]
Naming of visibility classes should replicate Foundation for Sites

Currently they are 
- .hide-for-small,
- .show-for-desktop 
- .show-for-small,
- .hide-for-desktop

Should be 
- .hide-for-small-only
- .show-for-small-only

**Comment by rafibomb** [comment]
just pushed up some changes https://github.com/zurb/foundation-emails/commit/f14e62d3b83b79d7f6e6c4246e5bb07fdfd850e4

**Comment by gakimball** [comment]
Looks correct! :)
