### ISSUE TITLE
[bug] 12 column row not rendering correctly in gmail

### ISSUE THREAD

**Issue by allenwoot** [foundation/foundation-emails#191]
Code for repro

```
<table class="row">
  <tr>
    <th class="small-12 large-12 columns first last">
      content
    </th>
  </tr>
</table>
```

`box-sizing` does not work consistently across clients. However, `td` elements with `columns large-12 small-12 first last`, for example, require that the client accepts box-sizing. otherwise the padding leaks outside of the element, causing rendering issues in gmail.
Possible resolution: Instead of setting width `($i*100/$num-cols)%`, account for gutters. So again, something more like `($i*(100-2*$grid_gutter)/$num-cols)%`, though this may need to get a bit fancier to handle `collapse`s correctly

Workaround: Use 2 tables :disappointed: 
1st table: Set up `columns first last`
2nd table: Set up `small-12 large-12 first last`
This means the first table sets padding, and the 2nd table sets width within the constraints of that padding

If this can be fixed so that we don't have to have nested tables, that would be much appreciated!

**Comment by rafibomb** [comment]
Thanks Allen - we'll test this out. 

We'd love to avoid adding an extra table if possible.

**Comment by rafibomb** [comment]
@tdhartwick Did you see any issues like this in testing?

**Comment by rafibomb** [comment]
@allenwoot We tested some templates with the new grid markup. What email clients are you seeing issues on? 

We tested all Gmail, yahoo, ofice365, android, ios, outlook and outlook.com

**Comment by allenwoot** [comment]
@rafibomb I'm seeing this specifically on the android gmail app (using litmus) using the first version of the RC.

Let me know if you'd like specific repro steps.

**Comment by kball** [comment]
@allenwoot I'm trying to work on this right now and I'm not seeing any obvious emails in the android gmail app on litmus.  See below:

<img width="361" alt="grid_test_-_litmus_builder" src="https://cloud.githubusercontent.com/assets/44007/13652660/46620a0a-e602-11e5-8f95-0ebe0be453e2.png">

This is using the code

```
<table class="container">
  <tr>
    <td>
      <table class="row">
        <tr>
          <th class="small-12 large-12 columns first last">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam aliquid tenetur dignissimos repellendus sapiente reprehenderit vero, possimus omnis necessitatibus ad, debitis, distinctio ea laudantium. Corrupti veniam harum sint, laboriosam aut.</p>
          </th>
        </tr>
      </table>
    </td>
  </tr>
</table>
```

I am working off of the latest v2.0 branch rather than the first RC, so that may have something to do with it.  @tdhartwick @gakimball @rafibomb  do you know if any changes you've made since would expect to address this?

**Comment by rafibomb** [comment]
I can't replicate it right now. Perhaps we resolved in a previous commit. We'll close this now, please open a new issue if you see this happening so we can address it. Thanks!
