### ISSUE TITLE
[question] How to handle all email templates in a big company in different languages and different email management services?

### ISSUE THREAD

**Issue by timaschew** [foundation/foundation-emails#192]
We have approximately 100 templates.
Of course many of them are not really necessary if we would use partials, but this is the step we want to go now. And foundation-emails, especially the new version looks awesome for this use case!

There are some other parts which I want to ask for best practice:
Imagine your company have at least 3 departments: marketing, customer support, sales.
Each of the department uses another email management service, for instance: MailChimp, Zendesk, etc. 
And each of the services provides its own email template managing mechanism.
Does it make sense to handle all the email templates at a central place?

Another question: the content of the emails can be splitted into 2 groups: 
- recipient related content (customer for instance)
- langauge related content

The recipient related content (name, email, interests) is stored at the email management service in most cases, that's okay.
But the language stuff is not and there is also no support to provide multi language templates at all at the services. So they need to be stored somewhere else, maybe the same central place as I asked above?

**Comment by rafibomb** [comment]
That's a lot of templates! 

You may be best off managing the templates in a single project on GitHub. Each department can have it's headers and footers that they'd re-use in HTML partials.

How are you language templates generated. If they are static translated version, then you can make each language a separate partial as well then just include the language you need.

Does that make sense/help?

**Comment by timaschew** [comment]
Yes that sounds good, I already started with an own GitHub repo and panini and add i18n into it. It works very well! I'm now working on a preview feature. I will show you when it's done.

**Comment by rafibomb** [comment]
Awesome!

**Comment by lbineau** [comment]
@timaschew Do you have a sample of i18n implementation ? I have also emailing for multiple languages to produce.

**Comment by timaschew** [comment]
I hope this helps
https://gist.github.com/timaschew/a8f4c6bcf5af3f53bd65cd22e9aaa931

**Comment by lbineau** [comment]
Thanks for reply.
I didn't want to modify the library itself and came with a simpler solution for my case (not as elegant as yours !): https://gist.github.com/lbineau/823c40e85e0ec2604895df8cc81bbd1f
I added a setlang and i18n helper for mustache.
Then you can launch `npm run start --lang=cn`, it will create a dist/cn folder with you email translated
