### ISSUE TITLE
Enable Partials being compiled by Inky in Foundation for Emails Template

### ISSUE THREAD

**Issue by hansspiess** [foundation/foundation-emails#193]
By moving `.pipe(inky())` past `.pipe(panini())` in the pages() function in gulpfile.babel.js in the _Foundation for Emails Template_ Inky compiling of partials would be enabled i guess.

**Comment by gakimball** [comment]
Does it work without any errors? If not, we can make fixes to Inky to compensate.

**Comment by hansspiess** [comment]
the only error (which is not related to the issue i guess) is that special characters like ä, ö etc. (and sadly, also when html-escaped) throw the following error:

```
[08:44:35] Failed to load external module babel-register
[08:44:35] Requiring external module babel-core/register
[08:44:42] Using gulpfile ~/fe2/gulpfile.babel.js
[08:44:42] Starting 'default'...
[08:44:42] Starting 'build'...
[08:44:42] Starting 'clean'...
[08:44:42] Finished 'clean' after 5.3 ms
[08:44:42] Starting 'pages'...
[08:44:43] 'pages' errored after 397 ms
[08:44:43] SyntaxError: Unmatched selector: &#xF6;nnen diesen Newsletter <a href="#">hier abbestellen</a>.

    at parse (/fe2/node_modules/inky/node_modules/cheerio/node_modules/css-select/node_modules/css-what/index.js:85:9)
    at compileUnsafe (/fe2/node_modules/inky/node_modules/cheerio/node_modules/css-select/lib/compile.js:31:14)
    at select (/fe2/node_modules/inky/node_modules/cheerio/node_modules/css-select/index.js:18:49)
    at CSSselect (/fe2/node_modules/inky/node_modules/cheerio/node_modules/css-select/index.js:41:9)
    at [object Object].exports.find (/fe2/node_modules/inky/node_modules/cheerio/lib/api/traversing.js:34:21)
    at [object Object].module.exports (/fe2/node_modules/inky/node_modules/cheerio/lib/cheerio.js:81:18)
    at new initialize (/fe2/node_modules/inky/node_modules/cheerio/lib/static.js:26:20)
    at initialize (/fe2/node_modules/inky/node_modules/cheerio/lib/static.js:23:14)
    at Inky.findNestedComponents (/fe2/node_modules/inky/lib/inky.js:74:16)
    at Inky.<anonymous> (/fe2/node_modules/inky/lib/inky.js:84:55)
```

**Comment by hansspiess** [comment]
i cant reproduce the [described error](https://github.com/zurb/foundation-emails/issues/193#issuecomment-189151162) in a fresh [foundation-cli installation of the template](https://github.com/zurb/foundation-emails-template#using-the-cli).

[edit] i have, however, reproduced the error: it happens when a special char is followed by an <a> tag without any other tag between. as in:
`Sie können diesen Newsletter <a href="#">hier abbestellen</a>.`
however i simply masked the char with a naked span, then everything passed the watch pipe.

**Comment by gakimball** [comment]
For the special character thing, can you give me a small sample piece of markup to test so we can maybe put together a fix?

**Comment by hansspiess** [comment]
modified pages() function in `gulpfile.babel.js`:

```
function pages() {
  return gulp.src('src/pages/**/*.html')
    .pipe(panini({
      root: 'src/pages',
      layouts: 'src/layouts',
      partials: 'src/partials'
    }))
    .pipe(inky())
    .pipe(gulp.dest('dist'));
}
```

`/src/layouts/default.html`

```
{{!-- This is the base layout for your project, and will be used on every page. --}}
<!doctype html>
<html>
  <head>
    <link rel="stylesheet" type="text/css" href="css/app.css">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width">
    <!-- inject:css -->
    <!-- endinject -->
  </head>
  <body class="c-bg--white">
    <table class="body">
      <tr>
        <td class="center" align="center" valign="top">
          <center>

            <!-- header -->
            <container class="c-fullwidth c-fullwidth--header">
            <container>

              {{> header.read-online }}
              {{> header.branding }}

            </container>
            </container>
            <!-- // header -->

            {{> body}}

            <!-- footer -->
            <container class="c-fullwidth c-fullwidth--footer">
            <container>

              {{> footer.imprint }}
              {{> footer.unsubscribe }}

            </container>
            </container>
            <!-- // footer -->

          </center>
        </td>
      </tr>
    </table>
  </body>
</html>
```

`/src/partials/footer.unsubscribe.html`

```

            <!-- footer.unsubscribe row -->
            <row class="collapse c-stripe">
              <columns small="8" large="8" class="c-stripe--white c-stripe--bottom">
                <small class="small hide-for-small">
                  Sie können diesen Newsletter <a href="#">hier abbestellen</a>.
                </small>
                <!--[if !mso]><!-->
                <div class="gmail">
                <table><tr><td>
                  <small class="small hide-for-desktop">
                    Newsletter <a href="#">abbestellen</a>.
                  </small>
                </td></tr></table>
                </div>
                </div>
                <!--<![endif]-->
              </columns>
              <columns small="4" large="4" class="c-stripe--green">&nbsp;</columns>
            </row>
            <!-- // footer.unsubscribe row -->

```

the `ö` char in the partial causes the error. when appearing behind a html tag on the same line, the error does not show up. must be something with inky and char encoding i guess.

**Comment by gakimball** [comment]
I was able to narrow this down to the use of special characters inside of an Inky-specific tag. This HTML creates the error:

``` html
<container>Sie können diesen Newsletter <a href="#">hier abbestellen</a>.</container>
```

You can replace `<container>` with any Inky tag and it will still break the same way. Looking into it!

**Comment by gakimball** [comment]
Fixed via zurb/inky@10393e0d6be7568f73e70448a0ee19d36b6a2eb0

We have a few more fixes to bring in before we patch Inky, but you can get the fix now by setting the version of `inky` to `master` in your `package.json`.

**Comment by hansspiess** [comment]
thanks for the quick help! however, i don't know how to update inky in my project to the fixed version, could you please be more specific?

**Comment by gakimball** [comment]
The `package.json` in your project has a list of every version of every library you're using, including Inky, the latest version of which is `1.0.0`. I won't be releasing a `1.0.1` until we get a few more fixes in.

If you need the fix now, it's possible to pull a Node library straight from GitHub. I also just realized the instructions I gave you are slightly inaccurate, so here's the right way to do it. In your `package.json`, under `devDependencies`, look for `inky` and change it to look like this:

``` json
"inky": "zurb/inky"
```

After you make the change, run `npm update`. That's going to pull straight from the `master` branch of the GitHub repo [zurb/inky](https://github.com/zurb/inky). You can basically pull the contents of any Git repo you want to load it into your project.

**Comment by hansspiess** [comment]
works! thanks again @gakimball !
