### ISSUE TITLE
[bug] Break tags moved around

### ISSUE THREAD

**Issue by jacobjpope** [foundation/foundation-emails#195]
This happens when I place a `<br>` tag between a closing `</columns>` and `</row>`.  It is moved above the opening `<table class="row">` in the `<td>` parent element.  Weirdly enough, this doesn't occur when placed between the closing `</row>` and `</container>`.

**Comment by gakimball** [comment]
Can you post a full code sample to help us recreate it?

**Comment by jacobjpope** [comment]
In /pages/index.html

```
<container>
  <row>
    <columns small="12" large="12">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
      quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
      consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
      cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
      proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    </columns>
    <br>
  </row>
</container>
```

This may be a browser specific bug and might not carry over to the emails.  In Firefox and Chrome they both move the `<br>` tag but the compiled code has it in the correct spot.

**Comment by JayBizzle** [comment]
@jacobjpope You wouldn't do this though would you? It's invalid markup

``` html
<table>
   <tr>
        <td>Some content</td>
        <br>
   </tr>
</table>
```

**Comment by gakimball** [comment]
@JayBizzle Yeah, if it's invalid markup then some browsers might handle it differently, in which case there's not much we can do about it.

Maybe @tdhartwick can chime in on a better way to create vertical space between elements. I'm guessing that's what you're trying to do?

**Comment by jacobjpope** [comment]
@JayBizzle very good point, if it's invalid markup then this is irrelevant.  Closing the issue!
