### ISSUE TITLE
Suggestion to make background color work in Yahoo mail

### ISSUE THREAD

**Issue by JulesWebb** [foundation/foundation-emails#196]
Hello

I realize that Yahoo is not on your list of supported clients, but thought this easy to implement tidbit would be worth taking note of.

In order to force a background color in yahoo mail, it needs to be applied to the table class="body" element.

I successfully tested adding background: #mycolor to .body. ---I did NOT remove the background color from the body element.

QUESTION: Why isn't there a global variable for the background color in src/assets/scss/_settings.scss?

Cheers!
jules

**Comment by jacobjpope** [comment]
I believe they are still cleaning up the sass, as is referenced in this issue https://github.com/zurb/foundation-emails/issues/184

Background color is in that file right now, so hopefully we will see it moved into the settings.scss

**Comment by JulesWebb** [comment]
Thanks Jacob ;)

**Comment by rafibomb** [comment]
The question is, should there be a variable for a body background color?

It sounds good to us - we'll consider this a feature request!

**Comment by JulesWebb** [comment]
@rafibomb --Yay ;)

What about including the background color on the body class as well as the body element?

**Comment by jacobjpope** [comment]
Background color (and background images if possible) support would be very useful! +1 to this request.

**Comment by JulesWebb** [comment]
I think it will be a long time before email clients support the use of background images, but it would be nice ;)

**Comment by jacobjpope** [comment]
Campaign Monitor's bulletproof backgrounds work pretty well with fallbacks for those clients that don't https://backgrounds.cm/

**Comment by JulesWebb** [comment]
I'm impressed! Thanks for the info and link.

**Comment by rafibomb** [comment]
So we did this:

`$body-background-color: $light-gray;`

It applies body, table.body (some clients strip out the body tag), and the html tag.

**Comment by rafibomb** [comment]
Done: https://github.com/zurb/foundation-emails/commit/ad98f78cdf0a5de27b085efaddba6ea6d5fd71bf

Thanks for the report!

And @jacobjpope  That's a great reference!
