### ISSUE TITLE
Updating $header-font-family global variable has no effect

### ISSUE THREAD

**Issue by JulesWebb** [foundation/foundation-emails#197]
RE: src/assets/scss/_settings.scss section 10. Typography
Updating $header-font-family has no effect. The $global-font-family variable is used instead.

I forced changes using the app.scss file. Just thought the feedback might be helpful
## My system details

OS: Windows 7 Pro
using Windows Shell and Foundation CLI

You guys are doing a stellar job of streaming the creation of email templates. Thank you!

Cheers!
Jules

**Comment by rafibomb** [comment]
Thanks for the props Jules! Looking into this one, I see the setting is set up correctly

```

h1,
h2,
h3,
h4,
h5,
h6 {
  word-break: normal;
  font-family: $header-font-family;
}
```

But the `$header-font-family: $global-font-family !default;` didn't have the default flag.

**Comment by rafibomb** [comment]
This fixes it https://github.com/zurb/foundation-emails/commit/0f72b0973101b81b0ed0019d2f92c2900bd4ba1f

**Comment by JulesWebb** [comment]
Thanks Rafi!
