### ISSUE TITLE
npm install fails for v2 

### ISSUE THREAD

**Issue by aacase** [foundation/foundation-emails#198]
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0

npm ERR! No compatible version found: inky@^1.0.0
npm ERR! Valid install targets:
npm ERR! 1.0.0-rc.4, 1.0.0-rc.3, 1.0.0-rc.2, 1.0.0-rc.1, 0.4.0, 0.3.0, 0.2.0, 0.1.0, 0.0.1

**Comment by gakimball** [comment]
Run `npm install inky` and it should install fine now. The new version didn't properly publish the first time.
