### ISSUE TITLE
Can't run build

### ISSUE THREAD

**Issue by leolopes** [foundation/foundation-emails#199]
I tried to run both `npm start` and `npm run build` and ran into problema with, probably, Gulp.
I attached the log for `npm run build`.
[npm-debug.log.txt](https://github.com/zurb/foundation-emails/files/152705/npm-debug.log.txt)

**Comment by gakimball** [comment]
Did you get an error in your console? `npm-debug.log` files don't always show a full stack trace, so we can't really see what's happening.

**Comment by rafibomb** [comment]
We'll need more info to help you with this. We'll close this issue, you can open a new if your still having issues with this. Thanks!

**Comment by rodoneill** [comment]
I'm getting the same problem with `npm run build`, however `foundation build` works fine.
