### ISSUE TITLE
Contribution guidelines need updating for v2.0

### ISSUE THREAD

**Issue by lurnid** [foundation/foundation-emails#202]
The [contribution guidelines](https://github.com/zurb/foundation-emails/blob/v2.0/CONTRIBUTING.md) need to be updated for version 2.0 to reflect the use of gulp instead of grunt.

**Comment by gakimball** [comment]
Yep, that appears to be boilerplate from another project.

**Comment by gakimball** [comment]
16915b6c6bbfdff7f06d771484fb9c648a3a4907
