### ISSUE TITLE
With OWA signature in mind.

### ISSUE THREAD

**Issue by paxperscientiam** [foundation/foundation-emails#204]
Hello y'all,

After much research, I have come to understand the Microsoft Exchange (OWA) limits signatures to 8096 bytes (at least in its latest iteration). Why? I have no idea, but it is what it is; signatures must obey this rule.

To this end, I think it would be very helpful to have a mode(?) that caters to OWA and it's mysterious byte size limitation for signatures. Use-case is to help developers create HTML sigs for businesses that use Microsoft Exchange server.

**Comment by rafibomb** [comment]
Hi
I'm not sure what you're referring to in context of an email framework. What changes are you looking for in the framework that would address this? Thanks!

**Comment by paxperscientiam** [comment]
Hi @rafibomb !

Just to quickly clarify the above, the limitation is even tighter than I first realized: the 8096bytes is the allowable size for the HTML signature + plain text.

In the context of an email framework, businesses that use OWA/Exchange server could employ foundation-emails to design corporate-approved employee signatures. An administrator could "install" a single design to be applied globally, such that all outgoing email uses the same design.

So, catering to this niche would, I think, expand Zurb's user-base as well the clientele base.

Now for the "how." Given the very tight byte limit, it would be necessary for the build process to strip away "id" and "class" attributes, assuming complete in-lining. Classes that cannot be in-lined -- barring specialty classes like ".ExternalClass" -- should have their names truncated.

I should note that I'm a bit behind the times; I'm still using Ink. Perhaps the above is handled by the new build process?

I could go into more detail and even do more research if you think this is an avenue worth pursuing.

**Comment by rafibomb** [comment]
Wouldn't stripping out the classes and id's make debugging very difficult? It might be an interesting option for the inliner. The inliner is using the latest build from Premailer. If you use the inliner there it has those options http://premailer.dialect.ca/

**Comment by rafibomb** [comment]
We'll close this here as Premailer has a solution for it. We added this to a milestone for a later release: https://github.com/zurb/foundation-emails/issues/248

**Comment by paxperscientiam** [comment]
@rafibomb good to see it becoming a feature for the next milestone.
