### ISSUE TITLE
[Button] Border-radius CSS needs to be added

### ISSUE THREAD

**Issue by rafibomb** [foundation/foundation-emails#214]
A variable exists. It needs to be applied on the `.radius` class or the `.rounded` class. The border and the `a` needs to get the radius when the classes are applied.

$button-radius: $global-radius !default;

**Comment by rafibomb** [comment]
We added the correct CSS to make this work: https://github.com/zurb/foundation-emails/commit/b7c45e286265877e6c818075ab7d220c248e54f7

<img width="213" alt="screen shot 2016-03-31 at 2 37 08 pm" src="https://cloud.githubusercontent.com/assets/5652085/14191680/22b91dd4-f74e-11e5-9d0a-1bc41061aa4d.png">

There is a question of how valuable this is in the framework though. You can't have a button with a border and a border-radius (the way the tables work). Given many email clients don't support border radius anyways, this may not be a valuable feature.

**Comment by rafibomb** [comment]
@tdhartwick @kball Thoughts? ^^

**Comment by EHackettTriCore** [comment]
I just added border-radius on my project even though I know it's degrades on many mail clients. I don't think rounded edges are crucial if you want to keep the project smaller but I do think the option is handy and I imagine a decent amount of designers would appreciate the option since it seems to be a popular design choice [Really Good Email - See Button Trends ](http://reallygoodemails.com)

**Comment by jasonlmann** [comment]
I was just trying to figure out why this wasn't working. I guess my issue was that I have a button border _and_ wanted a radius on the button. I suppose I can skip the radius, but it would be nice to have if possible.

**Comment by rafibomb** [comment]
@EHackettTriCore 2.1 has this in - does it work the way you did it? We found having the border and radius together was not achievable but happy to see another way if you have it.

**Comment by rafibomb** [comment]
I guess we can close this now since it's in the codebase ;)

**Comment by jondcallahan** [comment]
I've noticed that the `radius` class doesn't work when using a color class like `alert` on buttons.
