### ISSUE TITLE
Callouts with little content don't stretch full width

### ISSUE THREAD

**Issue by gakimball** [foundation/foundation-emails#216]
If a callout has just a few words in it, the box will only be as wide as its contents. @rafibomb @tdhartwick does this matter?

**Comment by kball** [comment]
Hmmm... what is our expected behavior?  Based on the behavior in foundation for sites, I'd expect them to go full width regardless, no?

**Comment by gakimball** [comment]
Yes, that's the intended behavior.

**Comment by kball** [comment]
ok I'll take a look

**Comment by kball** [comment]
@gakimball i'm not seeing this behavior, at least when a callout is inside columns it appears to expand appropriately.  I've added a set of test cases in 'grid-with-callouts-inky.html' and things appear to be all the right size... was there another case you were seeing problems with?  I'm going to close this tentatively assuming it has been fixed or was an error, but please reopen if you have a testcase that demonstrates the issue.

I am seeing a bunch of styling issues with callouts and a number of versions of outlook, but that is a different issue.

**Comment by gakimball** [comment]
@kball Yep, you're right. The reason I noticed this is because in the documentation, the code sample has `<callout>` standalone. But in any situation you'll have content inside of a column, making this issue moot.
