### ISSUE TITLE
[Block-grid] Does not work in Outlook or Android Native.

### ISSUE THREAD

**Issue by rafibomb** [foundation/foundation-emails#217]
Does not wrap 

![screen shot 2016-03-07 at 3 25 51 pm](https://cloud.githubusercontent.com/assets/5652085/13586912/f0058d06-e478-11e5-8ade-1960090c60dc.png)
![screen shot 2016-03-07 at 3 25 35 pm](https://cloud.githubusercontent.com/assets/5652085/13586911/f0054724-e478-11e5-8561-357a32ddc1c6.png)

**Comment by rafibomb** [comment]
![screen shot 2016-03-07 at 3 33 25 pm](https://cloud.githubusercontent.com/assets/5652085/13587042/188ff9fe-e47a-11e5-8af1-bb1075c22e12.png)

**Comment by gakimball** [comment]
Let me know if compressing the whitespace on the inlined email fixes this.

**Comment by rafibomb** [comment]
I'm seeing multiple issues but removing whitespace fixes one of them :)

**Comment by rafibomb** [comment]
Block-grid will now be part of main grid with Inky syntax. Closing this.
