### ISSUE TITLE
success button doesn't have a hover state

### ISSUE THREAD

**Issue by kball** [foundation/foundation-emails#226]
All of the other button types appear to change color on hover, but success does not.

**Comment by gakimball** [comment]
None of them will change on hover once you've inlined it, as pseudo-classes can't be inlined into a `style` attribute. This might not be something we address right away, but in theory we could inline `:hover`, `:active`, et al. styles into the `<style>` tag as part of the inlining process.

**Comment by gakimball** [comment]
Either way, t'was a mere typo preventing the hover state from applying.
