### ISSUE TITLE
Expanded button visual bugs

### ISSUE THREAD

**Issue by gakimball** [foundation/foundation-emails#229]
[Litmus test.](https://litmus.com/builder/documents/493848/edit#start-test)
- ~~In Outlook 2007, 2010, and 2013, buttons don't expand at all.~~
- In Gmail and Google Apps, the padding, text color, and text decoration is wrong.
- ~~In Office 365 and Outlook.com, the _first_ button will be correct, but if you place more expanded buttons below it, those won't be expanded. @rafibomb suggested an `.expander` cell may fix this.~~

Here's the correct look:

![image](https://cloud.githubusercontent.com/assets/1142001/13655420/09736532-e614-11e5-9f03-7724e0a835f5.png)

**Comment by rafibomb** [comment]
Is button-expanded the visual test for this?

**Comment by gakimball** [comment]
@rafibomb Yep

**Comment by rafibomb** [comment]
Added expander to each button.

Fixes `Outlook 2007, 2010, and 2013, buttons don't expand at all.` and `Office 365 and Outlook.com, the first button will be correct, but if you place more  the middle expanded button is too wide :/` 

Remaining issues:
- In Gmail and Google Apps, the padding, text color, and text decoration is wrong.
- In Outlook 2007, 2010, and 2013, buttons don't have vertical spacing between.
- Gmail mobile app, last button is wider!

**Comment by gakimball** [comment]
@rafibomb Nice!!

**Comment by gakimball** [comment]
Buttons still don't expand in Outlook 2007. Litmus test: https://litmus.com/builder/documents/493210/edit

**Comment by tdhartwick** [comment]
Fixed in d2d38ba9feb795718227f1a9b4d9b134ef7fc2e0
