### ISSUE TITLE
Tone down padding of menu?

### ISSUE THREAD

**Issue by gakimball** [foundation/foundation-emails#233]
Menus feel a little big right now, especially vertical ones. Here's an example from one of our templates—note how much vertical space the menu on the right takes up.

![image](https://cloud.githubusercontent.com/assets/1142001/13688486/21486766-e6d7-11e5-94db-e4531b38ce3b.png)

Unlike the menu in Foundation for Sites, this menu will never be used for "navigation" per se, more for lists of links. The distinction is important because, in Sites, you may put an active state on an item, so you need padding around it for that to make sense:

![image](https://cloud.githubusercontent.com/assets/1142001/13688452/ee8f3f70-e6d6-11e5-8f99-c5f51ba82b74.png)

In Emails, you'll never have a style like that, so maybe we don't need as much padding on each menu item. @tdhartwick @rafibomb thoughts?

**Comment by gakimball** [comment]
One way to approach it would be to take the padding on `.simple` and use that as the default, and then drop `.simple`.

**Comment by rafibomb** [comment]
Perhaps the menu would be useful if each item was equal width, like columns without a sizing class. It would make it easier to align the menu in center of the container.

**Comment by rafibomb** [comment]
Closing for https://github.com/zurb/foundation-emails/issues/247
