### ISSUE TITLE
How to use the included Grunt tasks

### ISSUE THREAD

**Issue by rizkysyazuli** [foundation/foundation-emails#235]
Hey all. My first time using this. A bit unclear with the included Grunt tasks and how to use it in my own workflow.

At a glance, it seems to be used for development of the framework itself and not for general users. If this is the case, is there a documentation/recommendation for users using Grunt/Gulp?

**Comment by gakimball** [comment]
Are you referring to [foundation-emails-template](https://github.com/zurb/foundation-emails-template)?

**Comment by rafibomb** [comment]
The https://github.com/zurb/foundation-emails-template will provide the Sass version of the framework. It uses a Gulp build system to watch sass changes, handlebars template, compress images, compile the Inky markup, and inline CSS. 

If you use the Sass version, this is the Stack you get.

**Comment by rafibomb** [comment]
Let us know if more questions come up! The [Foundation forum](http://foundation.zurb.com/forum/) would be a great place to chat about the new features!
