### ISSUE TITLE
content eventually breaks the grid

### ISSUE THREAD

**Issue by atahrijouti** [foundation/foundation-emails#239]
Hi,

if you put content that is bigger than the column's width, the content eventually breaks the grid layout.
here is one such example http://jsbin.com/gocafucale/1/edit?css,output
I am able to make columns stay in place using table-layout: fixed, which according to https://www.campaignmonitor.com/css/b/ should be supported everywhere.

What do you think ? is this way of doing it correct ?

**Comment by gakimball** [comment]
Need @tdhartwick to chime in on this.

**Comment by tdhartwick** [comment]
Hi @abderrahmane-tj,
Sorry for the delayed response. I'm having trouble understanding what you're trying to achieve here. Can you elaborate a little bit on the syntax you're using?

**Comment by atahrijouti** [comment]
@tdhartwick as shown in the example here http://jsbin.com/gocafucale/1/edit?css,output

I have two tables. in which there is a cell that has content that is bigger than the cell.
- First table grows with the content.
- Second table is fixed, and the content overflows when bigger than the cell

**Comment by tdhartwick** [comment]
We're no longer supporting v1, but we've made some big changes in the way columns and rows were structured for v2. Going to close this issue down for v1, we'd love to see this tested for v2. Thanks!
