### ISSUE TITLE
Inky versioning

### ISSUE THREAD

**Issue by gakimball** [foundation/foundation-emails#240]
I was thinking recently how we want to handle Inky versioning. Inky is currently following semver (as all of our projects do), but I wonder if it will become a hassle to keep Foundation for Emails versions in sync with Inky versions.

For example, right now Inky 1.2.x is slightly out of sync with RC3 of the framework, because we've been making changes to the framework and Inky in tandem. So as we patch the framework, how will people know which version of Inky matches the version of the framework they're using?

One solution is to have the two match version numbers exactly. When Foundation for Emails 2 is released, we bump Inky straight to 2.0.0, and then patch the two in tandem. So, for example, F4E 2.1.2 should be paired with Inky 2.1.2 to ensure the markup is the same. @kball thoughts?

**Comment by kball** [comment]
I'd rather not have to bump inky if nothing has changed, instead can we move to being 100% explicit about inky version in the F4E package.json?

**Comment by gakimball** [comment]
The dependency is going to be managed in the starter template ([foundation-emails-template](https://github.com/zurb/foundation-emails-template)), not the framework itself. Even if the framework had an inky dependency, with the way npm works, you wouldn't be able to make one package dictate a top-level dependency. Otherwise that would be the ideal solution.

We could also consider just keeping the minor versions (middle number) in sync. There's a larger question there anyway of how we want to handle patching, which we'll need to decide on soon. In Sites we would consider a markup change a "breaking change" (which means it can't be in a minor version), but Emails is a different beast entirely. So maybe the version policy is:
- 2.0.x: bug fixes that don't require HTML updates.
- 2.x.0: bug fixes or new features that _may_ require HTML updates.

If we stick to that, then we could just bump the minor versions of the two libraries in tandem.

**Comment by kball** [comment]
I'd love it if we could find a way to allow users to only have to think about one thing, even if they're not starting from the emails template... otherwise no matter what we do folks will get confused.  Can we force inky to depend on F4E or vice versa?  Or write a wrapper package?

**Comment by gakimball** [comment]
I'll look into it.

**Comment by gakimball** [comment]
I updated Inky to have an explicit `foundation-emails` dependency. However, depending on how we configure the `package.json` in foundation-emails-template, we're going to get different results in loading the framework.

We could expose _only_ the inky dependency in `package.json`:

``` json
"devDependencies": {
  "inky": "^1.3.0"
}
```

inky will load foundation-emails, and from there I believe we can properly load Foundation into the Sass compiler. However, it's going to look weird if foundation-emails is not a top-level dependency. When new projects come out, a developer's natural inclination may be to bump the version in `package.json` and then update.

So, you could change the `package.json` to look like this:

``` json
"devDependencies": {
  "inky": "^1.3.0",
  "foundation-emails": "^2.0.0"
}
```

In npm 3, only one version of foundation-emails will loaded (unless there's a version conflict). In npm 2, however, you'll get two versions of foundation-emails installed: one at the top level and one nested inside inky.

```
node_modules
  foundation-emails
  inky
    node_modules
      foundation-emails
```

Now we don't have a clear way to reference the correct version of foundation-emails.

So we could go with the route where we only declare inky as a top-level dependency, and tell users of the ZURB Stack, "when you go to update the framework, you're actually updating Inky". If that doesn't seem too weird, we could roll with it. @kball thoughts?

**Comment by kball** [comment]
I think we need to have only one dependency...  I wonder if this is a naming problem as much as anything?  What if inky was foundation-emails and foundation-emails got renamed to foundation-emails-runtime?  Or if we want to keep inky separate, what if  we 'foundation-emails' was simply a wrapper that contained inky and foundation-emails-runtime?

**Comment by DanielRuf** [comment]
I think the discussion has become very stale and we should not make this more complex. We might move this to a monorepo in the future and bump versions in sync using lerna.
