### ISSUE TITLE
[Inky] .menu should use th's

### ISSUE THREAD

**Issue by rafibomb** [foundation/foundation-emails#241]
`.menu` should use th's instead of td's to be responsive on andorid.

After testing with th's - looks good on all clients.

**Comment by gakimball** [comment]
From what I can tell, in some Outlook versions the menu items are equal-width.

**Comment by rafibomb** [comment]
That seems to be a different issue all-together. This is just going to help Android responsiveness.

**Comment by rafibomb** [comment]
Closing in favor of https://github.com/zurb/foundation-emails/issues/247
