### ISSUE TITLE
[Grid] collapse class cascades to nested grid

### ISSUE THREAD

**Issue by rafibomb** [foundation/foundation-emails#243]
Adding .collapse to a row removes padding from all columns within it. 

Expected behavior, only collapse the first child. @tdhartwick @gakimball What are your thoughts? 

The use case is a collapsed row acting as a wrapper with a background, and nested grids within.

**Comment by gakimball** [comment]
Haven't looked at the CSS, but might be fixable by adding `>` in the CSS, to scope the collapse.

**Comment by rafibomb** [comment]
Thanks @gakimball got it https://github.com/zurb/foundation-emails/commit/333300c771d22855549bae6a72f91044347cded5

**Comment by rickysullivan** [comment]
I was having an issue with this.

I wanted a collapsible row so I could insert two columns without padding. 

```
<container>
  <row class="collapse">
    <columns small="12" large="6">
      <img src="https://www.fillmurray.com/300/300" class="show-for-large" alt="DESKTOP"/>
      <img src="https://www.fillmurray.com/600/300" class="hide-for-large" alt="MOBILE"/>
    </columns>
    <columns small="12" large="6">
      <row class="collapse">
        <columns small="12" large="6">
          <h3>Sit amet consectetur</h3>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
          </p>
        </columns>
      </row>
    </columns>
  </row>
</container>
```

Expected:

![expected](https://cloud.githubusercontent.com/assets/437480/13833797/27adeea8-ec3d-11e5-91dc-6d03441df5de.png)

I think it should be like this:

```
.collapse > tbody > tr {
    > td.large-#{$i},
    > th.large-#{$i} {
     ...
    }
    ...
  }
```

**Comment by alex-ketch** [comment]
I also agree with @rickysullivan method.
`>` only works on _direct_ descendants, so there is never a match with the current selector.

The tests, screenshot attached below, also show no difference between a collapsed row and a non-collapsed row.

![screen shot 2016-03-17 at 7 23 05 pm](https://cloud.githubusercontent.com/assets/1646307/13864325/e1af444e-ec76-11e5-94c9-d689395d6b05.png)

**Comment by rickysullivan** [comment]
Much better @alex-ketch. But I think you still need the direct selector...

```
//Collapsed logic
  .collapse {
    > tbody > tr > td.large-#{$i},
    > tbody > tr > th.large-#{$i} {
      padding-right: 0;
      padding-left: 0;
      width: -zf-grid-calc-px($i, $grid-column-count, $global-width) + $global-gutter;
    }
    ...
}
```

**Comment by rickysullivan** [comment]
I'm still trying to figure out the _media-query.scss change required for mobile version.

**Comment by alex-ketch** [comment]
Hmmm, I see what you're trying to do @rickysullivan.
It seems Inky is applying `.collapse` class on both the `table` element and all the nested `th`s too.

```
<table class="row collapse">
  <tbody>
    <tr>
      <th class="collapse small-6 large-6 columns first">
        <table>
          <tbody>
            <tr>
              <th>
                <img src="/assets/img/image.png">
              </th>
              <th class="expander"></th>
            </tr>
          </tbody>
        </table>
      </th>
      <th class="small-6 large-6 columns last">
        <table>
          <tbody>
            <tr>
              <th>
                <h1 class="text-centre">Content.</h1>
              </th>
              <th class="expander"></th>
            </tr>
          </tbody>
        </table>
      </th>
    </tr>
  </tbody>
</table>
```

I wonder then if instead we need to do something like:
```
  .collapse:not(th) {
    > tbody > tr > td.large-#{$i},
    > tbody > tr > th.large-#{$i} {
      padding-right: 0;
      padding-left: 0;
      width: -zf-grid-calc-px($i, $grid-column-count, $global-width) + $global-gutter;
    }
```

**Comment by rickysullivan** [comment]
I can't see where Inky would be adding the collapse class to th elements.

What version are you running?

Ricky Sullivan
0409 895 923


http://rickysullivanphotography.com

[image: Facebook] <https://www.facebook.com/rickysullivanhimself> [image:
Twitter] <http://twitter.com/rickysullivan>

**Comment by alex-ketch** [comment]
Sorry, I misunderstood you previously.
I believe the code in question is around [highlighted here](https://github.com/zurb/foundation-emails/blob/v2.0/scss/components/_media-query.scss#L42-L49).

Is this what you're trying to do @rickysullivan?

``` sass
  // Collpased columns have no gutter.
  .collapse {
    > tbody > tr > .columns,
    > tbody > tr > .column {
      padding-left: 0 !important;
      padding-right: 0 !important;

      > table > tbody > tr > th > table > tbody > tr > .column,
      > table > tbody > tr > th > table > tbody > tr > .columns {
        padding-left: $global-gutter !important;
        padding-right: $global-gutter !important;
      }
    }
  }
```

Seems like an ugly solutions, the intent is to add back the column padding only to the first descendant columns of a `.collapse`d row.

I can incorporate this into my PR #254  if others agree that this is the correct logic.

**Comment by rickysullivan** [comment]
Check this: https://github.com/rickysullivan/foundation-emails/blob/v2.0/scss/components/_media-query.scss#L23-L49

Check out my PR #257
