### ISSUE TITLE
Grid does not work as expected (small != 12)

### ISSUE THREAD

**Issue by Nikkiez** [foundation/foundation-emails#245]
The grid does not work as expected. If I use a less number then 12 for small view, the columns still collapse as 12. The following example is from the offical foundation for emails/inky templates. (https://github.com/zurb/foundation-emails/tree/v2.0/test/visual/pages)

Example HTML:

```
<container>
    <row>
        <columns small="12" large="2">
            <p>(small="12" large="2") One Word</p>
        </columns>
        <columns small="4" large="4">
            <p>(small="4" large="4") Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga repellendus velit aut perferendis, eveniet delectus maxime quisquam recusandae assumenda culpa tenetur dolorem error voluptatibus. Animi accusamus molestiae placeat, sequi beatae.</p>
        </columns>
        <columns small="8" large="6">
            <p>(small="8" large="6") Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis quis obcaecati facere dolore laborum officia rem praesentium cumque culpa delectus alias ullam ad, doloremque, ipsa asperiores ex sit necessitatibus minima!</p>
        </columns>
    </row>
</container>
```

Desktop view (large):
![Desktop view (large)](http://s10.postimg.org/42zp7vowp/Fire_Shot_Screen_Capture_135_10_10_5_34_3.png)

Desktop view (small):
![Desktop view (small)](http://s30.postimg.org/cq0026r4x/Fire_Shot_Screen_Capture_136_10_10_5_34_3.png)

**Comment by rafibomb** [comment]
Hmmm, we can't replicate this behavior

<img width="430" alt="screen shot 2016-03-16 at 7 25 22 am" src="https://cloud.githubusercontent.com/assets/5652085/13815571/5585cc92-eb48-11e5-918a-07a96e3f1182.png">

To make sure you are using the latest build, you can update you package.json file to grab the latest code on v2.0

`"foundation-emails": "zurb/foundation-emails#v2.0"`

And make sure you have inky set to 

`"inky": "^1.2.3",`

and run `npm update`

Let us know how that works for you!

**Comment by Nikkiez** [comment]
I'm up to date. ;)
I found out that the behavior only occurs if I dont inline the css "npm start" instead of "npm run build".
I don't know if this is a use case for someone or for you.

Thanks for the fast reply.

**Comment by rafibomb** [comment]
That's weird, seems to work both inlined and not. Since this grid has been through some extensive testing, we can't treat it as framework bug. Thanks for the report!
