### ISSUE TITLE
[Inky] Remove .expander from images too small

### ISSUE THREAD

**Issue by rafibomb** [foundation/foundation-emails#246]
If a column is less than full-width (12 columns), do not build .expander with Inky.

On Outlook 2000, 2002, 2003 images are shrunk due to .expander constraining image width. 

Reference https://github.com/zurb/foundation-emails/issues/50

**Comment by gakimball** [comment]
Implemented via zurb/inky@8bf3618e2e7202f24490d6225548fbd016473139
