### ISSUE TITLE
[Block grid] Remove

### ISSUE THREAD

**Issue by gakimball** [foundation/foundation-emails#249]
Following an internal discussion, the block grid is being removed from the framework. This is because it doesn't work if you try to create multiple rows of items.

Instead, we're going to add a shortcut to the `<row>` tag in Inky to apply classes for you.

``` html
<row small-up="1" large-up="3"></row>
```

**Comment by gakimball** [comment]
Removed the docs page.

**Comment by tazzydemon** [comment]
This makes my issue #201 even more important in that case, because IIUIC block grids were the only recommended way to get responsive reflow in the Gmail app

**Comment by gakimball** [comment]
Passing assignment to @rafibomb, as we're going to keep it but explain the caveats.

**Comment by rafibomb** [comment]
The block grid doesn't really solve the fact that Gmail doesn't support media queries. It's in the framework and we're open to other solutions. It was suggested and logged on our roadmap for Inky to use the spongy grid method as an option. That could be a great community project!

**Comment by tazzydemon** [comment]
Calling it "spongy grid" is neat. I am already using this grid in production. That roadmap is a great idea.
