### ISSUE TITLE
Smarty

### ISSUE THREAD

**Issue by andrewscofield** [foundation/foundation-emails#250]
I work regularly with a system that used Smarty templating engine to process emails.

Is there a way to wrap everything inside the `<style></style>` with `{literal}{/literal}` so that smarty stops freaking out about the use of curly brackets? Is there a hook in gulp or somewhere I could write this functionality? Thanks!

**Comment by rafibomb** [comment]
There is a similar question here with a solution: https://github.com/zurb/foundation-emails/issues/221 Let us know if that helps!

**Comment by andrewscofield** [comment]
That link you sent for sure lead me in the right direction. Here is what I ended up with, it works! 

Please let me know if there is a better way!

```
function inliner(css) {
  var css = fs.readFileSync(css).toString();
  var mqCss = siphon(css);

  var pipe = lazypipe()
    .pipe($.inlineCss, {
      applyStyleTags: false
    })
    .pipe($.injectString.replace, '<!-- <style> -->', `<style>{literal}${mqCss}{/literal}</style>`)
    .pipe($.htmlmin, {
      collapseWhitespace: true,
      minifyCSS: true,
      ignoreCustomFragments: [/{.*literal}/]
    });

  return pipe();
}
```

**Comment by rafibomb** [comment]
Nice - that looks right!
