### ISSUE TITLE
Where does the template generate from?

### ISSUE THREAD

**Issue by markholmes** [foundation/foundation-emails#253]
Let's say I make changes to `/src/assets/scss/app.scss` and then run `foundation new --framework emails`, should the changes made in the app.scss file be reflected in the css for the new project folder? That doesn't appear to be working, and as such, I'm confused as to what the `/src/` folder is for. Can anyone shine some light? Perhaps I'm going about this wrong. I have some default styles and partials that I use for all of my emails, and I'd like to have those created when I run `foundation new --framework emails`. Thanks!

**Comment by rafibomb** [comment]
The purpose of the `src` folder is to contain all your working files. The `dist' folder is where all the compiled assets go:
- flattened HTML files with handlebars parsed
- compiled CSS
- optimized images

**Comment by rafibomb** [comment]
Maybe @gakimball can comment on the best way to do that.

**Comment by DanielRuf** [comment]
> I have some default styles and partials that I use for all of my emails, and I'd like to have those created when I run foundation new --framework emails.

This is currently not supported.
