### ISSUE TITLE
Full width row in F4E 2.0

### ISSUE THREAD

**Issue by hedberg** [foundation/foundation-emails#255]
Is it possible to achieve a full width row in F4E 2.0?  (Similar to swapping the .row and .container classes in F4E1)

**Comment by rafibomb** [comment]
Are you trying to a make a fluid width header or background?

**Comment by hedberg** [comment]
Yes, a fluid width header.

**Comment by rafibomb** [comment]
Yes, it works the same way. If you wrap a table or a row around the container, you can do this. You might need to override the background of the container.

**Comment by ineptian** [comment]
is it possible to do this using INKY?
`<row>
  <container>
    <columns small="12" large="12">
    full width
    </columns>
  </container>
</row>`
Does not seem to work

**Comment by brandonbarringer** [comment]
I found a solution by doing the following:
`<row class="full-width"><td><container><row><columns></columns></row></container></td></row>`

**Comment by ineptian** [comment]
Brandon I also found at that you can do this using inky. Just wrap the container in a div with the class of header and boom!
