### ISSUE TITLE
[Grid] Collapse does not work on small

### ISSUE THREAD

**Issue by rafibomb** [foundation/foundation-emails#258]
Looks like a specificity issue

<img width="978" alt="screen shot 2016-03-17 at 10 35 22 pm" src="https://cloud.githubusercontent.com/assets/5652085/13869331/a174b8c2-ec90-11e5-8a59-1840bc306bab.png">

**Comment by alex-ketch** [comment]
I ventured at a [possible solution yesterday](https://github.com/zurb/foundation-emails/issues/243#issuecomment-198153909)

The intent is to add back the column padding only to the first descendant columns of a `.collapse`d row.
Probably would also have to repeat the [styling for the first and last columns](https://github.com/zurb/foundation-emails/blob/v2.0/scss/grid/_grid.scss#L103-L109) from the desktop _grid.scss.
Can provide a PR if this is an acceptable solution.

Changing the code in [_media-query.scss](https://github.com/zurb/foundation-emails/blob/v2.0/scss/components/_media-query.scss#L42-L49) to:

``` sass
  // Collpased columns have no gutter.
  .collapse {
    > tbody > tr > .columns,
    > tbody > tr > .column {
      padding-left: 0 !important;
      padding-right: 0 !important;

      > table > tbody > tr > th > table > tbody > tr > .column,
      > table > tbody > tr > th > table > tbody > tr > .columns {
        padding-left: $global-gutter !important;
        padding-right: $global-gutter !important;
      }
    }
  }
```

_Edit:_ Although I just realized this doesn't account for multiple nested collapsed columns.

**Comment by rafibomb** [comment]
I think this was resolved here by your PR https://github.com/zurb/foundation-emails/commit/892a444f12ab9321431e44180456d65695ef8904 Thanks! If you see any more issues with it, a PR would really help!

**Comment by rafibomb** [comment]
Targeting this for infinite nesting is not a use case we're going after since it would likely be an extreme edge case.
