### ISSUE TITLE
[2.0] inline css doesn't work in foundation-email-templates, but here it's working

### ISSUE THREAD

**Issue by timaschew** [foundation/foundation-emails#259]
Cloned a fresh copy of **foundation-email-templates** and run `PRODUCTION=1 npm start`. I even add a console.log in the `inliner` function.

Result is that `<!-- <style> -->` is not replaced. It's still there.

I tried to copy the gulp parts from this repo, unfortunately with gulp 3, so I needed to refactor some other parts and there it works fine to inline the the css

**Comment by gakimball** [comment]
Inlining only happens when you do `npm run build`. Our starter projects have two modes: development and production. `npm start` always runs development mode, while `npm run build` always runs production mode.

**Comment by Reon90** [comment]
timaschew is right! i have the same issue. inliner doesn't do anything
