### ISSUE TITLE
[Docs] Sticky sidebar needs to stop before footer

### ISSUE THREAD

**Issue by rafibomb** [foundation/foundation-emails#262]
Needs to add a wrapper to anchor to body only.

**Comment by gakimball** [comment]
Seems to work for me. Is there a specific page you see it on?

![screen shot 2016-03-21 at 1 54 12 pm](https://cloud.githubusercontent.com/assets/1142001/13933869/73634a46-ef6c-11e5-88ae-12cbe9ecc252.png)

**Comment by rafibomb** [comment]
Looks good! Closing
