### ISSUE TITLE
[Docs] Clicking the Inky code toggle causes page to jump

### ISSUE THREAD

**Issue by rafibomb** [foundation/foundation-emails#263]
All but the first toggle do this:

![gjetyxkkvm](https://cloud.githubusercontent.com/assets/5652085/13911252/64b615e0-eeeb-11e5-937c-b82b7672dede.gif)

**Comment by gakimball** [comment]
Fixed via 02999ef3e4eec3e9e65c7f69a9236dddcd159f04
