### ISSUE TITLE
[Docs] Some examples not indenting properly

### ISSUE THREAD

**Issue by rafibomb** [foundation/foundation-emails#264]
<img width="792" alt="screen shot 2016-03-20 at 10 55 54 pm" src="https://cloud.githubusercontent.com/assets/5652085/13911530/0a84e822-eeef-11e5-8260-6d200ec25022.png">

Seen on:
- button
- global
- grid

**Comment by rafibomb** [comment]
This could be the Inky formatting.

**Comment by gakimball** [comment]
Fixed via zurb/foundation-docs@8846fd4de19ac0ea478220cfcbc29fa61757683a
