### ISSUE TITLE
[Inky] Buttons doubling the button class

### ISSUE THREAD

**Issue by rafibomb** [foundation/foundation-emails#265]
<img width="792" alt="screen shot 2016-03-20 at 10 55 54 pm" src="https://cloud.githubusercontent.com/assets/5652085/13911569/75af0092-eeef-11e5-93f4-9baff4beb7c2.png">

**Comment by gakimball** [comment]
Not seeing this in the tests, I'll update foundation-docs with the latest version of Inky and see if it's still happening.

**Comment by gakimball** [comment]
Updated foundation-docs and everything looks chill. Run `npm update` inside the foundation-emails repo to pull a newer version.

![screen shot 2016-03-21 at 1 11 53 pm](https://cloud.githubusercontent.com/assets/1142001/13932677/869eec24-ef66-11e5-8163-9341fd8dd6a9.png)
