### ISSUE TITLE
Handlebars in Ver. 2?

### ISSUE THREAD

**Issue by bahamagician** [foundation/foundation-emails#267]
Hi,

I'm beta testing Ver. 2.  Is it possible to use handlebars in the new version?  For example, once I get a template created, it would be great if I could just populate it via a YML file.  Is that currently possible?

**Comment by gakimball** [comment]
If you're using the [template project](https://github.com/zurb/foundation-emails-template), you can populate content with external JSON or YML files. The [Foundation for Sites docs for Panini](http://foundation.zurb.com/sites/docs/panini.html#custom-data) cover this (it's the same library).

It only lets you generate page content programmatically, but you can't generate actual pages from data.

**Comment by bahamagician** [comment]
Where would I put the "data" folder and how would I tell the build process to include it?  The foundation for sites zurb template already has a data folder included.  However, the email template project doesn't.  

Also, looking at the gulpfile for the template project, I don't see any reference to data or handlebars:

``` sh
function pages() {
  return gulp.src('src/pages/**/*.html')
    .pipe(panini({
      root: 'src/pages',
      layouts: 'src/layouts',
      partials: 'src/partials'
    }))
    .pipe(inky())
    .pipe(gulp.dest('dist'));
}
```

Whereas the gulpfile for sites has a reference to both the data folder and handlebars:

``` sh
function pages() {
  return gulp.src('src/pages/**/*.{html,hbs,handlebars}')
    .pipe(panini({
      root: 'src/pages/',
      layouts: 'src/layouts/',
      partials: 'src/partials/',
      data: 'src/data/',
      helpers: 'src/helpers/'
    }))
    .pipe(gulp.dest(PATHS.dist));
}
```

Do I need to include those additions to the email gulpfile?

**Comment by bahamagician** [comment]
So I managed to get it working but I had to modify gulpfile.babel.js as per the following:

``` sh
function pages() {
  return gulp.src('src/pages/**/*.{html,hbs,handlebars}')
    .pipe(panini({
      root: 'src/pages',
      layouts: 'src/layouts',
      partials: 'src/partials',
      data: 'src/data/'
    }))
    .pipe(inky())
    .pipe(gulp.dest('dist'));
}
```

**Comment by gakimball** [comment]
Glad you got it working :)

We don't have the custom helpers or custom data features enabled by default in the template, because we anticipate (for now) that the majority of people won't use them. That `src` directory already has a lot of folders inside of it, so we don't want to overwhelm folks too much with all of the different features.

However, we can make sure it's clear in the documentation how to enable these features if you want them.

**Comment by justintemps** [comment]
Following up here as the requested change in documentation still hasn't been made. There's still nothing in the zurb panini docs that tells you that you have to modify the gulpfile.babel.js:

http://foundation.zurb.com/sites/docs/panini.html
