### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by kelvinaero** [foundation/foundation-emails#270]
After  installing foundation 2, parking inside the new project directory and running npm start on Mac OS X Command Line

We get the following Failed to load

[10:55:13] *_Failed to load external module *_ babel-register
[10:55:13] Requiring external module babel-core/register
....
...

Everything looks correctly and the project works, but we wanted to report this minor issue.

**Comment by tdhartwick** [comment]
@kelvinaero Thanks for pointing this out! This was really annoying to us too. I think we pushed an update  a few days ago. Maybe deleting the node_modules folder and reinstalling npm might fix it. @gakimball can you chime in on this?

**Comment by pdnellius** [comment]
I had to manually install babel-register with `npm install babel-register` to resolve this

**Comment by 1stevengrant** [comment]
Even after adding `babel-register` manually, I'm running into the same issues

```
[18:09:31] Requiring external module babel-register
module.js:338
    throw err;
    ^

Error: Cannot find module 'babel-runtime/core-js/symbol'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
```

**Comment by 1stevengrant** [comment]
Resolved this by `npm cache clean`

**Comment by kelvinaero** [comment]
Thank you for the quick reply. We are glad to help. For the moment npm install babel-register solves the error.

**Comment by tobystokes** [comment]
I think the cause is that the babel-register package is not included in the package.json dependencies?
Zurb guys have it all installed globally? i installed with 
`npm install babel-register --save-dev`

**Comment by gakimball** [comment]
@kelvinaero @tobystokes Do y'alls use npm 2 or 3?

**Comment by tobystokes** [comment]
npm -v == 3.5.3

Though I now suspect the message `Requiring external module babel-core/register` is not actually an error, just an alert. See e.g. https://markgoodyear.com/2015/06/using-es6-with-gulp/#comment-2355065905
The reason I though it was acquiring, not just requiring, is because there is about a one minute delay between this message and the rest of the gulp script executing:
`[17:05:43] Requiring external module babel-register
[17:06:56] Using gulpfile ~/[...]/gulpfile.babel.js`
Not sure it should take that long to get running? (Foundation v6 for sites certainly doesn't, fwiw)

**Comment by GuillermoCasanova** [comment]
I'm still getting the error below:

![screen shot 2016-05-31 at 1 54 00 pm](https://cloud.githubusercontent.com/assets/9218601/15684856/18902a50-2737-11e6-89dc-bc82869074b4.png)

Even after doing: 

Deleting all node_modules from originally install project (tired both through Foundation CLI and copying github repo) 
npm cache clean
npm install
npm install  babel-register --save-dev
npm start 
<FAILS>

Any help on this is much appreciated Ink 2 looks amazing to use!

**Comment by DanielRuf** [comment]
> [10:55:13] *Failed to load external module * babel-register
> [10:55:13] Requiring external module babel-core/register

This is just a warning and not an actual error. We can close this.
