### ISSUE TITLE
[Callout] Documentation requires update

### ISSUE THREAD

**Issue by meghanhorton** [foundation/foundation-emails#274]
**Versions**
foundation-emails v. 2.14.7
Foundation CLI version 2.1.0

**Issues**
The documentation on http://foundation.zurb.com/emails/docs/callout.html#basics states the following layout for a callout:

```
<table>
  <tr>
    <th class="callout primary">
      <table class="row">
        <tbody>
          <tr>
            <th class="small-12 large-12 columns first last">
              <table>
                <tr>
                  <th>
                    <p>This whole row is in a callout!</p>
                  </th>
                  <th class="expander"></th>
                </tr>
              </table>
            </th>
          </tr>
        </tbody>
      </table>
    </th>
  </tr>
</table>
```

In the NPM foundation-emails v 2.14.7, the [SCSS](https://github.com/zurb/foundation-emails/blob/develop/scss/components/_callout.scss) has a different structure:

```
table.callout {
  margin-bottom: $callout-margin-bottom;
  Margin-bottom: $callout-margin-bottom;
}

th.callout-inner {
...
```

By following the documentation, the callout is not styled properly.

**Comment by DanielRuf** [comment]
It seems the docs were accordingly updated.

**Comment by DanielRuf** [comment]
Closing as this should be resolved now.
