### ISSUE TITLE
Foundation for Emails - new project setup issue

### ISSUE THREAD

**Issue by johnbcable** [foundation/foundation-emails#275]
I have just installed the updated foundation-cli via npm and then tried to create a new email project using the recommended command:

foundation new --framework emails

The screen output I get is the following:

JCiMac:Emails a03pl$ foundation new --framework emails
? What's the project called? (no spaces) testinky

```
      _____
     /     \
    /=   . |
___| ==  | /    Thanks for using ZURB Foundation for Emails!
```

   /   | ===  \     -------------------------------------------
   |   | ====  |    Let's set up a new project.
   /**/| =====  \   It shouldn't take more than a minute.
       (   __   )
        (O)  (O)
       (   **,  )
        __****/

Downloading the project template...
Done downloading!

Installing dependencies...

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:559:26)
JCiMac:Emails a03pl$ 

Could you pleaser let me know how to fix this as right now I dont know if my email project is scaffolded correctly.

Thanks

**Comment by gakimball** [comment]
Looks like npm ran into a network error while trying to install. Are you behind a firewall or proxy or anything like that?

Also, could you let us know what OS you use, and what versions of Node (`node -v`) and npm (`npm -v`) you use? Thanks :)

**Comment by johnbcable** [comment]
Hi,

My machine is wired-connected to the household router and we are not behind a software firewall or use a proxy server of any sort.

My versions of node and npm are as follows:

node -v                               v0.12.2
npm -v                                2.7.4

My machine is running OS/X El Capitan   version 10.11.3

Thanks

On 23 Mar 2016, at 22:39, Geoff Kimball notifications@github.com wrote:

Looks like npm ran into a network error while trying to install. Are you behind a firewall or proxy or anything like that?

Also, could you let us know what OS you use, and what versions of Node (node -v) and npm (npm -v) you use? Thanks :)

**Comment by gakimball** [comment]
A project folder was still created, it just didn't finish getting set up. Could you open the folder in your command line, run `npm install`, and tell us what happens?

**Comment by johnbcable** [comment]
What I get are a whole load of unmet dependencies:

JCiMac:testinky a03pl$ npm install
npm WARN unmet dependency /Users/a03pl/Sites/Foundation/Emails/testinky/node_modules/gulp/node_modules/undertaker/node_modules/last-run requires es6-weak-map@'^1.0.1' but will load
npm WARN unmet dependency /Users/a03pl/Sites/Foundation/Emails/testinky/node_modules/gulp/node_modules/undertaker/node_modules/es6-weak-map,
npm WARN unmet dependency which is version 2.0.1
npm WARN unmet dependency /Users/a03pl/Sites/Foundation/Emails/testinky/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream requires through2@'^0.6.0' but will load
npm WARN unmet dependency /Users/a03pl/Sites/Foundation/Emails/testinky/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2,
npm WARN unmet dependency which is version 2.0.1
npm WARN unmet dependency /Users/a03pl/Sites/Foundation/Emails/testinky/node_modules/gulp-htmlmin/node_modules/gulp-util/node_modules/dateformat/node_modules/meow requires object-assign@'^4.0.1' but will load
npm WARN unmet dependency /Users/a03pl/Sites/Foundation/Emails/testinky/node_modules/gulp-htmlmin/node_modules/gulp-util/node_modules/object-assign,
npm WARN unmet dependency which is version 3.0.0
npm WARN unmet dependency /Users/a03pl/Sites/Foundation/Emails/testinky/node_modules/gulp-htmlmin/node_modules/gulp-util/node_modules/multipipe/node_modules/duplexer2 requires readable-stream@'~1.1.9' but will load
npm WARN unmet dependency /Users/a03pl/Sites/Foundation/Emails/testinky/node_modules/gulp-htmlmin/node_modules/readable-stream,
npm WARN unmet dependency which is version 2.0.6
npm WARN unmet dependency /Users/a03pl/Sites/Foundation/Emails/testinky/node_modules/gulp-imagemin/node_modules/gulp-util/node_modules/dateformat/node_modules/meow requires object-assign@'^4.0.1' but will load
npm WARN unmet dependency /Users/a03pl/Sites/Foundation/Emails/testinky/node_modules/gulp-imagemin/node_modules/gulp-util/node_modules/object-assign,
npm WARN unmet dependency which is version 3.0.0
npm WARN unmet dependency /Users/a03pl/Sites/Foundation/Emails/testinky/node_modules/gulp-inject-string/node_modules/gulp-util/node_modules/dateformat/node_modules/meow requires object-assign@'^4.0.1' but will load
npm WARN unmet dependency /Users/a03pl/Sites/Foundation/Emails/testinky/node_modules/gulp-inject-string/node_modules/gulp-util/node_modules/object-assign,
npm WARN unmet dependency which is version 3.0.0
npm WARN unmet dependency /Users/a03pl/Sites/Foundation/Emails/testinky/node_modules/gulp-inline-css/node_modules/gulp-util/node_modules/dateformat/node_modules/meow requires object-assign@'^4.0.1' but will load
npm WARN unmet dependency /Users/a03pl/Sites/Foundation/Emails/testinky/node_modules/gulp-inline-css/node_modules/gulp-util/node_modules/object-assign,
npm WARN unmet dependency which is version 3.0.0
npm WARN unmet dependency /Users/a03pl/Sites/Foundation/Emails/testinky/node_modules/gulp-load-plugins/node_modules/gulp-util/node_modules/dateformat/node_modules/meow requires object-assign@'^4.0.1' but will load
npm WARN unmet dependency /Users/a03pl/Sites/Foundation/Emails/testinky/node_modules/gulp-load-plugins/node_modules/gulp-util/node_modules/object-assign,
npm WARN unmet dependency which is version 3.0.0
npm WARN unmet dependency /Users/a03pl/Sites/Foundation/Emails/testinky/node_modules/gulp-sass/node_modules/gulp-util requires object-assign@'^3.0.0' but will load
npm WARN unmet dependency /Users/a03pl/Sites/Foundation/Emails/testinky/node_modules/gulp-sass/node_modules/object-assign,
npm WARN unmet dependency which is version 4.0.1
npm WARN unmet dependency /Users/a03pl/Sites/Foundation/Emails/testinky/node_modules/inky/node_modules/vinyl-fs/node_modules/glob-stream requires through2@'^0.6.0' but will load
npm WARN unmet dependency /Users/a03pl/Sites/Foundation/Emails/testinky/node_modules/inky/node_modules/through2,
npm WARN unmet dependency which is version 2.0.1
JCiMac:testinky a03pl$ 

On 23 Mar 2016, at 22:56, Geoff Kimball notifications@github.com wrote:

A project folder was still created, it just didn't finish getting set up. Could you open the folder in your command line, run npm install, and tell us what happens?

**Comment by johnbcable** [comment]
Just managed to get this to work on the 4th time of trying so at least I can get testing now! I'll raise this again if the issue occurs again.
P.S.  No external software updates applied during the life of this issue.

**Comment by rafibomb** [comment]
Hmm, we'll keep an out for more reports of it - glad you got it!
