### ISSUE TITLE
Breaking XHTML validity when inlining css

### ISSUE THREAD

**Issue by rickysullivan** [foundation/foundation-emails#278]
If you inline an XHTML based email, there's a chunk of css that will break the validity of the XHTML doc. I'm using foundation-emails and inky, but I'm still sticking with XHTML for my templates.

The problem lies with this section of code:

```
//For viewing email in browser
html {
  min-height: 100%;
  background: $body-background;
}
```

https://github.com/zurb/foundation-emails/blob/develop/scss/grid/_grid.scss#L17-L21

This will add a `style` attribute to the `html` node, which causes XHTML to be invalid.

I suggest wrapping like this:

```
//For viewing email in browser
@media only screen {
  html {
    min-height: 100%;
    background: $body-background;
  }
}
```

It will then remain in in the `<style>` tag.

Thoughts?

**Comment by gakimball** [comment]
@rafibomb @tdhartwick Is it possible to make this an optional style, if it's specifically for browsers?
