### ISSUE TITLE
It seems new markup for block-grid doesn't work.

### ISSUE THREAD

**Issue by karalkou** [foundation/foundation-emails#279]
```
<row small-up="1" large-up="3">
  <column>Thing 1</column>
  <column>Thing 2</column>
  <column>Thing 3</column>
</row>
```

I see only inserted <column> tags on my page.

**Comment by gakimball** [comment]
Where did you see this markup? It hasn't been implemented yet.

**Comment by karalkou** [comment]
Here is the link
http://foundation.zurb.com/emails/docs/migration.html#block-grid

**Comment by gakimball** [comment]
@rafibomb Can we scrub this from the migration guide?

**Comment by tdhartwick** [comment]
We changed the syntax and updated the docs. Closing this for now. @karalkou let us know if there's any problems!
