### ISSUE TITLE
&apos; not rendered in outlook

### ISSUE THREAD

**Issue by bharrisau** [foundation/foundation-emails#281]
**How can we reproduce this bug?**
The password template example. https://litmus.com/checklist/emails/public/96b083d#ol2013

**What did you expect to happen?**
An apostrophe to appear.

**What happened instead?**
An `&apos;` appeared.

**What email clients does this happen in?**
Looks like all the Outlook examples.

Would `&#39;` be a better escaped apostrophe to render to?

**Comment by rafibomb** [comment]
We noticed this too! Tried some different variations of character code and still not working. Hoping someone has experience with this!

**Comment by rafibomb** [comment]
Looks like it's the inliner causing it - https://github.com/jonkemp/gulp-inline-css/issues/4

We'll try updating to see if it helps.

**Comment by acezard** [comment]
in the meantime it seems possible to use `’` which is `&rsquo;`, it does render correctly

**Comment by rafibomb** [comment]
Oh nice! I went into the dist compiled version and changes it back to a '

**Comment by rafibomb** [comment]
We have a fix in for this, we're testing it.

**Comment by rafibomb** [comment]
Looks like this is an issue due to Cheerio used in Inky. There was a suggested solution we're testing now.

**Comment by rafibomb** [comment]
It was recommended to swap the character to &#8217;

There is a PR on Cheerio to fix this that needs testing https://github.com/cheeriojs/cheerio/issues/319

**Comment by rafibomb** [comment]
Merged in https://github.com/zurb/inky/pull/57 after testing it and it resolves all the reported Inky issues here: https://github.com/zurb/foundation-emails/blob/develop/test/visual/pages/inliner-bugs.html

If you have more use cases that should be covered, please add them to this test and file a new issue.

Thanks!

**Comment by jijo-paulose** [comment]
k
