### ISSUE TITLE
'foundation watch' does not recognize new files

### ISSUE THREAD

**Issue by cdymond** [foundation/foundation-emails#282]
When I create a new file, I have to end the process and restart it or `foundation watch` will throw this:

```
Starting 'sass'...
Error in plugin 'sass'
Message:
    src\assets\scss\components\_all.scss
Error: File to import not found or unreadable: preheader
       Parent style sheet: c:/xampp/htdocs/mailchimp/tradingpinsdirect/src/assets/scss/components/_all.scss
        on line 5 of src/assets/scss/components/_all.scss
>> @import 'preheader';
```

It seems that it refuses to recognize new files until the process is restarted. My current set up does not require restarting the process every time a file is created, so this is an unexpected behavior for me, but I'm just starting to dig into this so I may just be expecting a behavior that isn't possible.

**Comment by rafibomb** [comment]
@gakimball Is there a good way to add these files?

**Comment by cdymond** [comment]
There may be more to this than I initially realized.

I'm getting a lot of this import not found or unreadable error, even with files and folders that were already there. It seems to be totally random. Sometimes it won't have any problem at all and sometimes it does. It is completely sporadic.

This could be an issue with gulp-sass itself, as I've found [this issue](https://github.com/dlmanning/gulp-sass/issues/235), but the solution isn't super ideal, so I might start digging into that. My other option is to try to swap over to gulp-ruby-sass if that's possible, but I haven't even started looking.

**Comment by rafibomb** [comment]
Yes, ruby sass should work fine as well 3.4+

It does seem intermittent because most of the time it works but sometimes...

**Comment by gakimball** [comment]
Just to be sure, does the same thing happen if you run `npm start` instead of `foundation watch`?

(One is a wrapper command for the other, but just want to make sure it's not a CLI-specific issue.)

**Comment by rbrtsluk** [comment]
Sounds like im getting the same problem. I'm only new to foundation cli and sass and I just got my head around installing my first email project.
When I place new images in my assets/img folder they dont show on BrowserSync untill I restart my project in terminal?
Also making changes to my_settings.scss file like $body-line-height...etc sometimes wont update?

**Comment by Flixt** [comment]
In fact I have the same on my ubuntu vagrant machine, but it works fine on OSX. Maybe it has to to with leveraging fsevent (which is OSX only).

**Comment by ronnidc** [comment]
I have the exact same issue on Windows 10 when running `npm start` or `npm run build`.

It happen's if i make changes to a scss file and hit save. It doesn't happen if I hit save without making changes to the scss file. So the temporary (and ugly) fix is to hit save two times every time I make a change..

Using latest version of [foundation-emails-template](https://github.com/zurb/foundation-emails-template) and haven't changed or developed anything yet.
````
Error in plugin 'sass'
Message:
    src\assets\scss\app.scss
Error: File to import not found or unreadable: template/template
       Parent style sheet: D:/Projects/Dev.Website/src/context/frontend/email-foundation/src/assets/scss/app.scss
        on line 4 of src/assets/scss/app.scss
>> @import 'template/template';
````

**Comment by tdhartwick** [comment]
We're not able to replicate this on the latest version. Seems like it was fixed somewhere down the line in our previous updates. Going to close for now, feel free to reopen if we're still seeing issues!

Thanks!
