### ISSUE TITLE
[Getting Started with CSS] Images didn't responsive in small screen please fix this issue

### ISSUE THREAD

**Issue by bulbul84** [foundation/foundation-emails#283]
**How can we reproduce this bug?**
1. Step one: i think you need indicate a class (img-responsive) of every responsive images (specially full width images)
2. Step two: edit/add your foundation.css file line: 1115 (@media max-width: 596px) like below:
   table.body img.img-responsive {
     width: 100% !important;
     height: auto !important; }
3. Step three: Then when anyone write their code where they used full width images/ or when they used max 270px images they should be used img-responsive class on their image

**What did you expect to happen?**
I expect when template go to small screen, images will be auto resize. 

**What happened instead?**
Now, full width images template aren't responsive. this images not resize on small screen.

**Test case**
[hero.zip](https://github.com/zurb/foundation-emails/files/188287/hero.zip)

Give us a link to a [CodePen](http://codepen.io) or [JSFiddle](http://jsfiddle.net) that recreates the issue.
http://codepen.io/bulbul84/pen/zqwbYN

**Comment by rafibomb** [comment]
Right now, the images are width auto on small screens so they shrink with the container and do not stretch out (which would distort them). Thanks for the example! I didn't see an issue with how the images are handled. Can you provide a screenshot for which you would change the behavior?

**Comment by bulbul84** [comment]
Hi...
Thank you for your reply....
I face this problem on Firefox, Internet Explorer Browser....
In this browser, images didn't resize with screen width...
I attached on a screenshot with html file that problem i face...
please check it on your firefox and internet explorer browser....

[hero.zip](https://github.com/zurb/foundation-emails/files/191649/hero.zip)
![screenshot_1](https://cloud.githubusercontent.com/assets/10453438/14076381/0aeea432-f503-11e5-9636-82218195223c.png)

if you see their happen above problem, please give me one way to solve this problem.

Regards
Bulbul Hasan

**Comment by DanielRuf** [comment]
Closing as outdated. The issue might be because of some element which has width and height set or wrong code. Or in cases where the style tag is missing in the head or inlining was not done.
