### ISSUE TITLE
Test template broken in a few email clients

### ISSUE THREAD

**Issue by toxsid** [foundation/foundation-emails#285]
**How can we reproduce this bug?**
By visiting the litmus link below

Write out the HTML (or Inky code) that causes the issue.
https://litmus.com/builder/9161804

**What did you expect to happen?**
Buttons rendering correctly.

**What happened instead?**
Didn't do the above.

**What email clients does this happen in?**
Yahoo Mail, Gmail Explorer, Firefox Gmail, Yahoo Mail Firefox, Gmail Chrome, Yahoo Mail Chrome, Outlook.com Explorer, Outlook.com Firefox, Outlook.com Chrome, Google Apps Explorer, Google Apps Firefox, Office 365 Firefox, Office 365 Explorer, Office 365 Chrome, Outlook 2010 Windows 7, Outlook 2013 Windows 7, Outlook 2013 DPI

**Comment by rafibomb** [comment]
Thanks for the report! Are you saying the buttons don't render correctly? We didn't see any code in the test you linked.

**Comment by toxsid** [comment]
Rafi,

The codeviewer should be on the left of the building link I provided. Here it is again: https://litmus.com/builder/9161804. Thank you in advance!

**Comment by rafibomb** [comment]
We put a fix in for buttons yesterday https://github.com/zurb/foundation-emails/commit/1519cfc03aa4649cd52e5223deb04ebd2682ded7

Can you make the change and see it it solves it for you?

**Comment by toxsid** [comment]
Thanks @rafibomb this seemed to fix all button rendering issues. The following mail clients however choose to truncate the social buttons on the footer I have on this template for some strange issue. Maybe it is a litmus only problem?

Clients:

Gmail (Explorer, Firefox, Chrome)
Google Apps (Explorer, Firefox, Chrome)
Yahoo Mail! (Explorer, Firefox, Chrome)

Let me know if you have any additional questions and thanks again!

**Comment by toxsid** [comment]
@rafibomb 

After further investigation the following clients are still not rendering the buttons correctly (no padding):
- Office 365 (Firefox, Chrome)
- Outlook.com (Explorer, Firefox, Chrome)

Please see the following litmus for code:
https://litmus.com/builder/9161804

Let me know if you have any questions.

**Comment by rolandovelez13** [comment]
Hello @rafibomb

Do you have any updates on this request? Also, there are some additional issues in Outlook 2013 120 DPI, the orange buttons do not have a background color.

**Comment by rafibomb** [comment]
@choppnutts Not sure, we've tried a few different things. Have you tried using the no-expander attribute on the column?

**Comment by tdhartwick** [comment]
hmm, apologies for the delayed response, but we're not seeing any button issues in our Litmus Tests. Going to close this down! Feel free to reopen this issue if there are still problems!
