### ISSUE TITLE
What would you think of an inky component to manage vertical spacing ?

### ISSUE THREAD

**Issue by acezard** [foundation/foundation-emails#289]
As we all know it's rather tricky to handle vertical spacing with html emails. Margin and padding often give various results or are flat out ignored. `<br>` tags are unreliable for a precise layout. The columns do indeed have padding-bottom, but what if I want to space elements that are inside the same column ? Or if I want a vertical spacing with a different background color than the container's one ?

Maybe you have a better way to deal with it than me, in my case I made a custom component

```
    // <spacer>
    case this.components.spacer:
      var classes = ['spacer'];
      var size = 10; // default spacing 

      if (element.attr('class')) {
        classes = classes.concat(element.attr('class').split(' '));
      }

      // custom spacing
      if (element.attr('size')) {
          size = element.attr('size');
      }

      return format('<table class="%s"><tbody><tr><td height="'+size+'px" style="line-height:'+size+'px">&nbsp;</td></tr></tbody></table>', classes.join(' '), inner);
```

```
.spacer {
    width: 100%;

    td {
        font-size: 1px;
        padding: 0;
    }
}
```

Usage  : `<spacer size="10"></spacer>`

The produced html gives a reliable result giving consistent spacing in all email clients. Would you be interested ?

**Comment by rafibomb** [comment]
It's an interesting proposal. I've found that `<br>` tags work better than padding in Outlook 2007, 2010, 2013. Those are the only clients we've seen padding not working consistently.

Have you found padding to work reliably on Outlook 2007, 2010, 2013?

If so, this could be a good replacement for the <br> tag (it could get ugly having multiple `<br>` tags).

**Comment by rafibomb** [comment]
Having said that, we'd love to see a PR on Inky to add this in. We have a perfect project to test it on!

**Comment by Xerxes-J** [comment]
Can confirm this works on all email clients! I've used something similar in the past using a handlebar helper. Here's an updated version with two tweaks added in:
1. `font-size:'+size+'px;` 
2. `mso-line-height-rule: exactly;`

**ComponentFactory.js**

`return format('<table class="%s"><tbody><tr><td height="'+size+'px" style="font-size:'+size+'px;line-height:'+size+'px;mso-line-height-rule: exactly;">&nbsp;</td></tr></tbody></table>', classes.join(' '), inner);`

**CSS:**

`.spacer {
  width: 100%;
  td {
    padding: 0;
  }
}`

**Comment by rafibomb** [comment]
Well if that's the case, this would be a great addition to Inky because vertical spacing always get's weird on Outlook 2007, 2010, 2013. We're planning a feature release in a couple weeks and this will go in. 

@acezard Thanks for the PR https://github.com/zurb/inky/pull/21  We'll be testing it and merging early next week!

**Comment by acezard** [comment]
yes I think it's a solid way of managing spacing.

I typically use it that way : `<row>
    <columns large="12" small="12">
        <img>
        <spacer size="20"></spacer>
        <p class="text-center f20 b">some text</p>
    </columns>
</row>`

or that way (for instance to make a fake margin between row)

`<row></row><spacer size="20" class="grey-background"></spacer><row></row>`

I also made a pr for the css rule https://github.com/zurb/foundation-emails/pull/293

**Comment by rafibomb** [comment]
@acezard Thanks for the PR! 
@Xerxes-J Thanks for the assist!

I set up a test in the `test -> visual` folder in this repo. This tests out great! https://litmus.com/checklist/emails/public/e6d9076

If anyone can verify it works in all cases (I didn't try adding content inside it) that would really help. The next patch is set for Apr 7!

**Comment by acezard** [comment]
yea I just noticed a slight issue on outlook 2016, first time I experience it. Seems a 1px line is inserted after the spacer in some cases. I wonder if it's linked to my markup (or even with EoA) because it doesn't appear on all emails.

Check this dark grey line above the button : it's not supposed to be there. Bug seem to only appear on outlook 2016.
![outlook](https://cloud.githubusercontent.com/assets/12577784/14191036/140f1322-f796-11e5-8cff-c0cf4be7ce3b.png)

I'm not sure about the details yet I didn't have time to investigate at all, I'll check tomorrow.

**Comment by markadrake** [comment]
Maybe you are running into a [sub-pixel rendering issue](http://stackoverflow.com/questions/31098642/ie-11-sub-pixel-rendering-overflow). This is the best example I could find to link to - but it happens to me all the time in Chrome.
