### ISSUE TITLE
[Callout] Expects <th> for callout-inner, Inky generating <td>

### ISSUE THREAD

**Issue by tomstock1337** [foundation/foundation-emails#291]
None of the callout examples are working on the docs website.  Using firefox, switch the tag from a td to th for a callout-inner and the coloring magically works.
http://foundation.zurb.com/emails/docs/callout.html

**What did you expect to happen?**
Coloring/border should be visible when using callout

**What happened instead?**
Coloring/border was not visible when a <td> was used with class callout-inner.

**Test case**

Give us a link to a [CodePen](http://codepen.io) or [JSFiddle](http://jsfiddle.net) that recreates the issue.
https://jsfiddle.net/yhpd3ysn/
Fixed the primary callout; the other callouts are broken.

**Comment by rafibomb** [comment]
fixed it here: https://github.com/zurb/inky/commit/a43da5653e54d684209cf48090515228abb23313

Thanks for the report! We'll be putting out a patch today!

**Comment by benortiz** [comment]
Quick question, how do I update an existing project once the patch is out? Thanks!

**Comment by Xerxes-J** [comment]
1. cd "project_folder"
2. npm update
3. npm outdated (if there's no result's you are GOLDEN)

**Comment by gakimball** [comment]
Fixed in Inky 1.3.4
