### ISSUE TITLE
Panni Errors out

### ISSUE THREAD

**Issue by HansUXdev** [foundation/foundation-emails#292]
**How can we reproduce this bug?**
Just try using a partial.

**Write out the HTML (or Inky code) that causes the issue.**
{{>menu}}

**What did you expect to happen?**

<div>some html</div> 

**What happened instead?**
The task is completed but displays the following error:

Panini: rendering error ocurred.
 [Error: Parse error on line 34:
...ble>  </div>{{&gt; menu}}  
------------------^
Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'INVALID']

**The Cause?**
" > " is confused for " &gt; " and does not compile ... I think

**Comment by gakimball** [comment]
Not able to recreate this. I made a file called `src/partials/menu.html` and put in this content:

``` html
<menu>
  <item href="#">Menu!</item>
</menu>
```

And then in `src/pages/index.html` I added at the top:

``` hbs
{{> menu}}
```

Is this similar to what you did?

**Comment by HansUXdev** [comment]
Yeah that is exactly what I did.... hmm--

That's weird.. I'm going to see if I can narrow it down further then... Hopefully I just have a bad npm package...

**Comment by gakimball** [comment]
Does the content of the partial have any Handlebars code? And is there any Handlebars anywhere else on the main page?

**Comment by HansUXdev** [comment]
I had multiple partials some had handlebars code and some didn't. I managed to fix it by changing the version of Panni and eventually it fixed itself. Weird. Now I can't reproduce it...

**Comment by gakimball** [comment]
Strange, what version did you move to?
