### ISSUE TITLE
Documentation error : text-center used instead of float-center

### ISSUE THREAD

**Issue by atahrijouti** [foundation/foundation-emails#294]
**How can we reproduce this bug?**
1. [`follow this link`](http://foundation.zurb.com/emails/docs/alignment.html#centering-images)
2. Look at the code, and see `text-center`
3. Look at the doc, it says :

> In the CSS version, our centering recipe includes three ingredients:
> `.float-center` class on the <img> element

**Comment by rafibomb** [comment]
You're right! Luckily they both do the same thing so it works either way. We'll update the naming in Inky.

**Comment by rafibomb** [comment]
Thanks! Made the change in Inky https://github.com/zurb/inky/commit/9e88d07f60232e0268597f10d436e0eb45e15100

The text-center class works the same for this but for accuracy it should be `.float-center`
