### ISSUE TITLE
$button-border variable not being applied with zurb stack

### ISSUE THREAD

**Issue by bahamagician** [foundation/foundation-emails#295]
I'm using the Zurb Email Template.  

When I edit the $button-border in the _settings.scss it doesn't get applied to the compiled file.  

For example, let's say I use the following code in the settings file:

``` sh
$button-border: 2px solid #123456;
```

When I run "foundation watch" or "npm run build" and search for "#123456" it doesn't appear anywhere within the code.

**Comment by tdhartwick** [comment]
Looks like this might be fixed. Tested in the latest build and the variable seems to work. Closing this. Feel free to reopen this if you're still experiencing issues!
