### ISSUE TITLE
gulp inky infinite loop

### ISSUE THREAD

**Issue by twilly86** [foundation/foundation-emails#296]
I'm getting an infinite loop when using inky inside gulp.  I traced the loop happening here (see screenshot)  Is this a problem with my html or inky?

![2016-03-28_11-54-52](https://cloud.githubusercontent.com/assets/3496838/14085256/071fa756-f4dc-11e5-8758-4e765dc13086.png)

note, i just put  in a limit to make it stop.

gulp file..

function parse() {
  gulp.src('views/emails/src/*_/_.html') 
    .pipe(inky())
    .pipe(gulp.dest('dist'));
}

**Comment by gakimball** [comment]
Can you paste the code you're running through the parser? Or try and narrow it down to the specific code that creates the infinite loop?

**Comment by rafibomb** [comment]
Not sure if this is still happening or if you have more information to narrow it down. We'll close this here - please open a new issue if you have more info on it. Thanks!
