### ISSUE TITLE
Add !default flag to variables

### ISSUE THREAD

**Issue by KittyGiraudel** [foundation/foundation-emails#298]
It is good practice to add the `!default` flag to configuration variables. In this project, it would be all variables in https://github.com/zurb/foundation-emails/blob/develop/scss/settings/_settings.scss.

I’m willing to send you a PR for this if you want.

**Comment by gakimball** [comment]
Thanks Hugo! It may be the different way these variables are set up:

The actual variable definitions all use the `!default` flag—see [buttons](https://github.com/zurb/foundation-emails/blob/develop/scss/components/_button.scss) for an example.

From these, we generate a settings file (using [this tool](https://github.com/zurb/octophant)) that aggregates all of them together. The `!default` flag shouldn't be necessary in the settings file, as it's designed to be a file of overrides.

This file isn't used by the framework itself at all. Rather, it's a reference for our [project boilerplate](https://github.com/zurb/foundation-emails-template).

Does that make sense?

**Comment by KittyGiraudel** [comment]
Mokay. :)

**Comment by KittyGiraudel** [comment]
Mokay. :)
