### ISSUE TITLE
.hide-for-large max-height:0

### ISSUE THREAD

**Issue by ghost** [foundation/foundation-emails#300]
the .hide-for-large class doesn't override  the "max-height : 0" when triggering the small screen media query which leads to not seing the element correctly.

**Comment by gakimball** [comment]
Can you post an HTML example that isn't working?

**Comment by rafibomb** [comment]
@diskokevin Thanks for the report! It would also help to know what email client the issue relates to - thanks!

**Comment by ghost** [comment]
HTLM:

`<container class="hide-for-large"></container>`

_visibility.scss :

```
table.body table.container .hide-for-large {
    display: none;
    width: 0;
    mso-hide: all;
    overflow: hidden;
    max-height: 0px;
    font-size: 0;
    width: 0px;
    line-height: 0;
}

@media only screen and (max-width: 596px){
    table.body table.container .hide-for-large {
        display: block !important;
        width: auto !important;
        overflow: visible !important;
    }
}
```

So basically, "max-height: 0px;" is still used from the classic version of the class, even when the media query is triggered.

**Comment by tdhartwick** [comment]
Thanks! Closed here: https://github.com/zurb/foundation-emails/commit/c76d5c2b6360576c501290bad57f35e9ce728301
