### ISSUE TITLE
Character entities not working

### ISSUE THREAD

**Issue by Madd4Computers** [foundation/foundation-emails#302]
Ever since the update/changes to the inliner (interface included) sometime last week, my templates have not inlined correctly and render poorly in browser and in the email client I use.

**How can we reproduce this bug?**
Here's a file I use: 
[appDev_template.zip](https://github.com/zurb/foundation-emails/files/194093/appDev_template.zip)
 Try it out (inline it) for yourself and see.

**Write out the HTML (or Inky code) that causes the issue.**
&amp;amp;  causes the issue. So far the amp, lt, and gt, entities, but I wouldn't be surprised if other entities types produce the same issues.

**What did you expect to happen?**
Expected it to work...?

**What happened instead?**
It didn't work - see below
![capture 2](https://cloud.githubusercontent.com/assets/18037522/14119579/a6038122-f5a3-11e5-88b2-cb48de2c837f.PNG)

**What email clients does this happen in?**
Outlook 2010 (I wouldn't be surprised if it happened in newer and older versions, but I don't have access to test)

**Comment by rafibomb** [comment]
We have a fix in for this which we are testing today. We'll update soon!

**Comment by rafibomb** [comment]
Looks like a duplicate of https://github.com/zurb/foundation-emails/issues/334 We'll close this in favor of https://github.com/zurb/foundation-emails/issues/334
