### ISSUE TITLE
[Foundation for Emails] Apostrophes in outlook

### ISSUE THREAD

**Issue by k4xdm** [foundation/foundation-emails#303]
**How can we reproduce this bug?**

 **April’s**  produces HTML output `April&#x2019;s` (This works in Outlook)

**April's** produces HTML output `April&apos;s` (Outlook renders April&apos;s )

**Comment by rafibomb** [comment]
There is a duplicate open - looks like there is a solution there https://github.com/zurb/foundation-emails/issues/281 Thanks!
