### ISSUE TITLE
Margin & Margin-bottom incorrectly capitalized and included twice in inlined-styles

### ISSUE THREAD

**Issue by tayvano** [foundation/foundation-emails#304]
When compiling sass version using `npm run build`, margin and margin-bottom are often included twice, once as `Margin:` and `Margin-bottom` and once with the correct, all-lowercase format.

An example: 

`style="Margin:0;Margin-bottom:10px;color:#111;font-family:Lato,Helvetica,Arial,sans-serif;font-size:14px;font-weight:400;line-height:19px;margin:0;margin-bottom:10px;padding:0;text-align:center"`

**Comment by rafibomb** [comment]
The capital M is a workaround for Outlook.com https://www.emailonacid.com/blog/article/email-development/outlook.com-does-support-margins to support margins.

The use of margin: 0; then margin-bottom: 10px; could be optimized. Can you point to a class that has this CSS?

**Comment by tayvano** [comment]
Ah! Thank you for that FYI.

In the aforementioned example, that style was taken off an arbitrary p. I do not believe there is any class.

**Comment by rafibomb** [comment]
Sounds good! We'll close this here and looks for places we can merge those properties.

**Comment by joaostein** [comment]
@rafibomb — also thought this was an issue and almost issued a PR to remove the duplicated margin.  gladly I found this issue, thanks for the link.  any ideas on how to make this more evident to the user that is looking directly to the code?

**Comment by joeworkman** [comment]
This issue has been mentioned on **Foundation Open Source Community**. There might be relevant details there:

https://foundation.discourse.group/t/double-margin-line/3220/2

**Comment by sandinmyjoints** [comment]
To save bytes, helping prevent gmail clipping, would it be possible to drop the lowercased version and just use the uppercased version for maximum compatibility?
