### ISSUE TITLE
[Foundation for Emails] Wrong gulp.watch image path?

### ISSUE THREAD

**Issue by DanielHitchen** [foundation/foundation-emails#306]
Hi,

When adding an image to your email i.e placing an image in the `src/assets/img` folder, then adding it to your email, the email build does not update because the Gulp watch path for the images maybe incorrect.

On line 88 of the `gulpfile.bable.js` the path is set to `src/img/**/*`, should this not be `src/assets/img/**/*`? Once I changed this in my project the images compiled upon change.

Also, when removing an image from the `src/assets/img` folder, the image is not removed from the `dist/assets/img` folder - is there a reason for this?

**Comment by rbrtsluk** [comment]
I went and corrected what you have described here but my images still don't display in browserSync. The only way I can get them to load is to close terminal and restart my project?

**Comment by DanielRuf** [comment]
Which repo / template was used?

**Comment by DanielRuf** [comment]
Closing as we did not receive further feedback.
