### ISSUE TITLE
[The Grid] Column offsets are over-ridden when using collapse

### ISSUE THREAD

**Issue by DanielHitchen** [foundation/foundation-emails#307]
Hi,

If using the `collapse` class on a row, if you try to offset a column within that particular row, the offsets' `padding-left` left value is over-ridden by the `collapse` padding.

**Comment by rafibomb** [comment]
Thanks for the report Daniel! Do you have a code snippet we can use to test this?

**Comment by DanielHitchen** [comment]
Hi @rafibomb , here is a zip with the code snippet: 
[collapse-bug.zip](https://github.com/zurb/foundation-emails/files/197489/collapse-bug.zip)

Thanks

**Comment by emcacace** [comment]
Hi @rafibomb any update on this. In the example below the small offset works because it uses margins but the large offset doesn't because it is using padding and as Daniel explained it is being overwritten. 

`<container class="footer">

```
<row class="collapse">
    <columns small="2" large="1" class="large-offset-1 small-offset-1">          
    </columns>
    <columns small="7" large="8">           
    </columns>
    <columns small="2" large="2">
    </columns>
</row>
```

</container>`

**Comment by jsit** [comment]
PR #777 should fix this.
