### ISSUE TITLE
Outlook fowarded messages add line breaks after every row

### ISSUE THREAD

**Issue by getglad** [foundation/foundation-emails#308]
Using just a basic template like so:

```
<container>
 <row>
    <columns large="4">
      abc
    </columns>
    <columns large="4">
      def
    </columns>
    <columns large="4">
      ghi
    </columns>
  </row>
  <row>
    <columns>
      123
    </columns>
    <columns>
      456
    </columns>
    <columns>
      789
    </columns>
  </row>
<container>
```

This produces fine in Outlook on the first send, but Outlook is added a paragraph element between every table. This is no effect on the layout/appearance because the display is set to none.

Content Added by Outlook in Original Message:
`<P class=MsoNormal style="LINE-HEIGHT: 14.25pt"><SPAN style='FONT-FAMILY: "Helvetica",sans-serif; COLOR: #0a0a0a; **DISPLAY: none**'><?xml:namespace prefix = "o" ns = "urn:schemas-microsoft-com:office:office" /><o:p>&nbsp;</o:p></SPAN></P>`

If the message if forwarded, Outlook is changing each paragraph line between every table.

Forwarded Message:
`<P class=MsoNormal style="LINE-HEIGHT: 14.25pt"><SPAN style='FONT-FAMILY: "Helvetica","sans-serif"; COLOR: #0a0a0a'><?xml:namespace prefix = "o" ns = "urn:schemas-microsoft-com:office:office" /><o:p>&nbsp;</o:p></SPAN></P>`

It is dropping the `DISPLAY: none`. This causes the spacing to expand in any forwarded message.

This is true in Outlook 2010 and 2013.

Am I using Inky correctly? Is there any known hack to get around this problem?

Other than this issue - Inky + foundation for emails is _amazing_.

**Comment by Xerxes-J** [comment]
TBH, forwarding emails will always break your design/layout. I've always struggled in getting it work properly.

**Comment by rafibomb** [comment]
I'm not sure how the framework can solve this. Any ideas are definitely welcome!

**Comment by rafibomb** [comment]
Did some research but not seeing something tangible we can do yet:
https://www.emailonacid.com/blog/article/email-development/why_forwarding_emails_is_so_bad
https://www.campaignmonitor.com/forums/topic/537/forwarding-html-emails-without-corruption/

**Comment by getglad** [comment]
Yeah I'll be working on this off and on, so if you find something I'd be all ears. I have added a custom component to my local Inky, so happy to try pretty much anything.

It seems like what is really needed is just the ability to add an additional `<tr>`, rather than have every `<row>...</row>` add an additional `<table>`. Maybe there is a cross-client issue that makes that nonviable, but it seems like something worth trying to me.

Seeing that this is really more of an Inky issue, I can move myself over there if that's more appropriate.

**Comment by getglad** [comment]
To close the loop on this, I have made a PR for Foundation to update SCSS and for Inky to implement the additional components.
Foundation: https://github.com/zurb/foundation-emails/pull/348
Inky: https://github.com/zurb/inky/pull/34
