### ISSUE TITLE
Question: How do I include attributes into the pre-compiled (sass) version so that they show up in the compiled version?

### ISSUE THREAD

**Issue by tayvano** [foundation/foundation-emails#309]
For example, I want to include a `background=` and `bgcolor=` as attributes:

`<row class="background-image" background="image.jpg">`

so that it outputs to:

`<table class="row background-image" background="image.jpg" style="background:url(image.jpg); ... >`

Is this doable?

**Comment by rafibomb** [comment]
This should be doable. It could be a feature of the row. A wrapper might work better.

We're working on a `<wrapper>` component that may work for this. It would basically build a 

```
<table>
  <tr>
    <td >
```

For now, using the above structure to wrap the row should work best.

**Comment by awhitehouse104** [comment]
I ran into this as well trying to inline styles. Useful for something like the following with handlebars, but it's not preserved.

```
<row style="background-image:url({{image}})">
```

**Comment by mathiashelin** [comment]
As far as I know, Inky strips out all attributes except classes. It would be very useful if Inky could preserve all attributes, so you can write templates for MailChimp and Campaign Monitor. MC attributes like mc:edit etc. get thrown out, so now you have to add them to the compiled html, which is not very productive if you have to add/edit something afterwards.

**Comment by alex-ketch** [comment]
I've had success keeping attributes with escaping the first curly brace with a backslash, can't guarantee it though.
`<row style="background-image:url(\{{image}})">`

**Comment by rafibomb** [comment]
In 2.2 a new feature was added to allow Inky to apps in attributes to rows and columns. We started a discussion on it here: 
http://foundation.zurb.com/forum/posts/44863-add-html-attributes-to-your-inky-markup

We'd love to hear what problem you were trying to solve by adding in attributes it or what you originally had in mind for it.
