### ISSUE TITLE
Inliner stripping @font-face, not moving to body

### ISSUE THREAD

**Issue by tophed** [foundation/foundation-emails#310]
**How can we reproduce this bug?**

In the inliner ( http://foundation.zurb.com/emails/inliner.html ),
1. Paste HTML:
   `<!DOCTYPE html>
   <html>
   <head>
   <title></title>
   </head>
   <body>
   </body>
   </html>`
2. Paste CSS:
   `@font-face {
       font-family: 'Montserrat'; font-style: normal; font-weight: 400; src: local('Montserrat-Regular'), url('https://fonts.gstatic.com/s/montserrat/v6/zhcz-_WihjSQC0oHJ9TCYC3USBnSvpkopQaUR-2r7iU.ttf') format('truetype');
   }`
3. Click Inline.

**What did you expect to happen?**

Expected output is the html with the font-face in the style tags:
`<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title></title></head><body><style>@font-face {
        font-family: 'Montserrat'; font-style: normal; font-weight: 400; src: local('Montserrat-Regular'), url('https://fonts.gstatic.com/s/montserrat/v6/zhcz-_WihjSQC0oHJ9TCYC3USBnSvpkopQaUR-2r7iU.ttf') format('truetype');}</style></body></html>`

**What happened instead?**

Output does not contain the @font-face:
`<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title></title></head><body><style></style></body></html>`

Note:
This is also happening with the ZURB stack built-in inliner.
I know @font-face does not work in all emails clients, but it does in Apple mail, and that is a large percentage of our user base. I can manually add the @font-face tag into the compiled email, but it would be very convenient if the inliner put it there for me. Thanks :)

**Comment by tophed** [comment]
Whoops, there is a previous post I missed that highlights the same issue:
https://github.com/zurb/foundation-emails/issues/284

Not sure how I can delete this post.

**Comment by rafibomb** [comment]
Thanks! We'll close this in favor of #284
