### ISSUE TITLE
Buttons .expanded, only text is clickable after inlining

### ISSUE THREAD

**Issue by tophed** [foundation/foundation-emails#311]
**How can we reproduce this bug?**

-Create button with class="expanded" in Inky or HTML
-Inline CSS with Foundation web inliner, or ZURB stack run by 'npm run build'

``` html
<container>
  <row>
    <columns small="12">
        <button href="zurb.com" class="expanded">Expanded Button</button>
    </columns>
  </row>
</container>
```

**What did you expect to happen?**

Entire button to be clickable, like in the Foundation for Emails docs.

**What happened instead?**

Only text is clickable.

**What email clients does this happen in?**

Happening in the browser.

**Comment by rafibomb** [comment]
This was resolved in 2.1! Thanks!
