### ISSUE TITLE
Button - Generated Class being applied in the to the outer <table> as opposed the the inner <table> <td> 

### ISSUE THREAD

**Issue by jamiegiftbit** [foundation/foundation-emails#315]
The email docs suggest being able to apply `.radius` or `.rounded` to the Inky `<button class="radius rounded"> element, but once run through the generator, it creates a nested table and applies the classes to the outer table instead of the table > table > td as the css in the foundations node_module suggests 

Generated:
From: 
`<button class="button radius round">Click Me</button>`
To:

```
<table class="button radius round">
  <tbody>
    <tr>
      <td>
        <table>
          <tbody>
            <tr>
              <td><a href="#">Click Me</a></td>
            </tr>
          </tbody>
        </table>
      </td>
    </tr>
  </tbody>
</table>
```

Desired (based on css selectors in node module):

```
<table class="button">
  <tbody>
    <tr>
      <td>
        <table>
          <tbody>
            <tr>
              <td class="radius round"><a href="#">Click Me</a></td>
            </tr>
          </tbody>
        </table>
      </td>
    </tr>
  </tbody>
</table>
```

**Comment by rafibomb** [comment]
If you add the class on the `<td>`, does it work?

BTW the classes are made to be used either or, either radius or round.

It looks like this feature is not complete https://github.com/zurb/foundation-emails/issues/214 but we'd like to know what working solution you found!

**Comment by rafibomb** [comment]
We added the correct CSS to make this work: https://github.com/zurb/foundation-emails/commit/b7c45e286265877e6c818075ab7d220c248e54f7

<img width="213" alt="screen shot 2016-03-31 at 2 37 08 pm" src="https://cloud.githubusercontent.com/assets/5652085/14191680/22b91dd4-f74e-11e5-9d0a-1bc41061aa4d.png">

There is a question of how valuable this is in the framework though. You can't have a button with a border and a border-radius (the way the tables work). Given many email clients don't support border radius anyways, this may not be a valuable feature.

We'll copy this over in #214 and open it up for discussion.

**Comment by jamiegiftbit** [comment]
Yes, if you apply the generated class in the inspector, to the `td` it does work, however you have no control over this when you run the build. You can however take the generate inline styles and move them to the `td` which I've tested in Litmus for Gmail in free preview, I'm just going to set up a paid account too and i'll post findings. But I have the `border-radius` applied to both the `td` and the `a`. Let me know if I should remove one of those, based on your knowledge.

RE: BTW: I would assume someone would be using them independently, but thanks for the clarification!
