### ISSUE TITLE
Columns in a "block grid" row not stacked in Gmail App

### ISSUE THREAD

**Issue by jamesref** [foundation/foundation-emails#316]
When using the "block grid" layout with two columns, the second column does not get pushed down to the next row. Both stay on the same row and only get more narrow.
(I'm using version 2.1)

Here's a screenshot from Email On Acid:
https://eoass.s3.amazonaws.com/web/2016-03-31/gmailapp_ios/91220_135515.png?n=0

**How can we reproduce this bug?**

``` HTML
<container>
  <row small-up="1" large-up="2">
    <columns>
      <p>
      Lorem ipsum Velit veniam irure labore pariatur Ut minim eiusmod dolor cupidatat dolore laboris in Ut quis in officia ad proident. Lorem ipsum Laboris Duis sint et ut reprehenderit sed cupidatat pariatur est ut sunt fugiat aute proident culpa ut do minim sit proident Excepteur tempor laborum in.
      </p>
    </columns>
    <columns>
      <p>
      Lorem ipsum Velit veniam irure labore pariatur Ut minim eiusmod dolor cupidatat dolore laboris in Ut quis in officia ad proident. Lorem ipsum Laboris Duis sint et ut reprehenderit sed cupidatat pariatur est ut sunt fugiat aute proident culpa ut do minim sit proident Excepteur tempor laborum in.
      </p>
    </columns>
  </row>
</container>
```

**What did you expect to happen?**
The second column to be pushed below the first one.

**What happened instead?**
The columns stayed on the same row.

**What email clients does this happen in?**
Gmail App

**Comment by rafibomb** [comment]
Hmm, I'm not sure it was wrapping in v1 either but we'll did in a bit more. I wonder if Gmail is not handling display: inline-block; the same as others.

**Comment by sco-tt** [comment]
This is a hack and a workaround that doesn't address the stacking issue, but if you add:

`<div style="display:none; white-space:nowrap; font:15px courier; line-height:0;">
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
</div>`

right before the closing `</body>` tag in src/default.html, it prevents Gmail from automatically enlarging text, which prevents the design from looking broken. 

I've tried different responsive email techniques and I always have to add this code to make things work for the Gmail App on iOS when testing in Email on Acid.

See http://freshinbox.com/blog/gmail-on-ios-increases-font-size-on-some-emails/

**Comment by tdhartwick** [comment]
Closing this issue, unfortunately we had to remove block grids because Outlook 2007/10/13 had some major issues with `display: inline-block;`. However! Gmail will be supporting media queries later this week on top of recently supporting `display` properties!  Check it out here: http://googleappsdeveloper.blogspot.com/2016/09/your-emails-optimized-for-every-screen-with-responsive-design.html
