### ISSUE TITLE
[Visibility Classes] hide-for-large not responding in certain web-based clients

### ISSUE THREAD

**Issue by jakemailninja** [foundation/foundation-emails#319]
I am testing out some of the features in Foundation for Emails 2.

Found that the hide-for-large class does not apply in some web-based clients (Gmail, Google Apps, Yahoo! Mail)

http://codepen.io/anon/pen/vGegWp

Has anyone found a fix for this?

(Testing in Litmus & Email On Acid)

**Comment by markadrake** [comment]
Just going to try and expand on this - but I've found a lot of the "responsiveness" of the Zurb Email Template (even before 2) was indeed incorrect and not working in certain clients. Google especially is one who strips media queries and responsiveness away from your e-mails. 

This is why I stress "mobile-first" thinking when it comes to e-mail design. If it doesn't fit into a single column, why? What does two columns really provide to a user? Accept that some clients will only show a mobile view then (Google) and accept that some clients (Outlook) can be progressively enhanced with media query support. 

I think I'll monitor this thread just b/c I'd love to see someone find a solution to the issues within Gmail branded clients.

**Comment by eljazouli** [comment]
Hello @jakemailninja @markadrake  did you find a solution to this problem ? 
Thank you !!

**Comment by davehoran** [comment]
I've had similar issues as well. When I have two rows in place, one to `show-for-large` and another with 'hide-for-large', it seems that the show-for-large is displayed (when large size screen) but smaller image is not. I've had to instruct designers to just give me the smaller mobile version.

Anyone have a fix?

**Comment by tdhartwick** [comment]
It looks like we pushed a fix a few days ago. Check it out here: https://github.com/zurb/foundation-emails/commit/cf7d15a3ce7c9bb400094763a5f42282f57157d6

Going to close this. Please reopen if you're still experiencing issues!
