### ISSUE TITLE
[Callout] documentation uses <td> instead of <th>

### ISSUE THREAD

**Issue by dherges** [foundation/foundation-emails#321]
**How can we reproduce this bug?**
1. use a `<td>` for `<td class="callout-inner">`

**What did you expect to happen?**

working colouring :-)

**What happened instead?**

no colouring :-(

**How to fix**

use a `<th>` for `<th class="callout-inner">`

guess that's a documentation bug

**Comment by tdhartwick** [comment]
Looks like it's fixed! Check it out here: http://foundation.zurb.com/emails/docs/callout.html. Closing this for now. Feel free to reopen this if you have any more problems around this!
