### ISSUE TITLE
[Button] Warning Button

### ISSUE THREAD

**Issue by atahrijouti** [foundation/foundation-emails#323]
1. http://foundation.zurb.com/emails/docs/button.html#coloring
2. See Warning colored button
3. color is blue

Is the color supposed to be blue ?

**Comment by rafibomb** [comment]
It's supposed to be #ffae00. Is that something you can fix with a pull request - it would really help out! Thanks!

**Comment by stewartjarod** [comment]
I think y'all might just need to rebuild and upload. Or there is an issue with the gulp process that builds for the deploy.

**Comment by rafibomb** [comment]
Resolved by @iamsankalp in https://github.com/zurb/foundation-emails/pull/402
