### ISSUE TITLE
Special characters in raw handlebar fragments converted to entity codes

### ISSUE THREAD

**Issue by chedaroo** [foundation/foundation-emails#328]
I know you've had a couple of issues with entity tag conversion lately, but I think this one is in a different scope.

Using the default Panini / Inky stack, I'm trying to use the 'raw' helper to include unparsed handlebar fragments like so:

```
<html>
    ...
    {{{{raw}}}}
        {{var order.getCreatedAtFormated('long')}}
        {{layout handle="sales_email_order_items" order=$order}}
    {{{{/raw}}}}
    ...
</html>
```

I expected to get this:

```
<html>
    ...
    {{var order.getCreatedAtFormated('long')}}
    {{layout handle="sales_email_order_items" order=$order}}
    ...
</html>
```

But actually get this:

```
<html>
    ...
    {{var order.getCreatedAtFormated(&apos;long&apos;)}}
    {{layout handle=&quot;sales_email_order_items&quot; order=$order}}
    ...
</html>
```

As you can see the special characters in the literals have been replaced with entity codes, which is obviously not going to be correctly interpreted by my template processor.

**Comment by inssitu** [comment]
Did you find any solution @chedaroo ?

Thanks

**Comment by chedaroo** [comment]
No, didn't look into it particularly deeply though, sorry. Will do when I get time.

**Comment by erklat** [comment]
Hi, yes I also confirm, I was wrapping Laravel Blade syntax inside Inky blocks using this helper and they were parsed.

**Comment by kjbrum** [comment]
Anyone have any updates on this or fixes/workarounds?

**Comment by cascornelissen** [comment]
@kjbrum, use `zurb/inky#fix-character-escaping` for `inky` in your `package.json` it's a feature branch for Inky which should fix this issue but there are some other issues with it.

It changes the `decodeEntities` option for Cheerio to `false` which is causing this issue.

**Comment by kjbrum** [comment]
@cascornelissen, Awesome that did it. Thanks!

**Comment by rafibomb** [comment]
Ok, so there is a distinction between handlebars parsing and Inky.

The `{{{{raw}}}}` helper passes handlebars (panini) includes without parsing.
The fix for Inky is in the develop branch now. It includes a `<raw></raw>` tag you can add in your HTML to ignore code inside.

PR https://github.com/zurb/inky/pull/57

We'll close this - thanks!
