### ISSUE TITLE
Buttons not centering, nor 100% width in Outlook

### ISSUE THREAD

**Issue by lspoor** [foundation/foundation-emails#330]
**How can we reproduce this bug?**
Create a button with expanded class

Write out the HTML (or Inky code) that causes the issue.
`<table class="button expand">
    <tr>
        <td>
            <table>
                <tr>
                    <td class="radius">
                        <center data-parsed=""><a href="#">Book an Appointment</a></center>
                    </td>
                </tr>
            </table>
        </td>
        <td class="expander"></td>
    </tr>
</table>`

**What did you expect to happen?**
Button to fill width of container and text to be centered

**What happened instead?**
Button doesn't expand to full width and is left aligned

**What email clients does this happen in?**
Outlook 2007/2010/2013

**Comment by cheerfuloriole** [comment]
The table nested inside needs the width set to 100%. As of now, it collapses to its content because it doesn't know otherwise what to do.

**Comment by rafibomb** [comment]
@aaronkahlhamer Did adding width: 100% to the inner table fix it for you? If so, are you able to submit a Pull Request?

**Comment by rafibomb** [comment]
Resolved - duplicate of https://github.com/zurb/foundation-emails/issues/301
