### ISSUE TITLE
Issue with finishing in terminal

### ISSUE THREAD

**Issue by hswidarski** [foundation/foundation-emails#332]
When I try and finish my email and type in npm start build  in terminal I get most of it, but this pops up in my terminal (attached picture)
<img width="582" alt="screen shot 2016-04-06 at 4 11 16 pm" src="https://cloud.githubusercontent.com/assets/18315395/14333043/3d09ff50-fc12-11e5-8009-16eb3959a86e.png">

I only receive the index file in my dist folder, so I am not sure if there is a larger issue behind it, with the original download, but I seem to be having quite a few issues.

**Comment by stewartjarod** [comment]
Looks like there is an issue when it is trying to inline your css. Are you using the `src/assets/css/app.css` file to add your css styling? Did it get renamed or removed?

**Comment by hswidarski** [comment]
Yeah, that seems to be the issue. I am editing my CSS in the settings file and importing all of them in app.scss – could that be the issue that my app and settings files are .scss and not .css
My components I’m naming .scss because that’s how it was done in the video and the app and settings files came in as src/assets/scss/capp.scss.

## 

Hollie Swidarski
Designer
Hswidarski@everspringpartners.com

**Comment by hswidarski** [comment]
## Also, it when I try and inline that I don’t even get a css folder or app.css file in my dist folder.

Hollie Swidarski
Designer
Hswidarski@everspringpartners.com

**Comment by stewartjarod** [comment]
Since you are using the sass version, you should be using the `.scss` extension.

If your folder is really named `src/assets/scss/capp.scss`, you should rename `capp.scss` file to `app.scss`

**Comment by hswidarski** [comment]
## I apologize it was app.scss that was a misspell on my part

Hollie Swidarski
Designer
Hswidarski@everspringpartners.com

**Comment by hswidarski** [comment]
## I feel like there might be an issue with my zurb foundation download because in my terminal when I type nam start build I get this error. Is there a way for me to uninstall the whole program and try again. Or does that give you any more insight into what the issue is?

Hollie Swidarski
Designer
Hswidarski@everspringpartners.com

**Comment by stewartjarod** [comment]
Hrmm, will need more information then. Could you upload and share your npm-debug.log file?

**Comment by hswidarski** [comment]
## How would I do that?

Hollie Swidarski
Designer
Hswidarski@everspringpartners.com

**Comment by stewartjarod** [comment]
Copy all contents and create a public gist: https://gist.github.com/

**Comment by hswidarski** [comment]
## I don’t think I have that, am I supposed to install a debugging tool?

Hollie Swidarski
Designer
Hswidarski@everspringpartners.com

**Comment by rickysullivan** [comment]
The last line of your error output shows the log location.

**Comment by hswidarski** [comment]
## Interesting, the file was missing. I made a blank file with the name npm-debug.log and added it to my template_program folder and it worked! I’m not sure exactly what the issue was, but for some reason I was able to get the css file in my dist folder once created the blank nam-debug.log file.

Hollie Swidarski
Designer
Hswidarski@everspringpartners.com

**Comment by stewartjarod** [comment]
Feel free to close this issue if you think it is resolved :+1:

**Comment by tdhartwick** [comment]
Looks like this was resolved. @hswidarski Feel free to reopen this!
