### ISSUE TITLE
Css rule margin double all over the place

### ISSUE THREAD

**Issue by schwabsimon** [foundation/foundation-emails#336]
In scss/*.scss in almost any scss file the margin rule is there twice: 

Example in _grid.scss on line 30:

  &.container {
    background: $container-background;
    width: $global-width;
    margin: 0 auto;
    Margin: 0 auto;
    text-align: inherit;
  }

**Comment by billmorton** [comment]
I believe the capital M for margin is a hack to get margin working in Outlook.com

https://www.emailonacid.com/blog/article/email-development/outlook.com-does-support-margins

**Comment by schwabsimon** [comment]
@billmorton 

Ok, in that case see this issue closed. In regards of Outlook and such, I stopped wondering anyway.

**Comment by tdhartwick** [comment]
@billmorton exactly! Outlook forces us to do some weird things haha. Going to close this, feel free to reopen this if there is anything else that needs addressed!
