### ISSUE TITLE
Custom font <link> elements are stripped out by Inliner v2

### ISSUE THREAD

**Issue by twiginteractive** [foundation/foundation-emails#340]
I need to include external font faces for custom fonts (yes, I know they won't work in Outlook and other clients, but with font-family fallback it won't hurt) - but the Inliner v2 is stripping them out. I can't even include the @font-face declarations in-page, even inside an @media block.

**Comment by MichalKrakow** [comment]
Just use configuration:

in Your gulpfile.babel.js

```
function inliner(css) {
  var css = fs.readFileSync(css).toString();
  var mqCss = siphon(css);

  var pipe = lazypipe()
    .pipe($.inlineCss, {
      applyStyleTags: false,
      removeStyleTags: false,
      removeLinkTags: false
    })
    .pipe($.injectString.replace, '<!-- <style> -->', `<style>${mqCss}</style>`)
    .pipe($.htmlmin, {
      collapseWhitespace: true,
      minifyCSS: true
    });

  return pipe();
}
```

**Comment by rafibomb** [comment]
@MichalKrakow Thanks for jumping in! Can you describe what these additional params are helping with in this situation? 

If it's a universal solution, would be awesome if you submit a PR!

**Comment by MichalKrakow** [comment]
well defaults for: removeStyleTags and removeLinkTags are true so setting them to false will prevent inliner from removing Link, and Style from Your parsed html while also inline parts that can be embedded directly in html nodes. I figured that's what You're trying to achieve.

**Comment by rafibomb** [comment]
Sounds good! Just added this change - https://github.com/zurb/foundation-emails-template/commit/57bd9e0bbc123a2ad3ab41c6b3caaa5b028b9c06
