### ISSUE TITLE
Thumbnail images overflow becuase of border width

### ISSUE THREAD

**Issue by tdhartwick** [foundation/foundation-emails#341]
**How can we reproduce this bug?**
    <columns small="12" large="12">
      <img src="http://placehold.it/1400x200" alt="my thumbnail" class="thumbnail">
    </columns>
**What did you expect to happen?**
Image wouldn't overflow it's containing row.
**What happened instead?**
It did.
**What email clients does this happen in?**
Tested on chrome, so likely all email clients

**Comment by rafibomb** [comment]
This will be a feature - to bring in Thumbnail styles that work on every device.

**Comment by rafibomb** [comment]
Closing in favor of https://github.com/zurb/foundation-emails/issues/220
