### ISSUE TITLE
Include padding/margin css declarations within Inky language

### ISSUE THREAD

**Issue by probablyabear** [foundation/foundation-emails#343]
Using the Zurb email stack and Inky is great, they really streamline the initial layout of emails. However, it's often necessary to include additional padding on column elements.

Unless I've missed something, I don't believe it's possible to include padding/margin declarations within the Inky language that will be carried over and inserted into the distribution version of the email. 

This is pretty crucial to folks who have to send to lots of recipients with Outlook clients since Outlook disregards margin/padding styling on block-level and elements.

For now, I've found a solution by coding in vanilla HTML according to Zurb's docs, and manually adding padding to <th>'s where needed, but this doesn't feel like the most efficient workaround. 

Am I missing something in the Zurb Stack workflow that would eliminate this issue?

**Comment by rafibomb** [comment]
You can include classes. Since you are using the ZURB stack, the best practice is to create SCSS partials for your custom CSS and style with classes. You can also add CSS directly to the app.scss.

You can do things like 
`<row class="gallery">`

**Comment by probablyabear** [comment]
@rafibomb, thanks for the quick response.

You described exactly what I was looking for; I must've skimmed over that portion of the docs. 

As I understand it, I can apply custom classes to pre-compiled Inky markup elements. Is there a best practice for applying padding/margin focused classes to Inky rows and/or columns?

**Comment by probablyabear** [comment]
I ask because I've noticed applying classes with padding properties to Inky rows or columns often has no effect due to what I assume is the Ink framework's precedence over my custom scss. 

I can get around it with some !imporant declarations, but that feels kind of wrong, and I worry it may break the framework in some instances.

EDIT: Noticed left/right padding declarations on most rows/columns do not work. This could be problematic for some layouts.

**Comment by probablyabear** [comment]
Is there a way to modify the project setup from the Zurb stack to accommodate for adding padding to rows/columns? This is necessary because Outlook ignores margin on block level elements.

**Comment by rafibomb** [comment]
You can use the new `<spacer>` in 2.1 http://foundation.zurb.com/emails/docs/spacer.html
