### ISSUE TITLE
Error in plugin sass. Help

### ISSUE THREAD

**Issue by gdlmsn** [foundation/foundation-emails#345]
After compiling the css.sass, while making some changes, the css file disappear and when trying to npm start again this is what happen.

[errorlog.txt](https://github.com/zurb/foundation-emails/files/216456/errorlog.txt)

npm start

> foundation-emails-template@1.0.0 start /Users/jhulio/foundation-emails-template
> gulp

[16:01:41] Requiring external module babel-register
[16:01:41] Using gulpfile ~/foundation-emails-template/gulpfile.babel.js
[16:01:41] Starting 'default'...
[16:01:41] Starting 'build'...
[16:01:41] Starting 'clean'...
[16:01:41] Finished 'clean' after 4.82 ms
[16:01:41] Starting 'pages'...
[16:01:42] Finished 'pages' after 286 ms
[16:01:42] Starting 'sass'...
Error in plugin 'sass'
Message:
    src/assets/scss/_settings.scss
Error: argument `$color` of `darken($color, $amount)` must be a color

```
   Backtrace:
    src/assets/scss/_settings.scss:124, in function `darken`
    src/assets/scss/_settings.scss:124
    on line 124 of src/assets/scss/_settings.scss
```

> > $callout-border: 1px solid darken($callout-background, 20%);
> >    ---------------------------^

[16:01:42] Finished 'sass' after 34 ms
[16:01:42] Starting 'images'...
[16:01:42] gulp-imagemin: Minified 0 images
[16:01:42] Finished 'images' after 67 ms
[16:01:42] Starting 'inline'...
[16:01:42] 'inline' errored after 2.58 ms
[16:01:42] Error: ENOENT: no such file or directory, open 'dist/css/app.css'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at inliner (gulpfile.babel.js:94:16)
    at inline (gulpfile.babel.js:72:28)
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at asyncRunner (/Users/jhulio/foundation-emails-template/node_modules/async-done/index.js:36:18)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickDomainCallback (node.js:390:13)
[16:01:42] 'build' errored after 414 ms
[16:01:42] 'default' errored after 416 ms

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/Users/jhulio/.npm-packages/bin/npm" "start"
npm ERR! node v4.4.3
npm ERR! npm  v3.5.1
npm ERR! code ELIFECYCLE
npm ERR! foundation-emails-template@1.0.0 start: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the foundation-emails-template@1.0.0 start script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the foundation-emails-template package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs foundation-emails-template
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls foundation-emails-template
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jhulio/foundation-emails-template/npm-debug.log
jhulio: /Users/jhulio/foundation-emails-template

**Comment by fivedoor** [comment]
Hi there, 
Did you get any response or resolution on this issue?
I get a very similar fail on gulp with `npm start`

Issue opened here:
https://github.com/zurb/foundation-emails/issues/377

```
npm ERR! Darwin 10.8.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.4.2
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! foundation-emails-template@1.0.0 start: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the foundation-emails-template@1.0.0 start script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the foundation-emails-template package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs foundation-emails-template
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls foundation-emails-template
npm ERR! There is likely additional logging output above.
```

thanks

**Comment by tdhartwick** [comment]
@gdlmsn Can you elaborate on how you installed it and your environment? I'm trying to replicate it with a fresh cli instal and not hitting any errors.

**Comment by rafibomb** [comment]
@gdlmsn What change had you made that caused the error. The error seems to point to a `$color` variable being declared. How did you use it?

**Comment by gdlmsn** [comment]
I had figure it out. Thanks for your help.

**Comment by drawcard** [comment]
Just solved this issue, posting here for future reference https://github.com/zurb/foundation-emails/issues/325#issuecomment-446009038
