### ISSUE TITLE
npm ERR! No compatible version found: foundation-emails@2.0.1

### ISSUE THREAD

**Issue by arthurpf** [foundation/foundation-emails#349]
**How can we reproduce this bug?**
Normal installing..
git clone https://github.com/zurb/foundation-emails-template project
cd project
npm install

OS - Linux Ubuntu
npm version - 3.8.6
node version - 4.4.2

**What did you expect to happen?**
It should have installed with its latest version(2.0.1)

**What happened instead?**
NPM was unable to found the latest version showing the message:
npm ERR! No compatible version found: foundation-emails@2.0.1

**Comment by arthurpf** [comment]
The npm's package page shows **2.0.0** as latest version

**Comment by masterexploder** [comment]
I managed to get it working by tweaking the `package.json` to roll back the foundation-emails version to `2.0.0` and the panini version to `^1.2.0`. This appears to be the commit that broke everything: https://github.com/zurb/foundation-emails-template/commit/de83791d4a6c7fcb5cc1d27efdf36541f0e00552

**Comment by devmoreno** [comment]
Had this problem as well, I just added the modules one by one and eliminated the foundations-email from package.json to get it working

**Comment by ableandre** [comment]
Same issue guys.
– running 'foundation new' in terminal
– sudo npm install
– get the error: **npm ERR! No compatible version found: foundation-emails@2.0.1
npm ERR! Valid install targets:
npm ERR! 2.0.0, 2.0.0-rc.4, 2.0.0-rc.3, 2.0.0-rc.2, 2.0.0-rc.1, 2.0.0-beta.2, 2.0.0-beta.1**

The only fix I could get working was to roll back to 2.0.0 by modifying the package.json (line14) from "2.0.1" to "2.0.0"

Running MacOSX El Capitan (10.11.4)
Foundation CLI version: 2.1.0

**Comment by arthurpf** [comment]
Exactly what i did @ableandre, worked so far. I'm not sure, but I think the solution is to update the version at npm. Only @gakimball and @tdhartwick can do it.

**Comment by kball** [comment]
Thanks for the report.  Just pushed up the update.
