### ISSUE TITLE
Sass version

### ISSUE THREAD

**Issue by bbakersmith** [foundation/foundation-emails#35]
Is there / will there be a Sass version?

**Comment by rafibomb** [comment]
There is a a Sass version which we built and are currently testing. It will include a Gulp task to inline and we're experimenting with testing as well (integrating with mailgun or something like it). Thinking ahead, we'll need some people to help test it out before we launch.

**Comment by jacobjpope** [comment]
Would love to be a tester @rafibomb

**Comment by ivayloc** [comment]
I will gladly help

**Comment by elidickinson** [comment]
https://github.com/faustgertz/sassy-ink is a really well done SCSS implementation of Ink, for anyone looking for something they can use today.

**Comment by TomiS** [comment]
@rafibomb Any news about the official sass version?

**Comment by RopoMen** [comment]
How close is this sass release?
I was looking in to 'foundation-emails-template' project and did like it, but it would be more usefull if you could provide that inc.scss which is used (?) inside [here app.scss](https://github.com/zurb/foundation-emails-template/blob/master/src/assets/scss/app.scss)
