### ISSUE TITLE
Have Panini Ignore older emails

### ISSUE THREAD

**Issue by zurbrandon** [foundation/foundation-emails#351]
If I have 100 old emails and no longer want to compile all of them on build how would i do this? There should be some way to tell Panini not to compile the file, maybe an underscore like in Sass?

**Comment by rafibomb** [comment]
Might be able to do this with the front-matter, something like `published: false` http://assemble.io/docs/Built-in-Variables.html

This should be part of Panini anyways. We'll see if we can't get this into 2.2

**Comment by macbookandrew** [comment]
Similar to #470

**Comment by kball** [comment]
Implemented in zurb/foundation-emails-template#45
