### ISSUE TITLE
Button inside a center element does not center align below breakpoint

### ISSUE THREAD

**Issue by susantashiro** [foundation/foundation-emails#352]
I have two large-6 columns with a centered button in each column. At full size, the centering works great, however at the small breakpoint, the button is no longer centered - it shifts over to the left (the width of the center element changes from 100% to 50%)

**How can we reproduce this bug?**

``` html
  <row>
        <columns large="6" small="6">
            <img src="http://placehold.it/300/09f/fff.png" alt="" width="242" class="float-center">
        </columns>
        <columns large="6" small="6">
            <img src="http://placehold.it/300/09f/fff.png" alt="" width="242" class="float-center">
        </columns>
    </row>
    <row>
        <columns large="6" small="6">
            <center>
                <button href="#">Shop Now</button>
            </center>
        </columns>
        <columns large="6" small="6">
            <center>
                <button href="#" target="_blank">Shop Now</button>
            </center>
        </columns>
    </row> 
```

**What did you expect to happen?**
Below the breakpoint, I expected the button to stay centered

**What happened instead?**
The button shifted to the left. When I inspect the center element, it shows the following style:
@media only screen and (max-width: 596px) {
   .body .column td.small-6, .body .column th.small-6, 
   .body .columns td.small-6, .body .columns th.small-6, 
   td.small-6 center, th.small-6 center {
      display: inline-block!important;
      width: 50%!important;
  }
}

media-query.scss:75
  //Rules for the Center Tag
  @for $i from 1 through ($grid-column-count - 1) {
    .body .columns td.small-#{$i},
    .body .column td.small-#{$i},
    td.small-#{$i} center,
    .body .columns th.small-#{$i},
    .body .column th.small-#{$i},
    th.small-#{$i} center {
      display: inline-block !important;
      width: -zf-grid-calc-pct($i, $grid-column-count) !important;
    }
  }

**What email clients does this happen in?**
Just testing on localhost:3000

![buttons_not_centered](https://cloud.githubusercontent.com/assets/12661734/14541605/9c3d758c-023f-11e6-9a79-e60ccd7e6986.png)

**Comment by rafibomb** [comment]
I was able to replicate this. It seems like the grid CSS is more specific and overriding the button's behavior. I like the solution you mentioned in the course chat this morning.

**Comment by rafibomb** [comment]
Resolved!

**Comment by susantashiro** [comment]
Awesome thanks!! :)
