### ISSUE TITLE
Viewing New Pages

### ISSUE THREAD

**Issue by hswidarski** [foundation/foundation-emails#353]
Hi I was wondering how I view the different pages on my local host. I tried typing in localhost:300/pagename and it said it was not valid. How am I able to view it on my browser?

Thanks

**Comment by rafibomb** [comment]
It should be http://localhost:3000/pagename.html The file extension html is necessary as well.

**Comment by hswidarski** [comment]
## Oh great thank you. There’s a bunch of small issues we’re having. Are we able to do a google hang out with someone to get these specific questions answered?

Hollie Swidarski
Designer
Hswidarski@everspringpartners.com
