### ISSUE TITLE
P Tags don't change color from a Sass variable

### ISSUE THREAD

**Issue by zurbrandon** [foundation/foundation-emails#357]
Couldn't find a variable to change the color of P tags, but could change colors of H-tags.

**Comment by rafibomb** [comment]
There is a $global-font-color that works for this. The `$header-color` is set to inherit but that can be overridden as needed. Does this set up make sense or do you think there needs to be an explicit `$paragraph-font-color` instead of `$global-font-color`?

**Comment by tdhartwick** [comment]
The variable was somehow in global.scss. Moved it to typography.scss https://github.com/zurb/foundation-emails/commit/3dd792d9ed2bda6d86973f74a3d826bb5349cd6f
