### ISSUE TITLE
Trying to get three close images in footer

### ISSUE THREAD

**Issue by ementzer** [foundation/foundation-emails#361]
We are creating a footer and would like three social icons to be close and centered under the contact information. Currently we have the contact information in columns, but they also are a little too spaced out. The social icons were also in columns, but I have since removed them. I have tried removing the space in the gutter, but either was doing it incorrectly or couldn't get it to work. 

Here is the Inky code so far (we have the footer in a partial): 

<row>
  <columns class="padding">
  </columns>
</row>
<row>
![screen shot 2016-04-15 at 8 24 43 am](https://cloud.githubusercontent.com/assets/18484773/14563268/a7847de4-02e6-11e6-9b0d-ed8b0463a38b.png)

  <columns class="footerbar" small="12" large="12">
  </columns>
</row>
<row>
  <columns class="padding">
  </columns>
</row>
<row>
    <center>
        <columns small="12" large="5">
    <p style="font-size:12px;"><strong>Contact Us:</strong> Online Admissions</p>
    </columns>
    <center>
      <columns small="12" large="3">
      <img src="http://pages.universityadmissions.info/rs/731-FJI-115/images/ContactIcons-03.png" alt="Phone" style="float:left; height:20px;">
    <p style="font-size:12px; align:left;">(330) 474-3285</p>
    </columns>
      </center>
      <columns small="12" large="4">
      <img src="http://pages.universityadmissions.info/rs/731-FJI-115/images/ContactIcons-02.png" alt="E-mail" style="float:left; height:20px">
    <p style="font-size:12px;">onlinedegrees@kent.edu</p>
    </columns>
  </center>
</row>
<row>
  <columns small="12" large="12">
<img src="http://pages.universityadmissions.info/rs/731-FJI-115/images/facebook-128.png" href="google.com" alt="Facebook" style="height:30px;">
<img src="http://pages.universityadmissions.info/rs/731-FJI-115/images/twitter-128.png" href="google.com" alt="Twitter" style="height:30px;">
<img src="http://pages.universityadmissions.info/rs/731-FJI-115/images/youtube-128.png" href="google.com" alt="YouTube" style="height:30px;">
</columns>
</row>
<br/>
<br/>
<row>
  <columns small="12" large="12">
    <p style="text-align:center; font-size:10px;">Kent State University | 800 E. Summit St. Kent, Ohio 44240
  <br/><u><a style="color:#00b3ef" href="mailto:onlinedegrees@kent.edu">onlinedegrees@kent.edu</a></u> | <u><a style="color:#00b3ef" href="#">Privacy</a></u> | <u><a style="color:#00b3ef" href="#">Unsubscribe</a></u></p>
  </columns>
</row>

![screen shot 2016-04-15 at 8 24 43 am](https://cloud.githubusercontent.com/assets/18484773/14563283/b3f195d0-02e6-11e6-876b-959a2452b272.png)

**Comment by rafibomb** [comment]
The [Foundation forum](http://foundation.zurb.com/forum/) would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!
