### ISSUE TITLE
Localhost:300 - cannot get

### ISSUE THREAD

**Issue by hswidarski** [foundation/foundation-emails#365]
When I am in terminal and starting to 'foundation watch' a project, everything looks fine in terminal but when it opens in Localhost:3000 this shows up on my screen "Cannot GET /"
<img width="517" alt="screen shot 2016-04-15 at 4 06 23 pm" src="https://cloud.githubusercontent.com/assets/18315395/14574931/0bb3f334-0324-11e6-90b9-7ad30c427b6f.png">

**Comment by rafibomb** [comment]
Do you have an index.html file? The build is looking for that when it loads.

**Comment by rafibomb** [comment]
Things that may cause this
- a page moved
- no index.html page

We'll close this here as we are using GitHub to work on confirmed bugs. Thanks!
