### ISSUE TITLE
Class for telephone and address links on iOS devices?

### ISSUE THREAD

**Issue by sco-tt** [foundation/foundation-emails#367]
iOS devices turn telephone numbers and addresses into links. I always end up overwriting these with the last technique listed here:
https://litmus.com/blog/update-banning-blue-links-on-ios-devices

Does it make sense to incorporate this into the global CSS as a utility class with color: inherit? The issue is that it doesn't work when inlined, so it would need to be wrapped in @media screen { } so it appeared in the styles in the <head>

I think this makes sense from the point of the view that the framework should minimize cross-client visual differences as much as possible. I suppose that some might see this as a feature of iOS, and thus adding a global style in the <head>  for an optional utility class might not make sense. I'd also be happy to contribute a SCSS snippet to the docs to so that those interested could drop it into app.scss.

**Comment by rafibomb** [comment]
Hmm, in my mind the real question is - is this part of the framework or a technique that can be documented?

We have a document in the works that has all kinds of tips and tricks and hacks like this. Perhaps we publish it as a first step and you can add this example there? We can see if tons of people are still tripping up on it, then we can add it in a future release to the global CSS.

Thoughts?

**Comment by sco-tt** [comment]
Adding this to the tricks and hacks document sounds good, and then we can keep an eye on the issue list to see if it merits inclusion in the global CSS. Where should I look for the upcoming document?

**Comment by probablyabear** [comment]
@sco-tt I've found that using a combination of http://www.removebluelinks.com/ and wrapping the offending text in `<font color="#XXXXXX"></font>` works most of the time.

**Comment by tdhartwick** [comment]
@sco-tt or @stephenrust We'd love to see a PR on the docs page here: https://github.com/zurb/foundation-emails/blob/develop/docs/pages/tips-tricks.md
Thanks for point this stuff out!

**Comment by probablyabear** [comment]
@tdhartwick Submitted PR with this content.
