### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by hswidarski** [foundation/foundation-emails#369]
In our footer, we have three circular social icons that sit in the same row. Full screen they look fine, and work properly, but when pushed to mobile size they increase in size, even though we have defined a width on them and we can not seem to find a way for them to sit centered when on mobile and they also tend to stack.

Below I have included the footer and have attached a photo of how it appears when small vs. full screen
<img width="663" alt="screen shot 2016-04-19 at 11 19 24 am" src="https://cloud.githubusercontent.com/assets/18315395/14646819/a63f02f0-0620-11e6-903c-ab701ff989b4.png">
<img width="310" alt="screen shot 2016-04-19 at 11 19 34 am" src="https://cloud.githubusercontent.com/assets/18315395/14646820/a6401fa0-0620-11e6-9912-b415a62c3dd7.png">

:

<row>
  <columns class="padding">
  </columns>
</row>
<row>
  <columns class="footerbar" small="12" large="12">
  </columns>
</row>
<row>
  <columns class="padding">
  </columns>
</row>
<row>
        <columns small="12" large="5">
    <p class="small-text-left;" style="font-size:12px; float-for-large:right;"><strong>Contact Us:</strong> Online Admissions</p>
    </columns>
    <center>
      <columns small="12" large="3">
      <img src="http://pages.universityadmissions.info/rs/731-FJI-115/images/ContactIcons-03.png" alt="Phone" style="float:left; height:20px;" class="show-for-large">
    <p style="font-size:12px; align:left;" class="small-text-left">(330) 474-3285</p>
    </columns>
      </center>
      <columns small="12" large="4">
      <img src="http://pages.universityadmissions.info/rs/731-FJI-115/images/ContactIcons-02.png" alt="E-mail" style="float:left; height:20px;" class="show-for-large">
    <p style="font-size:12px;" class="small-text-left">onlinedegrees@kent.edu</p>
    </columns>
</row>
<row class="collapse">
  <columns small="4" large="1; large-offset-5;">
<img src="http://pages.universityadmissions.info/rs/731-FJI-115/images/facebook-128.png" href="google.com" alt="Facebook" style="float:right; width:30px">
</columns>
  <columns small="4" large="1" style="float:center;">
    <center>
<img src="http://pages.universityadmissions.info/rs/731-FJI-115/images/twitter-128.png" href="google.com" alt="Twitter" style="width:30px;">
</center>
</columns>
  <columns small="4" large="5" style="float:left;">
<img src="http://pages.universityadmissions.info/rs/731-FJI-115/images/youtube-128.png" href="google.com" alt="YouTube" style="floatleft; width:30px;">
</columns>

</row>

**Comment by sco-tt** [comment]
Do you have HTML you can share?

I did something similar recently; I put the social links in a div within my column

`<columns small="12" large="6" class="footer-section">
  <div class="social">
    <a href="#" class="social-link"><img src="#" alt="Intagram"></a>
    <a href="#" class="social-link"><img src="#" alt="Facebook"></a>
    <a href="#" class="social-link"><img src="#" alt="twitter"></a>
  </div>
</columns>`

In app.scss I had this

`// Footer
.footer-section {
  vertical-align: middle;
}
div.social {
  text-align: center;
  padding: 40px 0 0 0;
}
a.social-link:not(:last-child) {
  padding: 0 5px 0 0;
}
`

**Comment by hswidarski** [comment]
Two questions:

Can you use divs with the foundations 2? I was under the impression they got rid of them.
Also why did you put an a in front of social-link css, out of curiosity?

Thank you for your help

**Comment by sco-tt** [comment]
1) As far as I know, yes, you can use divs. I use them for positioning and grouping content within the <column> tags. Everything has worked as expected when I run my tests across clients

2) I use it as a reference for myself; the CSS will be inlined, so selector performance doesn't really matter. I over-qualify selectors so it's easy to read for me.

**Comment by hswidarski** [comment]
Did you make another column with the remaining "6" for large?

**Comment by hswidarski** [comment]
Also what does "a.social-link:not(:last-child)" mean? not last-child?

**Comment by sco-tt** [comment]
1. Yes, there was another 6 <column> tag as a sibling to the code I put up earlier
2. Yes, not last child. Again, stuff is getting inlined, so I'm writing CSS in ways that faster/easier for me.

**Comment by hswidarski** [comment]
![screen shot 2016-04-19 at 2 00 15 pm](https://cloud.githubusercontent.com/assets/18315395/14651820/2a00e8d6-0637-11e6-9f1c-b65735175e2d.png)
![screen shot 2016-04-19 at 2 00 40 pm](https://cloud.githubusercontent.com/assets/18315395/14651821/2a01ddb8-0637-11e6-833e-0956bce7e939.png)
<img width="518" alt="screen shot 2016-04-19 at 2 00 47 pm" src="https://cloud.githubusercontent.com/assets/18315395/14651819/2a00b550-0637-11e6-8219-e7a6383ddd1f.png">
for some reason it's now going vertical for me

**Comment by sco-tt** [comment]
Sorry, forgot the last rule

`
a.social-link {
  display: inline-block;
}
`

or 

`
.social a {
display: inline-block;
}
`

**Comment by rafibomb** [comment]
@sco-tt Great answers!

`<div>`'s don't work constantly other than to target elements wrapped in a div with a class. The `<wrapper>` component will work better. It will be in the 2.1 release this week.

The [Foundation forum](http://foundation.zurb.com/forum/) would be a great place to seek some help with discuss what might be going on here. Thanks!

**Comment by hswidarski** [comment]
## What day does 2.1 come out? Do we have to download anything or will it automatically update? And will we receive any emails or documents that explain all new elements in the update?

Hollie Swidarski
Designer
Hswidarski@everspringpartners.com
