### ISSUE TITLE
Visibility classes don't work on Gmail or Yahoo! clients

### ISSUE THREAD

**Issue by thirteenpixels** [foundation/foundation-emails#371]
**How can we reproduce this bug?**

Default project, no changes to styles, using this template:

```
<container>
  <row>
    <columns small="12" large="12" class="hide-for-large">
      <p>This is mobile content and will be visible in Yahoo! and Gmail but it shouldn't be. Yahoo! Explorer will hide this correctly.</p>
    </columns>
    <columns small="12" large="12" class="show-for-large">
      <p>This is desktop content.</p>
    </columns>
  </row>
</container>
```

**What did you expect to happen?**

Mobile columns should be hidden on desktop.

**What happened instead?**

Mobile columns are visible in addition to the desktop columns.

**What email clients does this happen in?**

All desktop Gmail and all but Explorer desktop Yahoo!

You can view a litmus test here:

https://litmus.com/builder/c575502

**Comment by rafibomb** [comment]
Hmm, it didn't get into the docs but this a know incompatibility with gmail and the `.hide-for-large` class

**Comment by rafibomb** [comment]
There hasn't been a suitable solution presented but we're open to ideas. For now, we'll add this to the docs and close this here. Thanks!
