### ISSUE TITLE
Social Icons

### ISSUE THREAD

**Issue by hswidarski** [foundation/foundation-emails#372]
I found this on the Zurb Playground

http://zurb.com/playground/social-webicons#

Do these work on emails as well? How do I import them so they function correctly?

**Comment by rafibomb** [comment]
Webfonts do NOT work reliably in html emails. Some clients might respect and render them, but the majority don't. You can import them through a CDN which is easiest. https://cdnjs.com/libraries/foundicons

**Comment by hswidarski** [comment]
## Is there another webinar this week?

Hollie Swidarski
Designer
Hswidarski@everspringpartners.com
