### ISSUE TITLE
Grid layout is broken on native iphone email client.

### ISSUE THREAD

**Issue by tompere** [foundation/foundation-emails#373]
Grid layout is **BROKEN** on iphone devices with native email client.

**Reproduction**
generate new project with foundation-cli (npm package), where npm module _foundation-emails_ is of version 2.0.1 (githead 3c1658219aea5933bb3dff8b4cc91c5c67b67f7c).
and use iphone 6/6s email clients.

[see html source](http://pastebin.com/t1EdFB1Y)
_note that two rows were added (each with a button)_

[see iphone 6s plus screenshot](http://g11i.imgup.net/iPhone6sPl2eea.png)

**Comment by rafibomb** [comment]
Can you help narrow down what element is causing the grid width issue you are seeing?

**Comment by rafibomb** [comment]
Testing on 2.1  - Not seeing this happen in litmus though the bulletproof button does not need a table. Just to be sure, tested your email on an iPhone 6 and 5 and looks good. We'll close this here - please open a new issue if you are still seeing an issue with this. Thanks!
