### ISSUE TITLE
Foundations 2.1

### ISSUE THREAD

**Issue by hswidarski** [foundation/foundation-emails#374]
When does the updated foundations come out? Do we have to do anything to get the update? Is there another webinar? Will there be a document that tells us all the updates that are happening?

**Comment by rafibomb** [comment]
Foundation 2.1 will be out tomorrow! You can see the changelog here: https://github.com/zurb/foundation-emails/releases

You can update in the command line: 'npm update'

**Comment by hswidarski** [comment]
## Is it still going to be released today?

Hollie Swidarski
Designer
Hswidarski@everspringpartners.com
