### ISSUE TITLE
How can I add style declaration blocks to the CSS for editable MailChimp templates?

### ISSUE THREAD

**Issue by landitus** [foundation/foundation-emails#376]
In order to add support for MailChimp templates, it would be desirable to be able to add the @style declaration to the headings styles as noted [here](http://templates.mailchimp.com/getting-started/template-language/). This would enable to add h1, h2, h3 styles in editable regions in MailChimp. Unfortunately the "@style" gets strip out in the compilation process. How could this be added or achieved?

<img width="285" alt="screen shot 2016-04-20 at 23 20 44" src="https://cloud.githubusercontent.com/assets/239215/14696098/a7a6f56a-074e-11e6-8095-3f095f33fc15.png">

**Comment by sco-tt** [comment]
Have you tried putting this code in src/layouts/default.html ?

**Comment by sco-tt** [comment]
Actually, I think you need to modify your gulpfile. 

in app.scss, wrap your Mailchimp code in a media query @media screen {} so it's included in a style tag.

In your gulpfile, find the function `inliner()` (it should be towards the bottom) and change `minifyCSS: true` to  `minifyCSS: false`

**Comment by sco-tt** [comment]
Did this work?

**Comment by rafibomb** [comment]
@sco-tt Thanks for jumping in here!
