### ISSUE TITLE
updates

### ISSUE THREAD

**Issue by hswidarski** [foundation/foundation-emails#381]
What are the steps used to download the email updates? And for wrapper and spacer tag, does the closing tag immediately follow or further down the coding? Lastly, is there a video showing how to use the updated components?

**Comment by hswidarski** [comment]
When I type in 'npm update' - nothing happened and when I typed in 'npm foundation update' and 'foundation update' it told me, nothing to update, you're good.

**Comment by alex-ketch** [comment]
@hswidarski First you need to point you `package.json` file to point to GitHub instead of the published NPM package.
You can also specify a branch as you can see with `foundation-emails` below.

```
"devDependencies": {
    "foundation-emails": "zurb/foundation-emails#develop",
    "inky": "zurb/inky"
},
```

**Comment by rafibomb** [comment]
I would add that you'd only point to the Inky repo if you were testing new changes BEFORE they were pushed as a release. We're trying to match our Foundation-emails releases with Inky releases. 

Instead make sure your `package.json` dependancies are up to date: 

About line 16

```
  "dependencies": {
    "foundation-emails": "2.1.0"
  },
```

and Inky about line 39

```
"inky": "^1.3.5",
```

Then run `npm update`
