### ISSUE TITLE
&nbsp; is converted to &amp;nbsp;

### ISSUE THREAD

**Issue by mkelley82** [foundation/foundation-emails#384]
```
&nbsp; is converted to &amp;nbsp;
```

This happens during the conversion process..

**Comment by davidhouweling** [comment]
I also have a similar issue with `'` being shown in the email as `&apos;`

**Comment by REJack** [comment]
thats happened with `&gt;` & `&lt;` too, formerly it transform every `&` to `&amp;`

**Comment by rafibomb** [comment]
Are you using the [web inliner](http://foundation.zurb.com/emails/inliner-v2.html) or the `npm run build` command?

**Comment by REJack** [comment]
@rafibomb i used the web inliner

**Comment by davidhouweling** [comment]
I'm using the `npm run build`, getting the result of that and emailing it through `nodemailer` to an address being consumed by Outlook.

**Comment by jasonlmann** [comment]
I'm seeing the `&apos;` issue using `npm run build` and `npm run litmus`

**Comment by REJack** [comment]
with `npm run build` i get no failures

**Comment by mkelley82** [comment]
I am seeing it happen with the inliner.

**Comment by rafibomb** [comment]
Looks like this is not an inliner issue. 

If you are using `npm start` and not inlining, then view page source - it seems that you still see the character is converted. It seems to be related to Cheerio which is used in Inky. Working to track that down.

**Comment by rafibomb** [comment]
There is a Cheerio option to prevent the characters from being converted. We're testing the option here: https://github.com/zurb/inky/tree/fix-character-escaping

It would help resolve this sooner if you can test this fix out by pointing your package.json inky dependency to this branch and running `npm update`

<img width="506" alt="screen shot 2016-05-06 at 8 41 21 am" src="https://cloud.githubusercontent.com/assets/5652085/15078077/5601cd7e-1366-11e6-90e7-3f975dd21b7e.png">

**Comment by rafibomb** [comment]
Added test cases here: 9a09698

**Comment by jasonlmann** [comment]
I can confirm this works for the apostrophe / `&apos;` issue. 

I'm kinda new to Github. Is that commit you linked to just for reference or did you want us to leave comments on it to confirm it's working?

**Comment by ghost** [comment]
@rafibomb i tried the fix above and the issue that I had with 
`<< >>` causes the parser to just stop working. Which means I would have to go through about 20 emails where dynamic content is injected just to get it to inline correctly. However, I tried to go back to what I had before and now the inliner will not work for me as it did before. It keeps erroring when it gets to the double brackets for the dynamic code that's injected by my email provider.

**Comment by michael-mader** [comment]
Seems to fix most problems. No more escaped quotes. 

But comparing the output of this branch with 2.1 stable, I noticed that `=` characters in urls get escaped with `&#x3D;`. Not sure if they will work like expected.

**Edit:** Chrome handles the urls fine. But I can't test on Outlook and other mail programs
Example: `https://test.com?utm_source&#x3D;test&amp;utm_medium&#x3D;test&amp;utm_campaign&#x3D;test`

**Comment by rafibomb** [comment]
Resolved by https://github.com/zurb/inky/pull/57

@coreyschaaf We added a `<raw>` tag that you can wrap HTML with to not convert or not run through Inky. It's in the `develop` branch on Inky now. The Inliner may still convert it but at least Inky does not.

Use it like this: 
`<raw><<LCG Program\TG LCG Coupon Code Default='246996'>></raw>`

**Comment by rafibomb** [comment]
@Fender123 The branch has been updated and since merged into `develop` because it passed testing. Can you add a test case for the URL piece you're referring to here? https://github.com/zurb/foundation-emails/blob/develop/test/visual/pages/inliner-bugs.html

**Comment by rafibomb** [comment]
@jasonlmann Good question! When a potential fix is pushed it does help if people test it and report back  - that way we can confidently merge it quicker. The more people who test it - the more use cases we can cover. Thanks!

**Comment by m-i-k-e** [comment]
@kball Any idea when this will be merged to master and released?
