### ISSUE TITLE
$anchor-text-decoration not being utilised

### ISSUE THREAD

**Issue by davidhouweling** [foundation/foundation-emails#385]
**How can we reproduce this bug?**
Set `$anchor-text-decoration` to underline and notice that it does not actually alter the markup.

This has been hard coded in https://github.com/zurb/foundation-emails/blob/develop/scss/components/_type.scss#L241 rather than using the variable.

**What did you expect to happen?**
Anchor to be underlined.

**What happened instead?**
Anchor remains without text decoration.

**What email clients does this happen in?**
All of them.

**Comment by tdhartwick** [comment]
Nice catch, addressed it here: https://github.com/zurb/foundation-emails/issues/400
