### ISSUE TITLE
Content must match specified doctype

### ISSUE THREAD

**Issue by OEvgeny** [foundation/foundation-emails#387]
**How can we reproduce this bug?**

You can examine source of this exmple to see it
http://foundation.zurb.com/downloads/templates-emails/basic.html
For example there are no self-closing tags in XHTML spec. (Line 5)

**What did you expect to happen?**

I did expect content matches declared DOCTYPE.

**What happened instead?**

There are a lot of errors. Check this https://validator.w3.org/check?uri=http%3A%2F%2Ffoundation.zurb.com%2Fdownloads%2Ftemplates-emails%2Fbasic.html&charset=%28detect+automatically%29&doctype=Inline&group=0

**Comment by rafibomb** [comment]
What issues does this cause in real world testing? Is there another doctype you suggest?

**Comment by OEvgeny** [comment]
@rafibomb I think content must match doctype. So, I don't know why this doctype is chosen. If there is no metter what doctype to use, we can use html 4.1/5 doctype instead.

**Comment by rafibomb** [comment]
The doctype xhtml strict is pretty standard for email development. If you see one that works better, we'd love to hear about it. This article describes it well: https://www.campaignmonitor.com/blog/email-marketing/2010/11/correct-doctype-to-use-in-html-email/

**Comment by OEvgeny** [comment]
@rafibomb Good to hear. But why are you ignoring doctype restrictions? It potentially can cause some parsers to fail on generated html.
