### ISSUE TITLE
Center tags did not remove from generated html

### ISSUE THREAD

**Issue by OEvgeny** [foundation/foundation-emails#388]
**How can we reproduce this bug?**

See generated example template sources:

http://foundation.zurb.com/downloads/templates-emails/hero.html

```
Line 14: <center data-parsed="">...</center>
```

Write out the HTML (or Inky code) that causes the issue.

```
<center>...</center>
```

**What did you expect to happen?**

I did expect center tag not appears in generated HTML

**What happened instead?**

`center` tag appears in generated html 

**What email clients does this happen in?**

All

**Comment by rafibomb** [comment]
Are you referring to the `data-parsed=""` attribute? Is it causing issues and if so whhat issues is it causing?

**Comment by OEvgeny** [comment]
@rafibomb I thought that the whole `center` tag should not appear in generated html. It's not about `data-parsed` attribute. I mean tag should be removed from template like for example `columns` and other inky tags. Am I wrong?

**Comment by rafibomb** [comment]
In emails, especially Outlook and some others the `<center>` tag is a valid use case. It is required in fact to center things across all email clients. We'll close this here - thanks!
