### ISSUE TITLE
NPM Run build not working

### ISSUE THREAD

**Issue by hswidarski** [foundation/foundation-emails#389]
![npm run build](https://cloud.githubusercontent.com/assets/18315395/14823006/7c9f9128-0b96-11e6-9e4b-41ec76795337.png)

When I am trying to inline my emails and do NPM run build I receive this error. I used NPM start build like we were taught in the previous lectures before the updates and used inliner to combine the two. Which worked except there was some issues among the different email clients with spacing, footer, and logo in the header not showing up,
![litmus1](https://cloud.githubusercontent.com/assets/18315395/14823197/397017e6-0b97-11e6-8427-c63298976cf1.png)
![litmus2](https://cloud.githubusercontent.com/assets/18315395/14823196/396ee024-0b97-11e6-9434-15ce3da1fd4e.png)
![litmus3](https://cloud.githubusercontent.com/assets/18315395/14823198/3972696a-0b97-11e6-923c-6cf0453b9770.png)

**Comment by rafibomb** [comment]
Hmm, we're not able to replicate this. What version are you using? Have you made changes to the default template and if so what were those?

**Comment by hswidarski** [comment]
I thought I got the update because the spacer tag is now working. This is the very top of terminal when I put in ‘NPM build’ (attached) as well as the bottom with the errors.

## I tried deleting the HTML files in the dist folder and starting over and doing NPM run build and still came across the same error.

Hollie Swidarski
Designer
Hswidarski@everspringpartners.com

**Comment by rafibomb** [comment]
The command to start the server is `npm start` and then `npm run build` for production. You can try deleting the node_modules folder and then running `npm install` to re-build it.

**Comment by hswidarski** [comment]
Do I also delete what's in the dist folder to re run it?

**Comment by hswidarski** [comment]
So I deleted the node_modules folder on both these tests I did and ran an 'npm install'
![screen shot 2016-04-29 at 8 27 59 am](https://cloud.githubusercontent.com/assets/18315395/14917567/5fa069de-0de5-11e6-8a41-7dcdcea04636.png)
![screen shot 2016-04-29 at 8 32 10 am](https://cloud.githubusercontent.com/assets/18315395/14917569/630011f6-0de5-11e6-9782-12b29bf089b0.png)

 to one a folder that had the dist folder deleted as well as one that had it still filled from the 'npm start build' html files and this is what happened in my terminal:

**Comment by rafibomb** [comment]
Not sure what  `npm run install` does? The commands are as follows:
- `npm start` to run the project and watch for changes
- `npm run build` to run the project and run the production functions
- `npm update` updates the dependancies in node_modules
- `npm install` creates and installs the dependancies in node_modules

**Comment by rafibomb** [comment]
The [Foundation forum](http://foundation.zurb.com/forum/) would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!
