### ISSUE TITLE
Why are colours and patterns set on 0-width borders?

### ISSUE THREAD

**Issue by Synchro** [foundation/foundation-emails#390]
I'm not sure if this is a bug or not. The CSS includes lots of elements like this:

```
border: 0px solid #3adb76;
```

If a border has 0 width, whether it's solid or what colour it is doesn't matter, yet this pattern appears in many places. If this has some specific purpose then please ignore this ticket, but if it's not intentional, I'll make a PR to clean them up.

**Comment by rafibomb** [comment]
Can you point to the files or lines that have these? Sounds incorrect but we can make sure.

**Comment by Synchro** [comment]
Actually I think they are all in _buttons.scss, it just expands to more when generating the CSS, but these are in the source (there are others in there too):

[1](https://github.com/zurb/foundation-emails/blob/develop/scss/components/_button.scss#L209) [2](https://github.com/zurb/foundation-emails/blob/develop/scss/components/_button.scss#L258) [3](https://github.com/zurb/foundation-emails/blob/develop/scss/components/_button.scss#L271) [4](https://github.com/zurb/foundation-emails/blob/develop/scss/components/_button.scss#L283) [5](https://github.com/zurb/foundation-emails/blob/develop/scss/components/_button.scss#L80)

**Comment by Synchro** [comment]
The only reason I can see for having them there is if later overrides change only the width, they will still inherit the line style and colour. Not sure if that's actually the case though.

**Comment by tdhartwick** [comment]
@Synchro Yeah, this looks a little odd. Looks like I changed it a few months ago as we were developing this. See: https://github.com/zurb/foundation-emails/commit/f7762f49667d5cb3ee2aa1f9860437c91d52290d

It looks like there was an odd gap that appeared in some email clients. I don't remember if this was a hack or a quick fix...

Any chance you can test it out to see if anything happens once it's removed?

**Comment by codedbypaul** [comment]
I've found that changing:

```
table.button table td a
```

to:

```
border: none
```

or

```
border: 0px solid transparent
```

causes the button to lose all padding in Outlook 2013 (possibly other Outlooks but only using the free trial of Litmus atm).

If I keep it I end up with a border around the link tag as well.

**Comment by rafibomb** [comment]
I think this was part of the hybrid buttons patterns. We're also looking to get Bulletproof buttons into Inky!
