### ISSUE TITLE
Apostrophe converting to &apos;

### ISSUE THREAD

**Issue by jasonlmann** [foundation/foundation-emails#393]
**How can we reproduce this bug?**

My index.html partial contains this code:
`<columns small="12">
        <h2>Don't miss out!</h2>`

**What did you expect to happen?**
The text renders fine in browser tests, and using Litmus it looks fine in all clients except Outlook.

**What happened instead?**
However, the apostrophe in "Don't" is converted to `&apos;`. 

See this snippet from the dist folder:
`<h2 style="Margin:0;Margin-bottom:10px;color:inherit;font-family:HelveticaNeue-CondensedBold,'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:30px;font-weight:700;line-height:1.3;margin:0;margin-bottom:10px;padding:0;text-align:left;word-wrap:normal">Don&apos;t miss out!</h2>`

That leads to this result in Outlook:
<img width="424" alt="screenshot 2016-04-27 16 13 29" src="https://cloud.githubusercontent.com/assets/6288069/14866745/19669144-0c93-11e6-8372-2da3942e3872.png">

**What email clients does this happen in?**
Outlook 2007, 2013

**Comment by rafibomb** [comment]
Thanks for the report Looks like a duplicate issue. We'll close this in favor of https://github.com/zurb/foundation-emails/issues/281
