### ISSUE TITLE
$anchor-text-decoration not updating

### ISSUE THREAD

**Issue by jordanbommelje** [foundation/foundation-emails#400]
**How can we reproduce this bug?**
Change default value of $anchor-text-decoration in _settings.scss file
Write out the HTML (or Inky code) that causes the issue.
$anchor-text-decoration: underline;
**What did you expect to happen?**
An underline applied to my links.
**What happened instead?**
No default value remains the same, no underline.
**What email clients does this happen in?**
All. Including web browser testing, the tex-decoration attribute is not being updated

Using Foundation CLI version 2.1.0. Issue persists in multiple projects.

**Comment by rafibomb** [comment]
Thanks for the report! Can you see where the issue is coming from? Is there a specificity issue or are you seeing a missing declaration in the Sass?

**Comment by tdhartwick** [comment]
Knocked it out here: https://github.com/zurb/foundation-emails/commit/d535580dc56e9a66af916814e6fa463126b6db55

**Comment by jordanbommelje** [comment]
Awesome. Thanks Tim!
