### ISSUE TITLE
How to put custom styles/css?

### ISSUE THREAD

**Issue by iamsankalp** [foundation/foundation-emails#403]
Hey! I have question regarding how should we be using custom css?

Two approaches - 

1) When i put in `<style>` in Inky - it's stripped out on`npm run build` And, thus, not showing up in final version.

2) I changed default.html to include a `custom.css` link. Put up a file in `dist` named `custom.css` and it works for me.

Is it how it's supposed to work?

Thanks,
Sankalp

**Comment by iamsankalp** [comment]
Since, dist folder rebuilds everytime - the second approach is of no real use. :(

**Comment by iamsankalp** [comment]
Hey @jasonlmann. Sorry to mention weirdly.

Since you are using custom css as i saw in some other issue... May you please help me with the above.

Thanks a lot,
Sankalp

**Comment by jasonlmann** [comment]
Hi @iamsankalp. Instead of putting your styles in index.html (where you use Inky), put them in src/assets/scss/app.scss 

That file gets compiled and then inlined when you run `npm run build`. Hope that helps.

**Comment by iamsankalp** [comment]
@jasonlmann Awesome. Thanks a ton, man! I should drink lesser. 😆
