### ISSUE TITLE
$anchor-text-decoration is not being used

### ISSUE THREAD

**Issue by syabro** [foundation/foundation-emails#407]
**How can we reproduce this bug?**
Set `$anchor-text-decoration: underline;` in `_settings.scss`

**What did you expect to happen?**
a links should be underlined

**What happened instead?**
No underline

**What email clients does this happen in?**
Any

In _type.scss:

``` sass

a {
  color: $anchor-color;
  text-decoration: none;

```

should be 

``` sass
a {
  color: $anchor-color;
  text-decoration: $anchor-text-decoration;

```

**Comment by davidhouweling** [comment]
duplicate... https://github.com/zurb/foundation-emails/issues/385

**Comment by syabro** [comment]
@davidhouweling ty, closing
