### ISSUE TITLE
Foundaion for emails' files name are conflicted with Foundation for sites

### ISSUE THREAD

**Issue by imabdulsal** [foundation/foundation-emails#409]
The files name `dist/foundation.css` and `dist/foundation.min.css` of Foundation for emails are conflicted with Foundation for sites files when they are located in the same app's folder. Therefore, I would suggest to change them to:
`dist/foundation-emails.css`
`dist/foundation-emails.min.css`

**Comment by rafibomb** [comment]
@kball informed me he ran into this setting up the Rails gem. It makes sense though something like this would need to happen at a larger point release because it would cause a migration.

We'll add a branch for 2.2 so this change can be pointed there. A PR for this would help as well!

**Comment by rafibomb** [comment]
Added a v2.2 branch to commit features to!

**Comment by imabdulsal** [comment]
@rafibomb I would appreciate it if you could review this #429

**Comment by rafibomb** [comment]
Thanks for the PR!
