### ISSUE TITLE
Inlining issue

### ISSUE THREAD

**Issue by hswidarski** [foundation/foundation-emails#411]
When I tried to run "NPM run build" I was told that command is not does not work, only when I used "npm start build" was I able to the html and css folders in dist and I used zurb inliner to combine them. Testing my emails in litmus I came across a few issues that can be seen from the screen shots. 
-the logos is not showing up anywhere
-in outlook 2013 the yellow bar at the top and grey bar at the bottom are expanding higher than its supposed to
-In gmail app on android the bullet points are moving below the button which is not supposed to happen
<img width="521" alt="screen shot 2016-05-02 at 9 58 17 am" src="https://cloud.githubusercontent.com/assets/18315395/14958550/e8e74e34-1050-11e6-9533-c16f1bc06984.png">
<img width="537" alt="screen shot 2016-05-02 at 9 58 24 am" src="https://cloud.githubusercontent.com/assets/18315395/14958552/e8f1f8a2-1050-11e6-8b02-8e222abbe326.png">
<img width="504" alt="screen shot 2016-05-02 at 9 58 36 am" src="https://cloud.githubusercontent.com/assets/18315395/14958551/e8e86c4c-1050-11e6-8c17-4dde938f6ec1.png">

**Comment by rafibomb** [comment]
`npm run build` is the correct command (lowercase)

**Comment by rafibomb** [comment]
Do these changes happen when you compare the web version before and after inlining?

**Comment by hswidarski** [comment]
no because I can't do npm run build . This is what shows up
<img width="734" alt="screen shot 2016-04-27 at 7 45 06 am" src="https://cloud.githubusercontent.com/assets/18315395/15028556/0b1eb752-120f-11e6-89bf-02d0877639df.png">

**Comment by rafibomb** [comment]
You might try deleting your node modules folder then running `npm i` to rebuild it.

**Comment by rafibomb** [comment]
We'd need to see the code to determine if this is an inliner issue or not. Can you share that or help pinpoint where the changes are happening?

**Comment by DanielRuf** [comment]
Closing as we did not receive further feedback.
