### ISSUE TITLE
Greater Than and Less than Signs getting converted to &lt; &gt;

### ISSUE THREAD

**Issue by ghost** [foundation/foundation-emails#417]
**How can we reproduce this bug?**
If you include the following markup in order for my email sender to inject a dynamic coupon code into individual emails.

`<<LCG Program\TG LCG Coupon Code Default='246996'>>`

After the code above is run through the inliner, the result is below. 
`&lt;<lcg program\tg="" lcg="" coupon="" code="" default="246996">&gt;</lcg>`

**What happened instead?**
The code shouldn't have broken. My expectation was that it would be as I entered it. 
`<<LCG Program\TG LCG Coupon Code Default='246996'>>`

I also reference this bug in the foundation forum here: 
[http://foundation.zurb.com/forum/posts/39801-question-about-characters-changing-after-using-in-liner-using-sass-version-of-foundation-for-emails](url)

**Comment by iampstew** [comment]
Same goes for`'`converting into `&apos;` was getting issues with that regarding my content getting rendered.

**Comment by rafibomb** [comment]
@coreyschaaf This is s tough one because it seems like every inliner I've tested does the same thing. It looks like invalid code. This may be better handled by the inline-css maintainer as that is the inliner we're using. We're not manipulating the inliner beforehand.

In fact Premailer and CM both strip the whole statement out
![screen shot 2016-05-05 at 2 40 44 pm](https://cloud.githubusercontent.com/assets/5652085/15058136/7cbdda44-12cf-11e6-96ac-3a3a4842580d.png)

I'd suggest opening this one up here instead: https://github.com/jonkemp/inline-css/

**Comment by ghost** [comment]
@rafi - Transferring.

**Comment by iturgeon** [comment]
I'm having this same issue with my own tags building emails templates that will be sent through sendgrid.

The raw text I need to end up with:
`<%asm_group_unsubscribe_raw_url%>`

Which is of course being escaped.

**Comment by ghost** [comment]
@rafi, is there something else you needed me to do on this? I'm new to git, so I see the "awaiting reply" tag - just not sure if you're waiting on me to do something else. I opened this bug up based on where you told me to move it to.

**Comment by rafibomb** [comment]
@coreyschaaf Saw you posted the issue on inline-css which is great! We'll followup with the maintainer on this as well.

**Comment by teoeugene** [comment]
In my email, I used & lt; and & gt;, which was getting converted to & amp;lt; and & amp;lt; respectively.

(Without the spacing, as I'm not sure how do get it formatted correctly here)

**Comment by tdhartwick** [comment]
Looks like @coreyschaaf moved the issue here: https://github.com/jonkemp/inline-css/issues/41

Going to close this, and direct issues to the issue above.

Thanks for reporting the issue!
