### ISSUE TITLE
Inliner not adding media query CSS to Body tag

### ISSUE THREAD

**Issue by antonydjames** [foundation/foundation-emails#418]
**How can we reproduce this bug?**

I'm using the SASS version of Foundation for Emails, with the boilerplate 'default.html' left as it was upon install. I have created my own 'index.html' with but only used simple Inky markup.

**What did you expect to happen?**

When running the `npm run build` command, it's my understanding that all media query CSS should be moved from 'app.css' to the commented out `<style>` tag in the `<body>` of 'index.html' (the full HTML email file that then resides in /dist).

**What happened instead?**

Neither the default media query CSS from the Ink framework nor any of my own custom media query CSS has been placed with the `body` of 'index.html'. Therefore the email is not responsive.

**What email clients does this happen in?**

This isn't an issue with an email client - when running the inliner, it simply seems to ignore the media queries.

If I manually add the CSS to 'index.html' the mailer is fully responsive upon testing. However this is not an adequate solution as each time the inliner process is run, my additions are overwritten.

**Comment by javimayor** [comment]
Hi Antony,

I have had a similar problem and I have solved it by reseting the css comment body from default.html. Maybe you changed it by error and now it is not similar to:

```
<body>

  <!-- <style> -->

  <table class="body" data-made-with-foundation>
```

**Comment by antonydjames** [comment]
That does indeed seem to have fixed it - thank you. Such a small thing! 

I thought I'd tried resetting the whole file to match the default template but evidently I missed something.
