### ISSUE TITLE
&nbsp; converted to &amp;nbsp;

### ISSUE THREAD

**Issue by SimonSteinberger** [foundation/foundation-emails#422]
If the HTML source contains &nbsp; it gets converted by Foundation's online CSS Inliner to &nbsp; to &amp;nbsp;

That happens also with other representations of the nonbreakable space - possibly with all &-encoded HTML entities. We use non-compressed HTML output.

**Comment by rafibomb** [comment]
Looks like a duplicate - we'll close this in favor of https://github.com/zurb/foundation-emails/issues/384
