### ISSUE TITLE
Compressed HTML is broken

### ISSUE THREAD

**Issue by SimonSteinberger** [foundation/foundation-emails#423]
In several occasions, compressed HTML output of the CSS Inliner was broken. Sorry, I don't have a test snippet to reproduce the bug. If I find the time, I'll give more details.

**Comment by rafibomb** [comment]
Thanks for the report! We'll need more information to track this down and resolve it. An example code to test, how to reproduce it, what the expected outcome is, and screenshots all would be great. Please open a new issue with some supporting info so we can investigate. Thanks!
