### ISSUE TITLE
Character Inlining Issues

### ISSUE THREAD

**Issue by ghost** [foundation/foundation-emails#424]
`&mdash;` is being converted to `&#x2014;` 
`"` is being converted to `&quot;`
`'` is being converted to `&apos;`
`&nbsp;` is being converted to `&#xA0;`
`…` is being converted to `&#x2019;`

**How can we reproduce this bug?**
This can be reproduced by using the command 
`foundation build` or
`npm build`

**Comment by rafibomb** [comment]
There is an explanation and fix on issue https://github.com/zurb/foundation-emails/issues/384 . We'll close this in favor of it. If you are able to test the changes that would really help!

**Comment by rafibomb** [comment]
Also, thanks for the extra test cases!  Added test cases here: https://github.com/zurb/foundation-emails/commit/9a09698fcd2e7c587710baaad3937d76c9354dd2
