### ISSUE TITLE
[Getting Started with CSS] ISSUE NAME HERE

### ISSUE THREAD

**Issue by DNIU14** [foundation/foundation-emails#428]
In the installation instructions for CSS:

Where is this mysterious file listed under "Boilerplate"?

 "Inside src/layouts/default.html, you can see the boilerplate needed to make an HTML work, with comments explaining what does what.

**Comment by marcsoler** [comment]
You find this at the Foundation for [Emails Template](https://github.com/zurb/foundation-emails-template) which is in a separate repo

**Comment by rafibomb** [comment]
Just updated the copy on the page to reflect the correct boilerplate and location. Thanks! https://github.com/zurb/foundation-emails/commit/89d26de89477c4d0f21bb83cffd0f1d7846f30f2
