### ISSUE TITLE
Gem version for Rails ?

### ISSUE THREAD

**Issue by anthony-robin** [foundation/foundation-emails#430]
I couldn't find any informations about this, did you plan to create a **gem** version to use with **Rails** ? 
That would be awesome !

**Comment by rafibomb** [comment]
A Rails version has been started and should be in place to share it out soon for testing and contributions. You can follow the roadmap which will be evolving the structure of the project https://github.com/zurb/foundation-emails/wiki/Roadmap

**Comment by rafibomb** [comment]
We'll have the first version ready for testing today. Are you able to try it out and provide feedback?

**Comment by RegisFrey** [comment]
Hi Rafi, I'm interested in a Foundation for Emails 2.0 Gem / workflow. Is there a repository / website for this gem? Any documentation? 
Thanks.

**Comment by jfalk** [comment]
I'd be interested in testing this out as well.

**Comment by jfalk** [comment]
Will the inky-rb repo be opened up soon? I have version 0.0.2 of the gem that was published and was able to mount the engine so I could use inky templates. Not sure how this works for actually sending the emails (as right now I have it mounted to the development email preview path), but it's good enough to get developing with.

Edit: Would also be interested in getting this to work with haml as right now it only seems to work with erb.

**Comment by MSeneadza** [comment]
@rafibomb Is inky-rb still available for testing?  I'd love to try it out

**Comment by jfalk** [comment]
@MSeneadza It is in the rubygems repo: https://rubygems.org/gems/inky-rb/versions/0.0.2

**Comment by zokioki** [comment]
@jfalk @MSeneadza @RegisFrey The inky-rb repo will be open soon - until then, we have pushed v0.0.3 to Rubygems. You can find some setup instructions here https://github.com/zurb/foundation-emails/pull/446#issuecomment-229549261

**Comment by zokioki** [comment]
The [inky-rb](https://github.com/zurb/inky-rb) repo has been opened - have at it y'all!

**Comment by MSeneadza** [comment]
Thanks @zokioki

**Comment by oyeanuj** [comment]
@zokioki @rafibomb I was looking to understand if the 'foundation_email' gem works with Rails API only project (on Rails 4 or 5)? Are there assumptions that the project makes that one should be aware of?

**Comment by zokioki** [comment]
@oyeanuj At this time, using the `foundation_emails` gem would not be the best choice to get the Foundation Emails assets into your mailer layouts, since API-only Rails projects do not have the Asset Pipeline enabled to reference or process the packaged Sass.

An alternative approach would be to grab the [dist stylesheet](https://github.com/zurb/foundation-emails/blob/v2.2.1/dist/foundation-emails.css) and manually inline it within of your mailer layout. To keep the layout cleaner, you can use the [premailer-rails](https://github.com/fphilipe/premailer-rails) gem to reference that stylesheet from the `/public` directory.

**Comment by oyeanuj** [comment]
@zokioki Thanks for the quick response. I'll try out your suggestion (are there any major downsides to that?) If that doesn't work out, I'll try to see if there is a way to get the Asset Pipeline enabled.

Also, is supporting API-only Rails project in the plans? Anecdotally, with SPAs, I see a lot more of us floating around..

**Comment by oyeanuj** [comment]
@zokioki Also, it seems that if I just use one of the template HTMLs, and have the premailer-rails run through it, that would be equivalent to the option your suggested. Is that correct?
