### ISSUE TITLE
graceful-fs need update

### ISSUE THREAD

**Issue by hswidarski** [foundation/foundation-emails#431]
When I try and do foundation watch I receive and error that says I need to update the graceful-fs module because I'm not able to watch my project live, nor am I able to even start a new one.
<img width="572" alt="screen shot 2016-05-09 at 3 10 23 pm" src="https://cloud.githubusercontent.com/assets/18315395/15126630/68323f6c-15f8-11e6-92cd-8a4239024e81.png">

**Comment by rafibomb** [comment]
You might try to delete your node_modules folder and then run `npm i` to re-build it.
