### ISSUE TITLE
[Button] target attribute not passed through to the <a< tag on the button

### ISSUE THREAD

**Issue by Alex-Munro** [foundation/foundation-emails#432]
**How can we reproduce this bug?**

```
<button href="http://a.com" target="_blank" class="expand">Button</button>
```

**What did you expect to happen?**

Expected final link in inlined email to have the target attribute set to _blank to ensure web clients open the link in a new tab

**What happened instead?**

target attribute missing

**What email clients does this happen in?**

All

**Comment by cossssmin** [comment]
Indeed it doesn't.

However, is there any web email client that will not open links in a new browser tab/window, by default? Is this really necessary?

**Comment by ClementParis016** [comment]
Indeed, I guess every webmail opens links in new tab by default (no proof of this), but then the `target="_blank"` attribute still makes sense for the "View in browser" version of emails.

**Comment by cossssmin** [comment]
Not sure I understand why it would make sense for "view in browser" - it's just another link in the email, that you would click. The actual browser version (hosted HTML) of your email should not have "view in browser", since that's what you're already seeing.

Maybe I misunderstood?

**Comment by ClementParis016** [comment]
Haha, sure! But I'm not talking about the actual "view in browser" link, but about the links that are contained in the email, i.e if you're reading the browser version, if you click a link in the email that doesn't have a `target="_blank"`attribute, then the link will open in the same tab as the email you were reading.

**Comment by rafibomb** [comment]
@alex-ketch When adding code on GitHub, wrap it in 3 ` so that it renders as a code example.

**Comment by rafibomb** [comment]
We were wondering if this was necessary anymore. Any links that prove it still is? 

We're happy to add this to Inky (ability to pass in attributes) as a PR on Inky or maybe even set the `target="_blank"` as a default.

**Comment by bc-ian** [comment]
@rafibomb I think what he is saying is that when users view the version of his email in the browser and not in their mail client, the links do not have `target="_blank"` so that when they click anything they are taken away from the email. For this reason I think it might make sense to have this passed onto the links of the buttons. Some people might not want this by default.

**Comment by ClementParis016** [comment]
@bc-ian it's exactly that.
@rafibomb maybe not as a default, but the ability to pass it as an attribute would be nice. I've already submitted a PR for this at zurb/inky#42.

**Comment by rafibomb** [comment]
@bc-ian  Great! Now I understand and agree this should be in.

@ClementParis016 Thanks for the PR! We've reviewed it and looks good to merge in pending resolving a travis error. We'll close this here and work on getting the PR merged with you!

**Comment by antonydjames** [comment]
Is there an ETA for when it'll be possible to pass attributes to buttons? I ran 'npm update' very recently but the functionality doesn't seem to be there yet. I see this task was added to the 2.1.1 milestone - has 2.1.1 been released?

My boss is asking for it to be included on our templates as a catch-all so it'd be good to be able to pass on an estimate of when we'll be able to.

**Comment by rafibomb** [comment]
The PR has been merged into Inky https://github.com/zurb/inky/pull/42

It will go out with 2.2 Due by June 30

If you need it sooner - you can make the code changes in the PR in the node_modules -> inky folder or you can add the targets in the output HTML you get in the dist folder.
