### ISSUE TITLE
```npm build``` silently fails, instead running  ```gulp --production``` produces error?

### ISSUE THREAD

**Issue by mentorkadriu** [foundation/foundation-emails#436]
**How can we reproduce this bug?**

Running `npm build` is doing nothing for me, so I run `gulp --production` .

**What did you expect to happen?**

`gulp --production` to run as expected and add inline css to `dist/index.html` and minify it.

**What happened instead?**

```
[09:20:55] Requiring external module babel-register
[09:20:56] Using gulpfile ~\Desktop\work\SB-170\sb-170\gulpfile.babel.js
C:\Users\Acer-Pc\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at C:\Users\Acer-Pc\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:19

    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:146:18)
    at node.js:404:3

```

**Comment by rafibomb** [comment]
Are you trying to run the production and start the server? If so that is `npm run build`

**Comment by mentorkadriu** [comment]
Well what I wanted was to run only `build`` like`npm build`, but this command does not work for me.`npm run build``` it does the job pretty well. Thank you for your help
