### ISSUE TITLE
[Undefined] in Menu 

### ISSUE THREAD

**Issue by camaech** [foundation/foundation-emails#444]
![undefinded_menu_inky](https://cloud.githubusercontent.com/assets/977957/15331014/e48d04ac-1c24-11e6-878b-f3b6421e2deb.png)

**How can we reproduce this bug?**
Build a basic menu with an item with class="show-on-large"

Write out the HTML (or Inky code) that causes the issue.
`<menu class="small-vertical">
         <item class="show-for-large">test</item>
</menu>`

**What did you expect to happen?**
The menu items should be hidden on all small browsers.

**What happened instead?**
An [undefined] is added to the item.

**What email clients does this happen in?**
Outlook 365, Outlook Chrome, Outlook Firefox

**Comment by camaech** [comment]
Turns out it's not related to 'show-on-large' at all. It seems to be related to when you create an item and don't give it an href.

If you just throw a '#' in there it fixes it. 

`<item href="#">Test</item>`

**Comment by rafibomb** [comment]
Ok, that's a good tip to add to the documentation. It should be clear that it's for links.

**Comment by rafibomb** [comment]
Added this to the docs to help avoid this happening: https://github.com/zurb/foundation-emails/commit/c83c3d79a34332b4473b4fc1d97974388770e0df

**Comment by ClutchWriter** [comment]
[undefined] shows up whether you've got an href or not. I'd like to know how to get the image to render without the accompanying [undefined]

**Comment by philzelnar** [comment]
@AnikaJaffara Are you putting the href in as an attribute on the item tag (not adding a link inside item)? Easy to do the later out of habit :)
