### ISSUE TITLE
Columns inserting tables for non text elements

### ISSUE THREAD

**Issue by davidhouweling** [foundation/foundation-emails#445]
Is there a reason that whenever you use an element inside <columns> it will wrap a table with it rather than just using the already generated table from column? If there is no real reason for it, or a way that we can only inject the added table buffer for certain elements, it would cut down a fair bit of markup on bigger emails.

I guess it's more about what the `.expander` element is used for?

**How can we reproduce this bug?**

``` html
<container>
  <row>
    <columns>
      <p>
        some text here
      </p>
    </columns>
  </row>
</container>
```

**What did you expect to happen?**
Generated markup to be...

``` html
<table class="container">
  <tbody>
    <tr>
      <td>
        <table class="row">
          <tbody>
            <tr>
              <th class="small-12 large-12 columns first last">
                <p>some text here</p>
              </th>
            </tr>
          </tbody>
        </table>
      </td>
    </tr>
  </tbody>
</table>
```

**What happened instead?**

``` html
<table class="container">
  <tbody>
    <tr>
      <td>
        <table class="row">
          <tbody>
            <tr>
              <th class="small-12 large-12 columns first last">
                <table>
                  <tbody>
                    <tr>
                      <th>
                        <p>some text here</p>
                      </th>
                      <th class="expander"></th>
                    </tr>
                  </tbody>
                </table>
              </th>
            </tr>
          </tbody>
        </table>
      </td>
    </tr>
  </tbody>
</table>
```

**What email clients does this happen in?**
All (generated from inky)

**Comment by rafibomb** [comment]
The .expander is a workaround for some versions of Outlook, that do not allow column to go width: 100% if the content within it does not fill the container 100%. So, if you have a 570px wide column with an image that is 300px wide, without the expander the column collapses to 300px wide causing layout issues.
