### ISSUE TITLE
Buttons with mobile app links loosing padding on OWA

### ISSUE THREAD

**Issue by davidhouweling** [foundation/foundation-emails#448]
**How can we reproduce this bug?**

``` html
<button href="myapp://com.myapp/url?param=12345678" class="primary large radius">
  Some mobile app link
</button>
```

**What did you expect to happen?**
![image](https://cloud.githubusercontent.com/assets/9696959/15426210/f2ee04ee-1e84-11e6-8998-1887267c2f05.png)

**What happened instead?**
![image](https://cloud.githubusercontent.com/assets/9696959/15426223/0b588248-1e85-11e6-96c8-3b2fa305b51a.png)

The reason is, Office 365 strips anchors that do not link to web pages, however foundation-emails have styles on the anchor (such as padding, font size, color, etc.) which means that they no longer get applied. However, I don't really know if it can be resolved easily.

**What email clients does this happen in?**
Office 365 Web client

**Comment by rafibomb** [comment]
Can you think of a way, with Inky, that this can be circumvented? I don't think this is a Foundation issue but would like any ideas to get around it.

**Comment by davidhouweling** [comment]
I agree, i think the only way we really can get around it is to move as many of the attributes up to the td definition rather than on the anchor, but i don't know what issue that results in? Things like padding can be moved up, and font, font-size, color, etc can be applied to be the td and the anchor?

**Comment by cossssmin** [comment]
https://github.com/zurb/foundation-emails/issues/416#issuecomment-249432270 should help. I've been successfully using borders instead of padding, though I haven't tested a link such as yours with OWA...

**Comment by rafibomb** [comment]
We've seen this before specifically with Oulook.com anytime you don't use a traditional `http://` type url. Do you have an option to use that type of URL? 

In order to make a large touch target, the styles should be on the anchor. 

So, to reiterate, all Outlook.com passes when switching to an `http://` type url. There is a warning for this in the docs: http://foundation.zurb.com/emails/docs/button.html
