### ISSUE TITLE
 Spacer code &nbsp; issue

### ISSUE THREAD

**Issue by ghost** [foundation/foundation-emails#450]
**How can we reproduce this bug?**

Using the spacer code in the inliner tool ... ( http://foundation.zurb.com/emails/docs/spacer.html )

```
<table class="spacer">
<tbody>
<tr>
<td height="16px" style="font-size:16px;line-height:16px;">&#xA0;</td>
</tr>
</tbody>
</table>
```

**What did you expect to happen?**

&#xA0; would be converted to hidden &nbsp;

**What happened instead?**

&#xA0; was converted to &amp;nbsp; So it displayed as text when previewing the email, instead of being a hidden &nbsp;

**What email clients does this happen in?**

All.

**Comment by ghost** [comment]
Further to this if you use query strings in links then the & get turned into...

&amp;amp;

e.g.

`<a href="http://www.test.com?utm_source=mixpanel&utm_medium=email">Test</a>`

gets turned into...

`<a href="http://www.test.com?utm_source=mixpanel&amp;amp;utm_medium=email">Test</a>`

**Comment by rafibomb** [comment]
It makes sense for the query string. This inliner has an option to append the query string as is: http://foundation.zurb.com/emails/inliner.html

What email clients are displaying the text? We would like to know how this is affecting email clients in the real world. 

We can see the character is being converted in both inliners, old and new. This leads me to believe there is a reason it is being changed. There should be a way to exclude this change in the inliner.

Added the test case for now to make sure it's not converted: https://github.com/zurb/foundation-emails/commit/86b813d8eb1e914e6d5264def6adbbfe10f1dd2a

**Comment by ghost** [comment]
It would be great if you could add the query string tick box to the inliner V2.

**Comment by george-1000** [comment]
@rafibomb how do you tell the command line inliner to preserve query strings?

**Comment by rafibomb** [comment]
Yes, if it is an option here: https://github.com/jonkemp/inline-css

Do you know which one it is?

**Comment by jkd77** [comment]
Any suggested fixes for the original issue? (other than a find and replaced on the inlined html?)

**Comment by hardcodet** [comment]
Seems to be the `Copy` button. Manually selecting the markup and then copy/pasting it got me valid markup.

**Comment by DanielRuf** [comment]
Duplicate of https://github.com/zurb/foundation-emails/issues/841, can be closed.
