### ISSUE TITLE
style attribute on <columns> is not retained

### ISSUE THREAD

**Issue by fjaeger** [foundation/foundation-emails#451]
If I specify custom CSS style attributes to a <columns> tag in inky, these attribute is not retained in the output HTML file. Is this behavior intended?

**Comment by rafibomb** [comment]
Can you share an example where it's not?

**Comment by rafibomb** [comment]
Looks like this is resolved by https://github.com/zurb/inky/pull/45

It's in the `develop` branch for testing before release!

**Comment by rafibomb** [comment]
In 2.2 a new feature was added to allow Inky to apps in attributes to rows and columns. We started a discussion on it here: 
http://foundation.zurb.com/forum/posts/44863-add-html-attributes-to-your-inky-markup

We'd love to hear what problem you were trying to solve by adding in attributes it or what you originally had in mind for it.
