### ISSUE TITLE
Thumbnail component page missing from docs menu.

### ISSUE THREAD

**Issue by danielbraun** [foundation/foundation-emails#452]
This page:
http://foundation.zurb.com/emails/docs/thumbnail.html
is not included in the documentation component side menu.

It's a useful component, and I stumbled upon it accidentally while browsing the CSS file.

**Comment by rafibomb** [comment]
Right now the thumbnail component was a concept for emails, though it is not fully implemented across all email clients. The code is there but there are issues across the board. We'd like to add it officially, but can't until it tests out.

Is this something you can jump in on? How did it work for you?

**Comment by danielbraun** [comment]
In Apple Mail the border is seen, in GMail it's not.

**Comment by danielbraun** [comment]
Also the hover effect is lost once CSS is inlined. I don't think it's a thumbnail issue, because the effect is lost with buttons as well.

**Comment by rafibomb** [comment]
Yeah the hover part is an open issue on https://github.com/jonkemp/inline-css - still looking to resolve that separately

The thumbnail border showing on all email clients is key.

**Comment by rafibomb** [comment]
Closing in favor of https://github.com/zurb/foundation-emails/issues/220
