### ISSUE TITLE
[Wrapper] Using wrapper around a container doesn't centre in Outlook

### ISSUE THREAD

**Issue by nitrokevin** [foundation/foundation-emails#453]
**How can we reproduce this bug?**

```
<wrapper class="intro">
    <container>
        <row >
            <columns small="12" large="6">
            <img src="../assets/img/placeholder@2x.png" alt="placeholder"/>
            </columns>
             <columns small="12" large="6">
             <h2>Heading</h2>
             <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. </p>
             </columns>
         </row>
</container>
</wrapper>

```

**What did you expect to happen?**

In all email clients except outlook, the container is centered in the screen and the background extends to the full width of the window
**What happened instead?**
In outlook the container is aligned to the left with the background extending to the full width
**What email clients does this happen in?**

Outlook 2013

**Comment by rafibomb** [comment]
I think you need a `<center>` tag in there somewhere. Should wrap the container in a center tag.

**Comment by nitrokevin** [comment]
Thanks, you are right, though it is only needed for outlook (as usual)

Maybe this should be added to the wrapper page in the foundation docs

**Comment by rafibomb** [comment]
That's right! Can you add it? Hit edit page at the top:
<img width="408" alt="screen shot 2016-05-26 at 10 04 19 am" src="https://cloud.githubusercontent.com/assets/5652085/15583143/6184ed02-2329-11e6-8167-7141f84a3adb.png">

http://foundation.zurb.com/emails/docs/wrapper.html

Thanks!

**Comment by nitrokevin** [comment]
Whenever I try to edit a page it just takes me to a 404 I'm afraid

**Comment by rafibomb** [comment]
Oh, you need a GitHub account to contribute to most open source projects. It's super simple to get started with!

**Comment by rafibomb** [comment]
I added this one https://github.com/zurb/foundation-emails/commit/cc2c8faead5bd42f8a0c566d1564ead19e05da9d

Thanks!
