### ISSUE TITLE
[Visibility Classes] ISSUE NAME HERE

### ISSUE THREAD

**Issue by earthlingdavey** [foundation/foundation-emails#455]
**How can we reproduce this bug?**

Create the following elements as in the docs: 

```
<callout class="hide-for-large primary">
  <p>This callout will only appear on small screens.</p>
</callout>

<callout class="show-for-large alert">
  <p>This callout will only appear on large screens.</p>
</callout>
```

**What did you expect to happen?**

Elements hide on different screen sizes

**What happened instead?**

Nothing

**What email clients does this happen in?**

In Chrome.

**Comment by earthlingdavey** [comment]
It looks like the visibility classes can only be used in `table.body table.container` . My mistake

**Comment by rafibomb** [comment]
You should be able to add the classes to any element (except on img itself). I see it working on this test https://github.com/zurb/foundation-emails/commit/3ee7511ab12fa2b9806b14a4f46ae22f93e55acb case as well as in the docs. Make sure you are on version 2.1. We'll close this here - open a new issue if you are able to replicate on 2.1
