### ISSUE TITLE
Images are always full size in Outlook breaking layout

### ISSUE THREAD

**Issue by nitrokevin** [foundation/foundation-emails#457]
Whenever I make a column for an image and a column for text, the image always gets displayed full size in outlook pushing the text to a tiny column.

I've seen this issue mentioned before but I don't know what the solution is. Its a very common layout for newsletters to have an image next to text, but I just can't get it to work

Any tips?

Outlook

![screen shot 2016-06-03 at 12 20 54](https://cloud.githubusercontent.com/assets/16405648/15777256/b4f9736a-2985-11e6-8f15-2c779fc6aa43.png)

Everything Else
![screen shot 2016-06-03 at 12 21 09](https://cloud.githubusercontent.com/assets/16405648/15777260/b8c5bd50-2985-11e6-8d7e-a78ac4f74f5a.png)

**Comment by nitrokevin** [comment]
Sorry my mistake, I hadn't realised that the image size has to hardcoded for it to work in outlook.

`<center><img editable='true' src="{{root}}assets/img/placeholder@2x.png" width="270" alt="placeholder"/></center>`

I had just left the width as width="100%" which outlook doesn't like!

Wonder if there is a way to get inky to use the number of columns and the global width to automatically calculate the image width, is that feasible ?

**Comment by elliottregan** [comment]
That would be very nice, but this has been logged elsewhere. Want to close this issue so they can focus on the other bugs?

**Comment by markadrake** [comment]
Where else is this image bug logged? I don't see anything in the documentation. I came across this today using the framework and wouldn't have known unless I specifically searched **closed** issues.

If there are a list of caveats and known defects to working with images - shouldn't they be documented and shouldn't an issue here be left open so the community can address them? The framework's purpose is to make emails easy - so I don't feel any shame in saying that _images should just work_.

**Comment by Frazer** [comment]
This is still not fixed.

**Comment by simon-guider** [comment]
+1 still not fixed
