### ISSUE TITLE
Vertical align in outlook

### ISSUE THREAD

**Issue by nitrokevin** [foundation/foundation-emails#460]
**How can we reproduce this bug

When creating 2 columns, images and callouts in the right hand column are vertical aligned Center in outlook but aligned top everywhere else, when using inky markup
**What did you expect to happen?**
All to be top aligned
**What email clients does this happen in?**
Outlook 2010 2013

I can fix with th, td {vertical-align: top;}

**Comment by rafibomb** [comment]
Seems like that should be added to the _normalize.scss file. Is that something you can add with a PR?

**Comment by rafibomb** [comment]
I think that it happens because it's not explicitly set. You can now explicitely set the valign on a column Resolved by zurb/inky#45

It's in the develop branch for testing before release!
