### ISSUE TITLE
Feature request: Preheader

### ISSUE THREAD

**Issue by Baswazz** [foundation/foundation-emails#463]
I am missing support for a preheader.
Would be nice if this can be added by default. Or at least described in the docs how to implement one, so we have not to worry about cross email client support.

**Comment by rafibomb** [comment]
Good one - We've been using it on our internal templates with success.
Added the CSS here: https://github.com/zurb/foundation-emails/commit/cd44785ae07ef3685124690f6ebeafca046b08d4

Added the html to the template: https://github.com/zurb/foundation-emails-template/commit/01259351eba4420bfdf291fbcd4161431bbacecb

What CSS have you been using? Are you able to test out these changes and let us how it goes?

**Comment by rafibomb** [comment]
Would like to know how this tests out for you - we'll close this here as it in the codebase!
