### ISSUE TITLE
[Alignment] <center> tag increases grid width not centering image on Outlook 2013

### ISSUE THREAD

**Issue by GBratsos** [foundation/foundation-emails#464]
**How can we reproduce this bug?**
Use the center tag and test on outlook 2013

Write out the HTML (or Inky code) that causes the issue.

```
<columns small="12" large="4">
            <callout>
                <h3 class="small-text-center">Presentations.&nbsp;<span>8</span></h3>
                <spacer size="35"></spacer>
                <!--<img class="float-center" src="../assets/img/monitor.png" alt="Momencio emails send">-->
                <center>
                    <img src="http://placehold.it/74x50">
                </center>
                <spacer size="40"></spacer>
            </callout>
        </columns>
```

**What did you expect to happen?**
I expect to just center my image on Outlook 2013.

**What happened instead?**
Image is not centered at all and breaks the row/column's width.

**What email clients does this happen in?**
Not centering OUTLOOK 2013

**Comment by rafibomb** [comment]
Hmm, not seeing this here: https://litmus.com/checklist/emails/public/70bc23e

I didn't see a second column in your row. So I added it to test with:

```
<row>
    <columns small="12" large="4">
      <callout>
        <h3 class="small-text-center">Presentations<span>8</span></h3>
        <spacer size="35"></spacer>
        <center>
          <img src="http://placehold.it/74x50">
        </center>
        <spacer size="40"></spacer>
      </callout>
    </columns>
    <columns small="12" large="8">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum sapiente quis at fuga reprehenderit, velit iure fugiat debitis repellat assumenda perspiciatis? Commodi minus labore sit dolorem reprehenderit eveniet porro asperiores.</p>
    </columns>
  </row>
```

Having the columns add up to 12 would make a difference on Outlook.

**Comment by rafibomb** [comment]
Let us know how this helps!

**Comment by GBratsos** [comment]
I had this problem with the  <center> tag on Outlook 2013.

`center {
    width: 100%;
    min-width: 640px;
}`

i changed it to

`min-width: 100% !important;
    width: 100%;`

**Comment by rafibomb** [comment]
Awesome - glad you got it!
