### ISSUE TITLE
Cannot add target="_blank" attribute to <item> within <menu>

### ISSUE THREAD

**Issue by antonydjames** [foundation/foundation-emails#465]
**How can we reproduce this bug?**

`<menu><item href="http://www.address.com/" target="_blank"></item></menu>`

**What did you expect to happen?**

The hyperlink within the 'item' component to contain the target="_blank" attribute, so that links clicked by users via a web email client are guaranteed to open in a new tab/window, no matter the client's default action. This doesn't need to apply by default, but ideally we should have the option to include it.

**What happened instead?**

The hyperlink does not include the target="_blank" attribute.

**What email clients does this happen in?**

All inlined HTML, ergo all web clients.

This is a similar issue to #432 though that applies to 'button' Inky elements rather than 'item' ones.

**Comment by rafibomb** [comment]
Looks like the PR that solves this for buttons can be easily extended to menu items - https://github.com/zurb/inky/pull/42 Is that something you can help with?

**Comment by rafibomb** [comment]
Awesome PR by @ClementParis016 https://github.com/zurb/inky/pull/54

**Comment by ClementParis016** [comment]
Thanks, I'm glad to contribute to this nice project :)
