### ISSUE TITLE
[Alignment] center on small doesnt seems to work

### ISSUE THREAD

**Issue by maximebj** [foundation/foundation-emails#474]
Hello, 

the combo small and align doesn't  seem to work well, we can see in the doc than it doesn't render as expected 
![outch](https://cloud.githubusercontent.com/assets/1785489/16071315/f818140e-32da-11e6-88f3-3e5cc8d80997.jpg)

**Comment by rafibomb** [comment]
Can you share the code you're testing?
On the docs example - these classes are targeted for the small breakpoint only.
<img width="548" alt="screen shot 2016-06-15 at 9 54 49 am" src="https://cloud.githubusercontent.com/assets/5652085/16089361/87c9d606-32df-11e6-923e-3ca40a5d3f95.png">

**Comment by rafibomb** [comment]
We'll close this here. If you still see an issue, open a new issue with a code example we can test against. Thanks!

**Comment by maximebj** [comment]
Sorry my bad. I misunderstood the purpose of this class.
