### ISSUE TITLE
Inliner gives inconsistent results. Missing tags, unclosed tags.

### ISSUE THREAD

**Issue by dobromir-hristov** [foundation/foundation-emails#475]
Ok so after going through 5 or 6 versions of what I could find here in the issues, I cant get a consistent result from any of them. I tried develop branch on inky, the develop on foundation-emails, most of the times i get markup shown inside the email clients like in between the text i get `<th class="" ...`  ... Or the wrappers just stop existing at some point and content gets spewed all over the view port. Sometimes I got missing center styling and text just goes left for some reason.
Ofc the browser doesnt show any errors in the markup. 
These problems  are only when I try to use the inliner via `gulp --production`. If I use https://putsmail.com/inliner I at least get mostly good looking inlined templates, but not every time. Depends on which inky version I used before it.

What branch/version of foundation-emails should I use to atleast get consistent results?

PS: So setting the `collapseWhitespace: false,` on the minification task did a whole world of difference. Before it was cutting off tags and what not, I had to look at the minified code to actually spot the problem.

**Comment by rafibomb** [comment]
Are there specific examples that you've seen we can test against? That way we can file the issue with the inliner maintainer https://github.com/jonkemp/inline-css and work to resolve it

**Comment by dobromir-hristov** [comment]
Well my company's latest newsletter project, but I cant publish it atm here. As soon as I can, I will publish it. 
But after allot of other tests, without collapsing whitespace, I get good results around the board, EXCEPT a Bulgarian, very popular mail service `abv.bg` and I dont know why, but they really screw up the markup :)

**Comment by rafibomb** [comment]
So far we haven't seen this happening to any of our emails. We're looking for just a specific section of markup that is being removed that we can duplicate this.

**Comment by rafibomb** [comment]
Hi @dobromir-hristov Looking for a specific example we can test against that way we can figure out a solution. We'll close this issue - please open a new issue with a specific testable example so we can move forward on it. Thanks!
