### ISSUE TITLE
[Media Queries] Confusing / Incorrect information about grid columns

### ISSUE THREAD

**Issue by JoshHarrington** [foundation/foundation-emails#479]
The information around the grid for the email templates - in the 'Media Query' section - is very confusing. It seems to suggest that on mobile or 'small' sizes the grid only has 6 columns (or that's how I read it!).

[http://foundation.zurb.com/emails/docs/media-query.html](http://foundation.zurb.com/emails/docs/media-query.html)

> CSS Version In the code below, the left-hand column is six columns wide on small screens, hence .small-6. On medium-sized screens, the class .medium-4 overrides the small style, changing the column to be four wide.

It might be worth clearing up this communication in this paragraph to be clear that there are still 12 columns even on mobile.

Thanks,
Josh

**Comment by rafibomb** [comment]
Hi Josh,
I think the section looks to explain how the grid classes interact. How would it make more sense to describe it?

**Comment by JoshHarrington** [comment]
Hi Rafi,
I'm not sure to be honest, possibly showing a diagram of how columns are presented at different sizes? It wasn't particularly clear on first reading that the text (that I quoted) is referencing the code beneath.

When mentioning the 'left-hand' column it might not be completely clear to all readers straight away that as the code renders on the page the first of the two columns will be on the left. It might be more useful if there was a diagram as a reference point, then you'd be able to say "column A is sized at 6 columns of the total 12 at small sizes and 4 columns of 12 at large sizes".

Hope that's clear.

Thanks!

**Comment by rafibomb** [comment]
Thanks - took another stab at it and added a bit more visual description. Would love any more feedback on it! 

Annotate the update http://notebooks.zurb.com/posts/10061094?t=f281f441c8803e0c

**Comment by JoshHarrington** [comment]
Hi Rafi,

Looks great! Definitely think that will be helpful to people.
