### ISSUE TITLE
gulp failing

### ISSUE THREAD

**Issue by kareljan** [foundation/foundation-emails#482]
For some reason foundation is failing today. With yesterdays download everything worked fine. But today I get gulp errors. I suspect something is wrong on the gulp front.
When I replace the gulp node_module folders with a download from a couple of weeks ago (an other project) everything works fine. 

Just pointing it out. It has just cost me 45 minutes.

**Comment by rafibomb** [comment]
We hear you, it's a challenge with npm - npm installs could sometimes run into hiccups. It's been a thing with npm for a long time. Anytime we see an error, you can usually delete the node_modules folder and then run `npm install`

**Comment by kareljan** [comment]
Yes I tried that but, that didn't fix the problem.
