### ISSUE TITLE
[Wrapper] fluid width wrapper example in docs doesn't work

### ISSUE THREAD

**Issue by ryanrozich** [foundation/foundation-emails#485]
Just installed foundation-cli and created project via instructions in docs

Trying to start with the fluid wrapper example in the docs
http://foundation.zurb.com/emails/docs/wrapper.html

In my project, I replaced my `src/pages/index.html` with the example in the docs

``` html
<style type="text/css">
  .header {
    background: #8a8a8a;
  }

  .header .columns {
    padding-bottom: 0;
  }

  .header p {
    color: #fff;
    padding-top: 15px;
  }

  .header .wrapper-inner {
    padding: 20px;
  }

  .header .container {
    background: transparent;
  }
</style>

<wrapper class="header">
  <center>
    <container>
      <row class="collapse">
        <columns small="6">
          <img src="http://placehold.it/200x50/663399">
        </columns>
        <columns small="6">
          <p class="text-right">HEADER</p>
        </columns>
      </row>
    </container>
  </center>
</wrapper>
```

The resulting HTML file does not render as shown in the docs. 

Here is what it looks like in the docs
![docs screenshot](https://gmkr.io/s/5764dfcee141969f53536c3a/0)

Here is what my HTML file looks like
![my screenshot](https://gmkr.io/s/5764dfed377be8df254a6d71/0)

**Comment by ryanrozich** [comment]
If it helps, attached is the HTML file that the Zurb email framework generated from the inky markup above that I copied from the example docs
[index.html.zip](https://github.com/zurb/foundation-emails/files/321819/index.html.zip)

this is what gets compiled into `<project_dir>/dist/index.html`

_I had to zip the HTML becuase github wouldn't let me attach a file with `.html` suffix but I could attach a `.zip` file_

**Comment by rafibomb** [comment]
How are you building the project? `npm start` or `npm run build`?

**Comment by rafibomb** [comment]
The wrapper fluid header example on the docs has been updated since. You also want to take the CSS and move it into your custom stylesheet or in the head. Leaving it in the body will not yeild best results.
