### ISSUE TITLE
[Foundation for Emails] Missing Primary Button Styles

### ISSUE THREAD

**Issue by lukelarsen** [foundation/foundation-emails#487]
**How can we reproduce this bug?**

In Gmail the primary button background color doesn't render for me. If I replace the class on the `<button>` to secondary it always loads as expected. I looked in to the .scss files and noticed there isn't any styles for table.button.primary

Write out the HTML (or Inky code) that causes the issue.

`<button href="${urlSigninToAccount}" class="primary  radius  text-center  large">Sign In To Your Account</button>`

**What did you expect to happen?**
For the button to render with the primary color.

**What happened instead?**
The button didn't have a background color in Gmail

**What email clients does this happen in?**
Gmail and maybe others. I haven't tested it all yet.

**Comment by rafibomb** [comment]
The primary color for buttons is the default color for buttons. So there is no `.primary` class. If you change the primary color in your `_settings.scss` you'll see the change. You can also create custom CSS classes to style the buttons.
