### ISSUE TITLE
<wrapper> no longer working correctly in Outlook 2007 after upgrade to 2.1.0

### ISSUE THREAD

**Issue by smoca** [foundation/foundation-emails#490]
**How can we reproduce this bug?**
Install version 2.1.0 and follow the instructions in the email docs around the[ basic usage of wrapper in Inky](https://foundation.zurb.com/emails/docs/wrapper.html#basics).

**Write out the HTML (or Inky code) that causes the issue.**

```
<wrapper>
  content
</wrapper>
```

OR

```
<wrapper>
  <container>
     content
  </container>
</wrapper>
```

**What did you expect to happen?**
A centered table with the text _content_ in it.  This is what occurs in 2.0.1

**What happened instead?**
The text _content_ is left aligned in a fluid table.

The width is set to 100% by a class **wrapper**.  When debugging in dev tools, it looks like the .wrapper class sets the width to 100% in the [_global.scss file](https://github.com/zurb/foundation-emails/commit/7171f04c8953ae9990205212b07813b9fac3b66b).  This seems like a very odd place for this.  Is this correct?

**What email clients does this happen in?**
Outlook 2007

**Comment by rafibomb** [comment]
The purpose of the wrapper is to add classes to target elements inside or add styles to the table it creates. If you are looking to center align a table, there are suggestions in the [alignment docs](http://foundation.zurb.com/emails/docs/alignment.html)

The width 100% declaration helps attach background colors to it.
