### ISSUE TITLE
Single Word Too Long, Breaks Android 4.4

### ISSUE THREAD

**Issue by camaech** [foundation/foundation-emails#491]
**How can we reproduce this bug?**
Use a long word like "Construction" in an h1 tag. Make sure to have the font size large enough. I used 38px.

Write out the HTML (or Inky code) that causes the issue.

**What did you expect to happen?**
The word should either wrap or overflow: hidden;

**What happened instead?**
The word makes the width of the container extend outside the width of the window

**What email clients does this happen in?**
Android 4.4 is the only one I saw an issue in. (Using Litmus)

I've attached an image of what's happening:
![android4-vertical-allowed-1366](https://cloud.githubusercontent.com/assets/977957/16460981/d38b59f0-3def-11e6-833e-0238a13a44e5.png)

**Comment by rafibomb** [comment]
Wrapping content for these situations may be situational. Do you know of a universal solution?

You can use some CSS like this to force a break:

```
    overflow-wrap: break-word;
    word-wrap: break-word;
    -ms-word-break: break-all;
    word-break: break-all;
    word-break: break-word;
    -ms-hyphens: auto;
    -moz-hyphens: auto;
    -webkit-hyphens: auto;
    hyphens: auto;
    display: inline-block; 
    max-width: 450px; 
    vertical-align: middle;
```
