### ISSUE TITLE
Image sizes in Outlook 2003

### ISSUE THREAD

**Issue by parkersweb** [foundation/foundation-emails#50]
I've got a simple hero image in a template I've just created:

``` html
    <table class="body">
        <tr>
            <td class="center" align="center" valign="top">
        <center>


          <table class="container">
            <tr>
              <td>

                <table class="row">
                  <tr>
                    <td class="wrapper last">

                      <table class="twelve columns">
                        <tr>
                          <td>

                        <img width="580" height="300" src="http://placehold.it/580x300">

                          </td>
                          <td class="expander"></td>
                        </tr>
                      </table>

                    </td>
                  </tr>
                </table>
              </td>
            </tr>
          </table> 

        </center>
            </td>
        </tr>
    </table>
```

It's been through the zurb inliner and is using ink 1.0.4 - but for Outlook 2003 (and Outlook 2002, 2000) the image width is wrong:

http://cl.ly/image/3T1A0x020v07/o

I can't see anything else to reduce the problem further - is there something I'm missing?

Thanks!

Andrew

**Comment by lenymo** [comment]
I can confirm that this fix still works. I had to use it when there were multiple images in a row as shown below. They still work responsively as expected as well.

![screen shot 2015-04-29 at 12 10 18 pm](https://cloud.githubusercontent.com/assets/6083596/7383792/d6fd7208-ee68-11e4-8c09-5b3cc87e431c.png)

**Comment by rafibomb** [comment]
This is a great reference! It worked for me too, although really bizarre!

**Comment by rafibomb** [comment]
FYI - if you are using Foundation form Emails 2 with Inky - this can still happen but you can add a `no-expander` attribute to the column.

`<columns large="12" no-expander>`
