### ISSUE TITLE
[Button] small-expanded class missing?

### ISSUE THREAD

**Issue by sergeylukin** [foundation/foundation-emails#504]
Hi,

I don't seem to find `.small-expanded` class in Foundation Emails. Am I missing something?

**Comment by rafibomb** [comment]
You'll find it here: https://github.com/zurb/foundation-emails/blob/develop/scss/components/_media-query.scss#L118

The commit was in the 2.2.0 release so you'll need that version or 2.2.1 to have it.

**Comment by sergeylukin** [comment]
Oh, what a fast pace. I've just installed foundation-emails a few days ago and you already have moved pretty far away from that version :) Thank you! Upgraded to 2.2.1 and it's working fine now. Will check releases more frequently.
