### ISSUE TITLE
Button text color in Outlook mobile app

### ISSUE THREAD

**Issue by sergeylukin** [foundation/foundation-emails#510]
Sorry for poorly formatted issue. The mission of this issue is to let you know about this visual bug.
I will try to find real devices, install Outlook app and reproduce the bug and provide shots and more details but before that happens: I've noticed the button text color is blue on someone's Outlook for iOS (worth checking Android too), although it is supposed to be white as in all other email clients I've tested with default settings.

**Comment by edeoldi** [comment]
I can confirm this. Please find a visual comparison between Outlook for iOS and the standard iOS Mail App below:
![outlook_vs_mailapp](https://cloud.githubusercontent.com/assets/4718856/16615436/019e9abe-4377-11e6-8daf-3dc6a2b91b2f.jpg)

**Comment by sergeylukin** [comment]
That's why I love open source projects. Thank you @edeoldi !!

**Comment by rafibomb** [comment]
So this is only happening on Outlook for IOS?

One workaround for Outlook I've found to work is to wrap the text with:

```
<font color="#ffffff">Click me!</font>
```

Can you let us know if this helps?

**Comment by sergeylukin** [comment]
I'll be able to test this on iOS and Android tomorrow, stay tuned.

**Comment by sergeylukin** [comment]
@rafibomb it does the trick on Outlook for iOS. Didn't test on Outlook for Android yet.

**Comment by rafibomb** [comment]
It will work there as well, I'm sure. I wonder though what caused it for you. If you see a pattern that causes this, please open a new issue with the details!
