### ISSUE TITLE
Paragraph duplicate properties

### ISSUE THREAD

**Issue by florianbouvot** [foundation/foundation-emails#512]
Hello,

It isn't a bug but I wonder why `$paragraph-margin-bottom` are apply in two files:
- [normalize](https://github.com/zurb/foundation-emails/blob/develop/scss/components/_normalize.scss#L68-L71)
- [typography](https://github.com/zurb/foundation-emails/blob/develop/scss/components/_typography.scss#L222-L225)

What do you think?

**Comment by rafibomb** [comment]
Good catch! It's only needed once in the typography file. Is that something you can submit a PR for?

**Comment by florianbouvot** [comment]
@rafibomb thanks, PR submitted ;)

**Comment by rafibomb** [comment]
Awesome!

**Comment by florianbouvot** [comment]
@rafibomb sorry but I forget to remove `$paragraph-margin-bottom` from normalize... So I submit a second PR.
