### ISSUE TITLE
[docs] Sass and CSS guide boilerplate are not up to date 

### ISSUE THREAD

**Issue by florianbouvot** [foundation/foundation-emails#515]
`default.html` layout from [foundation-emails-template](https://github.com/zurb/foundation-emails-template) contain elements that aren't mentioned in [Sass](https://github.com/zurb/foundation-emails/blob/develop/docs/pages/sass-guide.md#boilerplate) and [CSS](https://github.com/zurb/foundation-emails/blob/develop/docs/pages/css-guide.md#boilerplate) guide:
- [`lang` and `xml:lang`](https://github.com/zurb/foundation-emails-template/blob/master/src/layouts/default.html#L6):

```
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
```
- [`preheader`](https://github.com/zurb/foundation-emails-template/blob/master/src/layouts/default.html#L15):

```
<span class="preheader">{{description}}</span>
```
- [Gmail on iOS font size trick](https://github.com/zurb/foundation-emails-template/blob/master/src/layouts/default.html#L26-L27):

```
<!-- prevent Gmail on iOS font size manipulation -->
<div style="display:none; white-space:nowrap; font:15px courier; line-height:0;"> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </div>
```

What do you think?

**Comment by rafibomb** [comment]
YES! Those need to be updated. Is that something you can help with?

**Comment by florianbouvot** [comment]
I can help, but can you confirm me that [foundation-emails-template](https://github.com/zurb/foundation-emails-template) repo is the source (and most "up to date")?

**Comment by rafibomb** [comment]
Yes - the develop branch is in sync with master and a great place to add features to test before merging

**Comment by stevenharman** [comment]
Did anything ever come of this? I just stumbled across it by looking for documentation on `.preheader`. I realized the `.stat` class is also undocumented.
