### ISSUE TITLE
Sidebar Images in Gmail

### ISSUE THREAD

**Issue by camaech** [foundation/foundation-emails#518]
**How can we reproduce this bug?**
Grab the basic sidebar inky test from Foundation. Insert two larger than column width images in the main column and a sidebar.

Write out the HTML (or Inky code) that causes the issue.

```
<container>
  <row>
    <columns large="7">
      <img src="https://gallery.mailchimp.com/be5c015055482731bbfcd45de/images/66c75b3f-8543-4f5d-b92f-068774d5f5de.png" />
    </columns>
    <columns large="5" class="sidebar">
      <img src="https://gallery.mailchimp.com/be5c015055482731bbfcd45de/images/1a1298cd-f9b6-4f9b-a781-28bd85d68f99.jpg" />
    </columns>
  </row>
</container>
```

**What did you expect to happen?**
The width shouldn't cause the page to scroll horizontally in Gmail (Explorer, Firefox) or Google Apps (Explorer, Firefox) according to a Litmus test.

Is this how it should work? Seems incorrect to me, but I wanted to verify that this isn't a bug.

**What happened instead?**
The page scrolls horizontally in certain browsers. The images seems to widen the page.

**What email clients does this happen in?**
Gmail (Explorer, Firefox) or Google Apps (Explorer, Firefox) according to a Litmus test.

Here is a test image from Litmus:
![gmailnew-vertical-allowed-1366 1](https://cloud.githubusercontent.com/assets/977957/16656827/bff2eed0-4425-11e6-9845-1646dbaff341.png)

**Comment by rafibomb** [comment]
You'll want the images to match the container width as much as possible. You should add a `width="580"` to contrain it

**Comment by markadrake** [comment]
The framework should handle this if it's a necessity to constrain images to specific widths. Also part of the build process is image optimization, so why does the image optimization not constrain the width of an image to a set max? There are a lot of issues open related to making images expand the full width of their container and it seems this is being casually cast aside. I wonder how many people have opened up the Zurb Foundation, tried to use it, realized that images aren't being handled correctly and just move on to another framework.

There is also no documentation or caveats listed on the documentation site for "working with images and media". Did I miss it? I suggest if the only way these problems can be solved are through hotfixes - a page should be added to the documentation listing all known issues with images and their respective fixes. Current issues seem to include html and build (image inside a wrapper, image inside an expander class) and email clients (image in a full width container in outlook).

http://foundation.zurb.com/emails/docs/

**Comment by cossssmin** [comment]
The image optimization packages that the template gets run through are there only for optimizing image file size for emails; I know of no node package that can check your HTML table width and then resize image(s) used in that table to the exact size. As @rafibomb said, the easiest is to use an attribute (it'll fix Outlook desktop, too, and you can even use it to have retina images).

Regarding the horizontal scrolling in Google email clients, the images are not constrained to the parent's width because the CSS to do so is inside a `@media` query - Gmail, and pretty much any Google email app ignore media queries.

**Comment by amadeus** [comment]
This appears to be a major flaw with this library. A scenario that I would like, is to put an image in a column, and simply have it take up as much width as the column. I don't want it to grow the column, I don't want to care how big the image is, I just want it to fit the column's width.

Am I missing something or is this not possible?

**Comment by cossssmin** [comment]
Well, it actually does. But not in email clients that do not support `@media` queries.

On the other hand, maybe moving this code outside of the `@media` query from `scss/components/_media-query.scss` would be better?

```
table.body img {
  width: auto;
  height: auto;
}
```

Note: haven't tested with Outlook, it might still not work.

**Comment by tdhartwick** [comment]
Gmail will be supporting media queries, so we might be in luck.

Here's the announcement: http://googleappsdeveloper.blogspot.com/2016/09/your-emails-optimized-for-every-screen-with-responsive-design.html

Would this help address the issue?

**Comment by DanielRuf** [comment]
Closing as we did not receive further feedback.
