### ISSUE TITLE
The problem with table borders and HTML email in iOS Mail app

### ISSUE THREAD

**Issue by martinjinda** [foundation/foundation-emails#521]
I have a problem with some lines which are showed only in iOS Mail app. I read some articles about it ([https://www.campaignmonitor.com/blog/email-marketing/2011/10/iphone-fail-the-trouble-with-table-borders-and-html-email/]) and I found that the solution could be add `cellspacing="0" cellpadding="0"`, but if I put it with Inky it's not showed in result code.

Does someone know how to manage this problem?

_That line under purple arrow shouldn't be there:_
![fullsizerender](https://cloud.githubusercontent.com/assets/9948632/16725406/676c8a5c-4757-11e6-918d-066872ac4122.jpg)

**Comment by rafibomb** [comment]
Are you on version 2.2.1? I'm seeing those attributes can be added with the latest version.

**Comment by jamesdixon** [comment]
I can also confirm that these attributes show up in 2.2.1.

**Comment by jamesdixon** [comment]
@martinjinda I'm able to see the `cellpadding` and `cellspacing` attributes using 2.2.1, but unfortunately the issue remains. Are you having luck with this fix?

**Comment by DanielRuf** [comment]
Closing as we did not receive furthr feedback and in our current email campaigns we did not see this issue so far.
