### ISSUE TITLE
button scss incompatibility 

### ISSUE THREAD

**Issue by dofu** [foundation/foundation-emails#531]
> $button-padding: (
>   tiny: 4px 8px 4px 8px,
>   small: 5px 10px 5px 10px,
>   default: 8px 16px 8px 16px,
>   large: 10px 20px 10px 20px,
> ) !default;

I am currently using sass (3.2.19) and I had problem loading the scss file. The above snippet does not work with the current version of mine. Do you have a library that's compatible with older SASS version?

**Comment by rafibomb** [comment]
Hmm, the framework was built with node-sass, which is 3.4+
You could remove the Sass maps in favor of a standard mixin. Everything else should work with older Sass versions. Its not something we're going to be changing so we'll close this here.
