### ISSUE TITLE
Callout break in Outlook

### ISSUE THREAD

**Issue by marcelo2605** [foundation/foundation-emails#534]
I have a callout component with 855px high and in Outlook 2010 it look break for a blank space.

![screenshot-2016-07-21-12 35](https://cloud.githubusercontent.com/assets/2372927/17028978/c9b6e8b6-4f3f-11e6-9abb-340265c1c93e.jpg)

**Comment by lunascura3** [comment]
It looks like you are running into the infamous Outlook Gap.
Outlook reads email as if it were a word document and assumes that, at some point, you will have a page break. This often occurs somewhere around 2000px down the page. If the content on the left is not the same length as the content on the right, Outlook will insert blank space to compensate.

More info here:
https://www.emailonacid.com/blog/article/email-development/horizontal_spacing_issues_in_outlook_2007_and_2010

**Comment by marcelo2605** [comment]
OK, thanks @lunascura3

**Comment by tdhartwick** [comment]
Woah, forgot about this bug! @lunascura3 thanks for pointing this out. @marcelo2605 looks like there are a few different approaches to handle this. Let us know which one worked out for you! 

Closing this, please reopen it if there are still any issues.
