### ISSUE TITLE
Inliner removes space when using !important

### ISSUE THREAD

**Issue by damongolding** [foundation/foundation-emails#542]
**How can we reproduce this bug?**

Test using outlook 2007 or 2013

```
.foo{
   bar : foobar !important
}
```

**What did you expect to happen?**
For the inliner to respect the space between `foobar` and `!important`.

**What happened instead?**
Inliner removes the space between `foobar` and `!important`.

```
style="bar:foobar!important"
```

The above logic is not respected in outlook

**What email clients does this happen in?**

outlook 2007 - 2013

**Comment by DanielRuf** [comment]
Hi @damongolding ,

this is from the html-minifier that we use.

See
![grafik](https://user-images.githubusercontent.com/827205/71241254-7bfcd100-230b-11ea-875d-04b762147edf.png)

This is valid CSS, see https://codepen.io/DanielRuf/pen/xxbqpoN

See https://stackoverflow.com/a/31143078/753676 and https://www.w3.org/TR/css-syntax-3/#consume-a-declaration
