### ISSUE TITLE
@font-face is stripped upon Inlining.

### ISSUE THREAD

**Issue by kp2615** [foundation/foundation-emails#543]
**How can we reproduce this bug?**

Attempt to inline any code with @font-face. @font-face in either the CSS or HTML section is deleted.

Write out the HTML (or Inky code) that causes the issue.

```
@font-face {
  font-family:"Polaris";
  font-style:normal;
  font-weight:500;
  src:[site-specific URLs redacted];
  }

@font-face {
  font-family:"Polaris";
  font-style:normal;
  font-weight:400;
  src:[site-specific URLs redacted];
  }
```

**What did you expect to happen?**

The @font-face code should still be somewhere in the `<style>` tags. They are not. 

**What happened instead?**

Code is removed entirely.

**What email clients does this happen in?**

Not happening in e-mail. Just happening with latest version of Foundation/Inky Inliner.

**Comment by DanielRuf** [comment]
Related
https://github.com/zurb/foundation-emails/issues/543
https://github.com/zurb/foundation-emails/issues/284

**Comment by Toflar** [comment]
Apparently `juice` is able to inline @font-face. Did you consider switching from `gulp-inline-css` to https://www.npmjs.com/package/gulp-juice?

**Comment by DanielRuf** [comment]
The last release was 3 years ago. The Gulp ecosystem is mainly rewrapping packages for Gulp.

We need another better maintained solution or have to upgrade the current dependencies.

**Comment by Toflar** [comment]
Well yeah, you can use `juice` directly instead of using the wrapper.

**Comment by DanielRuf** [comment]
> Well yeah, you can use juice directly instead of using the wrapper.

True. We'll have to evaluate possible solutions and test them thoroughly to see if these include any regressions or other issues.

**Comment by jhned** [comment]
To add to this: any SCSS **after** a @font-face call is not applied during the inline process. Thought I was losing my damn mind for about 15 minutes.

**Comment by DanielRuf** [comment]
Closing as duplicate. We will update html-minifier to the latest version and use its own css minifier.
