### ISSUE TITLE
Why does the email template still link to app.css after inlining?

### ISSUE THREAD

**Issue by analog-nico** [foundation/foundation-emails#544]
**How can we reproduce this bug?**
1. Use `foundation new --framework emails` with `foundation-cli@2.1.0` to set up a new project.
2. Run either `npm run build` or `npm run zip`.
3. `./dist/index.html` or `./dist/index.zip/index/index.html` is created.

**What did you expect to happen?**

Since all styles are inlined into `index.html` no external css files should be needed anymore.

**What happened instead?**

`index.html` still contains `<link rel="stylesheet" type="text/css" href="css/app.css">`. Is there a reason for that? Is the reference actually needed or should it be removed?

**Comment by thomasaustin** [comment]
I was wondering the same thing. It would be nice to know.

**Comment by cossssmin** [comment]
I always delete it from the inlined emails, and from what I've tested (using all Inky tags) it doesn't affect the template in any way.

**Comment by analog-nico** [comment]
As it seems the css file is really not needed anymore, I created the pull request above to update the gulp workflow of the project created by `foundation new --framework emails` to automatically remove the link tag when using `npm run build`.

**Comment by AndyBean** [comment]
Thanks for creating the pull request in this matter. You just saved me the effort of doing the exact same thing. Yes, the inlining process should strip all redundant exterior links.

**Comment by SebastianSchirmer** [comment]
Please see my comment in the PR (https://github.com/zurb/foundation-emails-template/pull/23), just adding removeLinkTags: true in the inliner function gives you what you are looking for.

**Comment by tdhartwick** [comment]
Fixed! Thanks for pointing this out! https://github.com/zurb/foundation-emails-template/commit/75d5f37749750c4b3a802e4f8e15387cf1e94da7
