### ISSUE TITLE
Anchor tag inside of paragraph removes its margin bottom

### ISSUE THREAD

**Issue by tobyimaginepublishing** [foundation/foundation-emails#550]
**How can we reproduce this bug?**
By placing an anchor tag inside of a paragraph

Write out the HTML (or Inky code) that causes the issue.

```
<p>And now with this amazing offer you can try the next <a href="#" target="_blank">3 issues of How It Works for just £1</a> - that's a saving of 92%. As well as this, we will deliver every issue for FREE so subscribe today!</p>
        <p>Live outside the UK? We have an exclusive offer for our US and Canada readers, <a href="#" target="_blank">subscribe today and get 13 issues for only $79</a> (saving over $50 compared with the newsstand price).</p>
```

With link:
![screen shot 2016-08-09 at 14 52 05](https://cloud.githubusercontent.com/assets/20928651/17519510/176fb3ae-5e44-11e6-9a1a-d099c8f16885.png)

Without link:
![screen shot 2016-08-09 at 14 51 30](https://cloud.githubusercontent.com/assets/20928651/17519524/2783a0ac-5e44-11e6-962f-7dc8e7f07a72.png)

**What did you expect to happen?**
Anchor tag to have no affect on the paragraph

**What happened instead?**
Anchor tag removed the paragraph's margin bottom

**What email clients does this happen in?**
Outlook 2007+

**Comment by tobyimaginepublishing** [comment]
This is an ongoing issue: https://github.com/zurb/foundation-emails/issues/224
Please fix this!

**Comment by tobyimaginepublishing** [comment]
Any help is much appreciated.

**Comment by ghost** [comment]
Try putting an actual value inside the anchor.  I've read that if you leave the anchor blank (even the #) can cause strange issues with spacing.

**Comment by tobyimaginepublishing** [comment]
@coreyschaaf I originally had a link in the href and it was doing the same thing. Any other ideas?

**Comment by tobyimaginepublishing** [comment]
Any help is much appreciated.

**Comment by rafibomb** [comment]
Reading back to the issue referenced here: it seems like this is general issue in Outlook 2007, 10, 13. We've worked around it with the spacer component. Have you tried that @tobyimaginepublishing ?

Otherwise, what other solution have you tried to work around this? Can you think of ways that the techniques used on the spacer can be used to create bottom spacing on elements?

**Comment by tobyimaginepublishing** [comment]
What about dynamic content? It doesn't seem very user friendly that the user has add Outlook conditional comments and a spacer tag after every paragraph that has a link within it. I'm assuming this is how you do it?

Perhaps by using line breaks as suggested by ManoID in this issue? https://github.com/zurb/foundation-emails/issues/224

**Comment by ghost** [comment]
the <spacer> tag would probably be a good use case here.

<spacer size="15"></spacer>

My only issue with spacer is it's a lot of bloat code just so you can add
consistent padding. But it's pretty rock solid and consistent across the
board.

**Comment by tobyimaginepublishing** [comment]
@coreyschaaf What about dynamic content?

**Comment by ghost** [comment]
Can't help you there toby. What's odd is I'm trying to replicate this in my own emails and I can't seem to do it. Do you have some inky code you can send me and I can test it on emailonacid and send you the link?

**Comment by tobyimaginepublishing** [comment]
@coreyschaaf It only affects Outlook 2007+.

**Comment by tobyimaginepublishing** [comment]
I changed the following in _typography.scss to fix it:

```
body,
table.body,
h1,
h2,
h3,
h4,
h5,
h6,
p,
td,
th,
a {
  color: $global-font-color;
  font-family: $body-font-family;
  font-weight: $global-font-weight;
  padding: 0;
  margin: 0;
  Margin: 0;
  text-align: left;
  line-height: $global-line-height;
}
```

To:

```
body,
table.body,
h1,
h2,
h3,
h4,
h5,
h6,
p,
td,
th,
a {
  color: $global-font-color;
  font-family: $body-font-family;
  font-weight: $global-font-weight;
  padding: 0;
  text-align: left;
  line-height: $global-line-height;
}

body,
table.body,
h1,
h2,
h3,
h4,
h5,
h6,
p,
td,
th {
  margin: 0;
  Margin: 0;
}
```

I tested it in the main email clients and it seems fine.

Credit goes to [nwerr](https://github.com/nwerr) for his lead.
