### ISSUE TITLE
The spacer tag doesn't seem to work inside Outlook conditional comments

### ISSUE THREAD

**Issue by tobyimaginepublishing** [foundation/foundation-emails#551]
**How can we reproduce this bug?**
By placing a spacer tag inside Outlook conditional comments

Write out the HTML (or Inky code) that causes the issue.
``

**What did you expect to happen?**
The tag to create the table structure

**What happened instead?**
It stayed the same

**What email clients does this happen in?**
N/A

**Comment by mfontani** [comment]
The "outlook conditional comments" are just… comments, and they get skipped over (and removed by a later process which strips comments).

Assuming the version of Inky you have supports the `raw` tag, try:

```
    <raw><!--[if gte mso 12]></raw><spacer size="23"></spacer><raw><![endif]--></raw>
```

Works for us :)

**Comment by tobyimaginepublishing** [comment]
Ok thank you.
