### ISSUE TITLE
Inliner obliterates client-specific style hacks?

### ISSUE THREAD

**Issue by thisisjamessmith** [foundation/foundation-emails#552]
The standard Foundation for Emails CSS includes things such as `#outlook a { padding: 0; }` and various `.ExternalClass` styles, presumably to fix various things in specific email clients. However, when an email template is run through the inliner tool, these styles are obliterated... Am I missing something here? What's the point in them if they never make it into the final email?

**Comment by rafibomb** [comment]
How are you using these styles? Are you adding them to a custom stylesheet or are you referring to the CSS that is in the `_normalize.scss file`.

**Comment by thisisjamessmith** [comment]
I'm referring to the normalize styles. Some research uncovers that `.ExternalClass` is a classname used by outlook.com's web UI... but that bit of CSS never makes it through the inliner as I don't use it in my own HTML.

**Comment by DanielRuf** [comment]
You have to readd it in a style tag. The online inliner inlines styles and removes unused code.

<img width="1196" alt="Bildschirmfoto 2019-12-22 um 12 02 56" src="https://user-images.githubusercontent.com/827205/71320928-06336980-24b3-11ea-94d1-8fa9df37f472.png">

The inline gulp task may be more sufficient (you can adjust the uncss configuration).
