### ISSUE TITLE
Inliner/SCSS output removes @keyframe

### ISSUE THREAD

**Issue by rl2999** [foundation/foundation-emails#553]
**How can we reproduce this bug?**

Including a @keyframe animation description in `./assets/scss/app.scss`

> `@keyframes fadein {
>   0%   { opacity: 0; }
>   100% { opacity: 1; }
> }`

**What did you expect to happen?**

The final output from `npm zip` should have inlined the `@keyframe` in the `style` tag.

**What happened instead?**

`@keyframe` is removed from the style tag

Although some other at-rules seem to be preserved, like media

**What email clients does this happen in?**
Client doesn't matter in this case

**Comment by callaginn** [comment]
I'm having this issue as well. Has anyone figured out how to fix or bypass this issue?

**Comment by DanielRuf** [comment]
Related
https://github.com/zurb/foundation-emails/issues/543
https://github.com/zurb/foundation-emails/issues/284

**Comment by DanielRuf** [comment]
Closing as duplicate. We will update html-minifier and use its own css minifier then.
