### ISSUE TITLE
New syntax <row> <columns> is not supported

### ISSUE THREAD

**Issue by HStokbro** [foundation/foundation-emails#558]
Tried pasting this into the inliner. Outcome is not transformed to tables.
The css version templates are not updated to the new syntax. Seems like the CSS version is behind the SCSS version.

Pasted this:
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
  <head>
    <link rel="stylesheet" type="text/css" href="css/app.css">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width">
    <title>{{subject}}</title>
  </head>
  <body>
    
    <span class="preheader">{{description}}</span>
    <table class="body">
      <tr>
        <td class="center" align="center" valign="top">
          <center>
            <container>
  <row>
    <columns small="12" large="12">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit totam quasi ab aliquam saepe non fugiat laborum, veniam corporis alias impedit est nesciunt. Provident numquam cum libero vero minus fuga.</p>
    </columns>
  </row>
  <row class="collapse">
    <columns small="12" large="12">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit totam quasi ab aliquam saepe non fugiat laborum, veniam corporis alias impedit est nesciunt. Provident numquam cum libero vero minus fuga.</p>
    </columns>
  </row>
  <row>
    <columns small="12" large="6">
      <p>One Word</p>
    </columns>
    <columns small="12" large="6">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure perferendis praesentium quia distinctio, assumenda dolor pariatur! Dolore perspiciatis ratione consequuntur obcaecati cumque molestias, corporis fugiat blanditiis, sit nisi deleniti beatae?</p>
    </columns>
  </row>
  <row>
    <columns small="12" large="2">
      <p>One word</p>
    </columns>
    <columns small="12" large="4">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus velit eveniet est odit doloribus minus, reprehenderit vitae excepturi numquam repellendus natus consectetur dolorem. Quam, voluptatem non aperiam rem voluptas sequi?</p>
    </columns>
    <columns small="12" large="6">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus velit eveniet est odit doloribus minus, reprehenderit vitae excepturi numquam repellendus natus consectetur dolorem. Quam, voluptatem non aperiam rem voluptas sequi?</p>
    </columns>
  </row>
  <row>
    <columns small="12" large="2">
      <p>One Word</p>
    </columns>
    <columns small="4" large="4">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga repellendus velit aut perferendis, eveniet delectus maxime quisquam recusandae assumenda culpa tenetur dolorem error voluptatibus. Animi accusamus molestiae placeat, sequi beatae.</p>
    </columns>
    <columns small="8" large="6">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis quis obcaecati facere dolore laborum officia rem praesentium cumque culpa delectus alias ullam ad, doloremque, ipsa asperiores ex sit necessitatibus minima!</p>
    </columns>
  </row>
</container>
          </center>
        </td>
      </tr>
    </table>
    
   <div style="display:none; white-space:nowrap; font:15px courier; line-height:0;"> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </div>
  </body>
</html>

**Comment by tdhartwick** [comment]
Looks like there's a partial tag in there with `{{subject}}`. Make sure Panini is running.

You can quickly see if the code is valid in this Codpen that supports the Inky templating language:
http://codepen.io/FoundationForEmails/pen/PGPNwk

Going to close for now. Please re-open if you're still running in to issues!
