### ISSUE TITLE
&nbsp; outputs as &amp;nbsp;

### ISSUE THREAD

**Issue by waldbach** [foundation/foundation-emails#560]
**How can we reproduce this bug?**
Use http://foundation.zurb.com/emails/inliner-v2.html (Inliner V2)

Write out the HTML (or Inky code) that causes the issue.

**What did you expect to happen?**
`&nbsp;`(no breaking space)

**What happened instead?**
`&amp;nbsp;`
Producing `&nbsp;` on the rendered page on many locations.
The ampersand should be a & instead of `&amp;`

**What email clients does this happen in?**
See http://foundation.zurb.com/emails/inliner-v2.html

**Comment by rafibomb** [comment]
Is it happening when you use the copy to clipboard button?

**Comment by waldbach** [comment]
Yes, I believe so.

**Comment by cgrymala** [comment]
I can confirm this as well. Yes, it's happening when I click the Copy to Clipboard button in the output window.

Also, looks like this was already reported at #549

**Comment by rafibomb** [comment]
Closing for #549
