### ISSUE TITLE
img not scale down in grid Outlook 2016

### ISSUE THREAD

**Issue by Baswazz** [foundation/foundation-emails#561]
When i create a 2 column grid as shown below and put a larger image inside this will break the layout on Outlook 2016 Windows it does not scale down like all other clients do.

**How can we reproduce this bug?**

OS: Windows 10 Enterprise Evaluation (Modern.IE) 64-bits
Outlook: 2016 MSI (16.0.7127.1021) 32-bits
[Putmail](https://putsmail.com/tests/new) to test.

```
<container>

  <row class="collapse">
    <columns>
      <center>
        <img src="http://placehold.it/600x250">
      </center>
    </columns>
  </row>

  <row>
    <columns small="6" large="12">
    <h4>Title</h4>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit totam quasi ab aliquam saepe non fugiat laborum, veniam corporis alias impedit est nesciunt.</p>
      <button href="#">Button</button>
    </columns>
    <columns small="6" large="12">
      <img class="float-right" src="http://placehold.it/400x300" alt="Test">
    </columns>
  </row>

  <spacer size="30"></spacer>

  <row>
    <columns small="6" large="12">
      <img class="float-left" src="http://placehold.it/400x300" alt="Test">
    </columns>
    <columns small="6" large="12">
      <h4>Title</h4>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit totam quasi ab aliquam saepe non fugiat laborum, veniam corporis alias impedit est nesciunt.</p>
      <button href="#">Button</button>
    </columns>
  </row>
</container>

```

**What did you expect to happen?**

The image to scale down to the width of it's parent.

**What happened instead?**

Layout breaks, image stays at it's native width x height.

**What email clients does this happen in?**

Outlook 2016 more info above.

**Comment by joseareland** [comment]
Have you tried this into the image tag?

`width="100"` height=""

Use the desired width for the image in your column, works for me.

**Comment by edeoldi** [comment]
> Use the desired width for the image in your column, works for me.

This is a know issue with all Outlook versions. You simply have to set **width** and **height** for every image you are using, like this:
`<img class="float-left" src="http://placehold.it/400x300" width="400" height="300" alt="Test">`

**Comment by tdhartwick** [comment]
Thanks for hopping in there @joseareland and @edeoldi. Unfortunately Outlook is pretty picky about needing a width attribute for images. Seems to be resolved, please reopen if there are still any issues.
