### ISSUE TITLE
Background Color

### ISSUE THREAD

**Issue by mannymuriel** [foundation/foundation-emails#563]
How do we make background color appear on emails in Gmail for Android and Android? It's not showing up.

It seems to me it doesn't like the bgcolor HTML attribute. How do we make it so it compiles it into CSS attribute also?

**Comment by DerektheDev** [comment]
@mannymuriel Your problem might also be directly related to inky-rb. https://github.com/zurb/inky-rb/issues

Check there as well.

**Comment by DerektheDev** [comment]
@maintainers - The issue he's reporting is that the CSS attribute "background-color" is substituted with the HTML property "bgcolor" when inlined. We want to preserve both, as bgcolor is not respected in Gmail for Android/Android... only the CSS attribute is.

**Comment by mannymuriel** [comment]
This turned out to not be an issue with the email. Litmus' test renders were the ones that were incorrect.
