### ISSUE TITLE
[Getting Started with Sass] Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit

### ISSUE THREAD

**Issue by dylannnn** [foundation/foundation-emails#565]
# **How can we reproduce this bug?**

Downloading the project template...
Done downloading!

Installing dependencies...

(node:12720) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:12720) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:12720) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:12720) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:12720) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:12720) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:12720) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:12720) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:12720) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:12720) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:12720) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:12720) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:12720) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:12720) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:12720) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:12720) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:12720) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:12720) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:12720) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:12720) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:12720) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:12720) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:12720) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:12720) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:12720) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:12720) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:12720) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:12720) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:12720) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:12720) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:12720) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:12720) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:12720) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:12720) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:12720) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
# (node:12720) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit

**What did you expect to happen?**

When I run "foundation new --framework emails", after I type the project name and hit the enter key, it start to installing the dependencies, and it gives me a lot of warnings.

How Can I fix it?

**Comment by minnaert** [comment]
I get the same error. Any ideas on how to fix?

**Comment by EstherMartz** [comment]
+1!

**Comment by f4f343w4tcfwv4tz5tb5** [comment]
Same issue - clean install Mac OS Sierra, clean install Node.js 4.5

**Comment by chedaroo** [comment]
Me too
nvm v0.31.7
node v6.5.0

**Comment by mdrick** [comment]
+1 !

**Comment by Stadly** [comment]
I get it too :/

**Comment by Stadly** [comment]
Workaround:
1. Navigate into the project folder.
2. Run `foundation watch`.
3. Look at the error messages. I got an error saying `Error: Cannot find module 'source-map'`.
4. Run an `npm install` for each error. In my case `npm install source-map`.
5. Run `foundation watch`.
6. Everything should be working fine :)

**Comment by minnaert** [comment]
Thanks @Stadly, but after using foundation watch, i now see that i have some external modules not loading
[15:27:25] Failed to load external module babel-register
[15:27:25] Failed to load external module babel-core/register
[15:27:25] Failed to load external module babel/register

I have tried to install babel several times, using this install command:
    npm install babel-register babel-preset-es2015
as well as a couple others, but i still get this same error with missing external modules.
any ideas?

**Comment by Stadly** [comment]
I've got no idea, @minnaert. Sorry.

**Comment by minnaert** [comment]
I needed to properly clone the emails template.
after running this:
git clone https://github.com/zurb/foundation-emails-template project
cd project
npm install
found here:
https://github.com/zurb/foundation-emails
into a new project, I was able to run & build successfully.

**Comment by DanielRuf** [comment]
Try updating your Node.js version.

**Comment by DanielRuf** [comment]
Closing as this is only an issue with Node and specific libraries and a too low setting for the listeners on systems. Warnings cna be often ignored and this is a warning thrown by Node itself.
