### ISSUE TITLE
3 cols breaking for small

### ISSUE THREAD

**Issue by cossssmin** [foundation/foundation-emails#574]
**How can we reproduce this bug?**

Using the default settings, set a 3-column layout to have the columns sized identically for large and small. 

**Write out the HTML (or Inky code) that causes the issue.**

```
<row>
    <columns small="3" large="4">
      <p><strong>Image</strong></p>
    </columns>
    <columns small="7" large="6">
      <p><strong>Description</strong>: Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
    </columns>
    <columns small="2" large="2">
      <p><strong>$12</strong></p>
    </columns>
  </row>
```

**What did you expect to happen?**

Have it look just as on desktop, 3 columns in a row. For example:

![image](https://cloud.githubusercontent.com/assets/1656595/18054535/f658d3d4-6e0c-11e6-878a-536e9f041fda.png)

**What happened instead?**

The third column breaks onto a new line.

![image](https://cloud.githubusercontent.com/assets/1656595/18054541/fb2b99e6-6e0c-11e6-9e21-360e6502da2d.png)

**What email clients does this happen in?**

Testing locally, as well as iOS Mail.

Haven't tested with more than three columns, I guess it's the same.

**Comment by tdhartwick** [comment]
Huh, nice catch. Will take a look at this.

**Comment by cossssmin** [comment]
Closing this, as I have tested thoroughly again (locally, Email on Acid), and I cannot replicate it in any way...
