### ISSUE TITLE
.hide-for-large bug after inliner

### ISSUE THREAD

**Issue by Typografics** [foundation/foundation-emails#576]
The .hide-for-large class isn't working because of the display: none !important on line 779.
If you remove the !important everything is working perfect.

**Comment by baumant** [comment]
This is discussed in PR #509

**Comment by lbineau** [comment]
+1

**Comment by tdhartwick** [comment]
Thanks for reporting! We merged in a https://github.com/zurb/foundation-emails/pull/509 which should fix it. Let us know if there are any issues.

Also, word on the street, is that Gmail will be supporting `<style>...</style>` later this week, which should alleviate this problem as well. :)
