### ISSUE TITLE
Inliner replaces '&' with '&amp;' in inconvenient places

### ISSUE THREAD

**Issue by sparxoo-tampa** [foundation/foundation-emails#577]
**How can we reproduce this bug?**
Create any email with images that contain an '&' in the src or that implements html entities

Write out the HTML (or Inky code) that causes the issue.
<img src="https://system.na1.netsuite.com/core/media/media.nl?id=819&c=4284155&h=b3bab42271f6207dc13d&whence=">
<a href="#">Read More &gt;&gt;</a>

**What did you expect to happen?**
The inline would ignore src attributes/link attributes, as well as existing html entities

**What happened instead?**
A lot of my markup was destroyed. All images broke and html entities I used were broken

**What email clients does this happen in?**
Any client

**Comment by marcpartridge** [comment]
Think this is related to this issue #560. 

Instead of using the "Copy to clipboard" button try triple clicking the code so it selects it all (better than scrolling down the page) and copying it (cmd+c/ctrl+c).

**Comment by tdhartwick** [comment]
Thanks for reporting @Sparxoo, we'll close this thread and reference #560 as @marcpartridge pointed out. Looking to resolve this soon!

**Comment by ghost** [comment]
"Copy to Clipboard" btn is still causing this issue as of now. Just FYI.
