### ISSUE TITLE
Feature request -- indentation

### ISSUE THREAD

**Issue by paxperscientiam** [foundation/foundation-emails#583]
I finally spun up Foundation for Emails and I am just floored by how simple it is to get started. Having the whole machinery pre-made takes away so much of the hassle, leaving the focus on the creativity.
## Bravo!

I've got a small feature request that I would implement myself if I knew anything about ruby.

Basically, introduce an Inky class/attribute that inserts non-breaking spaces for indents. That is:

``` html
<p indent="1">text</p>
<!-- would become -->
<p>&nbsp;text</p>
```

Doubly indented:

``` html
<p indent="2">text</p>
<!-- would become -->
<p>&nbsp;&nbsp;text</p>
```

EDIT: forgot my ampersands.

**Comment by tdhartwick** [comment]
Thanks for the kind words @paxperscientiam!
So this is a workaround for a Outlook 2007/10/13 padding issue? Was looking around, and it seems like the `text-indent` property is supported by the big guys, see: https://www.campaignmonitor.com/css/

What email client/use case does this appease?

**Comment by paxperscientiam** [comment]
Hi @tdhartwick,

D'oh -- you are right. That said, silly implementation aside, do you think such a syntactic addition would be beneficial to Inky?

**Comment by DanielRuf** [comment]
I think there is not much benefit for this and I think a helper CSS class makes even more sense. So far we had no similar requests or usage need so I'll close this for now.

Thank you for taking the time to propose that and tryoing to find a solution.
