### ISSUE TITLE
Images don't appear in browserSync

### ISSUE THREAD

**Issue by vvasyliev** [foundation/foundation-emails#585]
I'm using foundation for emails and want to include some images to the email. I placed all the images into /src/assets/img/ directory, required them in the html templates like that:

``` HTML
<img src="assets/img/logo.png" alt="logo">
```

and like that:

``` HTML
<img src="../../dist/img/logo.png" alt="logo">
```

and even like that:

``` HTML
<img src="src/assets/img/logo.png" alt="logo">
```

But all what I see is the word "logo" from the image's "alt" attribute. Is it a bug or am I doing something wrong?
There are no error logs in CLI, images were successfully copied to /dist/ folder after running "npm start", and the only message that appears in console is:

``` BASH
[12:55:37] gulp-imagemin: Minified 6 images (saved 171 B - 4.2%)
[RENDER] First phase complete. Panini, Inky, Sass, Images compiled.
[RENDER] Second phase complete. Css siphoned and copied.
[RENDER] Third phase complete. Css inlined.
```

**Comment by cossssmin** [comment]
You need to quit and restart the build process (`npm start` or `npm run build`). The first example you provided will work fine, once the `images()` task actually creates the `assets\img` folder in `dist`.

**Comment by tdhartwick** [comment]
@kball did you say you were taking a look at this?

**Comment by vvasyliev** [comment]
@hellocosmin yes, that actually creates images in `/dist/` directory, but they just don't appear, my path in pages/review/index.html looks like this:

``` CSS
<img src="assets/img/logo.png" alt="logo"></img>
```

**Comment by rosgzc** [comment]
I am having the same issue. Is there a solution for this?

**Comment by cossssmin** [comment]
@lbrasau - if you have the page in a subfolder of `/pages/`, then it will be in a subfoler in `/dist/`, too. So you would need:

```
<img src="/assets/img/logo.png" alt="logo" />
```

Btw, `<img>` is a self closing tag, what you have there is invalid markup.

**Comment by vvasyliev** [comment]
@hellocosmin thank you for the help, I've tried to fix invalid markup and took a look into /dist/ directory. There are no folders in /dist/img/. 
That's how my /dist/ directory looks like:
![dist_folder](http://i.imgur.com/heq5Gzc.png)
@rossgzc how many pages do you have in your zurb-emails? I think that issue somehow related to non-standard structure in directory with *html files.

**Comment by cossssmin** [comment]
OK, so it looks like you don't have something like `/src/pages/my-page.html` - then you don't need the `/` in front of `assets` in the src tag of the image. My reply above was referring to any pages you might have created in a subfolder of the `src/pages/` folder.
