### ISSUE TITLE
Spacer stretches button to be full width on Android when being placed before button

### ISSUE THREAD

**Issue by SebastianSchirmer** [foundation/foundation-emails#587]
When using a spacer before a button, the button gets stretched to full width on Android 4.4 (Litmus test) and a couple more devices. Interestingly, when a spacer is used after a button, everything is fine. On almost all other devices, everything works as expected.

**How can we reproduce this bug?**
Just use the following code and run a Litmus test:

```
<container>
    <row>
        <columns>
            <spacer size="16"></spacer>
            <p>some text</p>
            <center>
                <button class="" href="#">Click Me</button>
            </center>
        </columns>
    </row>
</container>
```

**What did you expect to happen?**
Button should not be stretched to full width even if a spacer is used before in the code

**What happened instead?**
Button is stretched to full width

**What email clients does this happen in?**
Litmus Android 4.4

**Comment by cossssmin** [comment]
I don't have a Litmus account, does it behave the same if you place the spacer just before the row?

```
<container>
    <spacer size="16"></spacer>
    <row>
        <columns>            
            <p>some text</p>
            <center>
                <button class="" href="#">Click Me</button>
            </center>
        </columns>
    </row>
</container>
```

**Comment by SebastianSchirmer** [comment]
I was trying to reproduce this issue on emailonacid, but could not. Therefore I assume it's a litmus issue, closing this one therefore.
