### ISSUE TITLE
Provide inliner API or library

### ISSUE THREAD

**Issue by bbakersmith** [foundation/foundation-emails#59]
We are running into encoding issues with the inliner, specifically that it does not preserve the encoding of `&ndash;` `&mdash;` `&copy;` etc... Premailer has a whole lot of open encoding issues in their repo, so I don't think they will be addressing this anytime soon.

If Ink's inliner were provided in a way that could be utlized programatically, we could fix some of these issues with another processing step.

Do you have any plans to provide the inliner as an open source library or via an API connection? I tried posting directly to your skate-proxy.php processing script, but there are cross-domain access control restrictions that prevent this approach.

Alternately, if you have any recommendations for fixing these encoding issues without inliner access, please share. Thanks!

**Comment by LunkRat** [comment]
http://premailer.dialect.ca/api

**Comment by kirkstrobeck** [comment]
FYI, the settings mentioned [above](https://github.com/zurb/ink/issues/59#issuecomment-36662624) are the ootb defaults per https://github.com/zurb/premailer/blob/master/lib/premailer/premailer.rb#L193-L212
