### ISSUE TITLE
Line height not working

### ISSUE THREAD

**Issue by tobyimaginepublishing** [foundation/foundation-emails#590]
**How can we reproduce this bug?**
Just by using it out of the box, inlining it and then testing in Outlook 2007+

Write out the HTML (or Inky code) that causes the issue.

```
body,
table.body,
p,
td,
th {
  font-size: $global-font-size;
  line-height: $body-line-height;
}
```

**What did you expect to happen?**
The line height to be consistent across all email clients

**What happened instead?**
The line height collapsed

**What email clients does this happen in?**
Outlook 2007+

I've tried using `mso-line-height-rule: exactly;` but it doesn't work

**Comment by cossssmin** [comment]
`_settings.scss` already defines a global line height, which gets applied (inlined) to all the elements you listed there:

![image](https://cloud.githubusercontent.com/assets/1656595/18645961/1a098d30-7eb8-11e6-9256-5be7b5ae47d8.png)

Your code won't make a difference, because:
1. you're not changing the line height value, you're just using the variable that already gets inlined
2. if that code is in `app.scss`, it won't override the variable in `_settings.scss` unless you add `!important`

**Comment by tobyimaginepublishing** [comment]
@hellocosmin Yes I know. I've changed the `$global-line-height` to 1.7 and it doesn't work in Outlook 2007+. I don't think Outlook 2007+ accepts a number value?

**Comment by tdhartwick** [comment]
Hmm... this is looking a little stickier than I was originally. Looks like we might need to wrap everything in a `<div>` and then set that line-height? 

See: https://www.campaignmonitor.com/forums/topic/5848/outlook-2007-issues-with-span-stylelineheight-25px/

But there's also this article, with someone reporting good results in 2007: https://www.emailonacid.com/blog/article/email-development/line_height_and_outlook.com

Anybody able to verify this?

**Comment by tobyimaginepublishing** [comment]
@tdhartwick I found changing all number values (1.7) to length values (25px) worked for me. I got the fix from this article which also explains not to use the line-height property in any line-level tags: https://www.marketingcloud.com/blog/design-tip-of-the-week-css-line-height-property-does-it-work-in-email/

**Comment by tdhartwick** [comment]
Oh nice! I'm wondering if a mixin similar to F4S's `remcalc()` might be worth pursuing?

**Comment by benjibee** [comment]
The easiest fix for this is documented well in [this article from Email on Acid](https://www.emailonacid.com/blog/article/email-development/line_height_and_outlook.com).

Yes Outlook does require `line-height` to be specified in percentages, but it also often simply ignores it. The best workaround I've found is to use Outlook's own `.ExternalClass` class as such:

``` css
.ExternalClass body,
.ExternalClass table.body,
.ExternalClass p,
.ExternalClass td,
.ExternalClass th {
    line-height: 130%;
}
```

Which should override their default of `* {line-height: 131%}` which is already applied to all elements.

On another note, if using the SASS version of Foundation Email, it seems to strip this class. Still not sure how to work around that!

**Comment by fernamp** [comment]
When I write
`<td style="line-height: 1px;">`
to solve the _underpadding_ from outlook, the framework outputs
`<td style="line-height: 1px solid;">`
rendering the code useless.

Is this another issue or is related to this one?

**Comment by tobyimaginepublishing** [comment]
@tdhartwick Yes that would work so please can you update the code for future use?
@fernamp That's a separate issue.

**Comment by jsit** [comment]
In my tests, simply changing `$global-line-height` to a percent value rather than a unitless value works, without the need for `.ExternalClass`.

@benjibee: The `.ExternalClass` declaration is being stripped due to [uncss](https://github.com/zurb/foundation-emails/issues/640). Try putting `/* uncss:ignore */` before it. (However, again, in my tests, you don't need `.ExternalClass`.)

**Comment by jsit** [comment]
@benjibee: The `.ExternalClass` declaration is being stripped due to [uncss](https://github.com/zurb/foundation-emails/issues/640). Try putting `/* uncss:ignore */` before it.

**Comment by philzelnar** [comment]
Has anyone noticed using a percent value on `$global-line-height` seems to muck-up buttons in Outlook 10/13/16 (testing in Litmus)? The result for me is extra color space under the button text.

Setting to a unitless value, buttons look good (but of course the issue of not-so-hot leading in Outlook remains.

**Comment by jsit** [comment]
Can you show us an example? I'm working on an email right now with percent
global line height and a button and it seems fine. Thanks!
