### ISSUE TITLE
space characters around comment tags are stripped out when comments are inline of text

### ISSUE THREAD

**Issue by justingit** [foundation/foundation-emails#591]
The following document, 

```
Here's a simple <!-- comment --> line of text.
```

When distributed using, 

```
npm run build
```

Will create the following text, 

```
Here's a simple<!-- comment --> line of text.
```

in the final file. Why the remove of the space between, "simple" and, ""? I'm using an app that has a templating system whose tags look like HTML comments, so whitespace before and after those tags are important.

**Comment by justingit** [comment]
This problem doesn't appear to happen in the online inliner, 

http://foundation.zurb.com/emails/inliner.html

```
<!-- Inliner Build Version 4380b7741bb759d6cb997545f3add21ad48f010b -->
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><p>Here's a simple <!-- comment --> line of text.</p></body></html>
```

**Comment by justingit** [comment]
Funnily, this problem will also happen if I have the following doc, 

```
Here's a simple {{{vars.foo}}} line of text.
```

If I have a, src/data/vars.yml file, with the following, 

```
foo: <!-- comment -->
```

The final output will produce, 

```
Here's a simple<!-- comment --> line of text.
```

So I can't workaround the problem. 

I guess whitespace before comments is always stripped, even if the comment is inline to just text.

**Comment by justingit** [comment]
In my gulpfile.babel.js file, I was hoping adding the following parameter, 

   conservativeCollapse: true, 

to htmlmin: 

```
.pipe($.htmlmin, {
  collapseWhitespace: true,
  conservativeCollapse: true, 
  minifyCSS: true
});
```

Would do what I wanted, as the docs (https://www.npmjs.com/package/html-minifier) seem to perhaps indicate, but no dice. I've had to set, collapseWhitespace to, false, which I guess isn't the worst of it.

**Comment by DanielRuf** [comment]
This is a bug in the old versions of html-minifier.

We use 1.x and this is the result with 4.0.0:
https://repl.it/@DanielRuf/PalegreenPungentMultiprocessing

With 1.5.0:
https://repl.it/@DanielRuf/IdealHonoredForm

This will be fixed when we update gulp-htmlmin and .

foundation-emails contains `collapseWhitespace: false` while foundation-emails-template uses the other setting.

**Comment by DanielRuf** [comment]
This is a bug in the old versions of html-minifier.

We use 1.x and this is the result with 4.0.0:
https://repl.it/@DanielRuf/PalegreenPungentMultiprocessing

With 1.5.0:
https://repl.it/@DanielRuf/IdealHonoredForm

This will be fixed when we update gulp-htmlmin and https://github.com/foundation/foundation-emails-template/pull/60.

foundation-emails contains `collapseWhitespace: false` while foundation-emails-template uses the other setting.

**Comment by DanielRuf** [comment]
Closing this one here so we can track it in the template in the PR.
