### ISSUE TITLE
SuperMail - field [align=center] does not exist 

### ISSUE THREAD

**Issue by mortennh** [foundation/foundation-emails#600]
**How can we reproduce this bug?**
Open the built html in SuperMailer (10.10) and try to send it. 

**Write out the HTML (or Inky code) that causes the issue.**
`table.menu[align=center]`

**What did you expect to happen?**
The SuperMailer-App opens the html and lets you send the newsletter

**What happened instead?**
SuperMailer tells me (in German), that the field [align=center] does not exist and won't let me open the file. 
![supermailer-error](https://cloud.githubusercontent.com/assets/11868007/18956539/08defa76-865c-11e6-86ce-c190eaa15193.png)

**What email clients does this happen in?**
In SuperMailer

**Additonal notes**
I solved the problem by removing the `table.menu[align=center]` from the built html. I was curious and thought someone forgot the exclamation marks but taking a look at the _menu.scss showed me that they are set correctly

**Comment by rafibomb** [comment]
`align="center"` is necessary for centering in Outlook 2007,10,13. In the SCSS file it has the quotes `[align="center"]` so not sure why SuperMail shows them without. Not seeing any issues with the underlying code so we'll close this here. Let us know if you find another workaround for it!
