### ISSUE TITLE
Would you be interested in a chart components?

### ISSUE THREAD

**Issue by rbaumier** [foundation/foundation-emails#601]
Hello everyone!

It would be awesome to have image charts in our emails, I discovered [Image-charts](https://image-charts.com/) that does perfectly that and would like to implement it as a component into foundation-emails, would you accept a PR for it?

**Comment by cossssmin** [comment]
Hey :)

Why would a component be needed, when all you have to do is set the `src=""` attribute of an image to the URL format they provide you with?

**Comment by cossssmin** [comment]
Also, you didn't exactly _discover_ Image-charts, did you?

> Please read these Terms of Service (the "Terms") carefully. These Terms govern your access to and use of the website located at image-charts.com (the "Site") and the hosted products and services available via the Site, including **the proprietary software "Image Charts", that are offered by Redsmin Inc. ("Redsmin")**. The Site and the hosted products and services are referred to collectively throughout these Terms as the "Services".

![image](https://cloud.githubusercontent.com/assets/1656595/18991050/d708ff42-871e-11e6-83f2-d42b121227a4.png)

Promoting like that kinda sucks, don't you think?

**Comment by rbaumier** [comment]
I **used to** work for Redsmin, I don't anymore, nor do I gain anything in promoting image-charts.

A friend there showed me the product and I simply wanted to help because I found it cool.

**Comment by davehoran** [comment]
Romain, https://image-charts.com/ looks pretty good. You could probably
implement this with a simple Panini helper function.

**Comment by DanielRuf** [comment]
I would close this as this looks like some advertisement and can be implemented in custom projects. Proprietary solutions make not much sense here.
