### ISSUE TITLE
Suggestion for responsive Gmail

### ISSUE THREAD

**Issue by allthosehumans** [foundation/foundation-emails#608]
After reading this in your compatibility table:

"Gmail app for Android: Works - does not recognize media queries so it will render large breakpoint."

I'd like to point you to a post with very detailed instructions on how responsive can be achieved on mobile Gmail. You may be able to re-work the grid a bit according to these tips. I'm sure a lot of people would appreciate this improvement.

https://julie.io/writing/gmail-first-strategy-for-responsive-emails/

**Comment by cossssmin** [comment]
Hi,

That hacky technique will not be needed, now that Gmail introduced support for `@media` queries. Also, the grid as it is now works great in Outlook, without those conditional comments.

Once the responsive support rollout is completed in Gmail, the docs should be updated to reflect that. I, for one, am checking daily and will test right away when I'll notice responsive support on my devices and in Email on Acid (no updates as of today).

**Comment by allthosehumans** [comment]
I just read the great news about future Gmail support for media queries. I was about to comment about that but you beat me to it! Hopefully it won't disappoint.
