### ISSUE TITLE
Gmail App - Stack/Responsive/Shrinking to fit screen

### ISSUE THREAD

**Issue by york-xtrem** [foundation/foundation-emails#617]
I thought the v2.2 solves this problem but I still happening.

https://github.com/zurb/foundation-emails/issues/122

Index.html
[index.zip](https://github.com/zurb/foundation-emails/files/555570/index.zip)

App.scss
[app.zip](https://github.com/zurb/foundation-emails/files/555574/app.zip)

<img src="https://cloud.githubusercontent.com/assets/14836838/19765114/fbe30f14-9c46-11e6-9d73-2470f4fb37c7.png" alt="" height="500px">

**Comment by rafibomb** [comment]
@york-xtrem  If you are looking for Gmail App responsive, the [ZURB Template has been updated](https://github.com/zurb/foundation-emails-template/tree/uncss) to have this and is a feature that is packaged up in the next release (2.2). Sound likes a different question than #122. 

You can grab that branch on GitHub and test it there.

BTW: Here's a list of Gmail App versions that support responsive: https://litmus.com/blog/gmail-to-support-responsive-email-design

**Comment by rafibomb** [comment]
We'll close this as it is in the emails template now. Thanks!
