### ISSUE TITLE
4 column layout with images in each column breaks outlook, inbox for ff, & yahoo ff

### ISSUE THREAD

**Issue by buzzguy** [foundation/foundation-emails#619]
I tested slinky with a 4 column large and 2 column small grid layout which breaks outlook 2010, outlook 2013, ff yahoo, & ff google inbox. 
```
 <row>
    <columns small="6" large="3">
          <a href="#">
            <img src="https://placeholdit.imgix.net/~text?txtsize=33&txt=540×540&w=540&h=540">
          </a>
        <spacer size="10"></spacer>

          <a href="#" class="product-item-link">PROD1NAME, $PROD1PRICE</a>

    </columns>
    <columns small="6" large="3">
          <a href="#">
            <img src="https://placeholdit.imgix.net/~text?txtsize=33&txt=540×540&w=540&h=540">
          </a>
        <spacer size="10"></spacer>

          <a href="#" class="product-item-link">PROD1NAME, $PROD1PRICE</a>

    </columns>
    <columns small="6" large="3">
          <a href="#">
            <img src="https://placeholdit.imgix.net/~text?txtsize=33&txt=540×540&w=540&h=540">
          </a>
        <spacer size="10"></spacer>

          <a href="#" class="product-item-link">PROD1NAME, $PROD1PRICE</a>

    </columns>
    <columns small="6" large="3">
          <a href="#">
            <img src="https://placeholdit.imgix.net/~text?txtsize=33&txt=540×540&w=540&h=540">
          </a>
        <spacer size="10"></spacer>

          <a href="#" class="product-item-link">PROD1NAME, $PROD1PRICE</a>

    </columns>
  </row>
```
![ffgoogleinbox-vertical-allowed-1366](https://cloud.githubusercontent.com/assets/1154836/19862512/05dbbd36-9f67-11e6-9c68-dad99c4b14b9.png)
![ffyahoo-vertical-allowed-1366](https://cloud.githubusercontent.com/assets/1154836/19862514/05dc83ba-9f67-11e6-828b-745fedc10b1d.png)
![ol2010-vertical-allowed-1366](https://cloud.githubusercontent.com/assets/1154836/19862513/05dc1cc2-9f67-11e6-8d75-8bbe43347785.png)
![ol2013-vertical-allowed-1366](https://cloud.githubusercontent.com/assets/1154836/19862511/05db7eca-9f67-11e6-9f21-b68a39e35f86.png)

**Comment by rafibomb** [comment]
A good rule of thumb is to add width and height attributes to your images and constrain them to their natural width in the grid. I inspected to find the image width and set them in the html

```
<img height="325" width="325" src="https://placeholdit.imgix.net/~text?txtsize=33&txt=540×540&w=540&h=540">
```

**Comment by buzzguy** [comment]
@rafibomb thanks for taking a look! I set width and heights to the images, but still came across similar issues. Here is my test codepen:
http://codepen.io/buzzguy/pen/NRZZEo/
setting width and height to 325, appears to scale the images too tall on gmail and ipad and breaks outlook etc:
<img width="744" alt="screenshot 2016-11-01 09 59 10" src="https://cloud.githubusercontent.com/assets/1154836/19892210/355d62f4-a01a-11e6-9e39-ef92d78bad45.png">

I did a few different tests with variable outcomes. setting only width to 325 fixed the scaling issue, but still breaks the layout in the same browsers

<img width="657" alt="screenshot 2016-11-01 10 08 48" src="https://cloud.githubusercontent.com/assets/1154836/19892465/633e6cee-a01b-11e6-88ea-b86818f9de1b.png">

and then, you were saying they should be set in it's natural width in the grid which would be 125 x 125, which still broke in outlook. 
<img width="537" alt="screenshot 2016-11-01 10 12 06" src="https://cloud.githubusercontent.com/assets/1154836/19892542/b8231c1e-a01b-11e6-9ce6-7898ea9b9699.png">
<img width="538" alt="screenshot 2016-11-01 10 12 02" src="https://cloud.githubusercontent.com/assets/1154836/19892545/be5807de-a01b-11e6-8940-360f00de22ff.png">
