### ISSUE TITLE
Inline tool bug.

### ISSUE THREAD

**Issue by surbhioberoi** [foundation/foundation-emails#622]
When I use your inline tool, it changes '&nbsp' to '&amp;nbsp' on copying from clipboard. Before finalising, this has to be corrected for all '&nbsp' errors. 
![screen shot 2016-11-07 at 1 37 22 pm](https://cloud.githubusercontent.com/assets/16307066/20050501/b5bbf896-a4ef-11e6-9669-3ad38dae09f5.png)

**Comment by rafibomb** [comment]
Looks like a duplicate issue. We'll close this in favor of https://github.com/zurb/foundation-emails/issues/305
