### ISSUE TITLE
Column widths not equal

### ISSUE THREAD

**Issue by benwakeford** [foundation/foundation-emails#625]
**How can we reproduce this bug?**

```html
<container>
  <row class="collapse">
    <columns small="4" large="4"><img src="http://placehold.it/196/ff0000/fff" width="196"></columns>
    <columns small="4" large="4"><img src="http://placehold.it/196/008000/fff" width="196"></columns>
    <columns small="4" large="4"><img src="http://placehold.it/196/0000ff/fff" width="196"></columns>
  </row>
</container>
```

**What did you expect to happen?**
The columns should span the width of the container equally.

**What happened instead?**
![image](https://cloud.githubusercontent.com/assets/2563376/20063008/9eeb4ed8-a4fd-11e6-9534-4fd07918fccd.png)

The container is 588, which is divisible by 196 into 3 columns, yet I'm seeing the above with column widths of: 200, 187, 201.

The problem only manifests on large size. If you reduce the browser down to small size and then proportions become equal. 

**What email clients does this happen in?**
Chrome Browser

Any thoughts?

**Comment by cossssmin** [comment]
Those columns also have gutters, I suggest you check the computed dimensions of each column `<th>` in your dev tools in Chrome. Something almost certainly doesn't add up (specifically, it might add up to more than your container's width).

**Comment by benwakeford** [comment]
Thanks for the feedback @hellocosmin. The columns are set to collapse though, so they shouldn't have gutters, surely?

The problem seems to lay with the first and last classes on the `<th>`s; dev tools readout:

```
.collapse th.large-4.first { width: 211px; }
.collapse th.large-4{ width: 196px; }
.collapse th.large-4.last { width: 211px; }
```

Which adds up to 618px, larger than the 588px container. Padding is zero on all.

Why would the first and last be set to 211px when they should be 196px, as they're set to collapse?

Is there something I'm not understanding about `.collapse`?

**Comment by staruc** [comment]
What's your $global-gutter variable set to (_settings.scss)? I think what you might be seeing is the automatic .first and .last classes affecting what's supposed to be "gutter-less" columns. I just ran into this issue.

If anything other than 0px, try setting it to 0px; default's 16px.
