### ISSUE TITLE
Output "Final Email HTML" is a mess

### ISSUE THREAD

**Issue by bbbenji** [foundation/foundation-emails#634]
**How can we reproduce this bug?**

Paste the following HTML and CSS into http://foundation.zurb.com/emails/inliner-v2.html

HTML: https://gist.github.com/bbbenji/37ac835de54423463cb601c8e15c6630
CSS: https://gist.github.com/bbbenji/7b64748f1d7c8146c1c82bec23eff0c8

**What did you expect to happen?**

OUTPUT: https://gist.github.com/bbbenji/949b25436d7e52740c2fb073a06e83e4

**What happened instead?**

OUTPUT: https://gist.github.com/bbbenji/189b22b9c74918dda40c0cd61daa4666
SCREENSHOT: https://cloud.githubusercontent.com/assets/1678118/20481850/a1e82f88-afe9-11e6-8100-7477b519cad8.png

**Comment by cossssmin** [comment]
The inliner might be choking on your custom src/href `[iai:]` placeholders, have you tried without them? Also, you have an empty `style` tag before your `doctype`

**Comment by bbbenji** [comment]
@hellocosmin I have removed the custom src/href placeholders as well as the empty style tag, issue still exists.

`&nbsp;` seem to have appeared among other issues.

SCREENSHOT: https://cloud.githubusercontent.com/assets/1678118/20485480/f5bde28a-affb-11e6-871a-d1b8a45f73e1.png

**Comment by cossssmin** [comment]
Looking at the link you shared (https://gist.github.com/bbbenji/37ac835de54423463cb601c8e15c6630), I see other issues with a `span` and anchor tag inside the doctype and html elements...

Is that code in the link above, the final output from the inliner? If yes, looks like the inliner has several issues:

1. `&nbsp;` gets transformed to `&amp;nbsp;` (I think this is an old bug)
2. `href` attribute src is populated with a full anchor, i.e. `<a href="http://example.com">` becomes `<a href="<a href="http://example.com">">`

Let's wait for someone from ZURB to chime in...

**Comment by bbbenji** [comment]
@hellocosmin Regarding the `span` and `a` tags in the doctype, that was an incorrect paste on my part. I have updated the gist to reflect the correct code. However, this is not related to the issue I am experiencing. Will wait for ZURB.

**Comment by cossssmin** [comment]
If those span and a tags in the doctype were not the output of the inliner, you should check your HTML, because you have many anchors like that. Check all of it, look for any unclosed tags and attributes too.

**Comment by bbbenji** [comment]
@hellocosmin the `span` and `a` tags are the output of the inliner. They do not exist in the input file. My last comment was in regards to an incorrect paste of the input HTML which I had corrected already.

No unclosed tags unless you call `<hr>` and `<img>` unclosed.

**Comment by bbbenji** [comment]
Ok, I have just realised the problem here! The issue occurs when clicking the "Copy to clipboard" button.

When manually selecting the output with the cursor and copy pasting, it works just fine, although when using the auto copy button, the code pasted is incorrect.

**Comment by cossssmin** [comment]
Glad to hear you found the issue.

I think it would help the guys if you could change the title of this issue to reflect what the actual problem is :)

**Comment by bbbenji** [comment]
See: https://github.com/zurb/foundation-emails/issues/635
