### ISSUE TITLE
Error while inlining for production

### ISSUE THREAD

**Issue by peacepostman** [foundation/foundation-emails#637]
Hello,

I have created a new project with ink mail. All is good while running **npm start** but when I try to run **npm run build**, build fail 😢 

Previous projects were running fine. Here are the version used in this project :

- MAC OS El Capitan 10.11.6
- Node 5.1.1
- NPM 3.7.2
- Foundation CLI 2.1.0
- Foundation Email 2.2.1

And the log from NPM
[npm-debug.txt](https://github.com/zurb/foundation-emails/files/605864/npm-debug.txt)

Bonus track, debug from terminal:
```
'sass' errored after 5.03 s
Error in plugin 'gulp-uncss'
Message:
    Unexpected EOF
Details:
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
```
Any help would be appreciated :D

**Comment by peacepostman** [comment]
*Update*

When commenting this code : 
````
    .pipe($.if(PRODUCTION, $.uncss(
      {
        html: ['dist/**/*.html']
      })))
````

Everything works fine :/

**Comment by josefarrugia** [comment]
@peacepostman that worked for me. Any idea why this is causing the build to fail?

**Comment by nitrokevin** [comment]
I'm getting a similar problem but mine is saying:
`[11:36:51] 'sass' errored after 18 s
[11:36:51] Error in plugin 'gulp-uncss'
Message:
    _RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.

Details:
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
`

**Comment by josefarrugia** [comment]
@nitrokevin have you tried updating your version of node? Once done, delete your node_modules directory and do a npm install.

**Comment by nitrokevin** [comment]
Yep I updated and started from scratch but the problem was the same

**Comment by zacwasielewski** [comment]
I'm also seeing the same error as the original poster. (Starting from scratch with a new project via `foundation new --framework  emails` just a few hours ago.)

**Comment by mrwade** [comment]
I had the same issue and was able to fix it. It ended up being a strange whitespace character in my html. I had to keep deleting portions of my html to narrow it down to a specific line.

**Comment by davehoran** [comment]
@mrwade Was this in the HTML itself, like with a specific tag, or was it something in an scss file somewhere?

**Comment by mrwade** [comment]
It was in some text (in the html) that I had copied and pasted in from somewhere else. After hunting down the weird whitespace character (not visible in my editor) and removing it, the build was able to complete successfully.

**Comment by Jon-Westbrook** [comment]
Yes to weird characters. Over here we've increasingly been finding weird characters coming in when copying from Sketch or Zeplin or Google Docs or Word. After a lot of pain, I finally found StringEncode for Sublime: https://packagecontrol.io/packages/StringEncode

This package allows you to highlight a block of text, then hit "Safe HTML Entitize" - it will catch any special characters and convert them to their HTML code. 

It is an extremely useful package for finding "weird characters" that are breaking your build process, or showing up funny on certain OS / Browser combinations.

**Comment by michalchovanak** [comment]
I can confirm, that this problem was caused by weird characters (unicode \2028) in my html files.

**Comment by peacepostman** [comment]
I can confirm it too, in my configuration the weird character was caused by copy/paste from sketch.

**Comment by renatocarvalho** [comment]
In my case, the issue seems to be caused by the version of node that I'm using. 

Doing some more tests over here. `node -v v8.6.0`

```0 info it worked if it ends with ok
1 verbose cli [ '/Users/renatocarvalho/.nvm/versions/node/v8.6.0/bin/node',
1 verbose cli   '/Users/renatocarvalho/.nvm/versions/node/v8.6.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.3.0
3 info using node@v8.6.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle foundation-emails-template@1.0.0~prebuild: foundation-emails-template@1.0.0
6 info lifecycle foundation-emails-template@1.0.0~build: foundation-emails-template@1.0.0
7 verbose lifecycle foundation-emails-template@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle foundation-emails-template@1.0.0~build: PATH: /Users/renatocarvalho/.nvm/versions/node/v8.6.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/renatocarvalho/Development/evino-mailing/node_modules/.bin:/Users/renatocarvalho/.rvm/gems/ruby-2.4.2/bin:/Users/renatocarvalho/.rvm/gems/ruby-2.4.2@global/bin:/Users/renatocarvalho/.rvm/rubies/ruby-2.4.2/bin:/Users/renatocarvalho/.nvm/versions/node/v8.6.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/renatocarvalho/.rvm/bin
9 verbose lifecycle foundation-emails-template@1.0.0~build: CWD: /Users/renatocarvalho/Development/evino-mailing
10 silly lifecycle foundation-emails-template@1.0.0~build: Args: [ '-c', 'gulp --production' ]
11 silly lifecycle foundation-emails-template@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle foundation-emails-template@1.0.0~build: Failed to exec build script
13 verbose stack Error: foundation-emails-template@1.0.0 build: `gulp --production`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/renatocarvalho/.nvm/versions/node/v8.6.0/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/Users/renatocarvalho/.nvm/versions/node/v8.6.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid foundation-emails-template@1.0.0
15 verbose cwd /Users/renatocarvalho/Development/evino-mailing
16 verbose Darwin 17.0.0
17 verbose argv "/Users/renatocarvalho/.nvm/versions/node/v8.6.0/bin/node" "/Users/renatocarvalho/.nvm/versions/node/v8.6.0/bin/npm" "run" "build"
18 verbose node v8.6.0
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error foundation-emails-template@1.0.0 build: `gulp --production`
22 error Exit status 1
23 error Failed at the foundation-emails-template@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by davehoran** [comment]
Do you have a virtual machine to try an older version of node?

**Comment by Pamps** [comment]
I used this [online tool](https://pteo.paranoiaworks.mobi/diacriticsremover/) to fix my non-ascii characters.

**Comment by simonda86** [comment]
Thanks @Pamps that's a really useful tool finding the invisible non-ascii characters!

**Comment by Andrew-Dyachenko** [comment]
> I used this [online tool](https://pteo.paranoiaworks.mobi/diacriticsremover/) to fix my non-ascii characters.

![img-2019-05-20-19-02-51](https://user-images.githubusercontent.com/10127643/58035662-ee1cf580-7b31-11e9-848f-991611cde211.png)
I've just found and removed all that symbols in my HTML code.
And error has solved

**Comment by Jon-Westbrook** [comment]
If you're using VS Code, and running into bad character issues, I recommend using the extension "Highlight Bad Chars": https://marketplace.visualstudio.com/items?itemName=wengerk.highlight-bad-chars . 

I configured this extension to always highlight bad characters with an obnoxious pink color that is impossible to miss. Works great, you see them right away, and can convert them to an HTML equivalent.

**Comment by Andrew-Dyachenko** [comment]
Yes, I'm. Thank U for lifehack. Installed it now.

**Comment by sbuteryd** [comment]
const clean = require('gulp-clean');

function mergeCss(){
    folders.map((element) => {
        return src(
            [
                `template/${element}/assets/**/css.css`,
            `template/${element}/assets/**/index.css`,
            `template/${element}/assets/**/cart.css`,
             `template/${element}/assets/**/webfont.css`,
            'template/**/lazyloaded.css'])
            .pipe(concatCss("/assets/css.css"))
            .pipe(print())
            .pipe(dest(`out/${element}`));
    })
}

The merged css error is as follows
 domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false

css annotation problem （ /*color: #fff*/;）
.footer_a h4 { margin-top: 0px; font-weight: 400; font-size: 14px; text-transform: uppercase; /*color: #fff*/; margin-bottom: 30px; }

Solve the problem Remove css comments
.footer_a h4 { margin-top: 0px; font-weight: 400; font-size: 14px; text-transform: uppercase;  color: #fff margin-bottom: 30px; }

**Comment by DanielRuf** [comment]
Hi @sbuteryd,

this is about another issue.
