### ISSUE TITLE
Unhandled rejection Error at build

### ISSUE THREAD

**Issue by fferrari1** [foundation/foundation-emails#639]
** At Run npm run build unhandled rejection error **

I am working with the Foundation emails and everything is going well
A few days ago this message arrived and I have no idea what it is.

The templates look good without any errors, but when we build the final solution, the inliner shows this error.

![error](https://cloud.githubusercontent.com/assets/20564276/20528161/dac1d64a-b0a9-11e6-9ea8-2d8ef4040b93.jpg)

If you can help me to understand what happens, I would appreciate it a lot

**Comment by cossssmin** [comment]
Looks like it's something the inliner can't... inline. Do you have a Google Fonts stylesheet in your `<head>`, by any chance? If not, take a look at anything that's being pulled from a remote source - the inliner might be choking on something like that.

I know the inliner was always failing with a Google Fonts `<link>` tag for me, but I was working behind a proxy - so there's that, too.

**Comment by fferrari1** [comment]
I am not using google fonts.
I am using another service for the fonts.
One of them is to an "http" url and the other is to an "https" url.
"http" works fine and compiles without problems but "https" dont.

Thanks for your help
I appreciate it a lot
