### ISSUE TITLE
Inliner throws ETIMEDOUT error

### ISSUE THREAD

**Issue by justintemps** [foundation/foundation-emails#645]
**How can we reproduce this bug?**
Clone [this repository](https://github.com/justintemps/foundation-build-example), install dependencies and execute `npm run build`.

**What's the error?**
```
[17:11:47] Starting 'inline'...
Unhandled rejection Error: connect ETIMEDOUT 172.217.21.42:443
    at Object.exports._errnoException (util.js:873:11)
    at exports._exceptionWithHostPort (util.js:896:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)
[17:12:09] The following tasks did not complete: default, build, inline
[17:12:09] Did you forget to signal async completion?
```

**What did you expect to happen?**
I expect Foundation to build a production-ready version of the template

**What happened instead?**
It threw the above error after `Starting 'inline'`

**Development environment**
I only encounter this issue at work using Windows 7 behind our corporate proxy. However, I have both npm and git configured for the proxy. Also, I've used Foundation in this environment before without any problems. I was unable to replicate this issue at home using OSX.

**Comment by justintemps** [comment]
Update, I only encounter this error at work using Windows 7...(I know, I know).

**Comment by rafibomb** [comment]
Hmm, it's odd one to be Windows only. Have you seen any other reports of this on GitHub you can link here?

**Comment by justintemps** [comment]
@rafibomb Haven't been able to find the exact same error, no. I thought [this topic](http://foundation.zurb.com/forum/posts/49060-not-able-to-npm-start-new-stack-project) in the Forum might have been related but suspect it's just an incomplete install.

**Comment by justintemps** [comment]
Turned out the problem was trying to include a google font in layouts/default.html like this:

`<link href="https://fonts.googleapis.com/css?family=Karla" rel="stylesheet">`

The inliner was trying to follow the link to google, hence the timeout connection error.

Simply including the font in the css fixed the error. It now builds fine. 

`@import url('https://fonts.googleapis.com/css?family=Karla');`

Head slap.
