### ISSUE TITLE
Inliner moves <style> inside <body> tag

### ISSUE THREAD

**Issue by stephencrowther** [foundation/foundation-emails#655]
I believe this is now not necessary and in fact causes problems with gmail - gmail will not see the <style> tag (and its contents) unless it is in the `<head>`

**Comment by DanielRuf** [comment]
`<style>` can be in the `<body>`, this is allowed.

See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style

> The <style> element can be included inside the <head> or <body> of the document, and the styles will still be applied, however it is recommended that you include your styles in the <head> for organizational purposes — it is a lot better to separate your content from your presentation as much as possible. Even better, put your styles in external stylesheets and apply them using <link> elements.

The setup of foundation-emails puts `<style>` into `<head>`, the inliner inlines it directly.

As this issue does not contain any reproducible tests case I am going to close it.
