### ISSUE TITLE
[Getting Started with CSS] it doesn't seem to support RTL

### ISSUE THREAD

**Issue by hadifarnoud** [foundation/foundation-emails#663]
There is no support for RTL in this framework. Am I missing something? It would be better to have native support for RTL.

**Comment by ronakjethwa** [comment]
+1 on this. Is there a way foundation-emails supports RTL?

**Comment by DanielRuf** [comment]
Hi, we would welcome a PR which adds support for RTL. This would be very great.

**Comment by DanielRuf** [comment]
Hi, this would be very great.
We would welcome a PR which adds support for RTL.

**Comment by vlad-ghita** [comment]
Hey. This feature would be great.

**Comment by hadifarnoud** [comment]
just use mjml instead
