### ISSUE TITLE
Remove link to all css file after inlining styles, not just app.css

### ISSUE THREAD

**Issue by klihelp** [foundation/foundation-emails#672]
Remove link to **all** css file after inlining styles, _not just app.css_

This is a comment on https://github.com/zurb/foundation-emails-template/pull/23
mention:  https://github.com/zurb/foundation-emails/issues/544

**Comment by diomededavid** [comment]
You can do that by 
changing the **removeLinkTags: true** setting in your gulpfile its at around line 122. 

` var pipe = lazypipe()
    .pipe($.inlineCss, {
      applyStyleTags: false,
      removeStyleTags: true,
      preserveMediaQueries: true,
      removeLinkTags: true
    })
`
