### ISSUE TITLE
Non-breaking space incorrectly inlined

### ISSUE THREAD

**Issue by andrewchilcott** [foundation/foundation-emails#675]
When including `&nbsp;` in html that is input into the inliner, the result is `&amp;nbsp;`

**Comment by captiva-megan** [comment]
This also seems to happen with ampersands. `&amp;` becomes `&amp;amp;`

**Comment by DanielRuf** [comment]
Duplicate of https://github.com/zurb/foundation-emails/issues/841, can be closed.
