### ISSUE TITLE
<hr> tables don't obey $hr-width

### ISSUE THREAD

**Issue by jsit** [foundation/foundation-emails#678]
**How can we reproduce this bug?**

Set `$hr-width` to something smaller than `$global-width`; say, `200px`.

**What did you expect to happen?**

The `<hr>` table should be the width specified, and centered

**What happened instead?**

The `<hr>` table is the full width of the `<container>`.

The interim `<hr>` code I'm using:

```html
<table class="hr">
  <tr>
    <td>&nbsp;</td>
  </tr>
</table>
```

**Comment by DanielRuf** [comment]
`<h-line>` element should be used here.
