### ISSUE TITLE
&nbsp; are not respected in Inky 

### ISSUE THREAD

**Issue by tdhartwick** [foundation/foundation-emails#687]
**How can we reproduce this bug?**
Write something like this:
```
<div class="preheader">
                             Welcome! Save 10% on your next order.&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;
                        </div>
```

**What did you expect to happen?**
The `&nbsp;` is respected, and unscathed.

**What happened instead?**
Got something like this:
```
<div class="preheader">
                                         Welcome! Save 10% on your next order.&#x200C;&#xA0;&#x200C;&#xA0;&#x200C;&#xA0;&#x200C;&#xA0;&#x200C;&#xA0;&#x200C;&#xA0;&#x200C;&#xA0;&#x200C;&#xA0;&#x200C;&#xA0;&#x200C;&#xA0;&#x200C;&#xA0;&#x200C;&#xA0;
                                    </div>

```
**What email clients does this happen in?**
All

**Comment by davehoran** [comment]
@tdhartwick Is there regular Inky code around this <div>? I have successfully used &nbsp; in many instances, e.g. padding some button content text, with no problem.

**Comment by tdhartwick** [comment]
hmmm, had a conversation with someone that was running into this issue, but admittedly I still need to verify! Will report back in a few :)

**Comment by warofthesun** [comment]
@davehoran this is how I'm seeing it happen at the moment,

```
<div class="preheader">
Welcome! Save 10% on your next order.&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;
</div>
```

gets turned into 

```
<div class="preheader">
Welcome! Save 10% on your next order.&#x200C;&#xA0;&#x200C;&#xA0;&#x200C;&#xA0;&#x200C;&#xA0;&#x200C;&#xA0;&#x200C;&#xA0;&#x200C;&#xA0;&#x200C;&#xA0;&#x200C;&#xA0;&#x200C;&#xA0;&#x200C;&#xA0;&#x200C;&#xA0;
</div>
```

This is true for any entity like `&nbsp` or `&copy;` etc.

**Comment by davehoran** [comment]
@warofthesun  Just off hand, what font are you using in your email? Does it support the half-space character (&zwnj;)? Also, like I asked Tim, what code do you have above/below the <div> you are showing here?

**Comment by tdhartwick** [comment]
:/ hm, I wasn't able to replicate it either...

**Comment by davehoran** [comment]
@tdhartwick Yeah, I'm wondering of the inliner is tripping over a character set issue or something?

**Comment by tdhartwick** [comment]
Hmm, going to close this down for now @warofthesun. Thanks for chiming in @davehoran! Yeah, maybe it's hanging on something else in the HTML. Going to see if I can't get to the bottom of this though :)
