### ISSUE TITLE
Compiled index.html is not gathering all CSS and loosing "responsiveness"

### ISSUE THREAD

**Issue by valbap** [foundation/foundation-emails#690]
**How can we reproduce this bug?**
Not sure. Here what I did:
1 - Followed all the instructions to install the SASS version here (http://foundation.zurb.com/emails/docs/sass-guide.html)

2 - Then realized that this command wasn't enough (sudo npm start) and as I was needing it to inline my code automatically I changed to (sudo npm run build).

3 - Started working on src/pages/index.html. Have one partial.

4 - No errors on terminal. Everything is well compiled. Uploaded images to my server and changed the path on default.html. Opened index.html and everything was ok. Made a test with putsmail and responsiveness was broken. Nothing was responding.

5 - Moved my compiled and responding index.html to desktop, opened and responsiveness were broken.

6 - Conclusion: the process of inlining is leaving some of the files out as as soon as I drop the css folder into my desktop it starts working again.

---------------------

_settings weren't changed.
_template changed just a color.

**Here is my index.html**

```
<spacer size="30"></spacer>
<container>
    <row>
        <columns small="6">
            <center><img src="https://****.com/logo1.png" alt=""></center>
        </columns>
        <columns small="6">
            <center><img src="https://****.com/logo2.png" alt=""></center>
        </columns>
    </row>
    <row>
        <columns>
            <h2 class="text-center">TEXT</h2>
            <p class="text-center">TEXT</p>
        </columns>
    </row>
    <row>
        <columns>
            <table class="callout">
                <tr>
                    <th class="callout-inner primary">
                        <table class="row">
                            <tbody>
                                <tr>
                                    <th class="small-12 large-12 columns first last">
                                        <spacer size="20"></spacer>
                                        <table>
                                            <tr>
                                                <th>
                                                    <p class="text-center cupom">TEXT</p>
                                                </th>
                                                <th class="expander"></th>
                                            </tr>
                                        </table>
                                    </th>
                                </tr>
                            </tbody>
                        </table>
                    </th>
                    <th class="expander"></th>
                </tr>
            </table>
        </columns>
    </row>
    <row>
        <columns>
            <ul>
                <li>TEXT</li>
                <li>TEXT</li>
            </ul>
            <spacer size="10"></spacer>
        </columns>
    </row>
    <row>
        <columns>
            <table class="callout">
                <tr>
                    <th class="callout-inner success">
                        <p>TEXT</p>
                    </th>
                    <th class="expander"></th>
                </tr>
            </table>
            {{>calltoaction}}
        </columns>
    </row>
    <row>
        <columns>
            <p>TEXT
            </p>
        </columns>
    </row>
</container>
```

-----------------

**Here is my app.scss**

```
@import 'settings';
@import 'foundation-emails';
@import 'template/template';

*{font-family: 'Roboto', sans-serif;}
h2{font-family: 'Roboto', sans-serif;font-size:24px;font-weight: 400;font-style: italic;} 
p.cupom{font-family: 'Roboto', sans-serif;font-weight: 700;font-size:40px;line-height: 50px;color:$primary-color;}
.success p{color:$secondary-color}
p, li{line-height: 26px;font-size:16px;}
ul{margin:0;padding:0;list-style-position: outside;padding-left:20px; }
```

---------

Here is my default.html

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
  <head>
    <link rel="stylesheet" type="text/css" href="{{root}}css/app.css">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width">
    <title>{{subject}}</title>
  <style>
@import url('https://fonts.googleapis.com/css?family=Roboto:400,400i,700');
</style>
  </head>
  <body>
    <span class="preheader">{{description}}</span>
    <table class="body">
      <tr>
        <td class="center" align="center" valign="top">
          <center>
            {{> body}}
          </center>
        </td>
      </tr>
    </table>
    <!-- prevent Gmail on iOS font size manipulation -->
   <div style="display:none; white-space:nowrap; font:15px courier; line-height:0;"> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </div>
  </body>
</html>

```

**Comment by davehoran** [comment]
Off chance, try changing the @import section in default.html to a regular <link> tag to pull in the font. I'm also using web fonts, and have used the standard <link> tag without problems. This is the only thing I can see that might cause the issue. It could be fine, but it's something I haven't done in files I have that are known to be working.

**Comment by valbap** [comment]
Hello Dave,
no luck with that.
Tried

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="{{root}}css/app.css">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,400i,700" rel="stylesheet">
    <title>{{subject}}</title>
</head>
<body>
    <span class="preheader">{{description}}</span>
    <table class="body">
        <tr>
            <td class="center" align="center" valign="top">
                <center>
                    {{> body}}
                </center>
            </td>
        </tr>
    </table>
    <!-- prevent Gmail on iOS font size manipulation -->
    <div style="display:none; white-space:nowrap; font:15px courier; line-height:0;"> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </div>
</body>
</html>
```

But same behaviour.
Let me paste the compiled HTML here and maybe you can give me a clue of what piece of css should I copy/paste from somewhere in order to make this single piece to work:

`<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en" style="background:#fff!important"><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta name="viewport" content="width=device-width"><link href="https://fonts.googleapis.com/css?family=Roboto:400,400i,700" rel="stylesheet"><title></title></head><body style="-moz-box-sizing:border-box;-ms-text-size-adjust:100%;-webkit-box-sizing:border-box;-webkit-text-size-adjust:100%;Margin:0;background:#fff!important;box-sizing:border-box;color:#0a0a0a;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:400;line-height:1.3;margin:0;min-width:100%;padding:0;text-align:left;width:100%!important"><span class="preheader" style="color:#f3f3f3;display:none!important;font-family:Roboto,sans-serif;font-size:1px;line-height:1px;max-height:0;max-width:0;mso-hide:all!important;opacity:0;overflow:hidden;visibility:hidden"></span><table class="body" style="Margin:0;background:#fff!important;border-collapse:collapse;border-spacing:0;color:#0a0a0a;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:400;height:100%;line-height:1.3;margin:0;padding:0;text-align:left;vertical-align:top;width:100%"><tr style="padding:0;text-align:left;vertical-align:top"><td class="center" align="center" valign="top" style="-moz-hyphens:auto;-webkit-hyphens:auto;Margin:0;border-collapse:collapse!important;color:#0a0a0a;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:400;hyphens:auto;line-height:1.3;margin:0;padding:0;text-align:left;vertical-align:top;word-wrap:break-word"><center data-parsed="" style="min-width:580px;width:100%"><table class="spacer float-center" style="Margin:0 auto;border-collapse:collapse;border-spacing:0;float:none;margin:0 auto;padding:0;text-align:center;vertical-align:top;width:100%"><tbody><tr style="padding:0;text-align:left;vertical-align:top"><td height="30px" style="-moz-hyphens:auto;-webkit-hyphens:auto;Margin:0;border-collapse:collapse!important;color:#0a0a0a;font-family:Helvetica,Arial,sans-serif;font-size:30px;font-weight:400;hyphens:auto;line-height:30px;margin:0;mso-line-height-rule:exactly;padding:0;text-align:left;vertical-align:top;word-wrap:break-word">&#xA0;</td></tr></tbody></table><table align="center" class="container float-center" style="Margin:0 auto;background:#fefefe;border-collapse:collapse;border-spacing:0;float:none;margin:0 auto;padding:0;text-align:center;vertical-align:top;width:580px"><tbody><tr style="padding:0;text-align:left;vertical-align:top"><td style="-moz-hyphens:auto;-webkit-hyphens:auto;Margin:0;border-collapse:collapse!important;color:#0a0a0a;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:400;hyphens:auto;line-height:1.3;margin:0;padding:0;text-align:left;vertical-align:top;word-wrap:break-word"><table class="row" style="border-collapse:collapse;border-spacing:0;display:table;padding:0;position:relative;text-align:left;vertical-align:top;width:100%"><tbody><tr style="padding:0;text-align:left;vertical-align:top"><th class="small-6 large-6 columns first" style="Margin:0 auto;color:#0a0a0a;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:400;line-height:1.3;margin:0 auto;padding:0;padding-bottom:16px;padding-left:16px;padding-right:8px;text-align:left;width:274px"><table style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%"><tr style="padding:0;text-align:left;vertical-align:top"><th style="Margin:0;color:#0a0a0a;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:400;line-height:1.3;margin:0;padding:0;text-align:left"><center data-parsed="" style="min-width:242px;width:100%"><img src="https://bomprapet.com/wp-content/uploads/2017/01/petsdobem.png" alt="Pets do Bem" align="center" class="float-center" style="-ms-interpolation-mode:bicubic;Margin:0 auto;clear:both;display:block;float:none;margin:0 auto;max-width:100%;outline:0;text-align:center;text-decoration:none;width:auto"></center></th></tr></table></th><th class="small-6 large-6 columns last" style="Margin:0 auto;color:#0a0a0a;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:400;line-height:1.3;margin:0 auto;padding:0;padding-bottom:16px;padding-left:8px;padding-right:16px;text-align:left;width:274px"><table style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%"><tr style="padding:0;text-align:left;vertical-align:top"><th style="Margin:0;color:#0a0a0a;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:400;line-height:1.3;margin:0;padding:0;text-align:left"><center data-parsed="" style="min-width:242px;width:100%"><img src="https://bomprapet.com/wp-content/uploads/2017/01/bomprapet.png" alt="Bom pra Pet" align="center" class="float-center" style="-ms-interpolation-mode:bicubic;Margin:0 auto;clear:both;display:block;float:none;margin:0 auto;max-width:100%;outline:0;text-align:center;text-decoration:none;width:auto"></center></th></tr></table></th></tr></tbody></table><table class="row" style="border-collapse:collapse;border-spacing:0;display:table;padding:0;position:relative;text-align:left;vertical-align:top;width:100%"><tbody><tr style="padding:0;text-align:left;vertical-align:top"><th class="small-12 large-12 columns first last" style="Margin:0 auto;color:#0a0a0a;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:400;line-height:1.3;margin:0 auto;padding:0;padding-bottom:16px;padding-left:16px;padding-right:16px;text-align:left;width:564px"><table style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%"><tr style="padding:0;text-align:left;vertical-align:top"><th style="Margin:0;color:#0a0a0a;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:400;line-height:1.3;margin:0;padding:0;text-align:left"><h2 class="text-center" style="Margin:0;Margin-bottom:10px;color:inherit;font-family:Roboto,sans-serif;font-size:24px;font-style:italic;font-weight:400;line-height:1.3;margin:0;margin-bottom:10px;padding:0;text-align:center;word-wrap:normal">Prezado Luiza Sanchez Blasco</h2><p class="text-center" style="Margin:0;Margin-bottom:10px;color:#0a0a0a;font-family:Roboto,sans-serif;font-size:16px;font-weight:400;line-height:26px;margin:0;margin-bottom:10px;padding:0;text-align:center">Agradecemos o seu interesse! O seu CUPOM de desconto segue abaixo:</p></th><th class="expander" style="Margin:0;color:#0a0a0a;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:400;line-height:1.3;margin:0;padding:0!important;text-align:left;visibility:hidden;width:0"></th></tr></table></th></tr></tbody></table><table class="row" style="border-collapse:collapse;border-spacing:0;display:table;padding:0;position:relative;text-align:left;vertical-align:top;width:100%"><tbody><tr style="padding:0;text-align:left;vertical-align:top"><th class="small-12 large-12 columns first last" style="Margin:0 auto;color:#0a0a0a;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:400;line-height:1.3;margin:0 auto;padding:0;padding-bottom:16px;padding-left:16px;padding-right:16px;text-align:left;width:564px"><table style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%"><tr style="padding:0;text-align:left;vertical-align:top"><th style="Margin:0;color:#0a0a0a;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:400;line-height:1.3;margin:0;padding:0;text-align:left"><table class="callout" style="Margin-bottom:16px;border-collapse:collapse;border-spacing:0;margin-bottom:16px;padding:0;text-align:left;vertical-align:top;width:100%"><tr style="padding:0;text-align:left;vertical-align:top"><th class="callout-inner primary" style="Margin:0;background:#def0fc;border:1px solid #444;color:#0a0a0a;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:400;line-height:1.3;margin:0;padding:10px;text-align:left;width:100%"><table class="row" style="border-collapse:collapse;border-spacing:0;display:table;padding:0;position:relative;text-align:left;vertical-align:top;width:100%"><tbody><tr style="padding:0;text-align:left;vertical-align:top"><th class="small-12 large-12 columns first last" style="Margin:0 auto;color:#0a0a0a;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:400;line-height:1.3;margin:0 auto;padding:0;padding-bottom:16px;padding-left:0!important;padding-right:0!important;text-align:left;width:100%"><table class="spacer" style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%"><tbody><tr style="padding:0;text-align:left;vertical-align:top"><td height="20px" style="-moz-hyphens:auto;-webkit-hyphens:auto;Margin:0;border-collapse:collapse!important;color:#0a0a0a;font-family:Helvetica,Arial,sans-serif;font-size:20px;font-weight:400;hyphens:auto;line-height:20px;margin:0;mso-line-height-rule:exactly;padding:0;text-align:left;vertical-align:top;word-wrap:break-word">&#xA0;</td></tr></tbody></table><table style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%"><tr style="padding:0;text-align:left;vertical-align:top"><th style="Margin:0;color:#0a0a0a;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:400;line-height:1.3;margin:0;padding:0;text-align:left"><p class="text-center cupom" style="Margin:0;Margin-bottom:10px;color:#2199e8;font-family:Roboto,sans-serif;font-size:40px;font-weight:700;line-height:50px;margin:0;margin-bottom:10px;padding:0;text-align:center">CUPOM: BOMPRAPET</p></th><th class="expander" style="Margin:0;color:#0a0a0a;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:400;line-height:1.3;margin:0;padding:0!important;text-align:left;visibility:hidden;width:0"></th></tr></table></th></tr></tbody></table></th><th class="expander" style="Margin:0;color:#0a0a0a;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:400;line-height:1.3;margin:0;padding:0!important;text-align:left;visibility:hidden;width:0"></th></tr></table></th></tr></table></th></tr></tbody></table><table class="row" style="border-collapse:collapse;border-spacing:0;display:table;padding:0;position:relative;text-align:left;vertical-align:top;width:100%"><tbody><tr style="padding:0;text-align:left;vertical-align:top"><th class="small-12 large-12 columns first last" style="Margin:0 auto;color:#0a0a0a;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:400;line-height:1.3;margin:0 auto;padding:0;padding-bottom:16px;padding-left:16px;padding-right:16px;text-align:left;width:564px"><table style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%"><tr style="padding:0;text-align:left;vertical-align:top"><th style="Margin:0;color:#0a0a0a;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:400;line-height:1.3;margin:0;padding:0;text-align:left"><ul style="list-style-position:outside;margin:0;padding:0;padding-left:20px"><li style="font-family:Roboto,sans-serif;font-size:16px;line-height:26px">Este <strong>CUPOM</strong> poderá ser usado uma só vez, para uma das seguintes ofertas:</li><li style="font-family:Roboto,sans-serif;font-size:16px;line-height:26px">Vale R$30,00 de desconto numa assinatura acima de R$100,00.</li><li style="font-family:Roboto,sans-serif;font-size:16px;line-height:26px">Vale isenção de frete em assinaturas acima de R$199,00</li><li style="font-family:Roboto,sans-serif;font-size:16px;line-height:26px">Todas as ofertas são válidas exclusivamente para novos clientes.</li></ul><table class="spacer" style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%"><tbody><tr style="padding:0;text-align:left;vertical-align:top"><td height="10px" style="-moz-hyphens:auto;-webkit-hyphens:auto;Margin:0;border-collapse:collapse!important;color:#0a0a0a;font-family:Helvetica,Arial,sans-serif;font-size:10px;font-weight:400;hyphens:auto;line-height:10px;margin:0;mso-line-height-rule:exactly;padding:0;text-align:left;vertical-align:top;word-wrap:break-word">&#xA0;</td></tr></tbody></table></th><th class="expander" style="Margin:0;color:#0a0a0a;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:400;line-height:1.3;margin:0;padding:0!important;text-align:left;visibility:hidden;width:0"></th></tr></table></th></tr></tbody></table><table class="row" style="border-collapse:collapse;border-spacing:0;display:table;padding:0;position:relative;text-align:left;vertical-align:top;width:100%"><tbody><tr style="padding:0;text-align:left;vertical-align:top"><th class="small-12 large-12 columns first last" style="Margin:0 auto;color:#0a0a0a;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:400;line-height:1.3;margin:0 auto;padding:0;padding-bottom:16px;padding-left:16px;padding-right:16px;text-align:left;width:564px"><table style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%"><tr style="padding:0;text-align:left;vertical-align:top"><th style="Margin:0;color:#0a0a0a;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:400;line-height:1.3;margin:0;padding:0;text-align:left"><table class="callout" style="Margin-bottom:16px;border-collapse:collapse;border-spacing:0;margin-bottom:16px;padding:0;text-align:left;vertical-align:top;width:100%"><tr style="padding:0;text-align:left;vertical-align:top"><th class="callout-inner success" style="Margin:0;background:#e1faea;border:1px solid #1b9448;color:#fefefe;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:400;line-height:1.3;margin:0;padding:10px;text-align:left;width:100%"><p style="Margin:0;Margin-bottom:10px;color:#777;font-family:Roboto,sans-serif;font-size:16px;font-weight:400;line-height:26px;margin:0;margin-bottom:10px;padding:0;text-align:left">Não se esqueça que a cada 10Kg de ração entregues na sua casa pela Pets do Bem, 1 Kg de ração é doado para uma ONG !</p></th><th class="expander" style="Margin:0;color:#0a0a0a;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:400;line-height:1.3;margin:0;padding:0!important;text-align:left;visibility:hidden;width:0"></th></tr></table><table class="spacer" style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%"><tbody><tr style="padding:0;text-align:left;vertical-align:top"><td height="20px" style="-moz-hyphens:auto;-webkit-hyphens:auto;Margin:0;border-collapse:collapse!important;color:#0a0a0a;font-family:Helvetica,Arial,sans-serif;font-size:20px;font-weight:400;hyphens:auto;line-height:20px;margin:0;mso-line-height-rule:exactly;padding:0;text-align:left;vertical-align:top;word-wrap:break-word">&#xA0;</td></tr></tbody></table><center data-parsed="" style="min-width:532px;width:100%"><table class="button large radius float-center" style="Margin:0 0 16px 0;border-collapse:collapse;border-spacing:0;float:none;margin:0 0 16px 0;padding:0;text-align:center;vertical-align:top;width:auto"><tr style="padding:0;text-align:left;vertical-align:top"><td style="-moz-hyphens:auto;-webkit-hyphens:auto;Margin:0;border-collapse:collapse!important;color:#0a0a0a;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:400;hyphens:auto;line-height:1.3;margin:0;padding:0;text-align:left;vertical-align:top;word-wrap:break-word"><table style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%"><tr style="padding:0;text-align:left;vertical-align:top"><td style="-moz-hyphens:auto;-webkit-hyphens:auto;Margin:0;background:#2199e8;border:none;border-collapse:collapse!important;border-radius:3px;color:#fefefe;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:400;hyphens:auto;line-height:1.3;margin:0;padding:0;text-align:left;vertical-align:top;word-wrap:break-word"><a href="#" style="Margin:0;border:0 solid #2199e8;border-radius:3px;color:#fefefe;display:inline-block;font-family:Helvetica,Arial,sans-serif;font-size:20px;font-weight:700;line-height:1.3;margin:0;padding:10px 20px 10px 20px;text-align:left;text-decoration:none">USAR CUPOM</a></td></tr></table></td></tr></table></center></th><th class="expander" style="Margin:0;color:#0a0a0a;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:400;line-height:1.3;margin:0;padding:0!important;text-align:left;visibility:hidden;width:0"></th></tr></table></th></tr></tbody></table><table class="row" style="border-collapse:collapse;border-spacing:0;display:table;padding:0;position:relative;text-align:left;vertical-align:top;width:100%"><tbody><tr style="padding:0;text-align:left;vertical-align:top"><th class="small-12 large-12 columns first last" style="Margin:0 auto;color:#0a0a0a;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:400;line-height:1.3;margin:0 auto;padding:0;padding-bottom:16px;padding-left:16px;padding-right:16px;text-align:left;width:564px"><table style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%"><tr style="padding:0;text-align:left;vertical-align:top"><th style="Margin:0;color:#0a0a0a;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:400;line-height:1.3;margin:0;padding:0;text-align:left"><p style="Margin:0;Margin-bottom:10px;color:#0a0a0a;font-family:Roboto,sans-serif;font-size:16px;font-weight:400;line-height:26px;margin:0;margin-bottom:10px;padding:0;text-align:left">*Coupom pode ser usado por novos clientes, oferta não acumulável com outras promoções da Pets do bem</p></th><th class="expander" style="Margin:0;color:#0a0a0a;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:400;line-height:1.3;margin:0;padding:0!important;text-align:left;visibility:hidden;width:0"></th></tr></table></th></tr></tbody></table></td></tr></tbody></table></center></td></tr></table><!-- prevent Gmail on iOS font size manipulation --><div style="display:none;white-space:nowrap;font:15px courier;line-height:0">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</div></body></html>`

**Comment by davehoran** [comment]
Is there anything in the npm log file that would indicate an error that the system simply bypassed? I was having issues with my own install failing on a couple small things, so sorry for the delay. For my own errors, I was able to trace an inlining failure to a typo in the app.scss file that caused the inliner to fail with a robust cascade of errors. Wading through everything, I was able to locate the simple error. I'll take a look more at this as I can -- I'm already behind with things because of the inliner error. 

@valbap Have you tried re-installing (globally) the foundation-cli tool?

**Comment by valbap** [comment]
I have this on the npm-debug.log inside my project folder:

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@2.11.2
3 info using node@v0.12.6
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild foundation-emails-template@1.0.0
6 info build foundation-emails-template@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info foundation-emails-template@1.0.0 Failed to exec build script
9 verbose stack Error: foundation-emails-template@1.0.0 build: `gulp --production`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid foundation-emails-template@1.0.0
11 verbose cwd /Users/valentino/Desktop/nw/bomprapet
12 error Darwin 16.3.0
13 error argv "node" "/usr/local/bin/npm" "run" "build"
14 error node v0.12.6
15 error npm  v2.11.2
16 error code ELIFECYCLE
17 error foundation-emails-template@1.0.0 build: `gulp --production`
17 error Exit status 1
18 error Failed at the foundation-emails-template@1.0.0 build script 'gulp --production'.
18 error This is most likely a problem with the foundation-emails-template package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     gulp --production
18 error You can get their info via:
18 error     npm owner ls foundation-emails-template
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

```

And this one outside (outside this project folder):

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.11.2
3 info using node@v0.12.6
4 verbose stack Error: ENOENT, open '/Users/valentino/Desktop/nw/package.json'
4 verbose stack     at Error (native)
5 verbose cwd /Users/valentino/Desktop/nw
6 error Darwin 16.3.0
7 error argv "node" "/usr/local/bin/npm" "start"
8 error node v0.12.6
9 error npm  v2.11.2
10 error path /Users/valentino/Desktop/nw/package.json
11 error code ENOENT
12 error errno -2
13 error enoent ENOENT, open '/Users/valentino/Desktop/nw/package.json'
13 error enoent This is most likely not a problem with npm itself
13 error enoent and is related to npm not being able to find a file.
14 verbose exit [ -2, true ]
```

Didn't know about that file, sorry for puting so late..It has some errors in fact.. Regardless, Im not sure what exactly.

But both have the changed date from yesterday and today I've already tested that font changing.

Haven't tried to re-install as this was a fresh installation.. And to be honest, terminal is not my thing and I'm not sure if I will be able to do it.

If you want i can send you the project file.

Thank you very much for your time.

**Comment by valbap** [comment]
New error on terminal

```
Unhandled rejection Error: socket hang up
    at createHangUpError (_http_client.js:215:15)
    at TLSSocket.socketOnEnd (_http_client.js:300:23)
    at TLSSocket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickDomainCallback (node.js:381:11)
```

**Comment by davehoran** [comment]
There seems to be something wrong with the underlying installation of the
foundation-cli. The only suggestion I can come up with is to reinstall the
system.

**Comment by valbap** [comment]
I deleted the comment has on a second try everything ran well..
I've manage to unistall ( npm uninstall foundation-emails --save) and reinstall it.. and same problem..

Thank you, I will move to the old way ;)

**Comment by valbap** [comment]
Removed two pieces of css inline into my CSS and responsiveness started working..
`" <center data-parsed="" style="min-width:532px;width:100%">"`
and one other similar with a different value for a two collumn block..
Just removed the min-width and everything is working now...moving to putsmail..

**Comment by davehoran** [comment]
Great news!!

**Comment by itamarro** [comment]
@valbap So is there an issue here? Or can be closed, no?

**Comment by DanielRuf** [comment]
I think we can close this.
