### ISSUE TITLE
[feature-request] Add option to specify port for server

### ISSUE THREAD

**Issue by djeglin** [foundation/foundation-emails#692]
For those working in environments with a number of different projects on the go at the same time, or looking to integrate into other workflows, being able to manually specify the port for the browser-sync server would be a helpful addition, I think.

**Comment by djeglin** [comment]
I created a PR #693 to address this request. I believe I have put it in the correct branch, but feel free to point me in another direction if required.

**Comment by DanielRuf** [comment]
Closing as this was already merged. Thanks for your contribution to Foundation Emails @djeglin.
