### ISSUE TITLE
Anyway to append text to inlined file name?

### ISSUE THREAD

**Issue by Creativenauts** [foundation/foundation-emails#707]
I'm wanting to have inline and non-inline versions of my emails. Would it be possible to append text to inlined version online?

Example:

- email-1.html
- email-1-inline.html
- email-2.html
- email-2-inline.html

**Comment by davehoran** [comment]
Can you modify the inline function in gulp to add this extension? I haven't tried this, but it seems like a good place to start.

**Comment by Creativenauts** [comment]
Currently working on it now actually. Shouldn't be too difficult to be honest.

@davehoran perhaps you can help me understand why the inliner tool is not honoring my custom styles?

Check this out, the inline margins are jacked up. Driving me absolutely insane!

http://creativenauts.com/clients/emails/insearch-medical/option-a-related-jobs.html
http://creativenauts.com/clients/emails/insearch-medical/option-a-related-jobs-inline.html

**Comment by Creativenauts** [comment]
What I ended up doing was simply changing inline dist folder to 'dist/inline'

**Comment by davehoran** [comment]
You are using the foundtion-cli inliner tool locally, right? That is, you aren't using the web-based inlining tool?

**Comment by Creativenauts** [comment]
@davehoran that is correct but I ended up reverting back to overriding dist folder when running build. Guess I'm still trying to grasp the concept behind how they attempted to setup this all up.

**Comment by Creativenauts** [comment]
Abandoned the idea of appended text to the emails. Running build is fine now that I have my gulp file readjusted to suit my needs.
