### ISSUE TITLE
Email i recieve from zurb are not responsive

### ISSUE THREAD

**Issue by IamManchanda** [foundation/foundation-emails#714]
I am not into mailer's (current moment) but emails that i recieve from zurb are not responsive!

**Test Case**: Android - Chrome ( Mobile browser )

**Comment by IamManchanda** [comment]
![screenshot_2017-02-19-09-53-01](https://cloud.githubusercontent.com/assets/4970624/23099301/42b6d55a-f689-11e6-968b-ec748b7396d6.png)

**Comment by Creativenauts** [comment]
can you provide your template code so we can investigate and try to help?

**Comment by Creativenauts** [comment]
@IamManchanda sorry, just re-read your post here. I thought you were personally having issues with a template you are building. Sorry bout that but github not the place to post this type of comment.

**Comment by IamManchanda** [comment]
@DerekBess ...... I feel that its related so i posted ..... i guess zurb emails are foundation ( inky ) one's only or are they not ? 
and, if yes ...... They are not responsive so that is the issue/bug. 
 
Tagging @rafibomb @tdhartwick to look into this!

**Comment by Creativenauts** [comment]
@IamManchanda shows up responsive for me while viewing in gmail.

**Comment by IamManchanda** [comment]
@DerekBess Really ?? because i tested with three android smart phones ( Sony Xperia, Moto G, Xiomi Red me ) and its not responsive .... I have tested in other mails like amazon mailers also and they are responsive in those phones!

**Comment by Creativenauts** [comment]
@IamManchanda what android OS version are you on? I'm using android gmail app when I view the email.

**Comment by IamManchanda** [comment]
@DerekBess No i am talking about the mobile browser ( chrome )

**Comment by Creativenauts** [comment]
@IamManchanda Sorry for the delay. I just tried accessing my gmail from my browser but seems like my messages are cached or something. It's not updating so I have no way of testing but I believe you when you say it's not working.

**Comment by Creativenauts** [comment]
@IamManchanda finally managed to get mail.google.com to display the email and you are correct that it is not displaying responsively.

**Comment by rafibomb** [comment]
The ZURB Stack comes with the latest updates for Gmail mobile.

For web clients Gmail still hasn’t rolled out mobile webmail support: https://litmus.com/blog/gmail-to-support-responsive-email-design

According to this list - Gmail web client is still not supporting responsive. If there is a case on this list that does work but should, please let us know!

**Comment by tdhartwick** [comment]
+1 @rafibomb 
Yeah, we're pretty much just waiting for the Gmail dev's to address this. It's probably a pretty low priority for them though as they probably want to focus on their native apps.

**Comment by IamManchanda** [comment]
Yes i have a case! @rafibomb @tdhartwick 
Emails i recieve from sites like **Flipkart, Amazon** works perfectly there!

![email-flipkart](https://cloud.githubusercontent.com/assets/4970624/23829606/71ddb422-071c-11e7-9fa9-d0190eab936f.png)
