### ISSUE TITLE
&nbsp; converts to &amp;nbsp;

### ISSUE THREAD

**Issue by bibblebabl** [foundation/foundation-emails#715]
**How can we reproduce this bug?**

Write out the HTML (or Inky code) that causes the issue.

**What did you expect to happen?**

**What happened instead?**

**What email clients does this happen in?**

**Comment by Creativenauts** [comment]
use raw tag.

`{{{{raw}}}}&nbsp;{{{{/raw}}}}`

**Comment by DanielRuf** [comment]
Duplicate of https://github.com/zurb/foundation-emails/issues/841, can be closed.
