### ISSUE TITLE
Sidebar column is pushed down in Outlook 2007/2013/2010/2016

### ISSUE THREAD

**Issue by frontuk** [foundation/foundation-emails#723]
Hi Zurb,

I decided to give a test (http://testi.at) to the the example page **sidebar.html** in a freshly generated project and I end up with the sidebar column pushed to the bottom (check the image):

![testi__foundation-emails](https://cloud.githubusercontent.com/assets/26119608/23471024/46ef874e-fea8-11e6-8d64-c7b63daa301a.png)

It breaks in Outlook 2007, Outlook 2013, Outlook 2010, Outlook 2016

I am using: 
npm -v 4.1.1
foundation-cli@2.1.0

The markup is the same as in the default examples **src/pages/sidebar.html**.

Do you have any idea why this is happening?

Thanks in advance,
truk

**Comment by alboth** [comment]
It also breaks in a "real" Win10+Outlook2016 - looks the same as in "testi"

**Comment by alboth** [comment]
I still made a test with a **freshly installed** _foundation new --framework emails_ without any changes (I only removed the menu in the sidebar as seen above and which is know to cause problems - #702).

The columns are fine, BUT the **sidebar is still pushed down** in **all the Outlook versions**
![outlook2016](https://cloud.githubusercontent.com/assets/1639894/23472534/6e0c6716-fead-11e6-9d22-46b1ebb43a90.jpeg)

Btw - also the buttons fail to have a background color....

**Comment by Creativenauts** [comment]
@alboth try added align="top"

**Comment by davehoran** [comment]
I have to agree with @DerekBess . It looks like the sidebar content is being centered vertically. Try using the valign attribute on the container element to push it to the top. For example:

```
<columns large="3" valign="top">
    <img class="float-right" src="http://placehold.it/50" alt="">
  </columns>
```

**Comment by Creativenauts** [comment]
@davehoran is correct, it's valign not align 👍

**Comment by frontuk** [comment]
@davehoran your solution seams to work well, thanks.
I completely forgot that we can still use such xhtml 1.0 attributes.
Bests!
