### ISSUE TITLE
Colon in subject message

### ISSUE THREAD

**Issue by rockse** [foundation/foundation-emails#724]
When we add a colon (`:`) in the subject message. It produces an error.

**How can we reproduce this bug?**

For e.g. `subject: My: First Subject`

I also tried it with an escape character `subject: My/: First Subject` but it still produces the error

`{ YAMLException: incomplete explicit mapping pair; a key node is missed at line 1, column 20:
    subject: My/:`

**What did you expect to happen?**

It should work with the escape character. Though it was working when it was `subject: My :\ First Subject`

**Comment by Creativenauts** [comment]
@rockse put it in quotes and it will work as expected. It's yaml syntax so that's normal.

`subject: "My: First Subject"`

**Comment by rockse** [comment]
@DerekBess If we have `{{someVar}}` in subject like `subject: My: {{someVar}}`, then?

**Comment by Creativenauts** [comment]
@rockse it's not a problem. For example I use this in one of my clients projects.

`pre_header: "A new {{{fields.job_title_dirty}}} opening is available."`
