### ISSUE TITLE
It encodes &nbsp; as &amp;nbsp; - but we often need non braking spaces within the HTML - why is this encoded further?

### ISSUE THREAD

**Issue by getandyjones** [foundation/foundation-emails#729]
**How can we reproduce this bug?**

Write out the HTML (or Inky code) that causes the issue.

**What did you expect to happen?**

**What happened instead?**

**What email clients does this happen in?**

**Comment by JuanmaMenendez** [comment]
I have the same problem.

**Comment by Creativenauts** [comment]
Use raw helper to avoid this issue or you can create YAML data file that includes the non braking space.

**Comment by DanielRuf** [comment]
Duplicate of https://github.com/zurb/foundation-emails/issues/841, can be closed.
