### ISSUE TITLE
Foundation API

### ISSUE THREAD

**Issue by brianbier** [foundation/foundation-emails#733]
Hi is there an api that I can tap into so that I can post to their server and inline my emails?

**Comment by Deckluhm** [comment]
Not that I am aware of.

You can do this:
- Manually, using [their inliner form](http://foundation.zurb.com/emails/inliner-v2.html)
- Automatically, using the [ZURB Stack](https://foundation.zurb.com/emails/docs/zurb-stack.html) (which use [`gulp-inline-css`](https://www.npmjs.com/package/gulp-inline-css) for inlining)

**Comment by tdhartwick** [comment]
Thanks @Deckluhm, those are our two options for inlining currently! Just run `npm run build` to inline your emails using the ZURB Stack.

Closing for now, feel free to reopen if you have any more questions!
