### ISSUE TITLE
<item> tag not rendered in outlook 2003

### ISSUE THREAD

**Issue by Jack89ita** [foundation/foundation-emails#735]
How can we reproduce this bug?
In newsletter test found in [this page](https://litmus.com/checklist/emails/public/34a1f59) the last elements (that are inside a `<menu>` tag) are not rendered on Outlook 2003, while in the other clients are displayed.

Example HTML
```
<menu>
    <item><img src="http://placehold.it/50x50" alt=""></item>
    <item><img src="http://placehold.it/50x50" alt=""></item>
    <item><img src="http://placehold.it/50x50" alt=""></item>
    <item><img src="http://placehold.it/50x50" alt=""></item>
    <item><img src="http://placehold.it/50x50" alt=""></item>
</menu>
```

What did you expect to happen?
Elements visible in Outlook 2003

What happened instead?
Elements are NOT visible in Outlook 2003

Anyone got this problem too?
Thanks in advance.

EDIT: screeshot to clarify
![ol2003-vertical-allowed-1366](https://cloud.githubusercontent.com/assets/15101779/24156103/ef862cb6-0e55-11e7-9a7b-fd5df756f33c.jpg)

**Comment by stevesmename** [comment]
Try checking the validation of your html; or attempt to use something other than placehold.it or images at all. Frankly, I think you just need to do `src="http://placehold.it/25x25"` and not `src="http://placehold.it/25"`
