### ISSUE TITLE
How to: inner tables with padding in inner cells

### ISSUE THREAD

**Issue by bfcamara** [foundation/foundation-emails#736]
**How can we reproduce this bug?**

```
<container>
  <row>
    <columns style="background-color: yellow;">
      <container>
        <row>
          <columns style="background-color: red">
            <p>Col 1</p>
          </columns>
          <columns style="background-color: green">
            <p>Col 2</p>
          </columns>
        </row>
      </container>
    </columns>
  </row>
</container>
```
**What did you expect to happen?**

I would like to still have padding in inner cells of inner tables

![image](https://cloud.githubusercontent.com/assets/822851/24211713/d3d34588-0f24-11e7-9f79-ea0dc12747d5.png)

**What happened instead?**
No padding in inner cells

![image](https://cloud.githubusercontent.com/assets/822851/24211750/ec63cec4-0f24-11e7-9d89-c93909d34806.png)

**What email clients does this happen in?**

All. Is there a workaround to keep the inner cells of inner tables with padding as if they were the outer row. I can make it work with something like this

```
                            th.columns .columns:not(.first) {
                              padding-left: 8px !important;
                            }
                            th.columns .columns:not(.last) {
                              padding-right: 8px !important;
                            }
```

But in a mobile device it doesn't work well, particularly if I have images in each column (columns stacked but images are not correclty aligned due padding added).

Any idea?

**Comment by Deckluhm** [comment]
As stated in the issue template, issues are for bugs only, if you need help please post your question on the [Foundation forum](http://foundation.zurb.com/forum) or on [StackOverflow](https://stackoverflow.com).

That being said, you should (re)read the [Grid section](http://foundation.zurb.com/emails/docs/grid.html) of the documentation, you aren't supposed to have multiple `container` elements in your email.

**Comment by bfcamara** [comment]
@Deckluhm Sorry, my mistake in reporting the issue when what I need is just some help. I am going to close it and ask for help on suggested sites (Foundation Forum, StackOverflow).

Anyway, I've just read the Grid section and I can't see any statement telling me that I should not have multiple containers or nested containers.

**Comment by Deckluhm** [comment]
I'm not a Foundation for Emails expert and I might be wrong but, even if it's not well explained in the documentation, you are not supposed to have nested `container` inside `row` (like you do).

You should take a look at [these templates examples](https://github.com/zurb/foundation-emails-template/tree/master/src/pages), maybe that will help you doing what you want.

**Comment by bfcamara** [comment]
Thank you @Deckluhm. I think the problem is not in the nested container. The problem is in the nested rows and columns, which I think it's valid from a framework perspective. I have the same result with this (not multiple containers).

```
<container>
  <row>
    <columns style="background-color: yellow;">
        <row>
          <columns style="background-color: red">
            <p>Col 1</p>
          </columns>
          <columns style="background-color: green">
            <p>Col 2</p>
          </columns>
        </row>
    </columns>
    <columns style="background-color: blue;">
    <row>
      <p>Test</p>
    </row>
    </columns>
  </row>
</container>
```

![image](https://cloud.githubusercontent.com/assets/822851/24256389/f897cd88-0fdf-11e7-8ab1-bf84d88b367b.png)
