### ISSUE TITLE
SASS classes that aren't used in .html files not being compiled

### ISSUE THREAD

**Issue by SimonIMG** [foundation/foundation-emails#757]
**How can we reproduce this bug?**
Foundation for Emails version: 2.2.1
NPM version: 4.5.0
1. Create a SASS class that isn't used in default.html, index.html or any partial (even try a media query)
```
.my_class {
   color: $black;
   font-weight:bold;
}
```
Now **DO NOT** apply my_class to any of your .html files.

2. Compile code

3. The class isn't added to the dist/index.html file

**What did you expect to happen?**
We add classes to our ZF4E projects to address some issues that arise when using some mass email clients (Vision 6, MailChimp, Campaign Monitor, Hubspot etc).

We also add some classes to fix other issues like automatic colouring of links (dates, addresses, phone numbers) on iOS.
eg. To fix automatically linked content on iOS devices...
```
@media only screen and (max-width: #{$global-breakpoint}) {
	a[x-apple-data-detectors] {
	    color: inherit !important;
	    text-decoration: underline !important;
	    font-size: inherit !important;
	    font-family: inherit !important;
	    font-weight: inherit !important;
	    line-height: inherit !important;
	}
}
```
**What happened instead?**
Recently, I've noticed that these classes are no longer being compiled into the distribution code. So the fixes we have applied for our mass email clients are no longer working. These classes were being compiled in previous versions of ZF4E.

**What email clients does this happen in?**
All clients.

**More info**
I can see why this has been done; so unused classes don't get compiled into the final eDM .html and bloat the file.

However, I'm sure my team and I are not the only one's who create little fixes for issues that arise from using mass email clients (eg. fixing the width auto-generated footer in Vision 6 for mobile), or from sending to mobile devices (eg. iOS automatically blue-linking and colouring dates, addressed etc).

I attempted to edit the gulpfile.babel.js
```
applyStyleTags: true,
removeStyleTags: false,
preserveMediaQueries: true,
removeLinkTags: false
```
This had no affect on the compiled code.

If there was a way we could ensure that all classes in my .scss files get compiled (or even better, all the classes in one particular .scss file - we use a file called _common.scss for these kind of fixes).

**Comment by SimonIMG** [comment]
Not long after I post this, I find the solution. I compared the gulpfile.babel.js in my project to a gulpfile.babel.js from an older ZF4E project. 

I commented out lines 78 to 81.

```
71 // Compile Sass into CSS
72 function sass() {
73   return gulp.src('src/assets/scss/app.scss')
74     .pipe($.if(!PRODUCTION, $.sourcemaps.init()))
75     .pipe($.sass({
76       includePaths: ['node_modules/foundation-emails/scss']
77     }).on('error', $.sass.logError))

78     // .pipe($.if(PRODUCTION, $.uncss(
79     //   {
80     //     html: ['dist/**/*.html']
81     //   })))

82    .pipe($.if(!PRODUCTION, $.sourcemaps.write()))
83    .pipe(gulp.dest('dist/css'));
84 }
```

Now all of my classes get compiled again.

NOTE: This adds a significant amount of extra  code for unused classes into the <head> of the eDM, including all the unused row/column classes. But all of our fixes for iOS and various mass email apps are being included again.

I'd like to come up with a way that one .scss (eg. _common.scss or _fixes.scss) file could contain classes that always get included, regardless of whether they're used in the .html code.

**Comment by rickysullivan** [comment]
Try adding `/* uncss:ignore */` before your selector.

**Comment by SimonIMG** [comment]
So an example of that would be, at the bottom of my .scss file...

```
/* uncss:ignore */
@media only screen and (max-width: #{$global-breakpoint}) {
	.my_class {
		color: $awesomesauce-red;
	}
}
```

Is this correct? Or does the `/* uncss:ignore */` go inside the @media query?

**Comment by DanielRuf** [comment]
That is intentional. uncss removes unused styles. This is not a bug.

**Comment by jkd77** [comment]
Is there a way to create exceptions to this feature? I have scenarios with email send services that dynamically create various elements (example: unsubscribe links) that don't exist in my source code. I can however style those elements by having a media query remain in the head that gets inlined by the service AFTER it adds the unsubscribe link.

**Comment by DanielRuf** [comment]
@jkd77 You can remove uncss from the gulp task(s) or check the documentation of uncss.

**Comment by jkd77** [comment]
@DanielRuf - good advice. That comment by @SimonIMG was the way to go. Thanks!

**Comment by DanielRuf** [comment]
I guess we can close this as this is intentional by default and not a bug. Never used the ignore annotations so far but this should be the solution to go or removing uncss from the task.
