### ISSUE TITLE
Inlining causes & to turn into &amp;amp;

### ISSUE THREAD

**Issue by t-webb** [foundation/foundation-emails#763]
**How can we reproduce this bug?**

Create an html document, place some text in the document and make sure there is a & somewhere in the text . If you look at the code for the & symbol, it should be `&amp;`. Now, inline that html using zurb's email inlining tool -  http://foundation.zurb.com/emails/inliner-v2.html

**What did you expect to happen?**

the `&amp;` in the code should be left as is.

**What happened instead?**

after inlining the html code, it changed the `&amp;` to `&amp;amp;`

**What email clients does this happen in?**

appears to be all, if not most of them. tested on all outlook versions, android, iphone and ipad with the same results.

**Comment by natantata** [comment]
Also, links with "&" variables get changed to "\&amp;" thus breaking the links. 
So, 
a href="www.mysite.com&var1=1" turns into 
a href="www.mysite.com\&amp;var1=1"

**Comment by ErikNatanael** [comment]
Also, any &nbsp; automatically inserted by the transpiler get changed to &amp;nbsp; and have to be manually changed back.

**Comment by DanielRuf** [comment]
Duplicate of https://github.com/zurb/foundation-emails/issues/841, can be closed.
