### ISSUE TITLE
Zip build produce wrong image paths

### ISSUE THREAD

**Issue by lbineau** [foundation/foundation-emails#766]
Latest version of foundation-emails.

https://monosnap.com/file/G9X1ogfnhOnfmj1DM80nuf7IWmadkb
https://monosnap.com/file/fNyXwrivF670AlgDlQisWbr1t60hFn

**How can we reproduce this bug?**
npm run zip

**What did you expect to happen?**
To have the correct image paths.

**What happened instead?**
The images are not in the right folder or the paths are wrong

**Comment by andremiguelaa** [comment]
same problem here

**Comment by DanielRuf** [comment]
Did you use the `{root}` handlebars variable in your templates?

**Comment by DanielRuf** [comment]
Try the following for the `moveImages` gulp task:

```js
    var moveImages = gulp.src(sourcePath)
      .pipe($.htmlSrc({ selector: 'img'}))
      .pipe($.rename(function (currentpath) {
        currentpath.dirname = path.join(fileName, currentpath.dirname.replace('dist', ''));
        return currentpath;
      }));
```

I will provide a PR.
