### ISSUE TITLE
'@gulp-sourcemaps/map-sources' is not in the npm registry.

### ISSUE THREAD

**Issue by mozeum** [foundation/foundation-emails#771]
Anyone else getting this issue or know how to fix it? I've tried installing via the cli and cloning from the repo.

npm ERR! code E404
npm ERR! 404 no such package available : @gulp-sourcemaps/map-sources
npm ERR! 404
npm ERR! 404  '@gulp-sourcemaps/map-sources' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'gulp-sourcemaps'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by DanielRuf** [comment]
How did you get this error?

**Comment by schmendrick** [comment]
me too. also looking for how to solve it.
i dont want to pollute this here with sth. off topic but since @DanielRuf  asked how to get this: 
i got it trying to npm install another project
https://github.com/yahiko00/PixiProject

**Comment by DanielRuf** [comment]
Generally it is there:
https://www.npmjs.com/package/@gulp-sourcemaps/map-sources

**Comment by DanielRuf** [comment]
@schmendrick I did not get the mentioned error when I installed the project:
```
PixiProject git:(master) npm i
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js

> fsevents@1.1.3 install /Users/druf/projects/PixiProject/node_modules/fsevents
> node install

[fsevents] Success: "/Users/druf/projects/PixiProject/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> uws@9.14.0 install /Users/druf/projects/PixiProject/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN pixi-project@0.1.0 No repository field.

added 942 packages in 35.995s
```

**Comment by DanielRuf** [comment]
Please check if you use the latets npm and Node.js versions.

**Comment by DanielRuf** [comment]
> npm ERR! 404 '' is not in the npm registry.

Also this is another issue and not related to the sourcemaps module.

**Comment by DanielRuf** [comment]
> npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
> npm ERR! 404 It was specified as a dependency of 'gulp-sourcemaps'

https://github.com/gulp-sourcemaps/gulp-sourcemaps/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+404

I guess this issue is well known, please file an issue at https://github.com/gulp-sourcemaps/gulp-sourcemaps/issues if you still have this issue.

I think we can close this issue here as we can not fix this on our side.

**Comment by schmendrick** [comment]
sure, thanks for the reply but i am fine. (when i use yarn to install mentioned project everything works out of the box) i just tried to provide you some info because you asked how mrmozza got this.

**Comment by DanielRuf** [comment]
Closing as this should be resolved.
