### ISSUE TITLE
Huge Images in Outlook 2010/2013

### ISSUE THREAD

**Issue by dustinlocke** [foundation/foundation-emails#784]
Even though I've inlined my height and width, I'm still getting huge images in outlook.

My image tags look like this:
`<img src="http://goskip.com/img/emails/welcome/welcome.png" alt="Welcome to Skip" width="600px" height="300px"  />`

Here's the output in Outlook:
<img width="811" alt="screen shot 2017-05-31 at 12 09 44 pm" src="https://cloud.githubusercontent.com/assets/3036411/26646857/84741578-45fa-11e7-8457-91368a9fcee8.png">
<img width="805" alt="screen shot 2017-05-31 at 12 10 05 pm" src="https://cloud.githubusercontent.com/assets/3036411/26646864/8d72cf0c-45fa-11e7-8e3d-80fb93bf1bbb.png">

The only help I can find in the docs is this:
>The problem is Outlook and Thunderbird like to show images in their ahem full glory. The solution is inline size attributes.

And I've searched through existing issues but those solutions aren't working for me. What am I missing?

**Comment by davehoran** [comment]
@dustinlocke My suggestion would be to (1) set the height and width attributes to numbers only (lose the 'px'), and (2) resize the image to max width of your email. The max width is set in your _settings.scss file. Outlook sucks and will (in many version) just show the image in it's native size if everything isn't perfect. Give it a try and see if it helps.

**Comment by dustinlocke** [comment]
@davehoran removing `px` from the dimensions seems to have done it. Thanks for the tip!

**Comment by tongrhj** [comment]
Does anyone have a solution if you don't have the width and height in advance? E.g. User uploaded banner.

Would really like to avoid calculating the height and width at time of user upload
