### ISSUE TITLE
Preview with fake data during testing, replace with real data at build

### ISSUE THREAD

**Issue by akorman** [foundation/foundation-emails#785]
**Background / The Problem**
I'm using Foundation for Emails to create HTML email templates for use in another system (SendGrid), where I'm ultimately going to merge in customer data at send time. So, my templates have a bunch of SendGrid variables in them, like [%first_name%].

This works fine, but it's hard to use Foundation to preview what the emails will actually look like. It's not such a big deal for a simple substitution like a first name, but for more complex messages, with a variety of variables (numeric values, longer blocks of text, etc.), it's hard to get a sense of what they will look like.

Typically, I start with fake data in the body of the message while working out the content, then replace the fake data the variables near the end. Of course, that's error prone, and inevitably you end up leaving fake data in a message that goes to customers. Even if you're not using an external delivery service, you run into the same problem doing any sort of local preview. 

**Enhancement Request**
Add some mechanism that lets you use fake data when you run `npm start` and real data (or variables) when you run `npm run build`.

I'm not a real dev, so I don't know the best way to do this, but a couple of ways I thought it might work:
* Within a file you could have something like `{{ #test "Hi John," }} {{ #build "Hi [%first_name%]," }}`
* Using an external config.json you could define data to use across all your templates in "test mode" vs. "build mode". So, within a file you have {{ first_name }} which might get replaced by _John_ in test mode and _[%first_name%]_ when you build.
...or it could be a combination (where there are global configs that can be overridden within a file).

**Comment by lspoor** [comment]
Its probably not exactly what you need, but a step forward in helping. Foundation Emails uses Panini for the templating system, and one of the features is pulling in data via .json file, how it will work for fake/real data I'm not sure - but maybe its of some help!

https://github.com/zurb/panini#data

**Comment by DanielRuf** [comment]
You can easily do this in the gulpfile and checking if the current env is production or not.

**Comment by DanielRuf** [comment]
Closing as we did not receive further feedback.
