### ISSUE TITLE
A callout with a class of primary uses the $secondary-color variable for it's border

### ISSUE THREAD

**Issue by nizzac** [foundation/foundation-emails#786]
**How can we reproduce this bug?**
Display a callout component with a class of primary

**Write out the HTML (or Inky code) that causes the issue.**
`<callout class="primary"></callout>
`

**What did you expect to happen?**
Call out to use the $primary-color variable

**What happened instead?**
The $secondary-color variable is used

**What email clients does this happen in?**
Not tested but I would assume all.

**Comment by DanielRuf** [comment]
https://github.com/foundation/foundation-emails/blob/develop/scss/components/_callout.scss#L58

**Comment by evanre** [comment]
Hi, @DanielRuf, there is a problem with your latest PR #978, `$callout-border-primary` variable is not defined.

**Comment by DanielRuf** [comment]
Hi @evanre,

thanks for the hint. I guess it should be `$callout-border`?

https://github.com/foundation/foundation-emails/blob/e0308e1d1ec3f5d5f97bdff6a85fd1abd007e363/scss/components/_callout.scss#L27

Do you want to provide a PR? That would be very helpful.

**Comment by DanielRuf** [comment]
But I guess we can remove the line there then, see https://github.com/foundation/foundation-emails/blob/develop/scss/components/_callout.scss#L52

**Comment by evanre** [comment]
@DanielRuf I've created a PR #979 (Used your latest PR as an example). I think the best way to solve this is to just define the variable and keep the consistency to other variables and modifier classes.
