### ISSUE TITLE
Firefox <columns small="6"> stacking vertically

### ISSUE THREAD

**Issue by ryanjavens** [foundation/foundation-emails#794]
Found a way to replicate a closed issue: #435 

So far, all that I've found is that it doesn't work in is Firefox and Firefox Developer Edition, but I've tested it in Chrome and Safari, as well as Outlook on Mac, Outlook on Windows, Office 365 mail, and Apple mail. 

**How can we reproduce this bug?**
1. I just created a brand new foundation email project using Foundation cli `foundation new --framework emails`
2. `npm start`
3. Modified the basic.html page template that is included in the initial build to have two columns of small="6" (see code below)
4. After doing this, if I shrink my Firefox window down below the 596px width breakpoint, my content is pushed into a single 'half' column. 
![screen shot 2017-06-09 at 4 36 10 pm](https://user-images.githubusercontent.com/12108116/26993919-4a03af58-4d33-11e7-8e45-5ecc8a644cc7.png)

Write out the HTML (or Inky code) that causes the issue.

```
---
subject: Test Subject
---

<container>
  <row>
    <columns small="6">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut optio nulla et, fugiat. Maiores accusantium nostrum asperiores provident, quam modi ex inventore dolores id aspernatur architecto odio minima perferendis, explicabo. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima quos quasi itaque beatae natus fugit provident delectus, magnam laudantium odio corrupti sit quam. Optio aut ut repudiandae velit distinctio asperiores?</p>
    </columns>
    <columns small="6">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut optio nulla et, fugiat. Maiores accusantium nostrum asperiores provident, quam modi ex inventore dolores id aspernatur architecto odio minima perferendis, explicabo. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima quos quasi itaque beatae natus fugit provident delectus, magnam laudantium odio corrupti sit quam. Optio aut ut repudiandae velit distinctio asperiores?</p>
    </columns>
  </row>
</container>
```

**What did you expect to happen?**

The columns should be stacked horizontally since they add up to the default column count of 12. 

**What happened instead?**

The columns stacked vertically, while maintaining half-width from being only 6 columns wide.

**What email clients does this happen in?**
None that I noticed after testing Outlook for Mac and Windows, Office 365 mail, and Apple Mail, but occurs in Firefox.

Here's a fix that I've found works:
```
@media only screen and (max-width: 596px) {
    td.small-6, th.small-6 {
        display: table-cell !important;
    }
}
```

Hope this helps!

**Comment by bmatzner** [comment]
The issue does not occur if whitespace between the two columns in the Inky template is removed. The fix provided does indeed resolve the issue.

**Comment by gregorywaynepower** [comment]
Can confirm that removing white space works! I recommend that this be closed.

**Comment by DanielRuf** [comment]
Thanks for the additional input and feedback.

Closing as this is an issue with the template. I guess inlining would also prevent this.
