### ISSUE TITLE
[Getting Started with Sass] ISSUE NAME HERE

### ISSUE THREAD

**Issue by AlbaroPereyra** [foundation/foundation-emails#797]
**How can we reproduce this bug?**
npm install --global foundation-cli;
Write out the HTML (or Inky code) that causes the issue.
N/A
**What did you expect to happen?**
Install requirements on this per this getting started guide
http://foundation.zurb.com/emails/docs/sass-guide.html
**What happened instead?**
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/darwin-x64-57_binding.node"; 

I get a 404 error when I visit the URI, the URI may just have to updated.
**What email clients does this happen in?**
N/A

**Comment by DanielRuf** [comment]
npm should build node-sass in this case. They do not provide binaries for all platforms and releases.

**Comment by DanielRuf** [comment]
Closing as we did not receive any further feedback.
