### ISSUE TITLE
Firefox responsive images

### ISSUE THREAD

**Issue by kyriakos** [foundation/foundation-emails#8]
Images are not responsive in firefox (possibly in thunderbird too).

**Comment by csavory** [comment]
Doesn't this bug also affect Gmail (desktop) in FireFox?  if i'm trying to use a Retina image then by setting the width to auto is going to cause FF to render the email beyond 580px wide.

**Comment by GNUletik** [comment]
Should this "bug" be reported to Firefox devs ?

**Comment by atinder90** [comment]
facing same issue in firefox. Image goes beyond 580px

**Comment by rafibomb** [comment]
Looks like this has been updated on FF46 - http://foundation.zurb.com/forum/posts/39847-non-responsive-firefox-foundation-for-emails-210
