### ISSUE TITLE
Grunt Plugin of Inliner?

### ISSUE THREAD

**Issue by jswhisperer** [foundation/foundation-emails#80]
Feature request: would be to create a grunt plugin of inky inliner so that one could automate the email build process and keep a working copy separate from a build copy.

**Comment by ganar** [comment]
@amclin The output from premailer is different somehow, I found out on doing a responsive template recently

**Comment by joeyfb** [comment]
The output of Gulp's premailer and Zurb ink look pretty different to me. Both Ink's inliner and Gulp spit out the same build version (as of this date), 4380b7741bb759d6cb997545f3add21ad48f010b, but here's an example of the opening table for my email from each:

**premailer**
<table class="body" style="-moz-hyphens: none; -ms-hyphens: none; -webkit-hyphens: none; border-collapse: collapse; border-spacing: 0; color: #222222; font-family: 'Helvetica', 'Arial', sans-serif; font-size: 14px; font-weight: normal; height: 100%; hyphens: none; line-height: 19px; margin: 0; padding: 0; text-align: left; vertical-align: top; width: 100%">

**zurb ink inlliner**
<table class="body" style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; height: 100%; width: 100%; color: #222222; font-family: 'Helvetica', 'Arial', sans-serif; font-weight: normal; line-height: 19px; font-size: 14px; -moz-hyphens: none; -ms-hyphens: none; -webkit-hyphens: none; hyphens: none; margin: 0; padding: 0;">

Different ordering of styles. Also, Zurb's Inliner remove lots of new lines so it's 30% shorter. Both seem to work when I compare them with a test on litmus.com, but with the finickyness of emails it makes me nervous.
