### ISSUE TITLE
problem with sass and @import

### ISSUE THREAD

**Issue by KonstantinKlepikov** [foundation/foundation-emails#801]
Constantly i see a similar error. 

Message:
    src\assets\scss\app.scss
Error: File to import not found or unreadable: settings
       Parent style sheet: C:/xampp/htdocs/zurb/src/assets/scss/app
.scss
        on line 1 of src/assets/scss/app.scss
>> @import 'settings';
   ^

**Comment by davehoran** [comment]
Is there a _settings.scss file in the directory?
Are directory/file permissions getting in the way somehow?

**Comment by KonstantinKlepikov** [comment]
Yes. Everything in its place. 
Error does not occur at the start, but continuously during operation.

**Comment by davehoran** [comment]
I don't have a specific answer, but perhaps doing a fresh install into a new directory, start up the stack, then start adding files from your other project and see what errors show up? Time consuming, yes, but will hopefully show the point at which the scss compiles break.

**Comment by KonstantinKlepikov** [comment]
It is so strange, but i cleaned my .scss files from empty lines and extra spaces ... and problem with @import became more rare

**Comment by davehoran** [comment]
Definitely strange. The only time I've had issues with this is when I have a path problem or permissions issue.

**Comment by KonstantinKlepikov** [comment]
oh, i see another yet anomaly. When i change something in src files, i see: 

[BS] Serving files from: dist/
[00:45:35] Starting 'pages'...
[00:45:35] Finished 'pages' after 521 ms
[00:45:35] Starting 'inline'...
[00:45:35] Finished 'inline' after 299 ms
**[00:45:35] Starting '&lt;anonymous&gt;'...**
[BS] Reloading Browsers...

but as result inliner completes files correctly

**Comment by davehoran** [comment]
Huh. Check the gulp file to see if its trying to run something that isn't there, but the error is getting trapped before it's output. I'll have to compare this to what I'm seeing -- I use it so often I sometimes don't pay too much attention to the output unless there is a large error.

**Comment by Creativenauts** [comment]
This occurs outside of foundation for me... just throwing that out there for anyone who feels this is related to zurb only.

**Comment by DanielRuf** [comment]
You may need `~foundation-emails/...`

**Comment by DanielRuf** [comment]
Closing as we did not receive further feedback.
