### ISSUE TITLE
Responsive Email Inliner rendering non-breaking spaces.

### ISSUE THREAD

**Issue by moehammoud** [foundation/foundation-emails#804]
**How can we reproduce this bug?**
Using the inliner: http://foundation.zurb.com/emails/inliner-v2.html
Every instance of **`&#xA0;`** renders as **`&amp;nbsp;`**

**What did you expect to happen?**
I expect **`&#xA0;`** to render as **`&nbsp;`**

**What happened instead?**
Every instance of **`&#xA0;`** renders as **`&amp;nbsp;`**

**What email clients does this happen in?**
All of them.

**Comment by jakriese** [comment]
I agree, this is driving me crazy. This tool should expect valid HTML.

**Comment by DanielRuf** [comment]
Duplicate of https://github.com/zurb/foundation-emails/issues/841, can be closed.
