### ISSUE TITLE
Style block at top of email not inlined

### ISSUE THREAD

**Issue by brandonvmoore** [foundation/foundation-emails#809]
The sample Order template has this style block at the top:

```
<style type="text/css">
  body,
  html, 
  .body {
    background: #f3f3f3 !important;
  }
</style>
```

However, when running "npm run build" it seems to be ignored. I noticed this problem when I tried to add a style block to my template that it just got stripped and not included in the output, so I went and looked at the output for the order template that comes with the samples but it seems to have the same problem.

Should it be inlining style block included in the email itself?

**Comment by saurabhnanda** [comment]
Facing the same issue. In fact placing custom styles even in `_templates.scss` doesn't seem to work.

**Comment by Rylai-Zihang** [comment]
Me too.

**Comment by DanielRuf** [comment]
> Should it be inlining style block included in the email itself?

By default it doesn't. You can change the setting `applyStyleTags`, see https://github.com/foundation/foundation-emails/blob/031b8d6cdb2615e7c20bd75505a52712fd57b9fe/gulpfile.js#L219
