### ISSUE TITLE
[The Grid] .small-12 not working

### ISSUE THREAD

**Issue by afroguy16** [foundation/foundation-emails#814]
**How can we reproduce this bug?**

Write out the HTML (or Inky code) that causes the issue.

<table class="container"> 
              <tr>
                <td>
                  
                  <table class="row"> 
                    <tr>
                      <th class="small-12 large-6 first columns">
                        Column One
                      </th>
                      <th class="expander"></th>
                      <th class="small-12 large-6 last columns">
                        Column One
                      </th>
                      <th class="expander"></th>
                    </tr>
                  </table> 

                </td>
              </tr>
            </table> 

**What did you expect to happen?**

I expect Column one and two to take up the full width in small devices like mobile phone

**What happened instead?**

Both columns are taking up just half width each, that is same as large devices

**What email clients does this happen in?**
On the browser, not yet inside email client

**Comment by s-en-o** [comment]
I second this issue.
Tried column instead of columns exactly like in the readme.md, it doesn't recognize column.

**Comment by s-en-o** [comment]
I didn't pay attention to media queries variables that has been provided. I change the settings value for $global-width and $global-width-small to what it was before and it works.

Hope this helps.

**Comment by rafibomb** [comment]
I can't reproduce this in any of my templates running latest version. Closing here - please re-open with more details if you still see an issue.
