### ISSUE TITLE
Adding HubSpot custom codes

### ISSUE THREAD

**Issue by marcelo2605** [foundation/foundation-emails#820]
I need to add some HubSpot custom codes inside email body. For example:

`{{ site_settings.company_name }}`

But the line was removed while Gulp process.

I try to add `<!-- htmlmin:ignore -->` without success.

**Comment by davehoran** [comment]
In the /src/helpers directory there is a file named raw.js. Take a look at the in-comment example and see if you can use this to add the HubSpot codes. The raw helper will let you pass things through without any interference from Panini. 

If the HubSpot codes take parameters, you can always use the provided helper files as examples to create your own. They are actually quite simple to create.

**Comment by marcelo2605** [comment]
Thanks @davehoran 

This work for me:

```
{{{{raw}}}}
	{{ site_settings.company_name }}&nbsp;
{{{{/raw}}}}
```
