### ISSUE TITLE
MailChimp Merge Tags

### ISSUE THREAD

**Issue by carterm90** [foundation/foundation-emails#826]
In MailChimp you can use merge tags so they are editable in the template. The only issue I have is when using buttons - if I do this for example:

`      <row>
        <columns large="6">
          <center>
            <button mc:edit="recipe_link_2" href="#">View Recipe</button>
          </center>
        </columns>
      </row>`

Unfortunately it wipes out the "mc:edit" once it's compiled so I have to go and insert it manually. I was just wondering if you anyone else has come across this?

Thanks!

**Comment by davehoran** [comment]
@carterm90 I would probably use a custom helper function or the raw.js helper function to render this. Many custom templating tags will get removed or altered by the inlining (and other) processes. My current employer uses Localytics, which uses Handlebars notation for template variables just like Foundation for Emails, so I've had to create a custom helper function to take care of this same issue. Here is a link to an example: http://bit.ly/2frPLEF

**Comment by carterm90** [comment]
@davehoran Thanks for your reply. I'll give it a go!

**Comment by t-wright** [comment]
@carterm90 you've probably already found your solution but if not perhaps you could put mc:edit on an element (e.g. a span) within the `<button>`?

**Comment by rafibomb** [comment]
Yeah - I second @t-wright on this. Though, it would be interesting if inky can pass over these attributes for such templating engines like Campaign monitor and Mailchimp. It would need to be a 3rd party plugin or add on for Inky.
