### ISSUE TITLE
Offline Documentation Broken?

### ISSUE THREAD

**Issue by lspoor** [foundation/foundation-emails#827]
**How can we reproduce this bug?**
Follow https://github.com/zurb/foundation-emails#documentation

No errors are reported on the command line, it runs smoothly.

**Write out the HTML (or Inky code) that causes the issue.**
N/A

**What did you expect to happen?**
The documentation to be loaded in the browser

**What happened instead?**
The documentation is broken, see the screenshot below.

**What email clients does this happen in?**
N/A

![foundation for emails 2 docs - broken](https://user-images.githubusercontent.com/1685176/30439967-28885e38-996d-11e7-9a59-02c9420c2ac1.png)

**Comment by rafibomb** [comment]
Thanks fixed!

**Comment by lspoor** [comment]
@rafibomb excellent thanks! What was the issue?
