### ISSUE TITLE
Ampersand in link URLs - Inliner modifies them

### ISSUE THREAD

**Issue by gegeke** [foundation/foundation-emails#829]
**How can we reproduce this bug?**
Try a URL with an ampersand ("&") in it. The inliner encodes it to "`&amp;`" (Space before the semicolon is intentional - otherwise the difference cannot be seen.)
Then use the "Copy to Clipboard" - that encodes it again (so it will be "`&amp;amp;`")

Write out the HTML (or Inky code) that causes the issue.
`<a href="http://example.com/example-&-example">example.com</a>`

**What did you expect to happen?**
Neither the Inliner, nor the "Copy to Clipboard" function changes "&" in link URLs.

**What happened instead?**
Ampersand in link URLs (href) is encoded twice.

**What email clients does this happen in?**
It's not connected to an email client, it's connected to the Foundation Inliner service.

I understand that ampersand should not be used in URLs, but it is not an error, it's only against best practice(s).

The same happens with `&nbsp;` in HTML texts - it's encoded to `&amp;nbsp;` (although it's only encoded once by using "Copy to Clipboard"). In this case the expected behavior would be `&nbsp;` -> `&nbsp;`

**Comment by rafibomb** [comment]
Looks there is an open issue already for this here: https://github.com/zurb/foundation-emails/issues/560

The inliner used is inline-css. There is a suggested solution here: https://github.com/jonkemp/inline-css/issues/41

If it works for you let us know. Ultimately we all need this inliner to provide an option for solution and it seems they are looking for some community help there.
