### ISSUE TITLE
[Getting Started with Sass] It doesn't generate an empty template

### ISSUE THREAD

**Issue by maikelthedev** [foundation/foundation-emails#834]
**How can we reproduce this bug?**
Running foundation new --framework emails

Write out the HTML (or Inky code) that causes the issue.
the commmand itself
**What did you expect to happen?**
have an empty template
**What happened instead?**
I have a template full of stuff I don't need. I just want an empty template

**Comment by nikitasol** [comment]
would be a good additional feature to have. For now I just wipe the contents of index.html which is a 5 second job. The default templates are included probably to make our life easier in case someone would like to use some of the proposed structures.

**Comment by Echelpoel** [comment]
Yes, I just delete every file in the /pages folder and clear the index.html file to get going.

**Comment by DanielRuf** [comment]
> The default templates are included probably to make our life easier in case someone would like to use some of the proposed structures.

Exactly, these templates are examples so you have some working templates to play with.
