### ISSUE TITLE
Online Inliner v2 not outputting styles correctly

### ISSUE THREAD

**Issue by lspoor** [foundation/foundation-emails#840]
I'm currently using the inliner for an email and had some problems with paddings in outlook. Although I was using the following.

```
td {
    padding:10px;
}
```

Should the inliner not convert this to `padding:10px 10px 10px 10px;` otherwise I was getting issues in Outlook with the padding not being respected.

**Comment by DanielRuf** [comment]
Afaik we do not actively expand such values.
For the online inliner we use `html-minifier` which minifies the code but does not do more.

See 
![grafik](https://user-images.githubusercontent.com/827205/71244080-00525280-2312-11ea-9182-c7a61b100413.png)

You should be able to change the paddings in the settings of foundation-emails (SCSS). Best is to always write the explicit padding-* rules.
