### ISSUE TITLE
_normalize.scss has margin property written as Margin, some of them has duplicated margin and Margin

### ISSUE THREAD

**Issue by dylannnn** [foundation/foundation-emails#845]
**How can we reproduce this bug?**
Correct Margin as margin.
Remove duplicated margin and Margin
Write out the HTML (or Inky code) that causes the issue.
Margin: 0;

Or 
margin: 0;
Margin: 0;

**What did you expect to happen?**

margin: 0;

**What happened instead?**

**What email clients does this happen in?**

**Comment by lspoor** [comment]
Outlook has struggles with reading margin, there is a hack available by capitalising the 'm' in margin, e.g. `Margin: 0 auto;`

**Comment by DanielRuf** [comment]
Exactly. This is a workaround / hack for specific clients.

So this is correct.

**Comment by DanielRuf** [comment]
Also see https://foundation.zurb.com/emails/docs/tips-tricks.html#margin-and-padding-
