### ISSUE TITLE
V1 Inky Inliner is not working ... Just says "loading" but never loads

### ISSUE THREAD

**Issue by mjwittkop** [foundation/foundation-emails#850]
**How can we reproduce this bug?**

Write out the HTML (or Inky code) that causes the issue.

**What did you expect to happen?**

**What happened instead?**

**What email clients does this happen in?**

**Comment by designchief** [comment]
Just ran into this issue, had to edit and re-supply an old email on V1 Inky framework, but V1 Inliner is not working. I am not getting proper results when using the V2 inliner (as suggested in forums). 

Any solutions would be great, is there another link that has the V1 inliner?

**Comment by DanielRuf** [comment]
Closing as outdated.
