### ISSUE TITLE
Segmentation fault with 'npm run build'

### ISSUE THREAD

**Issue by flyingL123** [foundation/foundation-emails#851]
When I run `npm run build` in my foundation email project, I suddenly receive this error:

```
[10:55:25] Requiring external module babel-register
[10:55:28] Using gulpfile ~/dev/emails/gulpfile.babel.js
[10:55:28] Starting 'default'...
[10:55:28] Starting 'build'...
[10:55:28] Starting 'clean'...
[10:55:28] Finished 'clean' after 4.79 ms
[10:55:28] Starting 'pages'...
[10:55:28] Finished 'pages' after 287 ms
[10:55:28] Starting 'sass'...
[10:55:28] 'sass' errored after 348 ms
[10:55:28] Error in plugin 'gulp-uncss'
Message:
    spawn ENOTDIR
Details:
    errno: ENOTDIR
    code: ENOTDIR
    syscall: spawn
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
[10:55:28] 'build' errored after 642 ms
[10:55:28] 'default' errored after 643 ms
Segmentation fault: 11
```

I recently upgraded my Mac to HighSierra. Could that be causing the problem? My Mac is running **MacOS High Sierra Version 10.13.1 (17B48)**

The project is using **node v9.0.0**. Does anyone have any insight as to what is causing this issue?

**Comment by flyingL123** [comment]
Looks like gulp-uncss is deprecated:

https://github.com/ben-eb/gulp-uncss

I resolved my issue by removing gulp-uncss and using gulp-postcss and postcss-uncss instead. It seems to have fixed the problem.

**Comment by jel04h** [comment]
I had the exact same issue, also immediately after upgrading to High Sierra. Reinstalling dependencies fixed it for me (deleted node_modules and ran "npm install").

**Comment by flppv** [comment]
I just commented lines 78-81 in gulpfile.babel.js (pipe with postCSS) and it works.

**Comment by philzelnar** [comment]
Same issue on High Sierra, and can confirm reinstalling node mods does the trick: 

1. in your project, delete the folder "node_modules"
2. run "npm install"

For good measure you can also clear npm cache, but prob not necessary.

**Comment by DanielRuf** [comment]
When you do a OS upgrade you have to rebuild the node_modules. Try deleting node_modules directory and run `npm install`.

**Comment by DanielRuf** [comment]
Closing as we did not receivy any further feedback.
