### ISSUE TITLE
ERROR - foundation-emails-template@1.0.0 start: `gulp`

### ISSUE THREAD

**Issue by Veer16** [foundation/foundation-emails#854]
Hi 

I am new to Foundation email. I am following the official documentation step by step. But when is tried to **_npm start_** in the project directory then I get a really flashy error as below:

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! foundation-emails-template@1.0.0 start: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the foundation-emails-template@1.0.0 start script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the foundation-emails-template package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs foundation-emails-template
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls foundation-emails-template
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Parmveer\Downloads\Email Foundation 6\EmailSass\EmailTemplate\npm-debug.log

Here's the log file:
[npm-debug.log](https://github.com/zurb/foundation-emails/files/1501134/npm-debug.log)

I have tried to fix the git path in environment variable of the os.
I am stuck here. Could you please help me out with this.

**Comment by Traufvihal** [comment]
Hello @Veer16 , I run into the same issue and also tried running:
`npm install`
In the project folder but also failed, then checked the node version I had installed on my laptop running:
`node --version`
And it was v6.11.2, so checked how to update it and the quickest way was running this:
`sudo npm install n -g`
To install the tool n and then update it to the latest stable version:
`sudo n stable`
After that, running again:
`npm install`
This will take a while and will download and install all the missing dependencies. After that running again `npm start` worked!
Hope this help you.
Regards!

**Comment by KonstantinKlepikov** [comment]
Hi, and what was the solution?

**Comment by DanielRuf** [comment]
Not much info here. Did you try to install the latest 7.x release of Node.js?

**Comment by Traufvihal** [comment]
I've did when fixed, however with further use I noticed that I need to run every npm start using sudo. Otherwise won't work but I suppose this is more related to how the foundation CLI is installed and where the project is located.
Suppose this should be closed as permission/version issue.

**Comment by DanielRuf** [comment]
> I've did when fixed, however with further use I noticed that I need to run every npm start using sudo. Otherwise won't work but I suppose this is more related to how the foundation CLI is installed and where the project is located.

This is related how you installed it with npm.

**Comment by DanielRuf** [comment]
Closing as we did not receive any further feedback.
