### ISSUE TITLE
master vs develop?

### ISSUE THREAD

**Issue by erickreutz** [foundation/foundation-emails#858]
Can someone help me understand the difference between master and develop? Develop seems to contain some critical bug fixes but there doesn't seem to be any push to get the 90+ commits upstream into master and released?

**Comment by DanielRuf** [comment]
`master` is for releases and `develop` for the bleeding edge deveopment version.

**Comment by DanielRuf** [comment]
We have also updated the branches so there should be more recent code on the `master` branch now.
