### ISSUE TITLE
node 8 support, deprecated node 6

### ISSUE THREAD

**Issue by KimSchneider** [foundation/foundation-emails#863]
**How can we reproduce this bug?**
`npm install` under node 8.x

**What did you expect to happen?**
npm modules installed and `npm start` firing up compilation and webserver.

**What happened instead?**
`npm install` crashed due to not found dependencies. A lot of dependencies are deprecated in node 6.x, too.

> $ npm install
> npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use lodash@^4.0.0.
> 
> > uws@0.14.5 install D:\dev\SEFrontend\emails\node_modules\uws
> > node-gyp rebuild > build_log.txt 2>&1 || exit 0
> 
> 
> > node-sass@3.13.1 install D:\dev\SEFrontend\emails\node_modules\node-sass
> > node scripts/install.js
> 
> Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node
> Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node":
>

**Comment by DanielRuf** [comment]
Try rebuilding node-sass with `npm rebuild node-sass --force` after running `npm install --global --production windows-build-tools`

**Comment by DanielRuf** [comment]
Closing as we did not receive any further feedback.
