### ISSUE TITLE
Update Gulp-Sass dependency to 3.1.0

### ISSUE THREAD

**Issue by dan10gc** [foundation/foundation-emails#866]
# Problem
I recently came upon an issue when running "npm start", I would get the following message error. 

12:43:02] Starting 'default'...
[12:43:02] Starting 'build'...
[12:43:02] Starting 'clean'...
[12:43:02] Finished 'clean' after 135 ms
[12:43:02] Starting 'pages'...
[12:43:06] Finished 'pages' after 3.95 s
[12:43:06] Starting 'sass'...
[12:43:11] 'sass' errored after 4.64 s
[12:43:11] **Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (57)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.13.1**

## Solution
I narrowed down the solution by updating **gulp-sass from 2.1.0 to 3.1.0.** I am not sure if anyone else has come across this issue but updating **gulp-sass** solved it for me.

**Comment by davehoran** [comment]
Nice catch! Thanks for posting the problem AND solution.

**Comment by colin-marshall** [comment]
Until this gets updated, another option is to run `npm rebuild node-sass`. There aren't pre-built binaries for every OS.

**Comment by vcoppolecchia** [comment]
Hey guys I came across this problem today too and **I managed to solve it** (read on for my solution).

## Environment
I'm on Windows 10, recently I had to update my Node version (npm 5.7.1 and node 8.10.0).

## The problem
Foundation E-mails started breaking because `npm run start` (or any other npm script really) didn't worked anymore.

## The solution
Easy: go to `packaje.json` and update `gulp-sass` (inside `devDependencies`) to version `^3.0.0`. Of course after this delete everything inside `node_modules` folder and `npm install` again.

Hope this helps, bye! 😁

**Comment by JMKP** [comment]
hi guys please help me i have tried to change the version package.json and i am still getting errors

Starting 'sass'...
[20:32:45] 'sass' errored after 167 ms
[20:32:45] Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (57)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.13.1

**Comment by colin-marshall** [comment]
@JMKP did you try running `npm rebuild node-sass`?

**Comment by JMKP** [comment]
@colin-marshall thanks for the response, yes I have tried that. I installed node.js, got because I want to do website using sass I am not sure if I am missing something. When I do foundation watch keep giving me errors

**Comment by colin-marshall** [comment]
What happens when you run `npm rebuild node-sass`? Does it compile successfully? Also, if you're not using foundation-emails this is the wrong repo to be looking for help.

**Comment by JMKP** [comment]
![img_20180425_231544](https://user-images.githubusercontent.com/38734532/39273307-afcaf01a-48de-11e8-9a8f-c0be2b4ce321.jpg)
It doesn't run see the image

**Comment by JMKP** [comment]
![img-20180425-wa0017](https://user-images.githubusercontent.com/38734532/39273646-b49c6032-48df-11e8-9b2c-78b1b8b532a8.jpeg)
And this is the error I am getting when I do foundation watch so that it can compile the files to create CSS folder on my web editor

**Comment by vcoppolecchia** [comment]
Hey JMKP, @colin-marshall is right about the repo: from your second screenshot it looks like you're in foundation-sites, not the framework for the e-mails. 

This is the wrong repo, go here: https://github.com/zurb/foundation-sites/issues

**Comment by colin-marshall** [comment]
@JMKP you have to run it from inside your project's folder. It looks like you're just running that in your home directory.

**Comment by DanielRuf** [comment]
You have to upgrade node-sass.
