### ISSUE TITLE
Generate plain text emails

### ISSUE THREAD

**Issue by lipis** [foundation/foundation-emails#869]
It's not uncommon to send the text version among with the HTML version when sending emails.. how about generating the text version when building for production? 

Does anyone have to do that as well.. what's your solution to it.. (besides doing it manually)?

**Comment by rickysullivan** [comment]
I'm looking at using [https://github.com/cheeriojs/cheerio](https://github.com/cheeriojs/cheerio) and [https://github.com/werk85/node-html-to-text](https://github.com/werk85/node-html-to-text) to render my plain text versions.

**Comment by lipis** [comment]
thanks @rickysullivan

**Comment by jonathanimo** [comment]
@rickysullivan any luck with implementing those packages for generating a plain text email?

**Comment by rickysullivan** [comment]
@jonathanimo I did. But there's a bit of tidying up to do with my templates. I have a lot of handlebars markup that needs to render in Mandrill.

Basically, I added some classes to my tempalte which I call in the function:
```
htmlToText.fromString(html, {
...(other opts)
baseElement: ["table.pt-header", "table.pt-body", "table.pt-footer"]
})
```

**Comment by DanielRuf** [comment]
Currently this is not a feature that we support. This depends on your implementation and there is often a different content for the plaintext version.

Currently this is out of the scope of Foundation Emails.
