### ISSUE TITLE
Issue with Gmail layout is completely wrong since a few days

### ISSUE THREAD

**Issue by gremo** [foundation/foundation-emails#873]
**How can we reproduce this bug?**

Send the basic template to a Gmail account and use the webmail. Basic template from official docs.

**What did you expect to happen?**

Email is displayed correctly.

**What happened instead?**

Email layout is completely wrong.

![cattura](https://user-images.githubusercontent.com/1532616/36195679-8a09be9e-116e-11e8-91b5-b87415d7cd93.JPG)

**Comment by nikitasol** [comment]
Hello Gremo!

Can you, please, give more info to try to reproduce your bug? Or can you post the flu html of your basic.html from the dist folder to see if it is any different? I have just compiled a test project from 0 using foundation cli and there is nothing wrong with the template - it displays perfectly fine both in gmail and inbox.

**Comment by gremo** [comment]
Hi @nikitasol, thanks for the reply.

I was having display issues with Gmail and emails sent (using a PHP script) with templates by Foundation for Emails.

So, to really test if it was my fault, I downloaded the [starter kit](https://s3.amazonaws.com/zurb-foundation/foundation-emails.zip). I sent a test email from Thunderbind (copy and paste from the basic.html template) to my Gmail account. Same identical issue.

No display issue so far with Thunderbird, Outlook and web-based email clients.

**Comment by nikitasol** [comment]
Hello Gremo,

The problem you are having is due to not inlining the css. Follow this link: <https://foundation.zurb.com/emails/inliner-v2.html>

There you can insert you html and css separately and it will inline it. You can try a different one, both litmus and mailchimp have one.

Without inlining you will always have different clients stripping css from head and/or body.

**Comment by gremo** [comment]
You are right, I know sorry... totally forgot! But I'm pretty sure that I'm inlining my css using PHP. I'll check tomorrow and report back, thank you.

**Comment by nikitasol** [comment]
I have tried inlining with litmus and it works as intended so there must be some issue with your php script. Try comparing between the two versions.

**Comment by gremo** [comment]
Was a fault in library that I used to send mails. Thanks @nikitasol, closing this.
