### ISSUE TITLE
foundation-emails@2.2.1 npm install error after update to node@v9.4.0 and npm@5.6.0 (update node-sass)

### ISSUE THREAD

**Issue by benny-ben** [foundation/foundation-emails#874]
Before I write all, I'd like to say that before the update everything worked well; while updating node from version 7.2.1 to version 9.4.0 and npm from version 5.5.1 to version 5.6.0 in Windows 7 (64-bit) using the installer (https://nodejs.org/en/download/) and installing globally gulp-cli version 2.0.0, as far as `npm install` starts I get the following error:

<pre>
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.6.0
3 info using node@v9.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle foundation-emails-template@1.0.0~prestart: foundation-emails-template@1.0.0
6 info lifecycle foundation-emails-template@1.0.0~start: foundation-emails-template@1.0.0
7 verbose lifecycle foundation-emails-template@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle foundation-emails-template@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Bob\Dropbox\Development\vhosts\mongoose-project\vanilla\themes\JointsWP\node_modules\node-sass\node_modules\.bin;C:\Users\Bob\Dropbox\Development\vhosts\mongoose-project\vanilla\themes\JointsWP\node_modules\.bin;C:\Users\Bob\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\GNU\GnuPG\pub;C:\Program Files\Git\cmd;C:\Program Files (x86)\Brackets\command;C:\Program Files\nodejs;C:\Users\Bob\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle foundation-emails-template@1.0.0~start: CWD: D:\Develop\FoundationEmail
10 silly lifecycle foundation-emails-template@1.0.0~start: Args: [ '/d /s /c', 'gulp' ]
11 silly lifecycle foundation-emails-template@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle foundation-emails-template@1.0.0~start: Failed to exec start script
13 verbose stack Error: foundation-emails-template@1.0.0 start: `gulp`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:160:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:160:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid foundation-emails-template@1.0.0
15 verbose cwd D:\Develop\FoundationEmail
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v9.4.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error foundation-emails-template@1.0.0 start: `gulp`
22 error Exit status 1
23 error Failed at the foundation-emails-template@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
</pre>

So I found out that the gulp-sass: ^2.0.1 installation installs node-sass@3.13.1 as well, but I'm frightened that node-sass@3.13.1 is not supported by node 8 and further versions. So I tried to indicate gulp-sass: ^3.0.0 in the package.json file and run `npm install` again and now everything seems ok!

**Comment by nikitasol** [comment]
Hello @benny-ben!

If you are still having issues you can try installing the LTS version (8.9.4 currently. I remember having issues before too after installing current versions.

**Comment by DanielRuf** [comment]
Try rebuilding `node-sass` with `npm rebuild node-sass --force` after running `npm install --global --production windows-build-tools`

**Comment by DanielRuf** [comment]
Closing as we did not receive any further feedback.
