### ISSUE TITLE
Generate and commit the lockfile.

### ISSUE THREAD

**Issue by jonkemp** [foundation/foundation-emails#883]
Last week a gulp plugin was updated using the patch version number with a dependency that broke builds for whoever ran npm install. Using a lockfile would have prevented this from happening. The lockfile can be generated with yarn or npm 5. Committing this file will prevent packages from updating to a new version unless specifically updated in the package.json file.

**Comment by DanielRuf** [comment]
Lockfiles are not used by module installs and only work on the root level. Version ponning can partly prevent this but deep down the deps are still not locked.

**Comment by DanielRuf** [comment]
Also `npm install` does not respect lockfiles, just `npm ci`.
