### ISSUE TITLE
Has foundation-emails been abandoned? 

### ISSUE THREAD

**Issue by tomgenoni** [foundation/foundation-emails#884]
I was going to report a bug and submit a fix but there hasn't been any activity for months. Just want to confirm a bug and/or PR is worth it or if I should fork for my fixes.

**Comment by igrschmidt** [comment]
Well... The last merged PR was in June, that says a lot 😢

**Comment by andrewerrico** [comment]
😕 Any alternatives?

**Comment by fsasvari** [comment]
MJML looks nice - https://mjml.io/

**Comment by andrewerrico** [comment]
Well, I got the builds working and added some custom components in a fork of inky. Let's see if it lasts.

P.S. I just came across this [https://heml.io/](https://heml.io/), might look promising.

**Comment by tomgenoni** [comment]
@rafibomb @gakimball As the most recent significant contributors would one of you mind commenting on the status of this project? Would be helpful to know if no more work is planned.

**Comment by ddowdall** [comment]
@tdhartwick Hi Tim, Can you give some details about the future plans for foundation for emails?

**Comment by memoht** [comment]
Adding my name to the list of people wondering when there will be another release or whether this project is winding down.

**Comment by JayBizzle** [comment]
Also wondering what the status of this project is :+1:

**Comment by AndreasGalster** [comment]
@andrewerrico Did you publish your fixes on npm? So I guess the build no longer working is a known issue, huh? I really want to build my stuff ... I can't believe that I've just worked on fixing up all my templates and then seeing this is completely unmaintained by a big org like ZURB :(

**Comment by AndreasGalster** [comment]
@gakimball @rafibomb seeing how you are the top contributors here... Can you please give feedback?

**Comment by JimmyMultani** [comment]
@tdhartwick @rafibomb can one of you please comment on the status of this project?

**Comment by paulfelton** [comment]
@ncoden Nick, you're working on Sites at the moment, but do you know Zurb's current position with Emails?  Thanks.

**Comment by gakimball** [comment]
I haven't worked on this project since I left ZURB over two years ago, so I can't speak to what their plans are.

**Comment by DanielRuf** [comment]
Foundation Emails is still actively maintained and developed. Closing this because the original question is answered now.
