### ISSUE TITLE
How to print the errors during build?

### ISSUE THREAD

**Issue by lipis** [foundation/foundation-emails#885]
<img width="309" alt="screen shot 2018-03-21 at 19 39 59" src="https://user-images.githubusercontent.com/125676/37727100-aa2edd2a-2d3f-11e8-80b1-2bbef50a4a28.png">

```
✔ 40 pages built, but 1 had errors.
```

Is there any way to see what went wrong? And/Or stop the process if error?

**Comment by DanielRuf** [comment]
I can not see this information in the current version. So this is currently not reproducible for us. Please provide a reproducible testcase as small repository.
