### ISSUE TITLE
[Getting Started with Sass] ISSUE NAME HERE

### ISSUE THREAD

**Issue by DoktorVonMixer** [foundation/foundation-emails#886]
**How can we reproduce this bug?**
Try to install the regular foundation-CLI package
Using the command provided after installing latest npm packages.
Write out the HTML (or Inky code) that causes the issue.
sudo npm install --global foundation-cli

**What did you expect to happen?**
An installation of foundation, in order to run the sass processor, inky markdown, etc.

**What happened instead?**
npm WARN deprecated bower@1.8.2: ...psst! Your project can stop working at any moment because its dependencies can change. Prevent this by migrating to Yarn: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm ERR! path /usr/local/lib/node_modules/foundation-cli/node_modules/npm/node_modules/ansistyles
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/foundation-cli/node_modules/npm/node_modules/ansistyles' -> '/usr/local/lib/node_modules/foundation-cli/node_modules/npm/node_modules/.ansistyles.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

Nothing that i can do from here. Foundation does not "work", not a valid terminal command. So i guess the installation process didn't complete.

FYI i also installed the latest yarn with a quick google search… but i guess it doesnt work that way, in terms of dependencies.

Using terminal on OSX.

**Comment by lenaive** [comment]
Try to remove /usr/local/lib/node_modules/foundation-cli/ directory via `sudo rm -rf /usr/local/lib/node_modules/foundation-cli/ ` then reinstall foundation-cli

**Comment by DanielRuf** [comment]
Closing as we did not receive any further feedback.
