### ISSUE TITLE
Ampersands incorrectly converted by web inliner

### ISSUE THREAD

**Issue by joenxt** [foundation/foundation-emails#889]
**How can we reproduce this bug?**
This can be reproduced by placing an "&" into the web inliner, and then copying to clipboard. When pasted the final result is &amp;amp; 

Inside the inliner this appears correct, but breaks when copied to clipboard

**Comment by AshleyJBartlett** [comment]
Is this issue where it will convert **&amp;amp;** to **&amp;amp;amp;** and the same with other such characters? As this is really annoying that you have to go back and rectify this after copying from the inliner tool. Overall **Foundation for Emails** is a fantastic tool though.
