### ISSUE TITLE
Remove autolinks on iOS devices - how to insert extra stylesheet?

### ISSUE THREAD

**Issue by jmartsch** [foundation/foundation-emails#891]
To remove autolinks on iOS devices I found this bulletproof solution
http://removebluelinks.com/
However according to Litmus, it has to be embedded as a separate style declaration in the head.
I tested it and it works if I insert the code in the head section of the final build:
```
<style>
          a[x-apple-data-detectors] {
                color: inherit !important;
              text-decoration: none !important;
              font-size: inherit !important;
              font-family: inherit !important;
              font-weight: inherit !important;
              line-height: inherit !important;
          }
      </style>
```
It does not work, if I add the code to the _template.scss.
I inserted the code into src/layouts/default.html but it gets stripped.
So what is the best way, to get this code into the header, without requireing manual action?

**Comment by DanielRuf** [comment]
> in the head section of the final build

Do you mean the inlined files?
Generally you can use the scss files to add this.
