### ISSUE TITLE
<hr> ignore SCSS settings

### ISSUE THREAD

**Issue by gwidonw** [foundation/foundation-emails#896]
**How can we reproduce this bug?**
Add 
```
<hr />
```
and change hr SCSS settings
```
$hr-width: 100px;
$hr-border: 1px solid $medium-gray;
$hr-margin: 100px auto;
```

**What did you expect to happen?**
'hr' element should change its styling according to settings. As far as I see in foundation-emails sources, it should be replaced with `<table class="hr"><th></th></table>`

**What happened instead?**
'hr' settings are ignored. 'hr' element is not replaced with 'table'

**What email clients does this happen in?**
Dev server

**Comment by pashkes** [comment]
me too

**Comment by onebitrocket** [comment]
same here

**Comment by gwidonw** [comment]
@onebitrocket @pashkes Well I think the project is dead. I've migrated to https://mjml.io/ and I really like it so if you just started using foundation-emails better look for alternatives.

**Comment by onebitrocket** [comment]
I made a work-around class to override the default css output

`.hr {
  height: 0;
  max-width: $hr-width;
  border-top: 0;
  border-right: 0;
  border-bottom: $hr-border;
  border-left: 0;
  margin: $hr-margin;
  Margin: $hr-margin;
  clear: both;
}`

**Comment by DanielRuf** [comment]
Please try `<h-line>` in inky. See https://github.com/foundation/inky/blob/develop/lib/inky.js#L29

**Comment by DanielRuf** [comment]
See also https://github.com/foundation/foundation-emails/blob/develop/scss/components/_typography.scss#L363
