### ISSUE TITLE
Can't convert my HTML to Inline for some reason...

### ISSUE THREAD

**Issue by dropswitchuk** [foundation/foundation-emails#897]
**How can we reproduce this bug?**

Write out the HTML (or Inky code) that causes the issue.

<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office"><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="Generator" content="Made with Mail Designer from equinux">
	<meta name="Viewport" content="width=device-width, initial-scale=1.0">
	<style type="text/css" id="Mail Designer General Style Sheet">
		a { word-break: break-word; }
		a img { border:none; }
		img { outline:none; text-decoration:none; -ms-interpolation-mode: bicubic; }
		body { width: 100% !important; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; }
		.ExternalClass { width: 100%; }
		.ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div { line-height: 100%; }
		#page-wrap { margin: 0; padding: 0; width: 100% !important; line-height: 100% !important; }
		#outlook a { padding: 0; }
		.preheader { display:none !important; }
		a[x-apple-data-detectors] { color: inherit !important; text-decoration: none !important; font-size: inherit !important; font-family: inherit !important; font-weight: inherit !important; line-height: inherit !important; }
		.a5q { display: none !important; }
		.Apple-web-attachment { vertical-align: initial !important; }
		.Apple-edge-to-edge-visual-media { margin: initial !important; max-width: initial !important; width: 100%; }
	</style>
	<style type="text/css" id="Mail Designer Mobile Style Sheet">
		@media only screen and (max-width: 580px) {
			table.email-body-wrap {
				width: 320px !important;
			}
			td.page-bg-show-thru {
				display: none !important;
			}
			table.layout-block-wrapping-table {
				width: 320px !important;
			}
			table.mso-fixed-width-wrapping-table {
				width: 320px !important;
			}
			.layout-block-full-width {
				width: 320px !important;
			}
			table.layout-block-column, table.layout-block-padded-column {
				width: 100% !important;
			}
			table.layout-block-box-padding {
				width: 100% !important;
				padding: 5px !important;
			}
			table.layout-block-horizontal-spacer {
				display: none !important;
			}
			tr.layout-block-vertical-spacer {
			   display: block !important;
			   height: 8px !important;
			}
			td.container-padding {
				display: none !important;
			}
			
			table {
				min-width: initial !important;
			}
			td {
				min-width: initial !important;
			}
			
			.desktop-only { display: none !important; }
			.mobile-only { display: block !important; }
			
			.hide {
				max-height: none !important;
				display: block !important;
				overflow: visible !important;
			}
			
			.EQ-00 { width: 15px !important; }
			.EQ-01 { width: 15px !important; }
			.EQ-02 { width: 290px !important; }
			
			.EQ-03 { width: 15px !important; }
			.EQ-04 { width: 15px !important; }
			.EQ-05 { width: 290px !important; }
			
			.EQ-06 { width: 15px !important; }
			.EQ-07 { width: 15px !important; }
			.EQ-08 { width: 290px !important; }
		}
	</style>
	
<link href="https://fonts.googleapis.com/css?family=Droid+Sans:700,regular" rel="stylesheet" type="text/css" class="EQWebFont"><link href="https://fonts.googleapis.com/css?family=Roboto:700,regular" rel="stylesheet" type="text/css" class="EQWebFont"><meta http-equiv="Content-Type" content="text/html; charset=utf-8"></head>
<body style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; " background="https://2b-connected.com/mails/samplesconfirm/page-bg.jpg"> 

<span id="preheader" class="preheader" style="display:none !important; ">Please click the link below to confirm your subscription!</span><table width="100%" cellspacing="0" cellpadding="0" id="page-wrap" align="center" background="https://2b-connected.com/mails/samplesconfirm/page-bg.jpg">
<tbody><tr>
	<td>

<table class="email-body-wrap" width="858" cellspacing="0" cellpadding="0" id="email-body" align="center">
<tbody><tr>
	<td width="30" class="page-bg-show-thru">&nbsp;</td>
	<td width="798" id="page-body" background="https://2b-connected.com/mails/samplesconfirm/background.jpg" bgcolor="#ffffff">
		
		
		<div id="eqLayoutContainer">
			
			<div class="desktop-only" width="100%">
				<table width="798" cellspacing="0" cellpadding="0" class="layout-block-wrapping-table" style="mso-hide:all; min-width: 798px; ">
					<tbody><tr>
						<td valign="top" class="layout-block-full-width" width="798" style="min-width: 798px; ">
							<table cellspacing="0" cellpadding="0" class="layout-block-full-width" width="798" style="min-width: 798px; ">
								<tbody><tr>
									<td width="798" style="min-width: 798px; ">
										<div class="layout-block-image">
											<img width="798" height="145" alt="" src="https://2b-connected.com/mails/samplesconfirm/image-3.jpg" border="0" style="line-height: 1px; display: block; width: 798px; height: 145px; ">
										</div>
									</td>
								</tr>
							</tbody></table>
						</td>
					</tr>
				</tbody></table>
			</div>
			
			
			
			<div style="display: none; max-height: 0px; overflow: hidden; " class="mobile-only hide" width="100%">
				<table width="320" cellspacing="0" cellpadding="0" class="layout-block-wrapping-table hide" style="display: none; max-height: 0px; overflow: hidden; min-width: 320px; ">
					<tbody><tr>
						<td valign="top" class="layout-block-full-width" width="320" style="min-width: 320px; ">
							<table cellspacing="0" cellpadding="0" class="layout-block-full-width hide" width="320" style="display: none; max-height: 0px; overflow: hidden; min-width: 320px; ">
								<tbody><tr>
									<td width="320" style="min-width: 320px; ">
										<div class="layout-block-image hide" style="display: none; max-height: 0px; overflow: hidden; ">
											<img width="320" height="145" alt="" src="https://2b-connected.com/mails/samplesconfirm/image-1.png" border="0" style="line-height: 1px; display: none; max-height: 0px; overflow: hidden; width: 320px; height: 145px; " class="hide">
										</div>
									</td>
								</tr>
							</tbody></table>
						</td>
					</tr>
				</tbody></table>
			</div>
			
			<div width="100%">
				<table width="798" cellspacing="0" cellpadding="0" class="layout-block-wrapping-table" style="mso-hide:all; min-width: 798px; ">
					<tbody><tr>
						<td width="37" class="EQ-00" style="min-width: 37px; ">&nbsp;</td>
						<td valign="top" align="left" class="EQ-02" width="724" style="min-width: 724px; ">
							<table cellspacing="0" cellpadding="0" align="left" class="layout-block-column" width="724" style="min-width: 724px; ">
								<tbody><tr>
									<td width="704" valign="top" align="left" background="https://2b-connected.com/mails/samplesconfirm/box-bg-5.jpg" style="padding-left: 10px; padding-right: 10px; min-width: 704px; " bgcolor="#ffffff">
										<table cellspacing="0" cellpadding="0" class="layout-block-box-padding" width="704" style="min-width: 704px; ">
											<tbody><tr>
												<td align="left" class="layout-block-column" width="704" style="min-width: 704px; ">
													<div class="heading" style="font-size: 16px; font-family: 'Lucida Grande'; "><div style="text-align: center; line-height: 35px; "><span style="font-size: 30px; "><font face="Helvetica"><br></font></span></div><div style="color: rgb(0, 0, 0); font-family: Helvetica, Arial, Roboto, 'Droid Sans', Arial, sans-serif; font-size: 30px; font-style: normal; font-weight: 700; line-height: 1; text-align: center; text-decoration: none; "><p style="line-height: 1; ">THANKS FOR&nbsp;<span style="line-height: 1; ">SUBSCRIBING</span></p><p style="line-height: 1; "><span style="line-height: 1; ">TO OUR AUDIO SAMPLES NEWSLETTER!</span></p><div><br></div></div>
														</div>
												</td>
											</tr>
										</tbody></table>
									</td>
								</tr>
							</tbody></table>
						</td>
						<td width="37" class="EQ-01" style="min-width: 37px; ">&nbsp;</td>
					</tr>
				</tbody></table>
			</div>
			
			<div width="100%">
				<table width="798" cellspacing="0" cellpadding="0" class="layout-block-wrapping-table" style="mso-hide:all; min-width: 798px; ">
					<tbody><tr>
						<td width="37" class="EQ-03" style="min-width: 37px; ">&nbsp;</td>
						<td class="EQ-05" width="724" style="min-width: 724px; ">
							<table cellspacing="0" cellpadding="0" align="left" class="layout-block-column" width="724" style="min-width: 724px; ">
								<tbody><tr>
									<td width="704" valign="top" align="left" background="https://2b-connected.com/mails/samplesconfirm/box-bg-5.jpg" style="padding-left: 10px; padding-right: 10px; min-width: 704px; " bgcolor="#ffffff">
										<table cellspacing="0" cellpadding="0" class="layout-block-box-padding" width="704" style="min-width: 704px; ">
											<tbody><tr>
												<td align="left" class="layout-block-column" width="704" style="min-width: 704px; ">
													<div class="text" style="font-size: 16px; font-family: 'Lucida Grande'; "><p style="text-align: center; margin: 0px; font-size: 25px; line-height: 25px; "><font face="Helvetica, Arial, Roboto, Droid Sans, sans-serif" color="#080202"><b>Dear [Name,fallback=Subscriber]</b></font></p><p style="font-size: 16px; text-align: center; margin: 0px; "></p><p style="font-size: 16px; text-align: center; margin: 0px; line-height: 21px; "><font face="Helvetica"><span style="font-size: 15px; "><br></span></font></p><div style="color: rgb(0, 0, 0); font-family: Helvetica, Arial, Roboto, 'Droid Sans', sans-serif; font-size: 15px; font-style: normal; font-weight: normal; line-height: 1; text-align: center; text-decoration: none; "><p>You are receiving this email as we have received a request to add [Email] to our e-mail list.</p></div><div style="color: rgb(0, 0, 0); font-family: Helvetica, Arial, Roboto, 'Droid Sans', sans-serif; font-size: 15px; font-style: normal; font-weight: normal; line-height: 1; text-align: center; text-decoration: none; "><p>Please confirm your subscription by clicking the button below:</p></div></div>
												</td>
											</tr>
										</tbody></table>
									</td>
								</tr>
							</tbody></table>
						</td>
						<td width="37" class="EQ-04" style="min-width: 37px; ">&nbsp;</td>
					</tr>
				</tbody></table>
			</div>
			
			<div class="desktop-only" width="100%">
				<table width="798" cellspacing="0" cellpadding="0" class="layout-block-wrapping-table" style="mso-hide:all; min-width: 798px; ">
					<tbody><tr>
						<td width="37" style="min-width: 37px; ">&nbsp;</td>
						<td background="https://2b-connected.com/mails/samplesconfirm/box-bg-7.jpg" bgcolor="#ffffff" width="724" style="min-width: 724px; ">
							<table cellspacing="0" cellpadding="0" align="left" style="padding-left: 10px; padding-right: 10px; min-width: 724px; " class="layout-block-box-padding" width="724">
								<tbody><tr>
									<td valign="top" class="layout-block-padded-column" align="center" width="704" style="min-width: 704px; ">
										<div class="layout-block-image">
											<a href="[confirmation_link]"><img width="704" height="100" alt="" src="https://2b-connected.com/mails/samplesconfirm/image-4.png" border="0" style="display: block; width: 704px; height: 100px; "></a>
										</div>
									</td>
								</tr>
							</tbody></table>
						</td>
						<td width="37" style="min-width: 37px; ">&nbsp;</td>
					</tr>
				</tbody></table>
			</div>
			
			
			
			<div style="display: none; max-height: 0px; overflow: hidden; " class="mobile-only hide" width="100%">
				<table width="320" cellspacing="0" cellpadding="0" class="layout-block-wrapping-table hide" style="display: none; max-height: 0px; overflow: hidden; min-width: 320px; ">
					<tbody><tr>
						<td width="18" style="min-width: 18px; ">&nbsp;</td>
						<td background="https://2b-connected.com/mails/samplesconfirm/box-bg-1.jpg" bgcolor="#ffffff" width="284" style="min-width: 284px; ">
							<table cellspacing="0" cellpadding="0" align="left" style="padding-left: 10px; padding-right: 10px; display: none; max-height: 0px; overflow: hidden; min-width: 284px; " class="layout-block-box-padding hide" width="284">
								<tbody><tr>
									<td valign="top" class="layout-block-padded-column" align="center" width="264" style="min-width: 264px; ">
										<div class="layout-block-image hide" style="display: none; max-height: 0px; overflow: hidden; ">
											<img width="264" height="100" alt="" src="https://2b-connected.com/mails/samplesconfirm/image-2.png" border="0" style="line-height: 1px; display: none; max-height: 0px; overflow: hidden; width: 264px; height: 100px; " class="hide">
										</div>
									</td>
								</tr>
							</tbody></table>
						</td>
						<td width="18" style="min-width: 18px; ">&nbsp;</td>
					</tr>
				</tbody></table>
			</div>
			
			<div style="background-image:url(https://2b-connected.com/mails/samplesconfirm/background-3.jpg); background-position: 0% 0%; " width="100%">
				<table width="798" cellspacing="0" cellpadding="0" class="layout-block-wrapping-table" background="https://2b-connected.com/mails/samplesconfirm/background-3.jpg" bgcolor="#060101" style="mso-hide:all; min-width: 798px; ">
					<tbody><tr>
						<td width="37" class="EQ-06" style="min-width: 37px; ">&nbsp;</td>
						<td class="EQ-08" width="724" style="min-width: 724px; ">
							<table cellspacing="0" cellpadding="0" align="left" class="layout-block-column" width="724" style="min-width: 724px; ">
								<tbody><tr>
									<td width="704" valign="top" align="left" background="https://2b-connected.com/mails/samplesconfirm/box-bg-10.jpg" style="padding-left: 10px; padding-right: 10px; min-width: 704px; " bgcolor="#000000">
										<table cellspacing="0" cellpadding="0" class="layout-block-box-padding" width="704" style="min-width: 704px; ">
											<tbody><tr>
												<td align="left" class="layout-block-column" width="704" style="min-width: 704px; ">
													<div class="text" style="font-size: 16px; font-family: 'Lucida Grande'; "><div style="text-align: center; line-height: 24px; "><br></div><div style="text-align: center; line-height: 18px; "><span style="font-size: 10px; "><font color="#165878" face="Arial, Arial, Roboto, Droid Sans, sans-serif">This newsletter has been sent to you because you’ve subscribed to our mailing list.</font></span></div><div style="text-align: center; line-height: 18px; "><span style="font-size: 10px; "><font color="#165878" face="Arial, Arial, Roboto, Droid Sans, sans-serif">You can </font></span><font face="Arial, Arial, Roboto, Droid Sans, sans-serif" color="#ffffff" style="font-size: 10px; "><a href="[unsubscribe]" style="color: rgb(255, 255, 255); ">unsubscribe</a></font><span style="font-size: 10px; "><font color="#165878" face="Arial, Arial, Roboto, Droid Sans, sans-serif">&nbsp;or view the </font></span><font face="Arial, Arial, Roboto, Droid Sans, sans-serif" color="#ffffff" style="font-size: 10px; "><a href="href=" "="" style="color: rgb(255, 255, 255); ">webversion</a></font><span style="font-size: 10px; "><font color="#165878" face="Arial, Arial, Roboto, Droid Sans, sans-serif">&nbsp;whenever you like of course.</font></span></div><div style="color: rgb(255, 255, 255); font-family: Helvetica, Arial, Roboto, 'Droid Sans', sans-serif; font-size: 10px; font-style: normal; font-weight: normal; line-height: 18px; text-align: center; text-decoration: none; ">If you have any questions or concerns please email <a href="mailto:questions@2b-connected.com?subject=Email%20List%20Question" style="color: rgb(255, 255, 255); ">questions@2b-connected.com</a></div><div style="color: rgb(255, 255, 255); font-family: Helvetica, Arial, Roboto, 'Droid Sans', sans-serif; font-size: 10px; font-style: normal; font-weight: normal; line-height: 18px; text-align: center; text-decoration: none; ">© 2018+ 2B-connected - 5500 Military Trl, Ste 22-306 - Jupiter - FL 33458 - USA</div><div style="text-align: center; line-height: 18px; "><br></div></div>
												</td>
											</tr>
										</tbody></table>
									</td>
								</tr>
							</tbody></table>
						</td>
						<td width="37" class="EQ-07" style="min-width: 37px; ">&nbsp;</td>
					</tr>
				</tbody></table>
			</div>
			
		</div>
		
		
	</td>
	<td width="30" class="page-bg-show-thru">&nbsp;</td>
</tr>
</tbody></table>

	</td>
</tr>
</tbody></table>

</body></html>

**What did you expect to happen?**

Inline version to be output. It works for any nonsense and worked for an earlier version of this html but has now stopped for some reason.

**What happened instead?**

Nothing. It just hung after I clicked the button, no info.

**What email clients does this happen in?**

NA

Thanks in advance.

Cheers - Matt

**Comment by Peeekay** [comment]
Not sure if you figured it out yet but I had to undo a bunch of changes in my code and got it working again.  Maybe there's an issue with your HTML.

**Comment by DanielRuf** [comment]
Please check if your HTML is valid. You can test this at https://kangax.github.io/html-minifier/
