### ISSUE TITLE
Background images not included in zip file

### ISSUE THREAD

**Issue by jasonlmann** [foundation/foundation-emails#900]
**How can we reproduce this bug?**
I am using bulletproof background images in an email. (Creating the email using the Zurb email stack. Which is great for everything else!)

Write out the HTML (or Inky code) that causes the issue.

Here's the relevant code:
```
<container>
  <wrapper class="hero-image">
    <row class="collapse">
  	   <columns small="12">

         <td class="image-holder" width="580" height="435" background="{{root}}assets/img/IMG_6399@2x.jpg" bgcolor="#30506B"  valign="top">
  <!--[if gte mso 9]>
  <v:rect xmlns:v="urn:schemas-microsoft-com:vml" fill="true" stroke="false" style="width:580px;height:435px;">
    <v:fill type="tile" src="{{root}}assets/img/IMG_6399.jpg" color="#30506B" />
    <v:textbox inset="0,0,0,0">
  <![endif]-->

</td>
  	    </columns>
    </row>
  </wrapper>
</container>
```

**What did you expect to happen?**

I expected to get an inlined html file and a .zip file containing all the referenced images.

**What happened instead?**
When I run `npm run zip`, I get a .zip file as expected, but it does _not_ include the background images. It does contain images that are referenced in `img` tags.

**What email clients does this happen in?**
n/a

**Comment by farmerau** [comment]
I experience the same behavior when setting the property in SASS.

**Comment by DanielRuf** [comment]
See https://github.com/foundation/foundation-emails-template/blob/master/gulpfile.babel.js#L220

We use gulp-html-src and the current code fetches all img elements using a selector.

You can use any gulp plugin and the advanced options to parse the background-image CSS property: https://www.npmjs.com/package/gulp-html-src#optionsgetfilename
