### ISSUE TITLE
email cli: build script is missing or incorrectly configured

### ISSUE THREAD

**Issue by st-h** [foundation/foundation-emails#901]
Currently the project setup for email (SASS) does not provide a task to build all files. This is fine for all manual tasks, but does not work well within CI setups.
Either a dedicated script to just build files should be added, or the build script should be changed to just build whatever is needed. I'll be happy to submit a PR once this is clear.

**How can we reproduce this bug?**
Set up foundation for email with SASS and try to build production files.
`npm run build`

**Write out the HTML (or Inky code) that causes the issue.**
this is package.json related:
`"build": "gulp --production",` launches the default task with production settings
whereas:
`"build": "gulp build --production",` would build the files and then quit

**What did you expect to happen?**
All files needed for production are compiled, then the process would terminate

**What happened instead?**
All files are compiled, then a server is spun up, which watches for development changes and never quits

**What email clients does this happen in?**
not applicable

**Comment by holzhuter** [comment]
I think I'm running into this problem too. Any solutions?

Full explainer: I haven't built an email with Zurb in a little while so I'm not sure if it's changed or I'm forgetting a step, but shouldn't the build process give me a zip file (with all the assets) in the dist folder? I ran the "npm run build" command and it's stopping ["Serving files from: dist"](https://foundation.zurb.com/forum/posts/58836-npm-run-build-zip-file)

I can't tell if I'm just being impatient and it needs more time to complete the process, but it's taking a lot longer than I remember and the progress indicator goes away.

**Comment by st-h** [comment]
@holzhuter any luck using `npm run zip`?

**Comment by holzhuter** [comment]
@st-h ah! I knew I must have been doing something wrong. That works, thanks for your help!

**Comment by DanielRuf** [comment]
You can safely change the scripts and remove the watch task.

Please close this issue if it is resolved.

**Comment by DanielRuf** [comment]
Closing as we did not receive any further feedback.
