### ISSUE TITLE
Email Inliner is changing HTML entities 

### ISSUE THREAD

**Issue by JenniferHock** [foundation/foundation-emails#906]
I'm processing some emails using the [Foundation Inliner](https://foundation.zurb.com/emails/inliner-v2.html). My HTML contains several HTML entities. When the form is inlined, these HTML entites are converted to plain text. However, some of these characters don't render correctly in browsers, so I need them to remain as they're coded in the original document.

This Example HTML:
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head></head>
<body>
<p>DON'T DELAY&mdash;SOAR NOW!</p>
<p>What about this mdash?&#8212;Is it the same?</p>

<p>&copy;2018&ndash;All rights reserved.</p>
</body>
</html>
```

Becomes this Final Email HTML:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head></head>

<body>
  <style></style>
  <p>DON'T DELAY—SOAR NOW!</p>
  <p>What about this mdash?—Is it the same?</p>

  <p>©2018–All rights reserved.</p>

</body>

</html>
```

Are there any solutions to this problem?

**Comment by sebastian-walter** [comment]
I am having a similar problem which leads to this: 
![screen shot 2018-09-07 at 12 56 54](https://user-images.githubusercontent.com/15271363/45215424-b15be780-b29d-11e8-8d78-4fe121f4683a.png)

**Comment by originaljensiegirl** [comment]
Having the same issue. It really messes up query strings, nbsp characters, etc.

**Comment by ghost** [comment]
Yup - having the same issue! Not being able to use &nbsp; is def a dealbreaker for me. The inliner changes &nbsp; to &amp;nbsp. Can I turn this feature off?

**Comment by ghost** [comment]
^^^whoops turns out this site ran my code in the comment:

> Not being able to use `&nbsp;` is def a dealbreaker for me. The inliner changes `&nbsp;` to `&amp;nbsp;`.

**Comment by davehoran** [comment]
You may be able to get around this by using the "raw" value or create your own function to add this. This is especially useful if you use the HTML entities in a sequence on a regular basis as part of your overall design branding.

**Comment by ghost** [comment]
Great! Could you give me an example using the raw value?

**Comment by ghost** [comment]
Apparently, this issue is caused by the "copy to clipboard" btn on the site. You can get around it by selecting all and `ctrl+c`
