### ISSUE TITLE
Problems with umlaut and HTML-Entities (german language)

### ISSUE THREAD

**Issue by bls8m** [foundation/foundation-emails#909]
**How can we reproduce this bug?** 

Write out the HTML (or Inky code) that causes the issue.:
 original: Übernachtungen -> output :Ãœbernachtungen
 original: "& sum;" -> output : ∑  -> what i expect:   "& sum;"

**What did you expect to happen?** 
maybe fix it? it would be nice

**What happened instead?**
nothing

**What email clients does this happen in?**
tested with gmail

**Comment by DanielRuf** [comment]
Closing as we did not receive a reproducible testcase.
