### ISSUE TITLE
[Grid] large="12" attribute doesn't work on large screen!

### ISSUE THREAD

**Issue by selfishprimate** [foundation/foundation-emails#911]
**How can we reproduce this bug?**

I'm just having a strange problem with the grid system. I have two columns with attributes of small="12" and large="12" and both columns are in a row. Bu this columns are still standing side-by-side on large screen instead of on top of each other. Thank you.﻿

**Write out the HTML (or Inky code) that causes the issue.**

`  <row>
    <columns large="12">
      <h4>Sub Section Title</h4>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod eum eius numquam sint dolore voluptatibus beatae ab ad, dignissimos fugiat? Nisi odio commodi debitis eveniet tenetur provident aliquid tempora placeat.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod eum eius numquam sint dolore voluptatibus beatae ab ad, dignissimos fugiat? Nisi odio commodi debitis eveniet tenetur provident aliquid tempora placeat.</p>
    </columns>
    <columns large="12">
      <h4>Sub Section Title</h4>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod eum eius numquam sint dolore voluptatibus beatae ab ad, dignissimos fugiat? Nisi odio commodi debitis eveniet tenetur provident aliquid tempora placeat.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod eum eius numquam sint dolore voluptatibus beatae ab ad, dignissimos fugiat? Nisi odio commodi debitis eveniet tenetur provident aliquid tempora placeat.</p>
    </columns>
  </row>
`

**What did you expect to happen?**

I expect the columns standing on top of each other on the large screen.

**What happened instead?**

They're standing side-by-side on large screen.

**What email clients does this happen in?**

On desktop browser (Chrome)

**Comment by selfishprimate** [comment]
Please someone fix that problem.

**Comment by davehoran** [comment]
As a test, have you tried small=12 medium=12? That should at least prove the responsive formatting is kicking in.

**Comment by selfishprimate** [comment]
I tried it also. It didn't work. Actually, I can see the class large-12 in the HTML output just properly, but somehow sass cannot calculate the width of the <th></th> when it is 12 columns wide.

**Comment by davehoran** [comment]
Have you changed any of the defaults to make the page more or less than 12
columns?

**Comment by selfishprimate** [comment]
Nothing I changed. You can try as well. Just download the latest version and you'll see the same error. I install a new project again and again, and the result is the same.

**Comment by nikitasol** [comment]
Hey @babilkuyusu!
Here is a short info from docs: 

> Foundation uses a 12-column grid, so 6 columns is half the width of the whole row.

So with your code you are trying to create a 24-column grid inside 1 row. If you want your columns to stack you should separate them into 2 rows. Also if you are using full 12-column grid you don't need to use column sizes. So your code should look like this:

```html
<row>
  <columns>
    <h4>Sub Section Title</h4>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod eum eius numquam sint dolore voluptatibus beatae ab ad, dignissimos fugiat? Nisi odio commodi debitis eveniet tenetur provident aliquid tempora placeat.</p> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod eum eius numquam sint dolore voluptatibus beatae ab ad, dignissimos fugiat? Nisi odio commodi debitis eveniet tenetur provident aliquid tempora placeat.</p>
  </columns>
</row>
<row>
  <columns>
    <h4>Sub Section Title</h4>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod eum eius numquam sint dolore voluptatibus beatae ab ad, dignissimos fugiat? Nisi odio commodi debitis eveniet tenetur provident aliquid tempora placeat.</p> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod eum eius numquam sint dolore voluptatibus beatae ab ad, dignissimos fugiat? Nisi odio commodi debitis eveniet tenetur provident aliquid tempora placeat.</p>
  </columns>
</row>
```

**Comment by selfishprimate** [comment]
Ok, but what if i want them to stand side by side on mobile screen by using small="12" attribute?

29 Ağu 2018 12:21 tarihinde nikitasol <notifications@github.com> yazdı:

Hey @babilkuyusu<https://github.com/babilkuyusu>!
Here is a short info from docs:

Foundation uses a 12-column grid, so 6 columns is half the width of the whole row.

So with your code you are trying to create a 24-column grid inside 1 row. If you want your columns to stack you should separate them into 2 rows. Also if you are using full 12-column grid you don't need to use column sizes. So your code should look like this:

<row>
  <columns>
    <h4>Sub Section Title</h4>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod eum eius numquam sint dolore voluptatibus beatae ab ad, dignissimos fugiat? Nisi odio commodi debitis eveniet tenetur provident aliquid tempora placeat.</p> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod eum eius numquam sint dolore voluptatibus beatae ab ad, dignissimos fugiat? Nisi odio commodi debitis eveniet tenetur provident aliquid tempora placeat.</p>
  </columns>
</row>
<row>
  <columns>
    <h4>Sub Section Title</h4>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod eum eius numquam sint dolore voluptatibus beatae ab ad, dignissimos fugiat? Nisi odio commodi debitis eveniet tenetur provident aliquid tempora placeat.</p> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod eum eius numquam sint dolore voluptatibus beatae ab ad, dignissimos fugiat? Nisi odio commodi debitis eveniet tenetur provident aliquid tempora placeat.</p>
  </columns>
</row>

**Comment by selfishprimate** [comment]
I ment bu using large="6" attribute.

29 Ağu 2018 12:47 tarihinde Halil İbrahim Çakıroğlu <ibrahimchll@hotmail.com> yazdı:
Ok, but what if i want them to stand side by side on mobile screen by using small="12" attribute?

29 Ağu 2018 12:21 tarihinde nikitasol <notifications@github.com> yazdı:

Hey @babilkuyusu<https://github.com/babilkuyusu>!
Here is a short info from docs:

Foundation uses a 12-column grid, so 6 columns is half the width of the whole row.

So with your code you are trying to create a 24-column grid inside 1 row. If you want your columns to stack you should separate them into 2 rows. Also if you are using full 12-column grid you don't need to use column sizes. So your code should look like this:

<row>
  <columns>
    <h4>Sub Section Title</h4>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod eum eius numquam sint dolore voluptatibus beatae ab ad, dignissimos fugiat? Nisi odio commodi debitis eveniet tenetur provident aliquid tempora placeat.</p> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod eum eius numquam sint dolore voluptatibus beatae ab ad, dignissimos fugiat? Nisi odio commodi debitis eveniet tenetur provident aliquid tempora placeat.</p>
  </columns>
</row>
<row>
  <columns>
    <h4>Sub Section Title</h4>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod eum eius numquam sint dolore voluptatibus beatae ab ad, dignissimos fugiat? Nisi odio commodi debitis eveniet tenetur provident aliquid tempora placeat.</p> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod eum eius numquam sint dolore voluptatibus beatae ab ad, dignissimos fugiat? Nisi odio commodi debitis eveniet tenetur provident aliquid tempora placeat.</p>
  </columns>
</row>

**Comment by nikitasol** [comment]
Hey @babilkuyusu !
I am not sure if you want them to be side by side on mobile or on large screen. If large screen and stack on mobile you should just use one row and use columns large="6". Like this:
```html
<row>
  <columns large="6">
    <h4>Sub Section Title</h4>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod eum eius numquam sint dolore voluptatibus beatae ab ad, dignissimos fugiat? Nisi odio commodi debitis eveniet tenetur provident aliquid tempora placeat.</p> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod eum eius numquam sint dolore voluptatibus beatae ab ad, dignissimos fugiat? Nisi odio commodi debitis eveniet tenetur provident aliquid tempora placeat.</p>
  </columns>
  <columns large="6">
    <h4>Sub Section Title</h4>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod eum eius numquam sint dolore voluptatibus beatae ab ad, dignissimos fugiat? Nisi odio commodi debitis eveniet tenetur provident aliquid tempora placeat.</p> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod eum eius numquam sint dolore voluptatibus beatae ab ad, dignissimos fugiat? Nisi odio commodi debitis eveniet tenetur provident aliquid tempora placeat.</p>
  </columns>
</row>
```

If what you want is stacked on large screen and side-by-side on mobile, I think this is mathematically  impossible using the code we have. I can suggest that you might try creating different blocks for each view and hiding the blocks depending on the screen size.

**Comment by selfishprimate** [comment]
Yes exactlly that is what I want: Stacked on large screen and side-by-side on mobile. But previous releases of the foundation for emails was supporting that, isn't that true?

**Comment by nikitasol** [comment]
I am not sure which release you mean - at least for the last couple of years it worked this way. The base template creates a table as a base for the content, so when you create two cells in the same table for the mobile version, you can't undo it and I think there is no way you can make cells stack over each other inside <tr> fields. You can try using visibility classes to achieve it though:
```html
<row class="show-for-large">
  <columns>
    <h4>Sub Section Title</h4>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod eum eius numquam sint dolore voluptatibus beatae ab ad, dignissimos fugiat? Nisi odio commodi debitis eveniet tenetur provident aliquid tempora placeat.</p> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod eum eius numquam sint dolore voluptatibus beatae ab ad, dignissimos fugiat? Nisi odio commodi debitis eveniet tenetur provident aliquid tempora placeat.</p>
  </columns>
</row>
<row class="show-for-large">
  <columns>
    <h4>Sub Section Title</h4>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod eum eius numquam sint dolore voluptatibus beatae ab ad, dignissimos fugiat? Nisi odio commodi debitis eveniet tenetur provident aliquid tempora placeat.</p> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod eum eius numquam sint dolore voluptatibus beatae ab ad, dignissimos fugiat? Nisi odio commodi debitis eveniet tenetur provident aliquid tempora placeat.</p>
  </columns>
</row>
<row class="hide-for-large">
  <columns small="6">
    <h4>Sub Section Title</h4>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod eum eius numquam sint dolore voluptatibus beatae ab ad, dignissimos fugiat? Nisi odio commodi debitis eveniet tenetur provident aliquid tempora placeat.</p> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod eum eius numquam sint dolore voluptatibus beatae ab ad, dignissimos fugiat? Nisi odio commodi debitis eveniet tenetur provident aliquid tempora placeat.</p>
  </columns>
  <columns small="6">
    <h4>Sub Section Title</h4>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod eum eius numquam sint dolore voluptatibus beatae ab ad, dignissimos fugiat? Nisi odio commodi debitis eveniet tenetur provident aliquid tempora placeat.</p> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod eum eius numquam sint dolore voluptatibus beatae ab ad, dignissimos fugiat? Nisi odio commodi debitis eveniet tenetur provident aliquid tempora placeat.</p>
  </columns>
</row>
```

**Comment by selfishprimate** [comment]
Thanks for the comments I think I get the idea!
