### ISSUE TITLE
Unable to install Foundation - npm install results in multiple errors. 

### ISSUE THREAD

**Issue by ericnguyen23** [foundation/foundation-emails#913]
Node v8.11.4
npm v5.6.0

I'm following instructions: 

```
git clone https://github.com/zurb/foundation-emails-template project
cd project
npm install
```

running npm install I'm getting these errors: 

> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the phantomjs-prebuilt@2.1.16 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/eric/.npm/_logs/2018-08-29T17_42_03_053Z-debug.log

Any help would be great.

**Comment by nikitasol** [comment]
Maybe try updating your node.js to the latest LTS version? Mine is 8.11.4 and it is working fine

**Comment by ericnguyen23** [comment]
Just updated Node. Same error results.

**Comment by ericnguyen23** [comment]
I'm trying the Foundation website documentation to create new project using : 

`foundation new --framework emails`

I receive this error:

` ✗ Node modules not installed. Try running npm install manually.`

Strange since I do see a node_modules folder with a list of sub folders.  However I installed manually using `npm install` then ran `foundation watch` which does run on http://localhost:3000/ which is great.

I made some changes and then ran `npm run build` and received the same failed @babel/register `Failed to load external module @babel/register` This destroyed all the formatting within the "dist" folder. 

At least with this method, I'm a little further as the process is working in the background and I'm able to view on localhost and make changes however inlining does not work.

Any tips?

**Comment by nikitasol** [comment]
Hey @ericnguyen23,

The Failed to load external module is normal behaviour. We all get it. I am thinking that there might be some issue with your permissions. Have a look at this thread: <https://github.com/npm/npm/issues/4815#issuecomment-48080140>. Also check if the foundation-cli is updated and there were no issues installing it.

**Comment by ericnguyen23** [comment]
Thanks @nikitasol 

I tried running commands from that thread and it didn't work.

Then I uninstalled and re-installed Foundation. Received no errors, just these warnings:

```
npm WARN deprecated bower@1.8.4: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
npm WARN notice [SECURITY] lodash has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=lodash&version=3.10.1 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
/usr/local/bin/foundation -> /usr/local/lib/node_modules/foundation-cli/bin/foundation.js
```

**Comment by nikitasol** [comment]
Do you have brew installed and updated? Just comparing to my installation. I think homebrew is the only one left.

Also concerning this:
>I made some changes and then ran npm run build and received the same failed @babel/register Failed to load external module @babel/register This destroyed all the formatting within the "dist" folder.

Have you tried running `foundation build` instead?

**Comment by nikitasol** [comment]
Also before installing foundation-cli did you install gulp and bower with `sudo npm install -g gulp bower`, as well as git from here: <https://git-scm.com/downloads>?

**Comment by ericnguyen23** [comment]
@nikitasol  installed homebrew, installed gulp bower, tried foundation build instead but getting the same broken styling within 'dist' folder.

Seeing this error while inlining:

```
[11:22:20] 'sass' errored after 496 ms
[11:22:20] TypeError in plugin 'gulp-uncss'
```

**Comment by nikitasol** [comment]
Let's back up a bit to the beginning then. Try doing a forceful install of phantomjs (there was an error thrown there):
```
$ cd node_modules/gulp-uncss/node_modules/uncss/node_modules/phridge/node_modules/phantomjs-prebuild
$ node install.js
```

**Comment by ericnguyen23** [comment]
that was it!! Thanks @nikitasol !

**Comment by edusurf10** [comment]
help me, i need help, error > 

Downloading the project template...
Done downloading!

Installing dependencies...

npm ERR! git rev-list -n1 4.0: fatal: ambiguous argument '4.0': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 4.0: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 4.0: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 4.0: 
\
There were some problems during the installation.

 ✓ New project folder created.
 ✗ Node modules not installed. Try running npm install manually.
 ✓ Bower components installed.

Once you've resolved the above issues, run foundation watch while inside the incentiv folder.

my Nodejs is version - v8.10.0


![image](https://user-images.githubusercontent.com/26351660/63556398-134b4680-c51b-11e9-94e9-72167d34475e.png)

**Comment by shnizmuffin** [comment]
Go into package.json and bump gulp up to ^4.0.0

**Comment by st-h** [comment]
@edusurf10 If you are just starting to use foundation-emails, you might be interested to check these issues and comments:
[still maintained?](https://github.com/zurb/foundation-emails/issues/944)
https://github.com/zurb/foundation-emails/issues/805#issuecomment-485822272
