### ISSUE TITLE
I got this error and I'm not able to figure out how to fix it.

### ISSUE THREAD

**Issue by rw215** [foundation/foundation-emails#919]
**How can we reproduce this bug?**

npm install

npm run build

Write out the HTML (or Inky code) that causes the issue.

Terminal error on install

[01:43:05] Try running: npm install gulp
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! foundation-emails-template@1.0.0 build: `gulp --production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the foundation-emails-template@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/robertwilliams/.npm/_logs/2018-11-01T05_43_05_503Z-debug.log

**What did you expect to happen?**

An install with no errors

**What happened instead?**

look at above errors, I tried to follow the instructions to fix and it never worked for some reason

**What email clients does this happen in?**

**Comment by DanielRuf** [comment]
Try removing node_modules and try `npm install` again. But just this at first.

**Comment by DanielRuf** [comment]
Closing as we did not receive any further feedback.
