### ISSUE TITLE
fail to install new foundation-emails project

### ISSUE THREAD

**Issue by jiehan1029** [foundation/foundation-emails#920]
I do see some old issues back in 2016 regarding to new project setup, but that doesn't solve my problem. anyone experience similar things recently?

**How can we reproduce this bug?**
On mac, already have 
node v10.13.0
npm v6.4.1
gulp [16:14:42] CLI version 3.9.1
bower v1.8.4
git already installed.

mkdir an empty folder, cd into it, and then run
$ foundation new --framework emails
fill-in a random project name, and it starts to run, but end up with

> npm ERR! git rev-list -n1 4.0: fatal: ambiguous argument '4.0': unknown revision or path not in the working tree.
> npm ERR! git rev-list -n1 4.0: Use '--' to separate paths from revisions, like this:
> npm ERR! git rev-list -n1 4.0: 'git <command> [<revision>...] -- [<file>...]'
> npm ERR! git rev-list -n1 4.0: 
> \
> There were some problems during the installation.
> 
>  ✓ New project folder created.
>  ✗ Node modules not installed. Try running npm install manually.
>  ✓ Bower components installed.

if I cd into the project folder and run
> npm install

it will error out saying

> npm ERR! code 1
> npm ERR! Command failed: /usr/bin/git checkout 4.0
> npm ERR! error: pathspec '4.0' did not match any file(s) known to git.
> npm ERR! 

Can someone please help? Really appreciate it!!

**Comment by lxbdr** [comment]
Seems like it tries to get Gulp 4.0 but the dependency is out of date. Inside the newly created project's package.json I changed `"gulp": "git+https://github.com/gulpjs/gulp.git#4.0"` to `"gulp": "^4.0.0"` after that run `npm install` and now it seems to work. You might need to do `npm uninstall -g gulp` and `npm install -g gulp-cli` in order to get Gulp 4 running

**Comment by jiehan1029** [comment]
@lxbdr Thank you!! yes this solved the problem!

**Comment by scleaver** [comment]
Solved it for me too

**Comment by jqhercules** [comment]
Could someone please update the package.json file please spent almost an hour trying to fix this issue.

**Comment by IngoVals** [comment]
There seems to be a pull request ready.

https://github.com/zurb/foundation-emails-template/pull/56

**Comment by rajithwijepura** [comment]
@lxbdr Thanks for the solution. This actually worked.

**Comment by daniel-thisnow** [comment]
thanks you guys. Finally I got it working, I did the update to the gulp version plus "npm rebuild node-sass" and it is working. I thought I would never get there.

**Comment by jsypolt** [comment]
This is still an issue on foundation cli 2.2.5. 

Installed today and ran foundation new --framework emails

This is the line in package.json:
"gulp": "git+https://github.com/gulpjs/gulp.git#4.0",

Should be:
"gulp": "4.0.0",

**Comment by DanielRuf** [comment]
Hi @jsypolt,

We are aware of it.
