### ISSUE TITLE
outlook email width too narrow & large columns not responsive

### ISSUE THREAD

**Issue by jiehan1029** [foundation/foundation-emails#921]
**How can we reproduce this bug?**
I'm using foundation for emails css version, so I just linked the foundation_emails.css file from the starter kit (downloaded here: [https://foundation.zurb.com/emails/docs/css-guide.html](https://foundation.zurb.com/emails/docs/css-guide.html) ) to my html and used the foundation classes.

```
<body>
  <table class="body" data-made-with-foundation>
     <tr>
       <td class="float-center" align="center" valign="middle">
         <center>
           <table align="center" class="float-center wrapper">
             <tr>
               <td class="wrapper-inner columns">
                 <table align="center" class="container">
                   <tbody>
                    <!-- email banner -->
                     <tr class="email-bg">
                       <th class="small-12 large-12 columns" >
                         <table class="row" id="email-banner">
                           <tr>
                             <th class="small-6 first columns" align="left">
                               <div><a href="{{base_url}}">
                                 <img src="{{base_url}}/static/images/logo-black.png"/>
                               </a></div>
                             </th>
                             <th class="small-6 last columns" align="right">
                               <div><a class="email-corner-link" href="{{base_url}}/dashboard">Visit Your Dashboard</a></div>
                             </th>
                             <th class="expander"></th>
                           </tr>
                        </table>
                       </th>
                     </tr>
// all the way close tags till </body>
```

**What did you expect to happen?**

I assume this should give me a responsive layout that will always occupies full width regardless of window size (because of the small-12 and large-12)

**What happened instead?**

The content width is fixed, not responsive, tested on mac client and gmail.

I think this is caused by the large-12. The foundation_email.css specifies a fixed with for this class, for example: 

```
td.large-12,
th.large-12 {
  width: 564px;
  padding-left: 8px;
  padding-right: 8px; }
```

I don't know why. Shouldn't it be responsive as in percentage?

Anyway, I then removed the large-12 class and it's now responsive on mac and gmail.

**However**
That html (with only small-12 first last columns classes) in outlook does not expand to full width, but a fixed narrow width. and I don't have a clue how to solve it....any help would be appreciated!!

**Comment by burgiuk** [comment]
You need to inline the styles.

**Comment by DanielRuf** [comment]
We are closing this issue asthis is issue is quite old and as it's unclear if the styles were inlined (in email design this has to be done).
