### ISSUE TITLE
[Alignment] "text-right" class not working

### ISSUE THREAD

**Issue by gdavida** [foundation/foundation-emails#924]
**How can we reproduce this bug?**

```
<row>
    <columns small="6" large="6" class="">
        <p class="text-left">Something:</p>
        <p class="text-left">Something:</p>
    </columns>
    <columns small="6" large="6" class="text-right">
        <p class="text-center">!Details</p>
        <p class="text-right">!Details</p>
    </columns>
  </row>
```

**What did you expect to happen?**
The "text-right" class to make that text align to the right side.

**What happened instead?**
It stayed left aligned.

**What email clients does this happen in?**
I was only working locally when I saw this.

**Comment by drawcard** [comment]
This also happens with text-center, and only affects Outlook 2016 as far as I can tell. It's not reproducible in localhost preview.

**Comment by mathiasmadsen** [comment]
Same problem for me. I have manually edited the table preferences in the build for the wrapper from 'text-align:left' to 'text-align:right'.

**Comment by DanielRuf** [comment]
It would be good to have a reproducible testcase and more information if you use the inline task from our gulpile which should properly inline these properties.

Closing as this issue is a duplicate (see the referenced issues) and lacks further information to reproduce this.

**Comment by alanbrozovich** [comment]
I was also repro'ing this issue on Outlook 2016, but running `npm run build` instead of `npm start` solved for me. `npm run build` includes the call to the `inliner` task that @DanielRuf referenced.
