### ISSUE TITLE
[Getting Started with Sass] package.json is out of date 

### ISSUE THREAD

**Issue by renandsgn** [foundation/foundation-emails#928]
package.json is out of date

**Comment by mingyjongo** [comment]
+1

**Comment by DanielRuf** [comment]
We are aware of this. I think we can close this issue.

**Comment by madrid1979** [comment]
Is there a new major version coming for foundation emails, or is this project on life support, because MJML is looking pretty good right now.

**Comment by DanielRuf** [comment]
It still works with the current dependencies but you are free to use any solution that you want. This project is maintained by volunteers.

**Comment by webuxr** [comment]
@DanielRuf Volunteers or not, I really enjoy using Foundation for Emails (via this email template stack repo) in it's current form. FYI: I use it to create "external emails" (aka: emails that need to be built by our internal team but that will be sent via one of our vendor's email systems).

When installed and setup in it's default state, the repo is a bit buggy in places, and the out-dated `package.json` has caused me many headaches (figuring out how to get back to a usable state) but for the most part, works well and does it's job.

Even still, I would REALLY like to see an official release candidate. Anything on the horizon? Maybe someone can create a tag of the repo for a commit that is somewhat stable that includes a `package.json` file (and maybe a `package-lock.json` file ... perhaps a version of `package.json` with very specific, non-ranging package versions)? Perhaps that's a tag of [some commit in this branch](https://github.com/zurb/foundation-emails-template/tree/working)?

I've been trying to find ways to help in this issue queue but find myself coming back, time and time again, looking for solutions (and not finding them) more than opportunities to help this amazing team of volunteers.

C'mon peeps, throw us a bone :)

Thanks in advance!
_rs

**Comment by DanielRuf** [comment]
If this is so buggy (please link the issues with the bugs / errors) I can fork and prepare a commit with updated dependencies. npm and Yarn can install directly from Git(Hub) repos.

But so far we had no real blocker at work (regarding dependencies).
