### ISSUE TITLE
[Getting Started with Sass] unable to install correctly

### ISSUE THREAD

**Issue by LyLuX** [foundation/foundation-emails#930]
Hello !
I'm not able to install correctly the email framework.
I tried by using founction-cli and by cloning the repo but both end with the same issue.

Thanks for any help !!

**How can we reproduce this bug?**
run `foundation new --framework emails`
name the project "crtsaver"
`✗ Node modules not installed. Try running npm install manually.`

![foundation-emails_1-2](https://user-images.githubusercontent.com/29945451/49454705-fbddf900-f7e5-11e8-9ec8-ea13a3e8e788.png)
run `npm i` in the crtsaver folder
`npm ERR! Command failed: C:\Program Files\Git\cmd\git.EXE checkout 4.0`
`npm ERR! error: pathspec '4.0' did not match any file(s) known to git`

![foundation-emails_2-2](https://user-images.githubusercontent.com/29945451/49454706-fc768f80-f7e5-11e8-9412-1dc87d820da8.png)

**What did you expect to happen?**
The project template will be downloaded, and the various dependencies installed

**What happened instead?**
The project template is downloaded, but the various dependencies are not istalled

**Comment by dan10gc** [comment]
change the `gulp` devDependencies to `"gulp": "4.0",`. Then run `npm install`, this will install gulp correctly as it was not finding gulp v4.0.

**Comment by rudants** [comment]
@LyLuX, Hi.

You can fix it by editing a few strings of devDependencies object in gulpfile.js as follows:

`"gulp": "^4.0.0",` and `"gulp-sass": "^3.2.1"`.

**Comment by DanielRuf** [comment]
A known problem as we used a tag instead of a version and the Gulp team removed it. The previous comments should solve this.

**Comment by LyLuX** [comment]
Hi guys !

Thanks for your answers, it works !

**Comment by IngoVals** [comment]
Was going to create a PR but it seems someone beat me to it by three months.

https://github.com/zurb/foundation-emails-template/pull/56

Who has the authority to accept and merge?
