### ISSUE TITLE
how can I install CLI on a mac?

### ISSUE THREAD

**Issue by DomWebster** [foundation/foundation-emails#933]
Last login: Fri Dec 14 19:47:46 on ttys000
Doms-MacBook-Pro:~ domwebster$ npm install -g foundation-cli
npm WARN deprecated bower@1.8.4: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules']
npm ERR!   stack:
npm ERR!    "Error: EACCES: permission denied, access '/usr/local/lib/node_modules'",
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/domwebster/.npm/_logs/2018-12-15T00_59_29_580Z-debug.log
Doms-MacBook-Pro:~ domwebster$ npm update -g foundation-cli

**Comment by burgiuk** [comment]
Have you tried using `sudo`?

**Comment by DomWebster** [comment]
Yes I tried and it didn't work. So am I basically out of $300? 




Get Outlook for Android







On Wed, Jan 16, 2019 at 9:17 AM -0500, "John Burgess" <notifications@github.com> wrote:












Have you tried using sudo?

**Comment by davehoran** [comment]
This seems like a file system permissions issue based on the errors shown. If you have tried running the same command with sudo, then delete the files and start fresh, this time using sudo from the start.

**Comment by DomWebster** [comment]
I will try it. Thank you




Get Outlook for Android







On Wed, Jan 16, 2019 at 10:22 AM -0500, "Dave Horan" <notifications@github.com> wrote:












This seems like a file system permissions issue based on the errors shown. If you have tried running the same command with sudo, then delete the files and start fresh, this time using sudo from the start.

**Comment by DanielRuf** [comment]
Closing as we did not receive any further feedback.
