### ISSUE TITLE
New foundation framework for email project setup fails with ambiguous argument - node modules not installed

### ISSUE THREAD

**Issue by coolsoftwaretyler** [foundation/foundation-emails#934]
Hey folks, I've really been loving this project, and have used it for a handful of email designs. I've installed the CLI on two different machines (Ubuntu 18.04 and Mac OSX High Sierra) and each CLI install worked correctly, but I have seen this bug on both machines when creating a new project. 

**How can we reproduce this bug?**

`foundation new --framework emails`

Provided project name as `bug-test`

**What did you expect to happen?**

I expected to get the new project directory installed and ready to run `npm start` 

**What happened instead?**
Received this message in terminal: 

```
Downloading the project template...
Done downloading!

Installing dependencies...

npm ERR! git rev-list -n1 4.0: fatal: ambiguous argument '4.0': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 4.0: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 4.0: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 4.0:

There were some problems during the installation.

 ✓ New project folder created.
 ✗ Node modules not installed. Try running npm install manually.
 ✓ Bower components installed.
```

**Fix** 
I googled around for the fatal: ambiguous argument error and found a solution. It looks like the problem is in the `package.json` 

Under `devDependencies`, gulp is listed as: 

`"gulp" : "git_https://github.com/gulpjs/gulp.git#4.0"` 

Changing this to 
`"gulp" : "4"` seems to fix the error. 

I'm pretty new to node and am unsure how to correctly push up a fix to the repo to solve this dependency issue, so I'm hoping a maintainer can get that squared away, or at least this issue will be a good source of documentation for anyone having the same issue.

**Comment by ieugen** [comment]
Yes, using `"gulp": "^4.0.0",` in `package.json` fixes `npm install` step. Gulp 4 was not released when the repo was written.

**Comment by lkimsey** [comment]
After change gulp value, what do you next ?

**Comment by ieugen** [comment]
Npm install

**Comment by dogancelik** [comment]
Duplicate of #930

**Comment by simondoescode** [comment]
+1

**Comment by DanielRuf** [comment]
Closing as duplicate.
