### ISSUE TITLE
ZURB Foundation for Emails

### ISSUE THREAD

**Issue by lkimsey** [foundation/foundation-emails#935]
Downloading the project template...
Done downloading!

Installing dependencies...

npm ERR! git rev-list -n1 4.0: fatal: ambiguous argument '4.0': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 4.0: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 4.0: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 4.0:

**Comment by peacefulseeker** [comment]
Duplicate #934

**Comment by DanielRuf** [comment]
Closing as duplicate.
