### ISSUE TITLE
[Foundation for Emails] Can't Set-up Email Project without errors

### ISSUE THREAD

**Issue by mhiland247** [foundation/foundation-emails#940]
**How can we reproduce this bug?**
I have node version v10.15.1 and npm version 6.4.1
When I run foundation new --framework emails I get this error message:
Thanks for using ZURB Foundation for Emails!
   /   | ===  \     -------------------------------------------
   |   | ====  |    Let's set up a new project.
   /__/| =====  \   It shouldn't take more than a minute.
       (   __   )
        (O)  (O)
       (   __,  )
        \______/

Downloading the project template...
Done downloading!

Installing dependencies...

npm ERR! git rev-list -n1 4.0: fatal: ambiguous argument '4.0': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 4.0: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 4.0: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 4.0: 
-
There were some problems during the installation.

 ✓ New project folder created.
 ✗ Node modules not installed. Try running npm install manually.
 ✓ Bower components installed.

Once you've resolved the above issues, run foundation watch while inside the email_templates folder.

**What did you expect to happen?**
Super easy to fire up a blank Foundation for Emails project. 

**What happened instead?**
Fails to setup the project because of node modules.  I have tried to manually install npm as directed.

**What email clients does this happen in?**
N?A

**Comment by drawcard** [comment]
From your project directory, try:

```bash
npm install -g npm@latest
npm cache clear && rm -rf node_modules && npm install
```
If you still have issues run ```npm install --verbose``` and post any error reports.

**Comment by mhiland247** [comment]
Thanks  I got it to work!

**Comment by drawcard** [comment]
Yeah 99% of the time it's because the install process fails and you get left with a bunch of broken stuff in node_modules. Glad to help!

**Comment by laurelstreng** [comment]
@drawcard so I actually ran into the same issue but still running into issues even after installing latest... though i've got very different versions of node and npm:
node: v11.10.0
npm: v6.8.0

**Comment by laurelstreng** [comment]
When I tried running `npm cache clear && rm -rf node_modules && npm install` I ran into these errors:
```
npm ERR! As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything is consistent, use 'npm cache verify' instead. On the other hand, if you're debugging an issue with the installer, you can use `npm install --cache /tmp/empty-cache` to use a temporary cache instead of nuking the actual one.
npm ERR!
npm ERR! If you're sure you want to delete the entire cache, rerun this command with --force.
```

**Comment by drawcard** [comment]
@laurelstreng I personally ignore those errors and run with the —force switch.

**Comment by DanielRuf** [comment]
Yarn could also be an option.

What exact errors do you get?

**Comment by DanielRuf** [comment]
The issue is caused by the gulp dependency which refers to a branch / tag which was deleted by the gulp team.

**Comment by ValdySERANT** [comment]
Hey guys, 

I'm running with the same issue.

I have node v18.12.1 installed

& Git version 2.38.1.windows.1

But when  installing Foundation for  Email with the following code :

npm install --global foundation-cli

foundation new --framework emails 

I get :
" Installing dependencies...

undefined

There were some problems during the installation.

 ✓ New project folder created.
 ✗ Node modules not installed. Try running yarn install manually.

Once you've resolved the above issues, run foundation watch while inside the S5 folder. "

Despite using 
npm install -g npm@latest
or 
npm install --verbose

What do you think I'm doing wrong here ?

**Comment by DanielRuf** [comment]
What happens if you go into the generated project folder and run `npm i`?

Also, please open a new issue and provide more details there.

**Comment by ValdySERANT** [comment]
Hey Daniel, 

Thank you for your quick response.

Sorry, I'm new to Github & coding also. 
& i don't know 
 How  to "open a new issue" ?

nor
"go into the generated folder" 

Would you mind explaining further more ?

**Comment by DanielRuf** [comment]
On your terminal you can change to another directory wiith `cd my-foldet-name`.

To create a new issue please go to https://github.com/foundation/foundation-emails/issues/new/choose
