### ISSUE TITLE
[The Grid] Jquery doen't work on site

### ISSUE THREAD

**Issue by videmann** [foundation/foundation-emails#942]
**How can we reproduce this bug?**

Write out the HTML (or Inky code) that causes the issue.

**What did you expect to happen?**

**What happened instead?**

**What email clients does this happen in?**

**Comment by mrdubz** [comment]
modern email clients don't support any javascript in emails

**Comment by drawcard** [comment]
@videmann I think you're confusing this project with https://github.com/zurb/foundation-sites
