### ISSUE TITLE
Background image breaking foundations columns in outlook

### ISSUE THREAD

**Issue by mhiland247** [foundation/foundation-emails#945]
**How can we reproduce this bug?**
Using foundations for email , I have a background image with text overlay that breaks in Outlook.

Write out the HTML (or Inky code) that causes the issue.
This is the code that is causing the problem:

 <table cellpadding="0" cellspacing="0" border="0" height="235" width="100%">
  <tr>
    <td background="http://prod.trainingpeaks.com/email-newsletter/templates/2019/training-plan-cta.jpg" bgcolor="#66cc66" valign="top" style="background-repeat: repeat-x; background-color: #66cc66; background-size:cover;">
      
      <div>
 		<row>
            <columns small="1" large="1"></columns>
            <columns small="10" large="10" style="padding-bottom: 0;">
   
                <spacer size="20"></spacer>
                <center>
               <img src="http://prod.trainingpeaks.com/email-newsletter/templates/2019/calendar-icon.png" alt="calendar" class="float-center" width="34" height="34" style="width:34px; height:34px;">
               <center>
                 <spacer size="10"></spacer>
                <h5 class="text-center" style="color:#ffffff; line-height: 32px;">Training Plan Store</h5>
                <p class="text-center" style="color:#ffffff; font-weight:normal; line-height:24px; font-size: 14px; font-family: 'HelveticaNeue-Light', 'Helvetica Neue Light','Helvetica Neue', Helvetica, Arial,sans-serif;">Browse through the worlds largest collection of triathlon, cycling and running plans and take the guesswork out of your training.</p>
                 <spacer size="6"></spacer>
                  <center><div><a href="https://www.trainingpeaks.com/training-plans"
                  style="background-color:transparent;border:2px solid #ffffff;border-radius:4px;color:#ffffff;display:inline-block;font-family:sans-serif;font-size:12px;font-weight:lighter;line-height:32px;text-align:center;text-decoration:none;width:160px;-webkit-text-size-adjust:none;mso-hide:all;">Browse Training Plans</a>
                  </div> </center>
                   <spacer size="16"></spacer>
             
            </columns>
            <columns small="1" large="1"></columns>
          </row>

       </div>
      
    </td>
  </tr>
</table>
**What did you expect to happen?**
Background image to appear with text overlay in a row and column. 

![image](https://user-images.githubusercontent.com/13631860/53691607-b080ab80-3d3e-11e9-9181-378b90f4cdfc.png)

**What happened instead?**
In outlook the image repeats, is full width and breaks the columns below and above.

![image](https://user-images.githubusercontent.com/13631860/53691595-8333fd80-3d3e-11e9-91af-cde94e7c1325.png)

**What email clients does this happen in?**
outlook - all

**Comment by turneja** [comment]
Outlook doesn't support background images, so you're luck you got anything at all... BTH if the text is static and doesn't dynamically change via data then I would just use a full image for this section.

**Comment by shnizmuffin** [comment]
@turneja,

> Outlook doesn't support background images...

That's not entirely accurate. This effect is possible in Outlook using Vector Markup Language. [Email on Acid Article](https://www.emailonacid.com/blog/article/email-development/how-to-make-your-emails-bulletproof/). [Litmus Article](https://litmus.com/blog/the-ultimate-guide-to-background-images-in-email).

**Comment by DanielRuf** [comment]
> That's not entirely accurate. This effect is possible in Outlook using Vector Markup Language. [Email on Acid Article](https://www.emailonacid.com/blog/article/email-development/how-to-make-your-emails-bulletproof/). [Litmus Article](https://litmus.com/blog/the-ultimate-guide-to-background-images-in-email).

But not really a cross-client solution =)

**Comment by shnizmuffin** [comment]
@DanielRuf and it's completely out of scope for this project! #wontfix

**Comment by DanielRuf** [comment]
I agree with @shnizmuffin that this is a very specific usecase that has to be covered by custom CSS and markup.

Alternatively use normal images like most of us do.
