### ISSUE TITLE
error: pathspec '4.0' did not match any file(s) known to git

### ISSUE THREAD

**Issue by khpeek** [foundation/foundation-emails#961]
**How can we reproduce this bug?**
Following the "Get started with SASS" instructions (https://foundation.zurb.com/emails/docs/sass-guide.html), I ran `npm install --global foundation-cli` followed by
```
foundation new --framework emails
```
and specified a project name, `myemails`. However, I get the following error:

```
git rev-list -n1 4.0: fatal: ambiguous argument '4.0': unknown revision or path not in the working tree.
```

(See screenshot below).
![image](https://user-images.githubusercontent.com/6617594/60905542-1ec40600-a22a-11e9-87aa-5a19334e4e80.png)

If I `cd myemails` and try `npm install`, I get a similar error:

![image](https://user-images.githubusercontent.com/6617594/60905650-592da300-a22a-11e9-91fb-bb74a9766506.png)

**What did you expect to happen?**
I expected the project to be set up correctly.

**What happened instead?**
I got an error.

**What email clients does this happen in?**
N/A

**Comment by peterwgnd** [comment]
Try opening changing `"gulp": "git+https://github.com/gulpjs/gulp.git#4.0"`, to `"gulp": "^4.0.0",` in package.json and then running npm install again

**Comment by DanielRuf** [comment]
Hi @khpeek,

We already have open issues about this.
I think you can close the issue as duplicate.

**Comment by bawantha** [comment]
> Hi @khpeek,
> 
> We already have open issues about this.
> I think you can close the issue as duplicate.

where

**Comment by DanielRuf** [comment]
See related issues eg https://github.com/zurb/foundation-emails/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+gulp+4.0

**Comment by bawantha** [comment]
> See related issues eg https://github.com/zurb/foundation-emails/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+gulp+4.0

Thanks
