### ISSUE TITLE
[Global Styles] ISSUE NAME HERE

### ISSUE THREAD

**Issue by Coco-Deng** [foundation/foundation-emails#962]
Write out the HTML (or Inky code) that causes the issue.
Inky
`<button class="button">button</button>`
Html
`<table class="button button">`
Why the button component need a same name class 'button', it's a bit wired there is 2 same classes for table.

Thanks!

**Comment by DanielRuf** [comment]
Hi @Coco-Deng,

You do not have to set the class as the `<button>` component already sets this one.

**Comment by DanielRuf** [comment]
See https://foundation.zurb.com/emails/docs/button.html

It just copies additional classes that you set.

**Comment by DanielRuf** [comment]
Closing as we did not receive any further feedback.
