### ISSUE TITLE
[Alignment] These classes will appy to the large breakpoint as well as the small.

### ISSUE THREAD

**Issue by Coco-Deng** [foundation/foundation-emails#963]
typo:

appy should be apply

**Comment by markokajzer** [comment]
Seems fixed

<img width="858" alt="Screen Shot 2020-08-11 at 19 40 18" src="https://user-images.githubusercontent.com/9379317/89930113-822d1e00-dc0a-11ea-8e4e-04cc3755f714.png">

I guess the issue can be closed :)
