### ISSUE TITLE
Error run build / run zip / run mail

### ISSUE THREAD

**Issue by mtvphnx** [foundation/foundation-emails#968]
If you has this error - **error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory** then use command yarn run build, yarn run zip, yarn run mail - run command **sudo apt-get install libfontconfig**, it's help you.

**Comment by DanielRuf** [comment]
Hi @mtvphnx,

Please provide all the required information and use our issue template from https://github.com/foundation/foundation-emails/blob/develop/.github/ISSUE_TEMPLATE.md

Your system may not have the needed dependencies to install some things.

And provide as much information from your terminal output as needed and possible.

This is so far a general issue that is not specific to foundation-emails and you can close it.

People should be already able to find the right solution depending on which dependency produces this issue. The issue tracker should be used to report actual bugs that we caused.
