### ISSUE TITLE
copy-paste of generated HTML to Outlook 2019 breaks markup

### ISSUE THREAD

**Issue by rmendadala** [foundation/foundation-emails#969]
**How can we reproduce this bug?**
1. Create an email template.
2. Build the email using "foundation build".
3. Open the HTML file from the dist folder in Firefox.
4. Copy the content (Command + A).
5. Paste it to online Outlook client. 
Write out the HTML (or Inky code) that causes the issue.

**What did you expect to happen?**
1. The email should copy in the exact format as it is displayed when opened in Firefox.
2. Sending the email should not auto bold the text and center the text.

**What happened instead?**
1. Copying the email to the online Outlook client auto bolds the text.
2. Sending the email centers the text and auto bolds the text.
3. The user receiving the email gets the email in bold and text-centered

**What email clients does this happen in?**
Microsoft Outlook v16.16.14

**Comment by DanielRuf** [comment]
Hi @rmendadala,

thanks for your report. I guess this is a copy-paste issue.
Can you test if this also happens on https://testi.at?

**Comment by rmendadala** [comment]
Hey Daniel,
I downgraded the firefox version to 60 and then tried copy-paste. It copied without the auto bold but when I send it through the online outlook client, the receiving user still sees the email as bolded text and centered! Any suggestions?

**Comment by DanielRuf** [comment]
> Can you test if this also happens on [testi.at](https://testi.at)?

In general you should not copy paste html into the email client as this may break the markup like in your case. Save the file as template an let your software send it.

Were you able to reprouce it on testi.at?

**Comment by rmendadala** [comment]
Yes, but not in testi.at, I use Litmus for testing. Please check the screenshot. The result in on a 2019 Outlook desktop client!

**Comment by DanielRuf** [comment]
> 5\. Write out the HTML (or Inky code) that causes the issue.

Please provide the needed information so we can reproduce it.

**Comment by rmendadala** [comment]
Below is the sample code.
Steps to reproduce:
1. Have this code built by running foundation build.
2. Go to the dist folder and open the index.html file in the firefox browser.
3. Now, copy the content in the browser by CMD+A.
4. Open the **online** Outlook client.
5. Paste the copied content into the body of the email.
6. Send the email to test users.
Result:
Having the **desktop** Outlook client opened, the end-user will see the content, text in bold and centered.


```
<row>
    <columns small="12">
      <p>Please join us at the International Arts Center today from 5 to 7 p.m. for Larry Strickland’s artist talk and reception. Strickland is an alumnus of TROY and is known for his 9-foot-tall bronze Trojan Warrior sculpture on the Academic Quad. His exhibition, Sticks and Stones, will debut at the reception and features a collection of sculptures which are composed of materials he has encountered in nature. Strickland describes his art as “a direct result of nature itself” as “wood is representative of life’s cycle: life-to-death-to-life as it is reborn through the artist’s eyes.”</p>
      <p>Come see the power of nature be brought back to life by Larry Strickland through the form of sculpture.</p>
      <p>Refreshments will be served.</p>

      <spacer size="5"></spacer>
      <hr>
      <spacer size="5"></spacer>
      <p><small>The nature of my work is a direct result of nature itself. The wood I   find along creeks, streams, and in wooded areas has fallen, weathering over time by the elements. This natural process of decay is the process I work with. As each piece is excavated and cleaned, only the hardest and most durable wood remains. The movement and beauty of this driftwood becomes the soul of the sculpted piece, as its original form is always left recognizable even after my interpretation is hewn.</small></p>
      <p><small>As the wood cures (more often, the wood is already cured) I study its form, sometimes for years before I see – or the piece allows me to see – what it is to become. Often, the subject is figurative, reflecting some aspect of man’s predicament of belief. I use symbolism through the addition of other materials such as bone and ivory to represent death, or gold and silver to represent materialism. Always, the wood is representative of life’s cycle: life-to-death-to-life as it is reborn through the artist’s eyes.</small></p>
      <p><small>All the carvings are made from wood native to the Southeast, from Florida to South Carolina. I am in constant production as an artist and consider painting and sculpture to be my lifetime career.</small></p>

    </columns>
  </row>

```

**Comment by DanielRuf** [comment]
Your initial post misses many relevant details.

So you are using the Foundation CLI and the Foundaztion Emails Templates project. Is this correct?

Can you upload a reproducible testcase as whole repository please?

**Comment by DanielRuf** [comment]
Your initial post misses many relevant details.

So you are using the Foundation CLI and the Foundation Emails Templates project. Is this correct?

Can you upload a reproducible testcase as whole repository please?

**Comment by rmendadala** [comment]
I am posting the **scr** folder, I hope this will help you to reproduce the issue.

**Comment by shnizmuffin** [comment]
Hey @rmendadala, you can't just paste the email from `dist` into the Outlook web client - it will apply its own style rules on top of yours, overriding them. You're better off sending your email through an email service provider (like ActiveCampaign, MailChimp, or Campaign Monitor) or Thunderbird with the [ThunderHTMLEdit](https://addons.thunderbird.net/en-US/thunderbird/addon/thunderhtmledit/) Extension.

**Comment by DanielRuf** [comment]
> In general you should not copy paste html into the email client as this may break the markup like in your case. Save the file as template an let your software send it.

Exactly. I am currently testing it with an instance of the Foundation Emails template.

**Comment by rmendadala** [comment]
So anyways on how to send it through Outlook? We do not use any software so that is where the issue is coming from!

**Comment by DanielRuf** [comment]
The `src` folder is not enough as reproducible test case. We need the whole project including the package.json file and so on.

**Comment by DanielRuf** [comment]
![](https://testi.at/44GGPPCC/REpcM3jCbMwi1mEik6ZTnOskX/30544be2201daea6a5df0536ba185379.jpeg)

Looks fine in Outlook 2019 when I test with Testiat.

**Comment by rmendadala** [comment]
I still want to send you the whole project folder but it is around 1GB.

**Comment by DanielRuf** [comment]
Take a look at the .gitignore file. Create a new GitHub repo and uploa it there. It should exclude `node_modules`.

**Comment by DanielRuf** [comment]
Take a look at the .gitignore file. Create a new GitHub repo and upload it there. It should exclude `node_modules`.
