### ISSUE TITLE
SASS variables for callout background colors

### ISSUE THREAD

**Issue by wynksaiddestroy** [foundation/foundation-emails#974]
If I want to change the border color of a certain callout class, I can easily set the respective SASS variable `$callout-border-secondary`, `$callout-border-success`, `$callout-border-warning` or `$callout-border-alert`.

But unfortunately there is no way to specify the background color in a similar manner. So it would be nice to have SASS variables to set the background color. For example: `$callout-background-secondary`, `$callout-background-success`, `$callout-background-warning` or `$callout-background-alert`.

Issue #767 already addressed the same problem.

**Comment by DanielRuf** [comment]
Hi @wynksaiddestroy,

So this issue here is a duplicate then?

**Comment by wynksaiddestroy** [comment]
> Hi @wynksaiddestroy,
> 
> So this issue here is a duplicate then?

More or less. I tried to make the problem a bit more clearer. But it in the end we both address the same issue.

**Comment by DanielRuf** [comment]
Ok, then it's better to close this here as duplicate.
