### ISSUE TITLE
Auto Zip Failing on All Images

### ISSUE THREAD

**Issue by burgiuk** [foundation/foundation-emails#975]
**How can we reproduce this bug?**

When running `npm run zip` to produce a zipped version of the email an error is thrown when trying to add images to the zip. The error reports that the image files are missing.

**What did you expect to happen?**
A zip file created in the `dist` folder.

**What happened instead?**
This error occured.
```
C:\inetpub\wwwroot\emails\bre-19-004-edm>npm run zip

> foundation-emails-template@1.0.0 zip C:\inetpub\wwwroot\emails\bre-19-004-edm
> gulp zip --production

[11:14:19] Requiring external module babel-register
[11:14:20] Using gulpfile C:\inetpub\wwwroot\emails\bre-19-004-edm\gulpfile.babel.js
[11:14:20] Starting 'zip'...
[11:14:20] Starting 'build'...
[11:14:20] Starting 'clean'...
[11:14:20] Finished 'clean' after 10 ms
[11:14:20] Starting 'pages'...
[11:14:21] Finished 'pages' after 337 ms
[11:14:21] Starting 'sass'...
[11:14:23] Finished 'sass' after 2.26 s
[11:14:23] Starting 'images'...
[11:14:24] gulp-imagemin: Minified 6 images (saved 104 kB - 21.4%)
[11:14:24] Finished 'images' after 665 ms
[11:14:24] Starting 'inline'...
[11:14:25] Finished 'inline' after 949 ms
[11:14:25] Finished 'build' after 4.23 s
[11:14:25] Starting 'zip'...
[11:14:25] 'zip' errored after 145 ms
[11:14:25] Error: ENOENT: no such file or directory, open 'C:\inetpub\wwwroot\emails\bre-19-004-edm\assets\img\brett-logo.png'
[11:14:25] 'zip' errored after 4.38 s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! foundation-emails-template@1.0.0 zip: `gulp zip --production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the foundation-emails-template@1.0.0 zip script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
**What email clients does this happen in?**
None

**Comment by burgiuk** [comment]
I *think* the problem is with line 222 in the `gulpfile.babel.js` but I am struggling to debug it properly.

`path.dirname = fileName + path.dirname.replace('dist', '');`

**Comment by DanielRuf** [comment]
The images should be added in `C:\inetpub\wwwroot\emails\bre-19-004-edm\assets\img`.

**Comment by burgiuk** [comment]
That is outside of the `dist` folder and would require being manually placed there.

**Comment by DanielRuf** [comment]
See https://github.com/foundation/foundation-emails-template/tree/master/src/assets

It should be there.

**Comment by DanielRuf** [comment]
It is then copied afaik.

**Comment by DanielRuf** [comment]
It is done in the template. I would recommend to use the template or add the needed gulp task or copy them manually.

See https://github.com/foundation/foundation-emails-template/blob/master/gulpfile.babel.js#L87

**Comment by burgiuk** [comment]
The images are in the `src/assets/img` folder and they are copied fine if I run `npm run build`. Am I missing something?

![screenshot](https://i.imgur.com/X2How5y.jpg)

**Comment by DanielRuf** [comment]
Generally the mentioned line is not the issue as this is only for replacing strings in files.

https://github.com/foundation/foundation-emails-template/blob/master/gulpfile.babel.js#L221

**Comment by burgiuk** [comment]
Ah! I've figured it out!

I was using relative paths instead of including `{{root}}`. I feel pretty stupid now.

It was
```
img src="../assets/img/brett-logo.png" alt="brett-logo" mc:edit="brett-logo">
```

Instead of
```
img src="{{root}}/assets/img/brett-logo.png" alt="brett-logo" mc:edit="brett-logo">
```

**Comment by DanielRuf** [comment]
Ah, right. Totally forgot that. Next time it would be helpful to have a reproducible testcase as repo or the code which causes the problem.

For reference if others face the same issue: https://foundation.zurb.com/emails/docs/panini.html#root
