### ISSUE TITLE
Mailchimp error when uploading zip from `npm run zip`

### ISSUE THREAD

**Issue by natebeaty** [foundation/foundation-emails#985]
**How can we reproduce this bug?**

On macos Catalina 10.15.3 — and I've locked node@10 with homebrew for compatibility with other sites. Perhaps this is the issue. Anyway:

- Create new project with `git clone https://github.com/zurb/foundation-emails-template test && cd test && npm install`
- Copy a jpg into `src/assets/img/` and reference it in one of the templates (let's say hero.html) with `<img src="{{root}}assets/img/test.jpg">`
- Run `npm run zip`
- Try uploading custom template to Mailchimp using `hero.zip`

**What did you expect to happen?**

New template in Mailchimp.

**What happened instead?**

Barfs out weird error: `An error occurred running this command: replace /opt/mailchimp/493065535fcbf73a32dc7aac44428e542c09390b/cache/campaign-import/36504161-27d80c7093/hero/assets/img/test.jpg? [y]es, [n]o, [A]ll, [N]one, [r]ename: NULL (EOF or read error, treating as "[N]one" ...)`

... and template is created. If I unzip `hero.zip` and archive it again myself, it works fine uploading as a new template. ¯\_(ツ)_/¯

**What email clients does this happen in?**
n/a

**Comment by DanielRuf** [comment]
>     * git clone https://github.com/zurb/foundation-emails-template test && cd project && npm install

This makes not much sense as `test` is the folder that is created.

**Comment by DanielRuf** [comment]
> /opt/mailchimp

I wonder where this path comes from.

**Comment by natebeaty** [comment]
> This makes not much sense as test is the folder that is created.

Was just a typo that I fixed, oops!

> I wonder where this path comes from.

I'm guessing it's related to to the script that runs on Mailchimp's end to decompress the zip and move files from a tmp folder to the new theme path. It's definitely a weird error — but the fact that I can just decompress the zip myself, recompress, and upload it without issue speaks to some glitch in the Foundation zip task.

Easy to work around this, but thought I'd post in case others are seeing the same issue. Would also love to have it work, it's super slick to get three template zips ready for uploading with a single npm command.

That said, I did also notice that the zip command doesn't move image files to `assets` that are only referenced as backround images in `_template.scss` which was another issue. So I ended up having to create my own zips using the `assets` folder output from `npm run build`.

**Comment by DanielRuf** [comment]
Hm, can this problem be reproduced locally? Otherwise we can not really test and debug this. Are there files with same name but different case?

**Comment by natebeaty** [comment]
It can be reproduced by trying to upload the generated zip to Mailchimp as a new custom template. 

I used the `foundation-emails-template` and only added one `assets/img/test.jpg`, changed a few of the `<img>` tags to point to it, and ran `npm run zip` and tried uploading `hero.zip` to Mailchimp as the most basic way to reproduce the issue.

It's also possible this is something on Mailchimp's end of things. Not a dire issue, but thought I would point it out as it was reproducible just using the basic template. I have to imagine other folks are using this (fantastic, godsend of a) toolkit to make custom Mailchimp templates.

**Comment by DanielRuf** [comment]
Well, this is not really a way for me to reproduce it. Maybe you can see differences in the zip files using 7zip and a zip info tool.

**Comment by shnizmuffin** [comment]
@natebeaty Are you sure the directory structures are the same? I vaguely remember Mailchimp expecting a layout slightly different that the Foundation default.

**Comment by natebeaty** [comment]
> @natebeaty Are you sure the directory structures are the same? I vaguely remember Mailchimp expecting a layout slightly different that the Foundation default.

Again, if I just unzip and rezip the file, it uploads fine to Mailchimp.

Not a huge deal, I'm working around it. Just wanted to point out my experience of the generated zip files causing an error when uploading to Mailchimp, and see if anyone else had that issue. The toolkit is still an amazing improvement over my previous experience of swimming around in indecipherable table markup.

**Comment by DanielRuf** [comment]
> and see if anyone else had that issue

Probably not. We used mailchimp, testi.at, cleverreach and others and never had any issues regarding the zip file.

**Comment by asha23** [comment]
Also experiencing the same issue. When you re-compress the generated zip file it all works fine though.
