### ISSUE TITLE
[Button] Add more attributes to the anchor tag

### ISSUE THREAD

**Issue by ARTUR3X** [foundation/foundation-emails#986]
Is there a way to add more attributes to the anchor when using the inky tab of button?
right now i can only put target to the button and when it converts to html the target attribute goes to the `<a>` tab but using Adobe Campaign i need to put  the attribute  _label="someTraking" to all the links  and i put it like this

` <button href="someLink" _target="blank" _label="someTraking">`

but when the final html gets formed I have to added manually to all the buttons because it wont carry it to the anchor tab

**Comment by DanielRuf** [comment]
This is not directly possible but you might be able to postprocess it with some gulp task, extend Inky with a new button component or patch it by using %[patch-package](https://npmjs.com/patch-package). See https://github.com/foundation/inky/blob/develop/lib/componentFactory.js#L36-L73

**Comment by DanielRuf** [comment]
This is not directly possible but you might be able to postprocess it with some gulp task, extend Inky with a new button component or patch it by using [patch-package](https://npmjs.com/patch-package). See https://github.com/foundation/inky/blob/develop/lib/componentFactory.js#L36-L73

**Comment by DanielRuf** [comment]
This is not directly possible but you might be able to postprocess it with some gulp task, extend Inky with a new button component or patch it by using [patch-package](https://npmjs.com/patch-package).

See https://github.com/foundation/inky/blob/develop/lib/componentFactory.js#L36-L73

**Comment by ARTUR3X** [comment]
Thank you!
