### ISSUE TITLE
[Getting Started with Sass] NODEJS version

### ISSUE THREAD

**Issue by ARTUR3X** [foundation/foundation-emails#991]
In our team some folks tried to install foundation using nodejs 12 but it seems to be working only with version 10. Are there any plans to make it available for the newer versions of nodejs?

**Comment by DanielRuf** [comment]
Yes, we will update the dependencies when we find the needed resources to push some new releases and work on it.

For now you can use nodenv, n or nvm to handle different versions.

**Comment by DanielRuf** [comment]
Hi @ARTUR3X,

Yes, we will update the dependencies when we find the needed resources to push some new releases and work on it.

For now you can use nodenv, n or nvm to handle different versions.
