### ISSUE TITLE
Merge conflicts in package-lock.json

### ISSUE THREAD

**Issue by manishbhatias** [foundation/foundation-emails#993]
**How can we reproduce this bug?**
Run npm install after checking out the master branch
Write out the HTML (or Inky code) that causes the issue.
NA
**What did you expect to happen?**
Clean install
**What happened instead?**
![image](https://user-images.githubusercontent.com/359189/75756896-68340900-5d57-11ea-9626-abcf93c52f06.png)

**What email clients does this happen in?**
NA

**Comment by DanielRuf** [comment]
Hi @manishbhatias,

you can safely remove the lockfile.

**Comment by DanielRuf** [comment]
This should resolve it: https://github.com/foundation/foundation-emails/commit/87f5e7c41aa3070b2e53dc6336a0a09eb47820ba
