### ISSUE TITLE
Published NPM module is out of date

### ISSUE THREAD

**Issue by gpoole** [foundation/foundation-emails#997]
The current NPM module is v2.2.1 and [according to NPM that was published 4 years ago](https://www.npmjs.com/package/foundation-emails). It looks like there's been a fair bit of activity on master since then, are you planning to publish a new version to NPM?

Sorry if this is a duplicate, I couldn't see anyone else asking.

**Comment by DanielRuf** [comment]
Hi @gpoole,

thanks for reporting this. We are aware of this.
See also https://foundation.discourse.group/t/next-foundation-emails-release-planning/83/6

We were focusing on Foundation Sites.

**Comment by gpoole** [comment]
Ok, makes sense, thanks!

-------- Original Message --------
